--STGAP00017262 - Release(5.0) MR-092:Add new Validate message                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                            
Insert into caps.message (NBR_MESSAGE, DT_LAST_UPDATE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,                                                                                                                                                                                                            
CD_PRESENTATION, IND_BATCH) Values (60942, SYSDATE, 'MSG_CMN_PASSWORD_VALIDATE',                                                                                                                                                                                                                                
'A password must be entered in order to Validate an event.', 500, 700, 'N');                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                            
insert into caps.schema_version(id_schema_version,application_version,comments)                                                                                                                                                                                                                             
            values (1143, 'SacwisRev5', 'Release 5.0 - DBCR 17262');                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                
commit; 