-- change STGAP00004588
-- from STGAP00004491 
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','1','Appling - 1160 West Parker St',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','2','Atkinson - P.O. Box 278',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','3','Bacon - P.O. Box 447',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','4','Baker - P.O. Box 540',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','5','Baldwin - P. O. Box 430',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','195','Baldwin - 120 S. Jefferson St.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','6','Banks - P.O. Box 159',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','7','Barrow - Po Box 546',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','8','Bartow - P.O. Box 818',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','9','Ben Hill - 124 South Grant St',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','10','Berrien - 301 S. Jefferson St.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','11','Bibb - 456 Oglethorpe Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','12','Bleckley - P.O. Box 499',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','13','Brantley - P.O. Box 308',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','14','Brooks - 201 S. Barnes St.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','15','Bryan - P. O. Box 398',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','54','Bryan - P. O. Box 474',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','16','Bulloch - P.O. Box 1103',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','17','Burke - P.O. Box 390',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','18','Butts - 178 Earnest Biles Dr',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','19','Calhoun - P.O. Box 9',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','20','Camden - P. O. Box 68',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','21','Candler - P.O. Box 46',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','22','Carroll - 165 Independence Dr',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','23','Catoosa - P.O. Box 58',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','24','Charlton - P.O. Box 395',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','25','Chatham - P.O. Box 2566',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','26','Chattahochee - 70 Mcnaughton St',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','27','Chattooga - 102 Hwy 48',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','28','Cherokee - P.O. Box 826',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','30','Clarke - P.O. Box 1887',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','31','Clay - P.O. Box 189',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','312','Clay - P.O. Box 788',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','32','Clayton - 877 Battlecreek Road',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','34','Clinch - P.O. Box 396',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','35','Cobb - 325 S. Fairground St',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','36','Cobb - 590 Commerce Park Dr',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','39','Coffee - P.O. Box 1119',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','40','Colquitt - P.O. Box 3008',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','41','Columbia - P. O. Box 340',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','194','Columbia - 4408 Evans Lock Rd',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','42','Cook - 1010 S.Hutchinson Ave',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','43','Coweta - 533 Highway 29 North',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','44','Crawford - P.O. Box 97',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','45','Crisp - P.O. Box 459',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','46','Dade - P. O. Box 159',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','47','Dawson - P.O. Box 867',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','48','Decatur - P.O. Box 1047',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','49','Dekalb - 178 Sams Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','51','Dekalb - 30 Warren Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','55','Dodge - P.O. Box 4219',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','313','Dodge - P.O. Box 398',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','56','Dooly - P.O. Box 385',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','57','Dougherty - P.O. Box 3249',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','93','Dougherty - 129 Whittlesey Court',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','53','Douglas - 4600 Timber Ridge Dr',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','58','Douglas - 8473 Duralee Ln #100',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','59','Early - P.O. Box 747',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','60','Echols - 106 Church Of God St.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','61','Effingham - P.O. Box 345',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','62','Elbert - P.O. Box 1010',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','63','Emanuel - P.O. Box 808',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','64','Evans - P.O. Box 578',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','65','Fannin - 990 E. Main St, Su-10',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','66','Fayette - 905 Highway 85 South',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','67','Floyd - 450 Riverside Parkway',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','68','Forsyth - P.O. Box 21',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','69','Franklin - P.O. Box 279',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','70','Fulton - 84 Walton Street, Nw',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','71','Fulton - 515 Fairburn Rd., S.W.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','72','Fulton - 1249 Dl Hollowell Pkwy',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','73','Fulton - 75 Marietta St. Nw',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','74','Fulton - 6075 Roswell Rd Ste300',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','75','Fulton - 341 Pon.De Leon Av.Ne',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','77','Fulton - 230 Peachtree St.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','78','Fulton - 54 Ellis Street N.E.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','79','Fulton - 1249 Bankhead Ave Nw',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','81','Fulton - P.O.Box 1857',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','82','Fulton - 5710 Stonewall Tell',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','192','Fulton - 1033 Jefferson St, Nw',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','84','Gilmer - 54 Kiker Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','85','Glascock - P.O. Box 225',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','86','Glynn - P. O. Box 400',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','87','Gordon - P O Box 217',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','88','Grady - P.O. Box 269',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','89','Greene - P.O. Box 460',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','90','Gwinnett - One Justice Square',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','190','Gwinnett - 2755 Sawnee Avenue',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','199','Gwinnett - 5030 Georgia Belle Ct',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','200','Gwinnett - 2211 Beaver Ruin Road',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','91','Habersham - P.O. Box 160',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','92','Hall - 970 Mcever Road Ext.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','94','Hancock - P. O. Box 70',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','95','Haralson - P.O. Box 324',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','96','Harris - P.O. Box 285',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','97','Hart - P.O. Box 518',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','98','Heard - P O Box 385',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','99','Henry - 125 Henry Parkway',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','100','Houston - 92 Cohen Walker Dr.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','315','Houston - P.O. Box 2286',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','102','Irwin - 108 N. Irwin Avenue',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','103','Jackson - 456 Athens Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','104','Jasper - 226 Funderburg Drive',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','105','Jeff Davis - P.O. Box 706',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','106','Jefferson - P.O. Box 570',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','107','Jenkins - P.O. Box 808',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','108','Johnson - P. O. Box 500',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','109','Jones - P.O. Drawer 1689',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','110','Lamar - 122 Westgate Plaza',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','111','Lanier - 313 Roquemore Circle',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','112','Laurens - P.O. Box 68',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','113','Lee - P.O. Box 145',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','114','Liberty - P.O. Box 710',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','115','Lincoln - P.O. Box 220',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','116','Long - P.O. Box 369',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','117','Lowndes - P.O. Box 5166',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','118','Lumpkin - 175 Tipton Drive',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','119','Macon - P.O. Box 457',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','120','Madison - P.O. Box 176',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','121','Marion - P.O. Box 473',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','122','Mcduffie - P.O. Box 507',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','123','Mcintosh - P.O. Box 1139',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','124','Meriwether - Po Box 1179',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','125','Miller - 69 Thompson Town Road',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','126','Mitchell - 90 West Oakland Ave',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','127','Monroe - P. O. Box 734',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','128','Montgomery - P.O. Box 217',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','129','Morgan - P.O. Box 89',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','130','Murray - P.O. Box 1014',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','131','Muscogee - 2100 Comer Ave',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','191','Muscogee - 1636 Second Avenue',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','196','Muscogee - 1226  10Th  Ave.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','132','Newton - P. O. Box 1588',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','133','Oconee - P.O. Box 105',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','134','Oglethorpe - P.O. Box 160',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','135','Paulding - P.O. Box 168',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','136','Peach - P.O. Box 976',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','137','Pickens - 255 Chambers Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','317','Pickens - P.O. Box 530',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','138','Pierce - P.O. Box 620',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','139','Pike - P.O. Box 387',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','140','Polk - P.O. Box 147',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','141','Pulaski - P.O. Box 567',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','142','Putnam - Po Box 3670',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','143','Quitman - P.O. Box 68',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','144','Rabun - P.O. Box 787',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','145','Randolph - 311 N. Webster Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','146','Richmond - P.O. Box 2277',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','149','Rockdale - 975 Taylor St',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','150','Schley - P.O. Box 367',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','151','Screven - P.O. Box 513',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','152','Seminole - 108 W 4Th St',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','153','Spalding - P.O. Box 1610',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','154','Stephens - 1000 Tugalo St.',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','155','Stewart - P.O. Box 308',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','156','Sumter - P.O. Box 1669',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','157','Talbot - P.O. Box 96',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','158','Taliaferro - P.O. Box 38',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','159','Tattnall - P.O. Box 528',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','160','Tattnall - P O Box 898',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','161','Taylor - P.O. Box 366',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','162','Telfair - P.O. Box 456',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','163','Terrell - P.O. Box 30',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','164','Thomas - P.O. Box 2740',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','165','Tift - P.O. Box 7550',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','166','Toombs - P.O. Box 191',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','167','Towns - P.O. Box 156',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','168','Treutlen - P.O. Box 625',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','169','Troup - 1220 Hogansville Rd',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','170','Turner - 336 North Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','171','Twiggs - P.O. Box 530',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','172','Union - P O Box 220',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','173','Upson - 711 N. Bethel Street',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','174','Walker - P.O. Box 689',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','318','Walker - Rr 2  Box 187',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','176','Walton - P.O. Box 927',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','178','Ware - P.O. Box 2048',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','179','Warren - P.O. Box 166',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','180','Washington - P.O. Box 108',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','181','Wayne - P.O. Box 267',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','182','Webster - P.O. Box 9',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','183','Wheeler - P.O. Box 221',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','184','White - 1241 Helen Hwy Un-200',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','185','Whitfield - P.O. Box 1203',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','186','Wilcox - P.O. Box 246',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','187','Wilkes - P.O. Box 126',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','188','Wilkinson - P.O. Box 526',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','189','Worth - P.O. Box 527',sysdate);
insert into caps.codes_tables (code_type, code, decode, dt_last_update) values ('COFCNM','999','State Office - Rsm Project',sysdate);

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (230, 'SacwisRev2', 'static updates');                        
commit;
