
-- Sequence Alter SQL

CREATE SEQUENCE CAPS.SEQ_INITIAL_MED_PARENT
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON CAPS.SEQ_INITIAL_MED_PARENT TO CAPSBAT
;
GRANT SELECT ON CAPS.SEQ_INITIAL_MED_PARENT TO CAPSON
;

-- Drop Constraint, Rename and Create Table SQL

CREATE TABLE CAPS.INITIAL_MED_PARENT
(
    ID_INITIAL_MED_PARENT NUMBER(16)  NOT NULL,
    DT_LAST_UPDATE        DATE        NOT NULL,
    ID_PERSON             NUMBER(16)  NOT NULL,
    ID_EVENT              NUMBER(16)  NOT NULL,
    IND_PARENT            VARCHAR2(1)     NULL,
    CONSTRAINT PK_INITIAL_MED_PARENT
    PRIMARY KEY (ID_INITIAL_MED_PARENT)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE CAPS.INITIAL_MED_PARENT IS
'This table contains data for the initial medicaid application that is specific to a particular parent.'
;
COMMENT ON COLUMN CAPS.INITIAL_MED_PARENT.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON CAPS.INITIAL_MED_PARENT TO CAPSBAT
;
GRANT INSERT ON CAPS.INITIAL_MED_PARENT TO CAPSBAT
;
GRANT SELECT ON CAPS.INITIAL_MED_PARENT TO CAPSBAT
;
GRANT UPDATE ON CAPS.INITIAL_MED_PARENT TO CAPSBAT
;
GRANT DELETE ON CAPS.INITIAL_MED_PARENT TO CAPSON
;
GRANT INSERT ON CAPS.INITIAL_MED_PARENT TO CAPSON
;
GRANT SELECT ON CAPS.INITIAL_MED_PARENT TO CAPSON
;
GRANT UPDATE ON CAPS.INITIAL_MED_PARENT TO CAPSON
;
GRANT SELECT ON CAPS.INITIAL_MED_PARENT TO OPERATOR
;


-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.INITIAL_MED_PARENT 
    ADD CONSTRAINT FK_INITIAL_MED_PARENT_INIT_APP
FOREIGN KEY (ID_EVENT)
REFERENCES CAPS.INITIAL_MEDICAID_APP (ID_EVENT)
ENABLE
;
ALTER TABLE CAPS.INITIAL_MED_PARENT 
    ADD CONSTRAINT FK_INITIAL_MED_PARENT_PERSON
FOREIGN KEY (ID_PERSON)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;


-- Alter Trigger SQL
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_INITIAL_MED_PARENT
BEFORE UPDATE
ON CAPS.INITIAL_MED_PARENT
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_INITIAL_MED_PARENT
BEFORE INSERT
ON CAPS.INITIAL_MED_PARENT
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:new.ID_INITIAL_MED_PARENT = 0) THEN
    SELECT  SEQ_INITIAL_MED_PARENT.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_INITIAL_MED_PARENT := dummy;
  END IF;
END;
/

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00003824
UPDATE CAPS.MESSAGE SET txt_message = 'Selecting %s will clear checkmarks.  Continue?' 
WHERE txt_message_name = 'MSG_INV_CONFIRM_NO_CHARS' AND nbr_message = 4024;

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (205, 'SacwisRev2', 'static updates, new init medicaid app table for parent'); 

commit;
