
-- change STGAP00002072
INSERT INTO CAPS.MESSAGE (ID_MESSAGE, NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) VALUES (0, 60313, 'MSG_SYS_NO_VISIT_CNCT_NARR', 'No parent/child visit contact narratives were found to match search criteria.', '560', '700', 'N');

-- change STGAP00002073
update CAPS.CODES_TABLES set DECODE = 'Maternity Home' where CODE = 'MH' and CODE_TYPE = 'CFACTYP4';

-- change STGAP00002076
-- updates to the CADOSVCD. The codes inserted had blank decode values. This script will correct that error. The query firsts deletes the code type before re-inserting it in.
DELETE FROM CAPS.CODES_TABLES CT WHERE CT.CODE_TYPE='CADOSVCD';

-- This represents the Adoption Services Code values used in the approval process for a Home

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '50807', '50807', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '50813', '50813', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '50913', '50913', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51033a', '51033a', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51033b', '51033b', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51033c', '51033c', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51033d', '51033d', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51033e', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51033f', '51033f', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51217', '51217', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51257', '51257', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51260', '51260', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51277', '51277', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51258a', '51258a', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51258b', '51258b', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51258c', '51258c', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES( 'CADOSVCD', '51258d', '51258d', SYSDATE);


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (162, 'SacwisRev2', 'static updates');  
commit;
