--STGAP00015644 - Release(3.4) DBCR: Update AFCARS Element Help

--The attached SQL performs updates to the AFCARS_ELEMENT_HELP table to correct 
--navigation and improve the formatting of the element help messages.

--It also includes the definition of a codes table to decode "13" as Georgia for AFCARS purposes.

UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_50';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_51';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52A';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52B';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52C';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52D';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52E';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52F';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_53';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54A';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54B';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54C';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54D';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54E';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54F';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navFadHomePersonList'')">FAD Stage Person Info</a>/<a href="javascript:caseWatchNavigation(''navCaretakerInfo'')">Caretaker Information</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_55';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navPersonDetail'')">Income and Resources</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_61';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navPersonDetail'')">Income and Resources</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_62';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_SOURCE_TEXT = '<a href="javascript:caseWatchNavigation(''navPersonDetail'')">Income and Resources</a>' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_64';

UPDATE CAPS.AFCARS_ELEMENT_HELP SET CD_AFCARS_DATA_TYPE = 'M' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_66';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET CD_AFCARS_DATA_TYPE = 'C', TXT_AFCARS_CODES_TABLE = 'CSTATEA' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_1';

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) SELECT 'CSTATEA','13','Georgia' FROM DUAL
WHERE NOT EXISTS (SELECT CODE FROM CAPS.CODES_TABLES WHERE CODE_TYPE = 'CSTATEA');

UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Local Agency:</b><br>County of report is based on the legal status county of the child at the time of report generation.  Any corrections should be made by updating or entering a corrected legal status.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_3';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of Most Recent Periodic Review:</b><br>For a child in foster care for seven months or longer this field is populated by the most recent administrative or court review date through the report period, which is  defined as one of the following:<br><br>The Court/Action date on a Legal Action where the Legal Action is a Citizen''s Panel Review or Panel/Admin, or where the Legal Action is Hearing and the Hearing/Court Order type is one of Judicial Review, Permanency, or Non-Reunification. The Legal Action must have been entered for the Primary Child in care.<br><br>Alternatively, this will be populated with the most recent Team Meetings/Review where the meeting type is Permanency Review Meeting and the meeting is recorded in the child''s FCC or ADO stage.<br><br>If this date seems to be missing or out of date, reconfirm that data was recorded within the child''s stage where required, and reconfirm the action and hearing type chosen for the legal action entered for the review.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_5';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child''s Date of Birth:</b><br>This is derived from the current DOB entered for the Primary Child in the stage.  If necessary correct the child''s birth date on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_6';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Sex:</b><br>This is derived from the current sex entered for the Primary Child in the stage.  Correct on Person Detail.  If necessary correct the child''s gender on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_7';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child Race:</b><br>This is derived from the current race entered for the Primary Child in the stage.  If necessary correct in the race/ethnicity section on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_8A';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child Race:</b><br>This is derived from the current race entered for the Primary Child in the stage.  If necessary correct in the race/ethnicity section on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_8B';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child Race:</b><br>This is derived from the current race entered for the Primary Child in the stage.  If necessary correct in the race/ethnicity section on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_8C';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child Race:</b><br>This is derived from the current race entered for the Primary Child in the stage.  If necessary correct in the race/ethnicity section on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_8D';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child Race:</b><br>This is derived from the current race entered for the Primary Child in the stage.  If necessary correct in the race/ethnicity section on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_8E';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child Race:</b><br>This is derived from the current race entered for the Primary Child in the stage.  If necessary correct in the race/ethnicity section on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_8F';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Hispanic or Latino Origin:</b><br>This is derived from the current ethnicity entered for the Primary Child in the stage.  If necessary correct in the race/ethnicity section on the Person Detail page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_9';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Has the Child Been Diagnosed with Disability(ies):</b><br>This will be yes if any of the diagnosis factors below are set to yes. See individual diagnosis factors below for detail.  Disabilities should never be Not Yet Determined after 6 months in care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_10';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Has the Child Been Diagnosed with Mental Retardation:</b><br>This is indicated when a person characteristic of Downs Syndrome or Mental Retardation - Diagnosed was selected for the child in care at the time of report generation.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_11';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Is the Child Visually or Hearing Impaired:</b><br>This is indicated when a person characteristic of either Hearing Impaired - Diagnosed or Visually Impaired - Diagnosed was selected for the child in care at the time of report generation.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_12';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Is the Child Physically Disabled:</b><br>This is indicated when a person characteristic of Mobility Impaired, Physically Disabled - Diagnosed, or Spina Bifida was selected for the child in care at the time of report generation.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_13';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Is the Child Emotionally Disturbed:</b><br>This is indicated when one or more of the following person characteristics was selected for the child in care at the time of report generation:<br><br>ADD/ADHD, Adjustment Disorder, Anxiety Disorder, Attachment Disorder, Autism, Bipolar, Conduct Disorder, Depression, Disruptive Behavior Disorder, Dysthymic Disorder, Eating Disorder, Emotionally Disturbed - Diagnosed, Impulse Control Disorder, Mood Disorder, Oppositional Defiant Disorder, Personality Disorder, Post-Traumatic Stress Syndrome, Psychotic Disorder, Schizoaffective, Schizophrenia, Separation Anxiety Disorder, or Tourette''s Disorder.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_14';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Has the Child Been Diagnosed with any Other Medical Condition:</b><br>This is indicated when one or more of the following person characteristics was selected for the child in care at the time of report generation:<br><br>Infant Alcohol Addiction, Infant Drug Addiction/Prenatal Drug Exposed, Cognitive Disorder, Intellectual Disability, Learning Disability, Speech Disability, Abnormal Bowel Movement Behavior, AIDS, Asperger''s Disorder, Asthma, Cancer, Diabetes, Eczema, Epilepsy, Hepatitis, HIV Positive, Other Medically Diagnosed, Rheumatic Fever, Heart Disease, Heart Murmur, Severe Allergies, Sexual Transmitted Disease, Sickle Cell Anemia, Terminal Illness, Traumatic Brain Injury, or Tuberculosis.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_15';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Has This Child Even Been Adopted:</b><br>This value is derived from the response to the "Previously Adopted" question on the Person Characteristics page for the child at the time of report generation.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_16';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>How Old Was Child When Previous Adoption Legalized:</b><br>This value is calculated using the Date of Previous Adoption as entered on the Person Characteristics Page and child''s date of birth.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_17';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of First Removal From Home:</b><br>This field is calculated based on data in previous cases: it is the earliest removal in SHINES as recorded using either the SHINES Custody Page or as converted from prior systems.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_18';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Total Number of Removals From Home to Date:</b><br>This field is calculated based on data in previous cases: it is a count of all removals in SHINES as recorded using the SHINES Custody page, plus additional removals converted from prior systems that may not have a Custody page in SHINES.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_19';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of Last Foster Care Discharge:</b><br>This is the date the child was discharged from the last foster care episode immediately prior to the current episode, determined using the most recent legal status date where the child has a legal status of "not in custody" immediately following an "in custody" legal status and the "not in custody" legal status occurred prior to the current removal.<br>In cases where a child remained in a trail home visit for over 6 months without legal discharge this date will be the trial home visit discharge date on Placement.<br>Note that in some cases this may be populated with converted data not associated to a SHINES case record.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_20';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of Latest Removal From Home:</b><br>This will be the date of the most recent removal record for the child occurring on or before the end of the reporting period.  This is entered using the SHINES Custody page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_21';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of Latest Removal Transaction Date:</b><br>This value is system generated and recorded as the date event occurred, visible on the Event List page, for the Custody record above.  This tracks the date the Custody record is actually entered into the system.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_22';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of Placement in Current Foster Care Setting:</b><br>This is populated using the Placement Start Date from the Placement Information page for the most recent placement event through the end of the reporting period, where the placement is an actual (not attempted) placement and is not a temporary placement of type concurrent, respite day, or respite night. ' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_23';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Number of Previous Placement Settings During This Episode:</b><br>This is populated with a count of placement events which have occurred since the most recent removal.  New placement events are counted as moves so long as: <br><br>1) The placement is an actual, as opposed to attempted, placement and not of type respite, concurrent, parental, or runaway<br><br>2) The placement does not fall within the set of placement moves not counted for AFCARS purposes such as returning to the preceeding foster placement when leaving a hospital setting.<br><br>For cases predating SHINES go live the count of moves occurring before SHINES comes directly from converted data sources.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_24';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Manner of Removal From Home for Current Placement Episode:</b><br>For the most recent Custody event, if voluntary surrender or voluntary placement is marked as the removal reason AFCARS will report a voluntary removal, otherwise it will report court ordered.  If corrections are necessary this must be corrected on the Custody page, not using a Legal Action or Legal Status.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_25';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Physical Abuse:</b><br>This applies of Physical Abuse/Risk was chosen as a removal reason on the custody record for the child''s current stay in care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_26';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Sexual Abuse:</b><br>This applies if Sexual Abuse/Risk was chosen as a removal reason on the custody record for the child''s current stay in care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_27';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Neglect:</b><br>This applies if any of the following were selected as removal reasons on the custody record for the child''s current stay in care:<br><br>Physical Neglect/Risk, Neglectful Supervision/Risk, Medical Neglect/Risk, Abuse/Neglect risk - Lack of Juvenile Justice Services, Abuse/Neglect risk - Lack of Mental Health or Mental Retardation Services, Abuse/Neglect Risk - Infant Left with Designated Emergency Infant Care Provider, Abuse/Neglect risk - Lack of Physical/Medical services, or Emotional Abuse/Risk.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_28';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Alcohol Abuse(Parent):</b><br>This applies if alcohol abuse was chosen as a caretaker removal characteristic on the custody record for the child''s current stay in care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_29';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Drug Abuse(Parent):</b><br>This applies if drug abuse was chosen as a caretaker removal characteristic on the current Custody event for the child.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_30';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Alcohol Abuse(Child):</b><br>This applies if Alcohol abuse was chosen as a child removal characteristic on the current Custody event for the child.  For this to occur Alcohol Abuse must have first been identified as a Person Characteristic for the child.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_31';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Drug Abuse(Child):</b><br>This applies if Drug abuse was chosen as a child removal characteristic on the current Custody event for the child.  For this to occur Drug Abuse must have first been identified as a Person Characteristic for the child.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_32';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child''s Disability:</b><br>This applies if any of the same person characteristics that factor into the question "Has the Child Been Diagnosed with Disabilities" above are selected as child removal characteristics on the current Custody page.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_33';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Child''s Behavior Problem:</b><br>This applies to the removal of any of the following person characteristics were chosen for the foster child on the Person Characteristics page and then selected on the Custody page as child characteristics contributing to removal:<br> Abnormal Bowel Movement Behavior, Aggressive, Animal Cruelty, Assaultive Behavior, Conduct Disorder, Eating Disorder, Fire Setting, Gang Activity/Affiliation, Has Trouble Sleeping, Inhalant Abuse, Prior Suicide Attempt, Prostitutes, Runs Away, Self Abuse, Sexually Acting Out, Sexually Promiscuous, Steals, Suicide Ideations, Violent, Wets Bed, or Other.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_34';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Death of Parent(s):</b><br>This applies if Death was chosen as a caretaker removal characteristic on the Custody record for the child''s entry into care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_35';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Incarceration of Parent(s):</b><br>This applies if Incarcerated was chosen as a caretaker removal characteristic on the Custody record for the child''s entry into care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_36';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Caretaker''s Inability to Cope Due to Illness of Other Reasons:</b><br>This applies if Caretaker Inability to Cope was chosen as a caretaker characteristic for removal on the Custody record for the child''s entry into care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_37';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Abandonment:</b><br>This applies if Abandonment was chosen as a Removal Reason on the Custody record for the child''s entry into care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_38';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Relinquishment:</b><br>This applies if Relinquishment was chosen as a caretaker removal characteristic on the Custody record for the child''s entry into care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_39';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Inadequate Housing:</b><br>This applies if Inadequate Housing was chosen as a caretaker characteristic for removal on the Custody record for the child''s entry into care.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_40';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Current Placement Setting:</b><br>Determined using the child''s most recent actual placement through the AFCARS report date, based on placement start date, where the placement is not respite or concurrent and the placement start does not equal placement end date (placement was at least one night).  SHINES placement types are mapped to AFCARS placement types as follows: <br><br>Adoptive Home:  Pre Adoptive Home <br><br>Relative-Paid, Relative - Unpaid, Relative Foster Home, Other Person: Foster Family Home (Relative) <br><br>Non-Relative Paid, DFCS Family Foster Home, CPA Family Foster Home, CCI Family Foster Home, Specialized Foster Home:  Foster Family Home (Non-Relative) <br><br>Group Home: Group Home <br><br>Emergency Shelter, Child Care Institution, Hospital, YDC/RYDC, Other Resource: Institution <br><br>Runaway:  Runaway <br><br>Parent: Trial Home Visit <br><br>If the last placement recorded is ended with a reason of runway; runaway is reported. <br><br>If placement does not match any of the criteria above, this entry is left blank.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_41';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Is Current Placement Setting Out of State:</b><br>If the address section of the current placement (through the end of the reporting period) indicates that the placement is not in Georgia yes will be reported, otherwise no will be reported.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_42';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Most Recent Case Plan Goal:</b><br>The most recent case plan goal is determined from the most recent Foster Care Family Case Plan that is approved and where the child is included on the list of principals on the plan.  If this is showing blank validate that the current plan is approved and that the child is included on the plan in the principals on plan section.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_43';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Caretaker Family Structure:</b><br>The Family Structure value is set according to the following Person Detail page gender and marital status value combinations for the identified primary caretakers (primary caretaker identification rules are described in the year of birty sections below):<br><br>If the first primary caretaker and second primary caretaker are male and female and married, the value reported is Married Couple <br><br>If the first primary caretaker and second primary caretaker are male and female and not married, the value reported is Unmarried Couple <br><br>If only one primary caretaker is identified, and gender is female, the value reported is Single Female<br><br>If only one primary caretaker is identified, and gender is male, the value reported is Single Male.<br><br>If only one primary caretaker is identified, and gender is unknown, the value reported is Unable to Determine <br><br>If the number of primary caretakers is more than two, the value reported is Unable to Determine. <br><br>If the logic otherwise cannot find a match AFCARS will report unable to determine. <br><br>If the family structure indicates a couple DOB should be provided for both caretakers.<br><br>When the child has both an active FCC and ADO stage, the relationships from the open Foster Care Child stage is used for the logic.  If an FCC stage is not open, the relationships come from the ADO stage.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_44';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Year of Birth: 1st Principal Caretaker:</b><br>The first primary caretaker isidentified using the following logic: <br><br>First - Any principal person in the stage where the most recent removal was recorded with a relationship of Primary Caretaker and identified on the Custody page as a part of the removal event as a member of the home of removal. <br><br>Second - Any principal person in the current foster care stage (most recent FCC) with a relationship (in order of preference) of Legal Mother, Legal Father, Biological Mother, Biological Father, Putative Mother, Putative Father, Parent, Absent Parent, Step Parent, Guardian, Grandparent. <br><br>Third - Any principal person in the stage where the most recent removal was recorded with a relationship of Primary Caretaker but not tied to the removal event on Custody as member of home of removal. <br><br>Fourth - Any principal person in the current foster care stage (most recent FCC) with a relationship (in order of preference) of Aunt/Uncle, Other Family Member, Unrel. Home Mem, Self/Minor Parent.<br><br>When the child has both an active FCC and ADO stage, the relationships are used from the open Foster Care Child stage.  If an FCC stage is not open, the relationships come from the ADO stage.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_45';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Year of Birth: 2nd Principal Caretaker:</b><br>The secondary caretaker is identified using the following logic (when appr. based on marital status): <br><br>First - If any principal in the stage where the most recent removal was recorded with a relationship of Primary Caretaker and identified on the Custody page as a part of the removal event, then select a person with the relationship of Spouse or Paramour depending on the primary caretaker''s marital status. <br><br>Second - Any principal in the current foster care stage with a relationship of Legal Mother, Legal Father, Biological Mother, Biological Father, Putative Mother, Putative Father, Parent, Absent Parent, Step Parent, Guardian, Grandparent where the person is different from the person selected as the first caretaker.<br><br>Third - If an principal in the stage where the most recent removal was recorded with a relationship of Primary Caretaker but not tied to the removal event on Custody, then select a person with the relationship of Spouse or Paramour depending on the primary caretaker''s marital status. <br><br>Fourth - Any principal in the current foster care stage with a relationship of Aunt/Uncle, Other Family Member, Unrel. Home Mem, and the person is different from the person selected as the primary caretaker. ' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_46';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Parental Rights Termination: Mother:</b><br>If a primary caretaker with a sex of female selected above has a date of death on Person Detail, AFCARS will report that date.  Otherwise it will report: <br><br>1) Date of Legal Action for Legal Action Type of Voluntary Surrender Mother (VLM), Voluntary Surrender by Adoptive Mother (VAM) <br><br>2) Date of Court Order for Legal Action where the Hearing/Court Order Type is TPR-Mother or TPR - Adoptive Mother and the Outcome is TPR Granted <br><br>If this date is not appearing for a court ordered TPR validate the action date, court order date, hearing type, and that the TPR Granted box has been checked for outcomes.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_47';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Parental Rights Termination: Father:</b><br>If a primary caretaker with a sex of male selected above has a date of death on Person Detail, AFCARS will report that date.  Otherwise it will report:<br><br>1) Date of Legal Action for Legal Action Type of Voluntary Surrender Legal/Biological Father, Voluntary Surrender Legal Father, Voluntary Surrender Biological Father, Voluntary Surrender by Adoptive Father, Voluntary Surrender-Father <br><br>2) Date of Court Order for Legal Action where the Hearing/Court Order Type is TPR-Father, TPR - Legal/Biological Father, TPR - Legal Father, TPR - Biological Father, TPR -  Adoptive Father and the Outcome is TPR Granted. <br><br>If this date is not appearing for a court ordered TPR validate the action date, court order date, hearing type, and that the TPR Granted box has been checked for outcomes.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_48';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Foster Family Structure:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Marital Status on the Home Information page.  For relative and other homes without FAD it will come from the Caretaker Information page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_49';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Year of Birth: 1st Foster Caretaker:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_50';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Year of Birth: 2nd Foster Caretaker:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_51';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 1 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52A';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 1 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52B';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 1 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52C';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 1 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52D';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 1 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52E';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 1 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_52F';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Hispanic or Latino Origin:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_53';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 2 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54A';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 2 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54B';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 2 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54C';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 2 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54D';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 2 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54E';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>FC Caretaker 2 Race:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_54F';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Hispanic or Latino Origin:</b><br>This field is only reported for current placement types of Pre-Adoptive, Relative Foster, or Non-Relative Foster Placement.  If the placement is tied to a resource with a FAD stage this information will come from Person Information for persons marked as foster or adoptive parents in the FAD stage.  For relative and other homes without FAD it will come from the Caretaker Detail page available under resource.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_55';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of Discharge from Foster Care:</b><br>The date the child was discharged from the current episode will be reported as: <br><br>1) The earliest legal status date where the child has a legal status of "not in custody" immediately following an "in custody" legal status and the "not in custody" legal status occurred after the current removal. <br><br>2) The Trial Home Visit Discharge Date, when the most recent previously approved placement is a trial home visit  that exceeds the court ordered end date. <br><br>3) The child''s 18th birthday if the child turned 18 years old during the reporting period and data for 1 or 2 above is not found.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_56';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Date of Discharge from Foster Care Transaction Date:</b><br>This system generated date can be seen on the Event List for the Legal Status event that updates the child''s legal status from in custody to not in custody.  It is recorded at the time the Legal Status is actually entered into the system and cannot be modified.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_57';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Reason for Discharge:</b><br>The reason for discharge is primarily derived from the Legal Status selected on the Legal Status event that records the discharge date above.   These are mapped below: <br><br>Aftercare/Supervision: Reunification with Parents/Primary Caretakers <br><br>Not In DFCS Custody Child Turned 18 (No ILP): Emancipation <br><br>Not in DFCS Custody Child Death: Death of Child <br><br>Not In DFCS Custody - Custody To Other: Transfer to Another Agency <br><br>Not In DFCS Custody - Custody Transferred To Tribe: Transfer to Another Agency <br><br>Not In DFCS Custody Emancipated: Emancipation <br><br>Not In DFCS Custody Guardianship: Guardianship <br><br>Not In DFCS Custody Parental Custody: Reunification with Parents/Primary Caretakers <br><br>Not in DFCS Custody - Custody to Relative: Living with Relatives <br><br>Committed To DJJ: Transfer to Another Agency <br><br>ILP Aftercare: Emancipation <br><br>If the child turned 18 without updated legal status, the reason will default to Emancipation.  If the child is discharged due to a trial home visit over the timeframe, the reason will default to Reunification.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_58';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Title IV-E (Foster Care):</b><br>Applies if for any time period during the reporting period, if an Eligibility Summary entry exists for the child on where selected eligibility is IV-E.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_59';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Title IV-E (Adoption):</b><br>Applies if the foster care child has not yet been adopted, and there exists an adoption subsidy agreement active during the reporting period with a type/class of assistance of Title IV-E Fin Asst and Medicaid, Title IV-E Fin Asst Only, or Title IV-E Fin Asst Medicaid Only.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_60';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Title IV-A (Aid to Families with Dependent Children/TANF):</b><br>Applies if the foster care child or any person selected as the primary or secondary foster caregiver above has an Income and Resources Entry active during the reporting period of with a type of "TANF".' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_61';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Title IV-D (Child Support):</b><br>Applies if there are one or more entries in Income and Resources for the foster child with dates active during the reporting period and the Income Resource type is "Child Support."' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_62';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Title XIX (Medicaid):</b><br>Applies if for any time period during the reporting period Eligibility Summary entry exists for the child on the with a class of assistance of  F11 - IV-E, F13 - IV-E Adopt, F15 - Newborn, F22- RSM, F40 - IV-B, F99 - Medically Needy, D02 - State Adopt, P01 - Pregnancy, EMA- Emer. Medical, or XXX - Other.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_63';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>SSI or Other Social Security Benefits:</b><br>Applies if there is one or more entries in Income and Resources for the foster child with dates active during the reporting period with an Income/Resource type of SSI.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_64';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>None of the Above:</b><br>This applies when none of the federal income sources above apply.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_65';
UPDATE CAPS.AFCARS_ELEMENT_HELP SET TXT_AFCARS_ELEMENT_HELP_TEXT = '<b>Amount of Monthly Foster Care Payment:</b><br>This data is based off of actual invoices paid through SHINES for this child, using the last payment month that could be identified for the child during the reporting period.  Perform an invoice search on the child to see details.' WHERE TXT_AFCARS_ELEMENT_SHORT = 'AFCARS_FC_66';


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (642, 'SacwisRev3', 'Release 3.4 - DBCR 15644');

commit;


