-- change STGAP00006099
update CAPS.CODES_TABLES 
set DT_END = '10/16/2007'
where CODE_TYPE = 'CINVUTYP'
and CODE = 'NOS';

-- change STGAP00006100
-- Updating MESSAGE for Defect STGAP00005769
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the legacy document cannot be fetched from the database.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_LEGACY_FETCH_DOCUMENT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the FPS.Documents/general configuration section is missing in the configuration file.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_MISSING_CONFIG_SECTION';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Generation of case file failed.  Please contact the SHINES Help Desk and provide them with the following information:  the FPS.CFP/general configuration section is missing in the configuration file.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_CFP_MISSING_CONFIG_SECTION';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed in PDF format.  Please contact the SHINES Help Desk and provide them with the following information:  the FPS.Common/activePDF configuration section is missing in the configuration file.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_ACTIVEPDF_MISSING_CONFIG_SECTION';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Please contact the SHINES Help Desk and provide them with the following information:  the FPS.Diagnostics/general configuration section is missing in the configuration file.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DIAGNOSTICS_MISSING_CONFIG_SECTION';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the metadata accessor cannot establish a connection to the database.' where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_METADATA_ACCESSOR_DB_CONNECT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot not be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  a configuration setting for document services is not correctly formatted.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_INVALID_SETTING';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with following information: an error has occurred retrieving configuration information for document services. ' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The document could not be saved.  Please contact the SHINES Help Desk and provide them with the following information:  an unexpected exception occurred while saving the XML document.  ' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_UNEXPECTED_XML_SAVE';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The document successfully saved, but could not be re-displayed.  Please contact the SHINES Help Desk and provide them with the following information:  a document could not be successfully reconstructed.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_SUCC_SAVE_FAIL_RECONSTRUCT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The MS-Word document successfully saved, but future saves will  not work correctly.  Please contact the SHINES Help Desk and provide them with the following information:  the MS-Word document saved, but a successful response could not be constructed.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_SUCC_SAVE_FAIL_XML_RESPONSE';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document could not be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the requested document type could not be found in the JNDI.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_JNDI_LOOKUP_FAILED';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document could not be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the document merger failed to fill repeaters.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_MERGER_FILL_REPEATERS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document could not be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the document merger failed to fill document data.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_MERGER_FILL_DOCUMENT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document could not be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the document merger failed to remove empty tokens.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_MERGER_REMOVE_EMPTY_TOKENS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Please contact the SHINES Help Desk and provide them with the following information:  an error has occurred retrieving configuration information for diagnostics.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DIAGNOSTICS_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Please contact the SHINES Help Desk and provide them with the following information:  a configuration setting for diagnostics is not correctly formatted.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DIAGNOSTICS_INVALID_SETTINGS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Please contact the SHINES Help Desk and provide them with the following information:  configuration information for diagnostics is missing.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DIAGNOSTICS_MISSING_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Please contact the SHINES Help Desk and provide them with the following information:  an error has occurred retrieving configuration settings for diagnostics.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DIAGNOSTICS_CONFIG_SETTINGS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed in PDF format.  Please contact the SHINES Help Desk and provide them with the following information:  an error has occurred retrieving configuration information for ActivePDF.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_ACTIVEPDF_CONFIG_SETTINGS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed in PDF format.  Please contact the SHINES Help Desk and provide them with the following information:  configuration information for ActivePDF is missing.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_ACTIVEPDF_MISSING_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed in PDF format.  Please contact the SHINES Help Desk and provide them with the following information:  a configuration setting for ActivePDF is not correctly formatted.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_ACTIVEPDF_INVALID_SETTING';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed in PDF format.  Please contact the SHINES Help Desk and provide them with the following information:  an error has occurred retrieving configuration information for ActivePDF.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_ACTIVEPDF_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Generation of case file failed.  Please contact the SHINES Help Desk and provide them with the following information:  an error has occurred retrieving configuration settings for CFP service.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_CFP_CONFIG_SETTINGS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Generation of case file failed.  Please contact the SHINES Help Desk and provide them with the following information:  configuration information for CFP service is missing.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_CFP_MISSING_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  an error occurred when building a legacy document query.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_LEGACY_BUILD_QUERYSTRING';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  A data accessor failed to initialize properly.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_INIT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  an error occurred when building a document data query.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_BUILD_QUERYSTRING';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information: a narrative cannot be fetched from the database. ' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_FETCH_NARRATIVE';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with following information:  a data accessor cannot establish a connection to the database.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_DB_CONNECT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with following information: a data accessor failed to execute command to fetch narrative.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_COMMAND_EXEC';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  a data accessor cannot read a database record.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_READ';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with following information:  a data accessor cannot deserialize a narrative.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_DESERIALIZE_NARRATIVE';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the metadata accessor failed to initialize properly.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_METADATA_ACCESSOR_INIT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the metadata accessor failed to get template version information.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_METADATA_ACCESSOR_TEMPLATE_VERSION';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'A document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  more than one document meets the query criteria.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_MULTIPLE_DOCS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The document could not be saved.  Please contact the SHINES Help Desk and provide them with the following information:  an unexpected error occurred while saving MS Word document.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_UNEXPECTED_SAVE_LEGACY';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Please contact the SHINES Help Desk. The child is in more than 1 active placement.' Where TXT_MESSAGE_NAME = 'MSG_CHILD_MULTIPLE_PLACEMENTS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Generation of case file failed.  Please contact the SHINES Help Desk and provide them with the following information:  a configuration setting for CFP service is not correctly formatted.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_CFP_INVALID_SETTING';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'Generation of case file failed.  Please contact the SHINES Help Desk and provide them with the following information:  an error has occurred retrieving configuration information for CFP service.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_CFP_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with following information: an error has occurred retrieving configuration information for document services. ' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_CONFIG_SETTINGS';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot not be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  configuration information for the document services is missing.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_MISSING_CONFIG';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The  requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the requested document was not found in the database. ' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_DATA_ACCESSOR_NARRATIVE_NOT_FOUND';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document  cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the legacy data accessor cannot establish a connection to the database.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_LEGACY_DATA_ACCESSOR_DB_CONNECT';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document  cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the legacy data accessor cannot deserialize a legacy document.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_LEGACY_DATA_ACCESSOR_DESERIALIZE_DOC';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document  cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the legacy data accessor failed to execute command to fetch document.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_LEGACY_DATA_ACCESSOR_COMMAND_EXEC';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the legacy data accessor failed to get document because it was not found in the database.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_LEGACY_DATA_ACCESSOR_DOC_NOT_FOUND';
Update CAPS.MESSAGE Set TXT_MESSAGE = 'The requested document cannot be displayed.  Please contact the SHINES Help Desk and provide them with the following information:  the legacy data accessor cannot read a database record.' Where TXT_MESSAGE_NAME = 'ARC_DOCS_ERR_LEGACY_DATA_ACCESSOR_READ';

-- change STGAP00006103
UPDATE caps.codes_tables SET dt_end = NULL WHERE code_type = 'CCHRTCAT' AND code IN ('CHB', 'CME', 'CPM', 'OTH');

-- change STGAP00006105
UPDATE CAPS.TASK SET TXT_TASK_DECODE='Approve Home Evaluation' WHERE CD_TASK ='8200';

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (253, 'SacwisRev2', 'static table updates');      
commit;
