--STGAP00016069 - Update TCM Denial Codes

--- Update existing TCM Denial codes with new decodes.
--- End-Date TCM Denial codes that are no longer in use
--- Insert missing TCM Denial code

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0439 - THE MEMBER ID IS MISSING OR INVALID'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0439';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '1153 - MEMBER ID NUMBER NOT ON FILE'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '1153';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0285 - MEMBER INELIGIBLE FOR DOS'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0285';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0252 - MEMBER NAME AND NUMBER DO NOT MATCH'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0252';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '4423 - NON EMERGENCY SERVICES ARE NOT PAYABLE FOR UNDOCUMENTED ALIENS'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '4423';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0471 - QMB Member Eligible For MCARE Crossovers Only'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0471';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '2091 - MEMBER SERVICES COVERED BY CMO PLAN'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '2091';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0578 - DOS IS BEFORE MEMBERS BIRTH DATE ON FILE. CORRECT OR SUBMIT PROOF OF DATE OF BIRTH.'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0578';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0284 - MEMBER IS ELIGIBLE FOR HOSPICE COVERAGE BY MEDICARE.'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0284';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '2031 - HOSPICE CLAIM SPANS A MEMBER HOSPICE SEGMENT'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '2031';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '4450 - MEMBER IS ELIGIBLE FOR HOSPICE RELATED SERVICES MUST BE BILLED TO THE HOSPICE'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '4450';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '2665 - A CONFLICT EXISTS BETWEEN THE AID CATEGORY (PEACHCARE 790 THRU 793) AND THE SERVICE RECIEVED'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '2665';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0535 - POSITIVE ADJUSTMENT EXCEEDS FILING DEADLINE'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0535';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0274 - DATE OF BIRTH ON CLAIM DOES NOT MATCH DOB ON MEMBER FILE'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0274';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '4714 - AGE TO PROCEDURE CODE CONFLICT'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '4714';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0737 - INVALID PROCEDURE CODE AND MODIFIER'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0737';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '0242 - NO PRICING SEGMENT FOR PROCEDURE/MODIFIER COMBINAT'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '0242'; 

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '4034 - PROCEDURE CODE/AGE CONFLICT'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '4034';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '2521 - Member Has COB Resource and the Service or COB Resource Indicates Pay and Chase'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '2521';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '5609 - SERVICE NOT ALLOWED SAME DOS AS A COMPREHENSIVE HEALTH CHECK SCREEN'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '5609';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '6386 - CASE MANAGEMENT CLAIM CANNOT BE BILLED IN THE SAME CALENDAR MONTH AS A PAID CLAIM FROM THE SAME OR ANOTHER CASE MANAGEMENT PROGRAM'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '6386';

UPDATE 	CAPS.CODES_TABLES CT
SET	CT.DECODE = '2806 - PROCTITIONER-EXACT DUPLICATE OF ANOTHER CLAIM'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '2806';
   

Update Caps.codes_tables ct set ct.DT_END = sysdate 
where ct.code_type = 'CTCMDEN' 
and ct.code in ('1128','2141','2143','2222','2264','2266','2343','2702','2712','2714','2716','2723','2725','2746','2750','4117','4321','4354','4355',
'4908','5750','5761','6007','6029','6101','4112','0778','2727');


Insert into caps.codes_tables
(CODE_TYPE,CODE,DECODE,DT_END,DT_LAST_UPDATE)
Values
('CTCMDEN','0465','MEMBER COVERED BY PRIVATE INSURANCE',null,sysdate);

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (960, 'SacwisRev4', 'Release 4.1 - DBCR 16069');

commit;

