
-- change STGAP00002534
INSERT INTO CAPS.TASK ( CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, CD_TASK_PRIOR, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_ENABLE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, IND_TASK_TODO_ENABLE, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE ) VALUES ( 
'8605',  sysdate, NULL, 'POC', NULL, NULL, 'ADO', 'CPS', NULL, NULL, '1', '1', NULL, '1', NULL, '0', '0', '0', '1', NULL, 'Payment of Care', 'CASE_CASESEARCH', 'PLACEMENT_EVENTLIST', 'PAYMENT_OF_CARE_EVENTLIST', '/casemgmt/PaymentOfCare/displayPOC', 3, '1', '0', '0'); 
INSERT INTO CAPS.TASK ( CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, CD_TASK_PRIOR, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_ENABLE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, IND_TASK_TODO_ENABLE, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL) VALUES ( 
'8606',  sysdate, NULL, 'APP', NULL, NULL, 'ADO', 'CPS', NULL, NULL, '0', '1', NULL, '1', NULL, '0', '0', '0', '0', NULL, 'Approve Payment of Care', 'CASE_CASESEARCH', 'PLACEMENT_EVENTLIST', 'PAYMENT_OF_CARE_EVENTLIST', '/casemgmt/PaymentOfCare/displayPOC'); 


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (172, 'SacwisRev2', 'static updates');   
commit;
