

--  STGAP00015185: Question are not displaying correctly for Safety Checklist for Caregivers,0-18 months.
delete from caps.spwb_age_group_lookup where cd_chck_list in ('BTQ1', 'BTQ2', 'BTQ3', 'BSQ3');
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'BTQ1','0','84', SYSDATE);
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'BTQ2','0','84', SYSDATE);
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'BTQ3','0','84', SYSDATE);
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'BSQ3','0','84', SYSDATE);


-- STGAP00015158: Grammatical Error on the Safety, Permanency and Well-Being Narrative Form
update caps.spwb_chck_list_lookup set txt_chck_list='Is this child receiving any educational, medical and/or psychological services?  Which ones? How often? Do you think that these services are meeting this child''s needs?  Are there any other services that you think that this child needs?' where cd_chck_list='WPCRQ7';


-- STGAP00015154: All Housing question are not displaying for Children 18-21
INSERT INTO CAPS.SPWB_CHCK_LIST_LOOKUP (CD_CHCK_LIST, TXT_CHCK_LIST, CD_SUB_CATEGORY, DT_LAST_UPDATE,  CD_AUDIENCE, CD_MAIN_CATEGORY) VALUES ('WPCQ154','When do you think you will move out of your current living arrangements?','HO',SYSDATE,  'CH', 'WBP');
INSERT INTO CAPS.SPWB_CHCK_LIST_LOOKUP (CD_CHCK_LIST, TXT_CHCK_LIST, CD_SUB_CATEGORY, DT_LAST_UPDATE,  CD_AUDIENCE, CD_MAIN_CATEGORY) VALUES ('WPCQ155','What type of living arrangement are you thinking about? e.g., living alone, sharing with a roommates, renting a room, etc.','HO',SYSDATE,  'CH', 'WBP');
INSERT INTO CAPS.SPWB_CHCK_LIST_LOOKUP (CD_CHCK_LIST, TXT_CHCK_LIST, CD_SUB_CATEGORY, DT_LAST_UPDATE,  CD_AUDIENCE, CD_MAIN_CATEGORY) VALUES ('WPCQ156','Do you understand how to search for an apartment?','HO',SYSDATE,  'CH', 'WBP');
INSERT INTO CAPS.SPWB_CHCK_LIST_LOOKUP (CD_CHCK_LIST, TXT_CHCK_LIST, CD_SUB_CATEGORY, DT_LAST_UPDATE,  CD_AUDIENCE, CD_MAIN_CATEGORY) VALUES ('WPCQ157','Do you understand what it takes to maintain your own apartment?','HO',SYSDATE,  'CH', 'WBP');
INSERT INTO CAPS.SPWB_CHCK_LIST_LOOKUP (CD_CHCK_LIST, TXT_CHCK_LIST, CD_SUB_CATEGORY, DT_LAST_UPDATE,  CD_AUDIENCE, CD_MAIN_CATEGORY) VALUES ('WPCQ158','Are you aware of any subsidized housing options available to youth leaving care?','HO',SYSDATE,  'CH', 'WBP');

INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'WPCQ154','216','264', SYSDATE);
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'WPCQ155','216','264', SYSDATE);
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'WPCQ156','216','264', SYSDATE);
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'WPCQ157','216','264', SYSDATE);
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'WPCQ158','216','264', SYSDATE);


-- STGAP00015149:  Permanency & Well being Checklist for Children ages 3-6 is missing a sentence
INSERT INTO CAPS.SPWB_CHCK_LIST_LOOKUP (CD_CHCK_LIST, TXT_CHCK_LIST, CD_SUB_CATEGORY, DT_LAST_UPDATE,  CD_AUDIENCE, CD_MAIN_CATEGORY) VALUES ('WPCQ159','Are there any things that you''d really like to be doing that you aren''t doing now?','SI',SYSDATE,  'CH', 'WBP');
INSERT INTO CAPS.SPWB_AGE_GROUP_LOOKUP (ID_SPWB_AGE_GROUP, CD_CHCK_LIST, NBR_MONTH_MIN, NBR_MONTH_MAX, DT_LAST_UPDATE) VALUES (CAPS.SEQ_SPWB_AGE_GROUP_LOOKUP.NEXTVAL, 'WPCQ159','36','84', SYSDATE);

-- STGAP00015148:Safety Checklist for Children ages 3-6 is missing a sentence
update caps.spwb_age_group_lookup set nbr_month_min=36 where cd_chck_list='SCCQ18';

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (523, 'SacwisRev3', 'Release 3.2 - SPWB Narrative Static Data');

commit;
