--STGAP00015788 - Release(3.5) DBCR Response to Case Review Request Form

-- Response to Case Review Request Form add new table ADMN_RVW_RESPONSE_NARR

CREATE TABLE CAPS.ADMN_RVW_RESPONSE_NARR ( 
	ID_EVENT NUMBER(16,0) NOT NULL ENABLE, 
	DT_LAST_UPDATE DATE NOT NULL ENABLE, 
	ID_CASE NUMBER(16,0), 
  NARRATIVE LONG RAW,
  ID_DOCUMENT_TEMPLATE NUMBER(16,0),
    CONSTRAINT PK_ADMN_RVW_RESPONSE_NARR PRIMARY KEY (ID_EVENT) using index tablespace index01,
    CONSTRAINT FK_ADMN_RVW_RESPONSE_REF_EVENT FOREIGN KEY (ID_EVENT) REFERENCES CAPS.EVENT(ID_EVENT),
    CONSTRAINT FK_ADMN_RVW_RESPONSE_REF_CASE FOREIGN KEY (ID_CASE) REFERENCES CAPS.CAPS_CASE(ID_CASE)
) tablespace data01;

create index caps.ind_ADMN_RVW_RESPONSE_NARR_1 on caps.ADMN_RVW_RESPONSE_NARR(id_case) tablespace index01;

grant select,update,insert,delete on caps.ADMN_RVW_RESPONSE_NARR to capson,capsbat,ops$datafix;

grant select  on caps.ADMN_RVW_RESPONSE_NARR to operator,shinesdm;


/
CREATE OR REPLACE TRIGGER CAPS.TIBR_ADMN_RVW_RESPONSE_NARR 
BEFORE INSERT ON CAPS.ADMN_RVW_RESPONSE_NARR
FOR EACH ROW

BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	SELECT	ID_CASE
	INTO		:new.ID_CASE
	FROM		EVENT
	WHERE 	ID_EVENT = :new.ID_EVENT;
EXCEPTION
	WHEN OTHERS THEN
		IF SQL%NOTFOUND THEN
			:new.ID_CASE := NULL;
		END IF;
END;
/

/
CREATE OR REPLACE TRIGGER CAPS.TUBR_ADMN_RVW_RESPONSE_NARR 
BEFORE UPDATE ON CAPS.ADMN_RVW_RESPONSE_NARR
FOR EACH ROW

BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (747, 'SacwisRev3', 'Release 3.5 - DBCR 15788');


commit;
 
