--STGAP00016074 - Release(4.2) MR-074-2 AFCARS Phase 2 Create New Table

-- STGAP00016074
-- MR-074-2 AFCARS Phase 2 Create New Table
-- For AFCARS Adoption History Table

CREATE TABLE CAPS.AFCARS_ADOPTION_HISTORY
  ( ID_AFCARS_ADO_HISTORY            NUMBER(16,0) NOT NULL,
    STATE                        VARCHAR2(2 BYTE),
    REPORT_DATE                  VARCHAR2(6 BYTE),
    RECORD_NUMBER                VARCHAR2(12 BYTE),
    STATE_AGENCY_INVOLVEMENT     VARCHAR2(1 BYTE),
    CHILDS_DATE_OF_BIRTH         VARCHAR2(6 BYTE),
    SEX                          VARCHAR2(1 BYTE),
    RACE_A                       VARCHAR2(1 BYTE),
    RACE_B                       VARCHAR2(1 BYTE),
    RACE_C                       VARCHAR2(1 BYTE),
    RACE_D                       VARCHAR2(1 BYTE),
    RACE_E                       VARCHAR2(1 BYTE),
    RACE_F                       VARCHAR2(1 BYTE),
    HISPANIC_OR_LATINO_ORIGIN    VARCHAR2(1 BYTE),
    STATE_AGENCY_SPECIAL_NEEDS   VARCHAR2(1 BYTE),
    PRIMARY_BASIS_SPECIAL_NEEDS  VARCHAR2(1 BYTE),
    MENTAL_RETARDATION           VARCHAR2(1 BYTE),
    VISUALLY_OR_HEARING_IMPAIRED VARCHAR2(1 BYTE),
    PHYSICALLY_DISABLED          VARCHAR2(1 BYTE),
    EMOTIONALLY_DISTURBED        VARCHAR2(1 BYTE),
    OTHER_DIAGNOSED_CONDITION    VARCHAR2(1 BYTE),
    MOTHERS_BIRTH_YEAR           VARCHAR2(4 BYTE),
    FATHERS_BIRTH_YEAR           VARCHAR2(4 BYTE),
    MOTHERS_MARRIED              VARCHAR2(4 BYTE),
    RIGHTS_TERMINATION_MOTHER    VARCHAR2(8 BYTE),
    RIGHTS_TERMINATION_FATHER    VARCHAR2(8 BYTE),
    DATE_ADOPTION_LEGALIZED      VARCHAR2(8 BYTE),
    ADOPTIVE_FAMILY_STRUCTURE    VARCHAR2(1 BYTE),
    YOB_ADOPTIVE_MOTHER          VARCHAR2(4 BYTE),
    YOB_ADOPTIVE_FATHER          VARCHAR2(4 BYTE),
    RACE_ADOPTIVE_MOTHER_A       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_MOTHER_B       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_MOTHER_C       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_MOTHER_D       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_MOTHER_E       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_MOTHER_F       VARCHAR2(1 BYTE),
    HL_ORIGIN_ADOPTIVE_MOTHER    VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_FATHER_A       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_FATHER_B       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_FATHER_C       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_FATHER_D       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_FATHER_E       VARCHAR2(1 BYTE),
    RACE_ADOPTIVE_FATHER_F       VARCHAR2(1 BYTE),
    HL_ORIGIN_ADOPTIVE_FATHER    VARCHAR2(1 BYTE),
    RELATIONSHIP_STEPPARENT      VARCHAR2(1 BYTE),
    RELATIONSHIP_OTH_RELATIVE    VARCHAR2(1 BYTE),
    RELATIONSHIP_FOSTER_PARENT   VARCHAR2(1 BYTE),
    RELATIONSHIP_OTH_NONRELATIVE VARCHAR2(1 BYTE),
    CHILD_WAS_PLACED_FROM        VARCHAR2(1 BYTE),
    CHILD_WAS_PLACED_BY          VARCHAR2(1 BYTE),
    MONTHLY_SUBSIDY              VARCHAR2(1 BYTE),
    MONTHLY_AMOUNT               VARCHAR2(5 BYTE),
    ADOPTION_ASSISTANCE_IV_E     VARCHAR2(1 BYTE),
    NM_FLAT_FILE                 VARCHAR2(35 BYTE),
    PERSON_ID                    NUMBER(16,0),
    CASE_ID                      NUMBER(16,0),
    PAD_PERSON_ID                NUMBER(16,0),
    PAD_CASE_ID                  NUMBER(16,0),
    EVENT_ID_LS_NAF              NUMBER(16,0),
    DT_LAST_UPDATE               DATE NOT NULL,
    DT_AFCARS_SUBMITTED                DATE,
    CONSTRAINT PK_AFCARS_ADOPTION_HISTORY PRIMARY KEY(ID_AFCARS_ADO_HISTORY)
  ) tablespace data01;

  COMMENT ON COLUMN CAPS.AFCARS_ADOPTION_HISTORY.DT_LAST_UPDATE IS
  'Indicates the date when the record was last updated';

  COMMENT ON COLUMN CAPS.AFCARS_ADOPTION_HISTORY.ID_AFCARS_ADO_HISTORY IS 'A unique identifier to the AFCARS_ADOPTION_HISTORY table' ;

  COMMENT ON TABLE CAPS.AFCARS_ADOPTION_HISTORY IS
  'To support state reporting, this request creates the AFCARS_ADOPTION_HISTORY table. Data will be loaded into this table following a new run of the AFCARS Batch Extract to store the information produced from the flat file.';

GRANT SELECT,UPDATE,INSERT,DELETE ON CAPS.AFCARS_ADOPTION_HISTORY TO CAPSON,CAPSBAT,OPS$DATAFIX;
grant select on caps.AFCARS_ADOPTION_HISTORY to operator,shinesdm;

CREATE SEQUENCE  CAPS.SEQ_AFCARS_ADOPTION_HISTORY  NOMINVALUE NOMAXVALUE INCREMENT
BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

grant select on CAPS.SEQ_AFCARS_ADOPTION_HISTORY  to capsbat,capson,ops$datafix;

/
CREATE OR REPLACE TRIGGER CAPS.TUBR_AFCARS_ADOPTION_HISTORY
BEFORE UPDATE
ON CAPS.AFCARS_ADOPTION_HISTORY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
   :NEW.DT_LAST_UPDATE := sysdate;
END;
/


/
CREATE OR REPLACE TRIGGER CAPS.TIBR_AFCARS_ADOPTION_HISTORY
BEFORE INSERT
ON CAPS.AFCARS_ADOPTION_HISTORY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
   dummy number;
BEGIN
:NEW.DT_LAST_UPDATE := sysdate;
  if :NEW.ID_AFCARS_ADO_HISTORY=0 then
    SELECT SEQ_AFCARS_ADOPTION_HISTORY.NEXTVAL INTO dummy  FROM DUAL;
    :NEW.ID_AFCARS_ADO_HISTORY := dummy;
  end if;
END;
/



insert into caps.schema_version(id_schema_version,application_version,comments)
            values (965, 'SacwisRev4', 'Release 4.2 - DBCR 16074');

commit;


