--STGAP00012041 - new entries for stage progression

--Note:   no impact to ado model

--new entries for stage progression

INSERT INTO CAPS.STAGE_PROG (CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM,
IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS,TXT_STAGE_PROG_EVNT_DESC)
VALUES ('ADO', 'PER', 'CPS', '0', 'STG', 'COMP', 'Adoption Stage Closed');

INSERT INTO CAPS.STAGE_PROG (CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM,
IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS,TXT_STAGE_PROG_EVNT_DESC)
VALUES ('ADO', 'PCR', 'CPS', '0', 'STG', 'COMP', 'Adoption Stage Closed');

INSERT INTO CAPS.STAGE_PROG (CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM,
IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS,TXT_STAGE_PROG_EVNT_DESC)
VALUES ('ADO', 'EMP', 'CPS', '0', 'STG', 'COMP', 'Adoption Stage Closed');

INSERT INTO CAPS.STAGE_PROG (CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM,
IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS,TXT_STAGE_PROG_EVNT_DESC)
VALUES ('ADO', 'C18', 'CPS', '0', 'STG', 'COMP', 'Adoption Stage Closed');

INSERT INTO CAPS.STAGE_PROG (CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM,
IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS,TXT_STAGE_PROG_EVNT_DESC)
VALUES ('ADO', 'RG', 'CPS', '0', 'STG', 'COMP', 'Adoption Stage Closed');

INSERT INTO CAPS.STAGE_PROG (CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM,
IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS,TXT_STAGE_PROG_EVNT_DESC)
VALUES ('ADO', 'NRG', 'CPS', '0', 'STG', 'COMP', 'Adoption Stage Closed');

INSERT INTO CAPS.STAGE_PROG (CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM,
IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS,TXT_STAGE_PROG_EVNT_DESC)
VALUES ('ADO', 'REU', 'CPS', '0', 'STG', 'COMP', 'Adoption Stage Closed');


--STGAP00011942 - Reports: Enable new SQR report in SHINES

--Note:  no impact to ado model

--To enable new SQR report Period Finalization Summary in SHINES for release 3.0

INSERT INTO CAPS.REPORTS ( NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, 
NM_RPT_TYPE, TXT_RPT_FULL_NAME,NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, 
TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE, CD_SEC_ATTR )
VALUES ('PeriodFinalizationSummary', '00', 7, 'A', 'Period Finalization Summary', 
'ondport', 'L', 'W', 'A list of counties and the number of adoptions finalized in the counties by month where the date of finalization is within the reporting period. Generated for a specific date range parameter. This report requires SAU staff security attribute.',
 'Adoptions', 'Y', '91');

INSERT INTO CAPS.REPORT_PARAMETER (NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, 
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME,TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL ) 
VALUES ('PeriodFinalizationSummary', '00', 1, 10, 'BEGINDATE', 'DATE', 'Y', 'Start Date');

INSERT INTO CAPS.REPORT_PARAMETER ( NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, 
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME,TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL ) 
VALUES ('PeriodFinalizationSummary', '00', 2, 10, 'ENDDATE', 'DATE', 'Y', 'End Date');


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (423, 'SacwisRev3', 'Release 3.0 - DBCRs 11916,11942,12041,12057');

commit;

