
-- Standard Alter Table SQL

ALTER TABLE SACWISIFC.ADOPT_TPR_OUTBOUND MODIFY(CD_ERROR  VARCHAR2(40))
;

-- Drop Constraint, Rename and Create Table SQL

ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND DROP CONSTRAINT FK_AG_CUST_PAR_CSUP_REF
;
ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND RENAME TO CHILDSUP_R_06292007173843000
;
CREATE TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND
(
    ID_CHILDSUP_REF_OUTBOUND     NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE               DATE         NOT NULL,
    INTERFACE_STATUS             VARCHAR2(3)  NOT NULL,
    DT_PROCESS                   DATE             NULL,
    CD_ERROR                     VARCHAR2(40)     NULL,
    ID_INITIATOR                 NUMBER(16)   NOT NULL,
    SHINES_LOGON_SHORT           VARCHAR2(8)      NULL,
    DT_CSUP_REQUESTED            DATE             NULL,
    ID_CASE                      NUMBER(16)   NOT NULL,
    ID_STAGE                     NUMBER(16)   NOT NULL,
    ID_CHILD                     NUMBER(16)   NOT NULL,
    NBR_CHILD_CRS_ID             NUMBER(9)    NOT NULL,
    IND_CHILD_PATERNITY_EST      VARCHAR2(1)      NULL,
    NBR_PER_DIEM                 NUMBER(5,2)      NULL,
    NBR_PER_MONTH                NUMBER(5,2)      NULL,
    DT_EFF_PER_DIEM              DATE             NULL,
    IND_CHILD_SUPPORT_ORDER      VARCHAR2(1)      NULL,
    CD_MED_COA                   VARCHAR2(3)      NULL,
    ID_NONCUST_PARENT            NUMBER(16)   NOT NULL,
    NBR_NONCUST_CRS_ID           NUMBER(9)    NOT NULL,
    ADDR_NONCUST_ADDR_ST_LN_1    VARCHAR2(25)     NULL,
    ADDR_NONCUST_ADDR_ST_LN_2    VARCHAR2(25)     NULL,
    ADDR_NONCUST_ADDR_CITY       VARCHAR2(20)     NULL,
    CD_NONCUST_ADDR_STATE        VARCHAR2(2)      NULL,
    ADDR_NONCUST_ADDR_ZIP        VARCHAR2(10)     NULL,
    TXT_INC_RSRC_DESC            VARCHAR2(80)     NULL,
    TXT_INC_RSRC_SRC_ADDR_ST_LN1 VARCHAR2(25)     NULL,
    TXT_INC_RSRC_SRC_ADDR_ST_LN2 VARCHAR2(25)     NULL,
    TXT_INC_RSRC_SRC_ADDR_CITY   VARCHAR2(20)     NULL,
    TXT_INC_RSRC_SRC_ADDR_STATE  VARCHAR2(2)      NULL,
    TXT_INC_RSRC_SRC_ADDR_ZIP    VARCHAR2(10)     NULL,
    IND_SSI_NONCUST              VARCHAR2(1)      NULL,
    CD_NONCUST_MARITAL_STATUS    VARCHAR2(2)      NULL,
    ID_AGENCY_CUSTODIAL_PARENTS  NUMBER(16)   NOT NULL,
    NBR_CUST_CRS_ID              NUMBER(9)        NULL,
    CD_COUNTY                    VARCHAR2(3)      NULL,
    ID_OFFICE                    NUMBER(16)       NULL,
    NM_OFFICE_NAME               VARCHAR2(15)     NULL,
    NM_CASEMANAGER_FIRST         VARCHAR2(12)     NULL,
    NM_CASEMANAGER_MIDDLE        VARCHAR2(12)     NULL,
    NM_CASEMANAGER_LAST          VARCHAR2(22)     NULL,
    NBR_CASEMANAGER_PHONE        VARCHAR2(10)     NULL,
    NBR_CASEMANAGER_FAX          VARCHAR2(10)     NULL,
    ADDR_CASEMAN_ADDR_ST_LN_1    VARCHAR2(30)     NULL,
    ADDR_CASEMAN_ADDR_ST_LN_2    VARCHAR2(30)     NULL,
    ADDR_CASEMAN_ADDR_CITY       VARCHAR2(20)     NULL,
    CD_CASEMAN_ADDR_STATE        VARCHAR2(2)      NULL,
    ADDR_CASEMAN_ADDR_ZIP        VARCHAR2(10)     NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
GRANT DELETE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO OPERATOR
;
ALTER TABLE SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND RENAME TO CSUP_CHILD_06292007173844000
;
CREATE TABLE SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND
(
    ID_CSUP_CHLDLFTCARE_OUTBOUND NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE               DATE         NOT NULL,
    INTERFACE_STATUS             VARCHAR2(3)  NOT NULL,
    DT_PROCESS                   DATE             NULL,
    CD_ERROR                     VARCHAR2(40)     NULL,
    ID_INITIATOR                 NUMBER(16)   NOT NULL,
    DT_CHILDHOME_REQUESTED       DATE             NULL,
    NBR_CHILD_CRS_ID             NUMBER(9)    NOT NULL,
    DT_LEFT_CARE                 DATE             NULL,
    CD_REASON_CODE               VARCHAR2(2)      NULL,
    ID_CASE                      NUMBER(16)   NOT NULL,
    NM_FULL_NAME                 VARCHAR2(30)     NULL,
    ADDR_PLCMT_CITY              VARCHAR2(20)     NULL,
    ADDR_PLCMT_LN1               VARCHAR2(25)     NULL,
    ADDR_PLCMT_LN2               VARCHAR2(25)     NULL,
    ADDR_PLCMT_ST                VARCHAR2(2)      NULL,
    ADDR_PLCMT_ZIP               VARCHAR2(10)     NULL,
    NBR_PLCMT_TELEPHONE          VARCHAR2(10)     NULL,
    NBR_NCP_CRS_ID               NUMBER(9)        NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON COLUMN SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND.NBR_NCP_CRS_ID IS
'This is the Client Identifier obtained from CRS (Client Repository System) which is used in state of Georgia applications.'
;
GRANT DELETE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO OPERATOR
;
ALTER TABLE SACWISIFC.CSUP_PARENT_OUTBOUND DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE SACWISIFC.CSUP_PARENT_OUTBOUND RENAME TO CSUP_PAREN_06292007173845000
;
CREATE TABLE SACWISIFC.CSUP_PARENT_OUTBOUND
(
    ID_CSUP_PARENT_OUTBOUND      NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE               DATE         NOT NULL,
    INTERFACE_STATUS             VARCHAR2(3)  NOT NULL,
    DT_PROCESS                   DATE             NULL,
    CD_ERROR                     VARCHAR2(40)     NULL,
    ID_INITIATOR                 NUMBER(16)   NOT NULL,
    DT_CSUPPAR_REQUESTED         DATE             NULL,
    NBR_CHILD_CRS_ID             NUMBER(9)    NOT NULL,
    NBR_NONCUST_CRS_ID           NUMBER(9)    NOT NULL,
    NM_NONCUST_LAST              VARCHAR2(22)     NULL,
    NM_NONCUST_FIRST             VARCHAR2(12)     NULL,
    NM_NONCUST_MIDDLE            VARCHAR2(12)     NULL,
    NBR_NONCUST_NUMBER           VARCHAR2(15)     NULL,
    CD_CRS_NONCUST_RACE          VARCHAR2(1)      NULL,
    DT_NONCUST_DOB               DATE             NULL,
    IND_SSI_NONCUST              VARCHAR2(1)      NULL,
    ADDR_NONCUST_ADDR_ST_LN_1    VARCHAR2(25)     NULL,
    ADDR_NONCUST_ADDR_ST_LN_2    VARCHAR2(25)     NULL,
    ADDR_NONCUST_ADDR_CITY       VARCHAR2(20)     NULL,
    CD_NONCUST_ADDR_STATE        VARCHAR2(2)      NULL,
    ADDR_NONCUST_ADDR_ZIP        VARCHAR2(10)     NULL,
    NBR_NONCUST_PHONE            VARCHAR2(10)     NULL,
    TXT_INC_RSRC_DESC            VARCHAR2(80)     NULL,
    TXT_INC_RSRC_SRC_ADDR_ST_LN1 VARCHAR2(25)     NULL,
    TXT_INC_RSRC_SRC_ADDR_ST_LN2 VARCHAR2(25)     NULL,
    TXT_INC_RSRC_SRC_ADDR_CITY   VARCHAR2(20)     NULL,
    TXT_INC_RSRC_SRC_ADDR_STATE  VARCHAR2(2)      NULL,
    TXT_INC_RSRC_SRC_ADDR_ZIP    VARCHAR2(10)     NULL,
    ID_CASE                      NUMBER(16)       NULL,
    NBR_PER_DIEM                 NUMBER(5,2)      NULL,
    NBR_PER_MONTH                NUMBER(5,2)      NULL,
    DT_EFF_PER_DIEM              DATE             NULL,
    CD_MED_CLASS_ASST            VARCHAR2(3)      NULL,
    NM_CASEMAN_LAST              VARCHAR2(22)     NULL,
    NM_CASEMAN_FIRST             VARCHAR2(12)     NULL,
    NM_CASEMAN_MIDDLE            VARCHAR2(12)     NULL,
    ADDR_CASEMAN_ADDR_ST_LN_1    VARCHAR2(25)     NULL,
    ADDR_CASEMAN_ADDR_ST_LN_2    VARCHAR2(25)     NULL,
    ADDR_CASEMAN_ADDR_CITY       VARCHAR2(20)     NULL,
    CD_CASEMAN_ADDR_STATE        VARCHAR2(2)      NULL,
    ADDR_CASEMAN_ADDR_ZIP        VARCHAR2(10)     NULL,
    NBR_CASEMAN_PHONE            VARCHAR2(10)     NULL,
    NBR_CASEMAN_FAX              VARCHAR2(10)     NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
GRANT DELETE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO OPERATOR
;

-- Add Constraint SQL

ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND ADD CONSTRAINT PK_CHILDSUP_REF
PRIMARY KEY (ID_CHILDSUP_REF_OUTBOUND)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 1M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;
ALTER TABLE SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND ADD CONSTRAINT PK_CSUP_CHILDHOME_OUTBOUND
PRIMARY KEY (ID_CSUP_CHLDLFTCARE_OUTBOUND)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 1M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;
ALTER TABLE SACWISIFC.CSUP_PARENT_OUTBOUND ADD CONSTRAINT PK_CSUP_PARENT_OUTBOUND
PRIMARY KEY (ID_CSUP_PARENT_OUTBOUND)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 1M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;

-- Add Indexes SQL


-- Add Dependencies SQL
/
DROP TRIGGER SACWISIFC.TIBR_CHILDSUP_REF_OUTBOUND
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_CHILDSUP_REF_OUTBOUND
BEFORE INSERT
ON SACWISIFC.CHILDSUP_REF_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:NEW.ID_CHILDSUP_REF_OUTBOUND IS NULL OR :new.ID_CHILDSUP_REF_OUTBOUND = 0) THEN
    SELECT  SEQ_CHILDSUP_REF_OUTBOUND.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_CHILDSUP_REF_OUTBOUND := dummy;
  END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ----------------------------------
/
/
DROP TRIGGER SACWISIFC.TUBR_CHILDSUP_REF_OUTBOUND
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_CHILDSUP_REF_OUTBOUND
BEFORE UPDATE
ON SACWISIFC.CHILDSUP_REF_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ----------------------------------
/
/
DROP TRIGGER SACWISIFC.TIBR_CSUP_CHLDLFTCARE_OUTBOUND
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_CSUP_CHLDLFTCARE_OUTBOUND
BEFORE INSERT
ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:NEW.ID_CSUP_CHLDLFTCARE_OUTBOUND IS NULL OR :new.ID_CSUP_CHLDLFTCARE_OUTBOUND = 0) THEN
    SELECT  SEQ_CSUP_CHILDLFTCARE_OUTBOUND.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_CSUP_CHLDLFTCARE_OUTBOUND := dummy;
  END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ----------------------------------
/
/
DROP TRIGGER SACWISIFC.TUBR_CSUP_CHLDLFTCARE_OUTBOUND
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_CSUP_CHLDLFTCARE_OUTBOUND
BEFORE UPDATE
ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ----------------------------------
/
/
DROP TRIGGER SACWISIFC.TIBR_CSUP_PARENT_OUTBOUND
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_CSUP_PARENT_OUTBOUND
BEFORE INSERT
ON SACWISIFC.CSUP_PARENT_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:NEW.ID_CSUP_PARENT_OUTBOUND IS NULL OR :new.ID_CSUP_PARENT_OUTBOUND = 0) THEN
    SELECT  SEQ_CSUP_PARENT_OUTBOUND.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_CSUP_PARENT_OUTBOUND := dummy;
  END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ----------------------------------
/
/
DROP TRIGGER SACWISIFC.TUBR_CSUP_PARENT_OUTBOUND
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_CSUP_PARENT_OUTBOUND
BEFORE UPDATE
ON SACWISIFC.CSUP_PARENT_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ----------------------------------
/

-- Add Referencing Foreign Keys SQL

ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND ADD CONSTRAINT FK_AG_CUST_PAR_CSUP_REF
FOREIGN KEY (ID_AGENCY_CUSTODIAL_PARENTS)
REFERENCES SACWISIFC.AGENCY_CUSTODIAL_PARENTS (ID_AGENCY_CUSTODIAL_PARENTS)
ENABLE
;

-- drop table SACWISIFC.CHILDSUP_R_06292007173843000;
-- drop table SACWISIFC.CSUP_CHILD_06292007173844000;
-- drop table SACWISIFC.CSUP_PAREN_06292007173845000;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00003696
UPDATE CAPS.METAPHOR SET TXT_TAB_URL = '/workload/EventSearch/displayEventList' WHERE ID_TAB = 220;

-- change STGAP00003702
UPDATE caps.message
SET txt_message = 'Press OK to add another approver or Cancel to continue.  Your approval will be recorded once the Save button is pressed'
WHERE txt_message_name = 'MSG_CMN_ADD_APRVR';

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (201, 'SacwisRev2', 'static updates, SACWISIFC changes');

commit;


