--STGAP00015624 - Release(3.4) DBCR: Populate CASE_WATCH_HELP

--The attached script populates the CASE_WATCH_FACTOR_HELP table for the Case Watch page.  
--Note that the script includes a delete to clear any data inserted in environments during testing.

DELETE FROM CAPS.CASE_WATCH_FACTOR_HELP;

INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('INV_RESPONSE_TM_HELP','<b>Response Time:</b><br>Response time is only met when all children alleged victims have been seen in person; the date will be set by when the final alleged victim is seen.  If this data appears incorrect please confirm that all children seen were recorded on all contacts made and that the contact method identifies the face to face contacts.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('INV_SPEC_INV_RSRC_HELP','<b>Special Investigation Resource ID:</b><br>Special Investigations are indicated by selecting a Resource ID on Intake Information while recording the Intake.  Since Intake data is frozen on approval corrections to the resource selection may require a data fix.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('INV_SPEC_INV_STAFF_HELP','<b>Date of 48 Hour Special Investigation Staffing:</b><br>All Special Investigations require a 48 Hour Staffing, to be entered as a contact on Contacts and Summaries with a purpose of Special Investigation - 48 hour staffing.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ONG_CONTACT_HELP','<b>Principal Contacts:</b><br>All principals in CPS Ongoing cases should be seen every month in most circumstances.  Ensure that face to face contacts are marked and that all principals seen are indicated on the Contact Detail page.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ONG_SAFETY_RSRC_HELP','<b>Safety Resource Placements:</b><br>Ensure that children are not remaining in safety resource placements beyond policy guidelines.  If the child has returned home terminate the safety resource placement as soon as this occurs.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ONG_FTM_HELP','<b>Date of Last Family Team Meeting:</b><br>Family Team Meetings are always to be entered using the Team Meeting/Review page.  When entering FTM, please ensure that all participants are marked in the participation section.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ONG_RISK_LEVEL_HELP','<b>Current Level of Risk:</b><br>Update the level of risk as Re-Assessments are done during the CPS Ongoing stage, including at CPS Ongoing stage closure.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_CUSTODY_HELP','<b>Current Custody Status:</b><br>SHINES tracks the exit of a child from foster care based on the date of the Legal Status marking that the child is no longer in DFCS custody.  If the child had exited custody, update the Legal Status as soon as possible to ensure that the discharge is recorded, even if the FCC stage remains open due to other factors.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_ELIGIBILE_HELP','<b>Is the child ECEM Eligible:</b><br>To be ECEM eligible, the child must be in care at least one day prior to the first day of the month and not exit care during the current month. If the child is showing as eligible but has actually exited care, update the child''s legal status to show the child is no longer in custody.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_CHILD_SEEN_HELP','<b>Child Seen During Month:</b><br>An ECEM contact is an announced or unannounced, face-to-face, purposeful contact made to a child in foster care or a pre-adoptive placement by an assigned or contracted case manager.<br>If a contact, which meets the above criteria, has in fact been made, but is not showing as such, go to the contact detail page to update or re-enter the contact correctly into the system.<br>If a contact, which meets the above criteria has not been made, make and enter such a contact prior to the end of the month.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_IN_HOME_HELP','<b>In Home:</b><br>An ECEM contact is an announced or unannounced, face-to-face, purposeful contact made to a child in foster care or a pre-adoptive placement by an assigned or contracted case manager.<br>For a contact to be considered one that has been made in the home, by ECEM standards, the contact must have occurred where the child resides.<br>A child''s residence is defined as the home where the child is residing, whether in-state or out-of-state, and can include the foster home, CCI/CPA, or the home from which the child was removed if the child is on a trial visit home.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_PRIV_CONVER_HELP','<b>Private Conversation:</b><br>An ECEM contact is counted as one where the child was interviewed privately when this action has been indicated on the contact detail page.<br>If the case manager in fact had a private conversation with the child during the ECEM contact, but this indicator is not showing as such, go to the contact detail page and make the necessary correction.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_SPWB_NARR_HELP','<b>Safety, Permanency, and Well Being Narrative:</b><br>Safety, Permanency, and Well Being should be addressed during the purposeful visit and recorded using the Safety, Permanency, and Well Being narrative available on the Contact Detail page.  To enter this narrative select the appropriate narrative radio button.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_DFCS_CNTCT_HELP','<b>Case Manager Contact:</b><br>ECEM contacts may be made by a DFCS case manager or a designee (a case worker, private provider or other party, whether in-state or out-of-state, which DFCS has assigned/contracted case management or visitation responsibilities) to meet ECEM frequency standards.<br>However, monitor contacts to the child to ensure enough of them are being made by DFCS case managers to meet CFSR quality standards.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_HOME_PERCENT_HELP','<b>% of Months ECEM Eligible Contact Has Been Made in the Home this Federal Fiscal Year:</b><br>ECEM standards require that a majority of ECEM contacts for the fiscal year be made in the child''s residence.<br>A child''s residence is defined as the home where the child is residing, whether in-state or out-of-state, and can include the foster home, CCI/CPA, or the home from which the child was removed if the child is on a trial visit home.<br>If a contact made in a child''s home has not been captured, go to contact detail page and make sure "residence," "foster home," "adoptive home," or "facility" has been selected.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_ECEM_COMPLIANT_HELP','<b>Has the Child Been Seen Every Month Under ECEM Standards this Federal Fiscal Year:</b><br>ECEM standards require a child to be seen every month they are in care for a full calendar month.<br>If the result of this indicator inaccurately shows this child as non-ECEM compliant (did not get a purposeful visit every month a visit was required), go to the contact detail page and verify your contacts.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('ECEM_DFCS_PERCENT_HELP','<b>% of Months the Child Has Been Seen by DFCS Case Manager This Federal Fiscal Year:</b><br>Children in care are to receive an announced or unannounced, purposeful, face-to-face, contact from agency staff all of the months they are in care.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_PERM_GOALS_HELP','<b>Permanency Goals:</b><br>The child''s permanency goal will be defined by the primary permanency goal on the most recent approved Foster Care Case Plan Family Plan on which the child was included as a principal.  If this is blank or incorrect, verify that the child is chosen on the plan and that the plan is approved.  If siblings have different primary goals, they should have different primary plans, not a single concurrent plan. ');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_CP_REVIEW_DATE_HELP','<b>Last Case Plan Review Date:</b><br>SHINES tracking of court or citizen reviews tracks the following Legal Actions and Outcomes:<br>Legal Action of Citizen''s Panel Review<br>Legal Action of Panel/Admin<br>Legal Action of Hearing with a Hearing/Court Order Type of Judicial Review<br><br>When entering the most recent review ensure that one of these is selected, including selecting the hearing type.  Also ensure that the legal action is entered for all children in care in each child''s stage.  Finally, if necessary update the child''s legal status or custody expiration date.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_PERM_REVIEW_DATE_HELP','<b>Date of Last Permanency Review Hearing:</b><br>SHINES tracking of court or permanency review hearings by looking for the following Legal Actions and Outcomes:<br>Legal Action of Hearing with a Hearing/Court Order type of Permanency<br><br>When entering the most recent review ensure that one of these is selected, including selecting the hearing type.  Also ensure that the legal action is entered for all children in care in each child''s stage.  Finally, if necessary update the child''s legal status or custody expiration date.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_FTM_HELP','<b>Date of Last Family Team Meeting:</b><br>Family Team Meetings are always to be entered using the Team Meeting/Review page.  When entering FTM, please ensure that all participants are marked in the participation section.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_ELIG_DETERMINATION_HELP','<b>IV-E Determination/Re-Determination Due Date:</b><br>Initial Foster Care Determinations are due within 60 days of the child entering care, after which Re-Determinations are due every 6 months.  Please note that it is important to submit Re-Determinations on a timely basis even if work has been done with Rev Max in the interim by submitting notifications of change.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_15_OF_22_HELP','<b>Number of Months in Care Out of Last 22:</b><br>A child is determined to have been in care during a month under the 15 of 22 months standard if the child was in the legal custody of the agency and in an out of home placement any day during that month.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_TPR_HELP','<b>TPR:</b><br>TPR petition is recorded with a Legal Action of type Petition and Order type of TPR for the appropriate relationship to the child.  Ensure that Legal Actions have been included for each child in sibling cases.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_ASFA_FLAG_HELP','<b>Does Case Plan ASFA Flag Indicate The Child Has Been in Care 15 of 22 Months:</b><br>Case Plan ASFA flag must match facts of case regarding months in care.  Be careful when copying Child Plans when this value may have changed.  If incorrect, create and complete the new Child Plan necessary to correct the value.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_TPR_COMMENTS_HELP','<b>Case Plan Comments Provided on Reasons Why TPR Has Not Been Filed:</b><br>Comments must exist in the Child Plan if the child has been in care over 15 months or other non-reunification flags are set and no TPR has been filed.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_HEALTH_SCREENS_HELP','<b>Date of Most Recent Screens:</b><br>Children in care are to initial health screens followed by recurring medical screens to look after the child''s health and wellbeing.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_CASA_GAL_HELP','<b>CASA/GAL Involvement:</b><br>Children in care should have a Court Appointed Special Advocate or Guardian Ad Litem.  If such persons exist for the child include them in the person list as collaterals for the FCC and ADO stages.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_ASSIGNED_ILP_HELP','<b>Assigned ILP Coordinator:</b><br>Children Eligible for ILP services should have an ILP coordinator assigned as a secondary worker to the child''s current FCC stage.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_WTLP_COORD_HELP','<b>ILP Coordinator Identified on WTLP:</b><br>Children reaching 14 years of age are required to have Written Transitional Living Plans and to be referred to Independent Living services even if the permanency plan is not for independent living.  Children should have up to date WTLP included in case plan reviews including up to date references to the current ILP case manager for the child.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_DILIGENT_SEARCH_CNTCT_HELP','<b>Date of Most Recent Diligent Search Contact:</b><br>Diligent searches should be recorded based on continuous search effort for missing persons.  Record diligent searches for unknown relatives using contacts with a purpose of Diligent Search, and document the persons searched for in the contact narrative.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_PARENTAL_CONTACT_HELP','<b>Date of Parental Contacts:</b><br>Case Managers should visit Every Parent Every Month while the case plan remains reunification.');
INSERT INTO CAPS.CASE_WATCH_FACTOR_HELP(TXT_CASE_WATCH_FACTOR,TXT_CASE_WATCH_FACTOR_HLP_TXT) VALUES ('FC_SIBLING_CONTACT_HELP','<b>Date of Most Recent Sibling Contact:</b><br>Sibling visits should be recorded in SHINES using contacts with a purpose of Sibling Visit and the siblings who visited marked as persons on the contact.');


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (627, 'SacwisRev3', 'Release 3.4 - DBCR 15624');

commit;

