--STGAP00015871 - Release(3.5) MR-62: Update table CS_SUMMARY_COMP_LOOKUP

INSERT INTO CAPS.CS_SUMMARY_COMP_LOOKUP (IND_FATHER_RULE_COMP, IND_MOTHER_RULE_COMP, IND_CTK_RULE_COMP) VALUES ('U', 'Y', ' ');

INSERT INTO CAPS.CS_SUMMARY_COMP_LOOKUP (IND_FATHER_RULE_COMP, IND_MOTHER_RULE_COMP, IND_CTK_RULE_COMP) VALUES ('U', 'Y', 'Y');

INSERT INTO CAPS.CS_SUMMARY_COMP_LOOKUP (IND_FATHER_RULE_COMP, IND_MOTHER_RULE_COMP, IND_CTK_RULE_COMP) VALUES ('Y', 'U', ' ');

INSERT INTO CAPS.CS_SUMMARY_COMP_LOOKUP (IND_FATHER_RULE_COMP, IND_MOTHER_RULE_COMP, IND_CTK_RULE_COMP) VALUES ('Y', 'U', 'Y');

INSERT INTO CAPS.CS_SUMMARY_COMP_LOOKUP (IND_FATHER_RULE_COMP, IND_MOTHER_RULE_COMP, IND_CTK_RULE_COMP) VALUES ('U', 'U', 'Y');

UPDATE CAPS.CS_SUMMARY_COMP_LOOKUP SET IND_CTK_RULE_COMP = ' ' WHERE ID_CS_SUMMARY_COMP_LOOKUP = 2;

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (805, 'SacwisRev3', 'Release 3.5 - DBCR 15871');

commit;


