--STGAP00012754 - Change to REPORT_LIST

--Note:  no impact to ado model


alter table caps.report_list add (nm_rpt_type varchar2(1));
comment on column caps.report_list.nm_rpt_type is 'Type of report generated';

-- alter table caps.report_list drop nm_rpt_type;

--STGAP00012716 - UDR Details and Parameters

--Note:   no impact to ado model


INSERT INTO CAPS.REPORTS
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE,
TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION,
TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE, CD_SEC_ATTR)
VALUES
('UDRIntakeAllegationsRept', '00','7', 'U',
'Investigation Allegations', 'ondport', 'L',
'W', 'This is a population of alleged and substantiated victims of allegations on investigation (INV) stages active at some point during the reporting period. Details related to the overall investigation are also provided for each victim record.', 'User Defined Reports', 'Y', '');

INSERT INTO CAPS.REPORTS
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE,
TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION,
TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE, CD_SEC_ATTR)
VALUES
('UDRFosterCareChildrenRept', '00','7', 'U',
'Foster Care Children', 'ondport', 'L',
'W', 'This is a population of children in either FCC or ADO stages active during the reporting period where the child also was in DFCS custody at some time during the reporting period.  Children with both an FCC and ADO stage open during the reporting period within the same overall case ID are listed once', 'User Defined Reports', 'Y', '');

INSERT INTO CAPS.REPORTS
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE,
TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION,
TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE, CD_SEC_ATTR)
VALUES
('UDRResourceDevRept', '00','7', 'U','Resource Development', 'ondport', 'L','W', 'This is list of Foster, Foster to Adopt, and Adoptive Homes recorded as FAD stages.  This list does not include resources outside of the FAD stage.  This list is further restricted to only homes that were in one of three active statuses as of the last day of the reporting period.', 'User Defined Reports', 'Y', '');

INSERT INTO CAPS.REPORTS
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE,
TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION,
TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE, CD_SEC_ATTR)
VALUES
('UDROngoingRept', '00','7', 'U',
'Ongoing', 'ondport', 'L',
'W', 'This is a population of ongoing (ONG) stages active at some point during the reporting period.  Results return one record per ongoing stage.', 'User Defined Reports', 'Y', '');


INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRIntakeAllegationsRept','00','1','10','BEGINDATE','DATE','Y','Date From (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRIntakeAllegationsRept','00','2','10','ENDDATE','DATE','Y','Date To (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRIntakeAllegationsRept','00','3','2','REGIONCD','CHAR','Y','Region');

INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRIntakeAllegationsRept','00','4','3','COUNTYCD','NUMBER','N','County');

INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRIntakeAllegationsRept','00','5','16','STAFFID','NUMBER','N','Staff Selection');


INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRFosterCareChildrenRept','00','1','10','BEGINDATE','DATE','Y','Date From (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRFosterCareChildrenRept','00','2','10','ENDDATE','DATE','Y','Date To (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRFosterCareChildrenRept','00','3','2','REGIONCD','CHAR','Y','Region');

INSERT INTO CAPS.REPORT_PARAMETER
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES
('UDRFosterCareChildrenRept','00','4','3','COUNTYCD','NUMBER','N','County');


INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDRFosterCareChildrenRept','00','5','16','STAFFID','NUMBER','N','Staff Selection');


INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDRResourceDevRept','00','1','10','BEGINDATE','DATE','Y','Date From (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDRResourceDevRept','00','2','10','ENDDATE','DATE','Y','Date To (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDRResourceDevRept','00','3','2','REGIONCD','CHAR','Y','Region');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDRResourceDevRept','00','4','3','COUNTYCD','NUMBER','N','County');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDRResourceDevRept','00','5','16','STAFFID','NUMBER','N','Staff Selection');


INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDROngoingRept','00','1','10','BEGINDATE','DATE','Y','Date From (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDROngoingRept','00','2','10','ENDDATE','DATE','Y','Date To (MM/DD/YYYY)');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDROngoingRept','00','3','2','REGIONCD','CHAR','Y','Region');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDROngoingRept','00','4','3','COUNTYCD','NUMBER','N','County');

INSERT INTO CAPS.REPORT_PARAMETER 
(NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ,
NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE,
IND_REQUIRED, NM_RPT_PARM_LABEL)
VALUES 
('UDROngoingRept','00','5','16','STAFFID','NUMBER','N','Staff Selection');



insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (443, 'SacwisRev3', 'Release 3.1 - DBCRs 12716,12754');

commit;


