--STGAP00010022 - Home Conversion - Need to correct the Task decode.

update CAPS.Task
set TXT_TASK_DECODE = 'Approve Home Conversion'
where CD_TASK = '9998';


--STGAP00010024 - Exchange Child Detail - Need new event type

Insert into CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_END,DT_LAST_UPDATE)
values ('CEVNTTYP','EXC','Exchange Child Registration',null,sysdate);


--STGAP00010029 - Exchange Home Detail - Need new event type

Insert into caps.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_END,DT_LAST_UPDATE)
values ('CEVNTTYP','EHR','Exchange Home Registration',null,sysdate);


--STGAP00010030 - Exchange Child Detail - New Task Codes

INSERT INTO CAPS.TASK ( CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE )
VALUES ('9530',  SYSDATE , 'EXC', 'ADO', 'CPS', '1', '1', '1', '0', '0', '0', '1', 'Exchange Child Registration', 'CASE_CASESEARCH', 'PERSON_PERSONLIST', 'EXCHANGE_CHILD_EVENTLIST', '/person/ExchangeChildDetail/displayExchangeChildDetail', 4, '1', '0', '0'); 

INSERT INTO CAPS.TASK ( CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING
, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE )
VALUES ('9531',  SYSDATE , 'EXC', 'PAD', 'CPS', '1', '1', '1', '0', '0', '0', '1', 'Exchange Child Registration', 'CASE_CASESEARCH', 'PERSON_PERSONLIST', 'EXCHANGE_CHILD_EVENTLIST', '/person/ExchangeChildDetail/displayExchangeChildDetail', 4, '1', '0', '0');


--STGAP00010033 - Exchange Detail - Metaphor table update

UPDATE CAPS.METAPHOR
SET TXT_TAB_URL = '/workload/EventSearch/displayEventList'
WHERE ID_TAB = 1620;


--STGAP00010036 - New Task for Exchange Home Detail

Insert into CAPS.TASK
(CD_TASK,DT_LAST_UPDATE,CD_TASK_EVENT_STATUS,CD_TASK_EVENT_TYPE,CD_TASK_LIST_WINDOW,CD_TASK_PRIOR,CD_TASK_STAGE,CD_TASK_STAGE_PROGRAM,CD_TASK_TOP_WINDOW,IND_TASK_DETAIL_ENABLE,IND_TASK_EVENT_CREATE,IND_TASK_EVENT_NAVIG,IND_TASK_LIST_ENABLE,
IND_TASK_MULTIPLE_INSTANCE,IND_TASK_NEW_ENABLE,IND_TASK_NEW_USING,IND_TASK_NU_ACROSS_CASE,IND_TASK_RTRV_PRIOR_STAGE,IND_TASK_SHOW_IN_LIST,IND_TASK_TODO_ENABLE,
TXT_TASK_DECODE,TXT_1ST_TAB,TXT_2ND_TAB,TXT_3RD_TAB,TXT_EVENT_DETAIL_URL,IND_TASK_CODE_PREFER,IND_TASK_NEW_CASE_TODO_ENABLE,IND_TASK_FORCE_EVENT_LINK,IND_STAGE_CLOSURE)
values ('8085',sysdate,'COMP','EHR','CCMN51W',null,'FAD','CPS','CSUB09C',null,'1','1',null,'1',null,'1','0','0','1',null,'Exchange Home Registration','CASE_CASESEARCH','HOME_INFORMATION_HOMEINFRMTN','EXCHANGE_HOME_DETAIL','/fad/ExchangeHomeDetail/displayExchangeHomeDetail','3','1','0','0');


--STGAP00010037 - Update METAPHOR table for Exchange Home Detail

update CAPS.METAPHOR set TXT_TAB_URL = '/workload/EventSearch/displayEventList', TXT_TAB_CONSTANT = 'EXCHANGE_HOME_DETAIL', TXT_TAB = 'Exchange Home' where ID_TAB =1630;

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (372, 'SacwisRev3', 'Release 3.0 - DBCRs 10022,10024,10029,10030,10033,10036,10037');

commit;

