-- change STGAP00006200

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CFLSVLNK','609SB','609',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CFLSVLNK','610SB','610',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CFLSVLNK','611SB','611',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CFLSVLNK','613SB','613',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CFLSVLNK','614SB','614',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CFLSVLNK','616SB','616',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CSVCCODE','609SB','609SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CSVCCODE','610SB','610SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CSVCCODE','611SB','611SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CSVCCODE','613SB','613SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CSVCCODE','614SB','614SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CSVCCODE','616SB','616SB - Sibling Subsidy',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CADDONLI','609SB','609SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CADDONLI','610SB','610SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CADDONLI','611SB','611SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CADDONLI','613SB','613SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CADDONLI','614SB','614SB - Sibling Subsidy',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CADDONLI','616SB','616SB - Sibling Subsidy',SYSDATE);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES (0,'SB','609SB','609','ALL','ALL','609SB',TO_DATE('09/01/2007','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES (0,'SB','610SB','610','ALL','ALL','610SB',TO_DATE('09/01/2007','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES (0,'SB','611SB','611','ALL','ALL','611SB',TO_DATE('09/01/2007','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES (0,'SB','613SB','613','ALL','ALL','613SB',TO_DATE('09/01/2007','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0); 

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES (0,'SB','614SB','614','ALL','ALL','614SB',TO_DATE('09/01/2007','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES (0,'SB','616SB','616','ALL','ALL','616SB',TO_DATE('09/01/2007','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','609SB','609SB',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','609SB','XXX',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','609SB','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','609SB','100',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','610SB','610SB',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','610SB','XXX',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','610SB','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','610SB','100',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','611SB','611SB',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','611SB','XXX',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','611SB','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','611SB','100',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','613SB','613SB',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','613SB','XXX',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','613SB','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','613SB','100',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','614SB','614SB',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','614SB','XXX',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','614SB','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','614SB','100',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','616SB','616SB',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','616SB','XXX',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','616SB','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','616SB','100',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','52060','52060',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','52060','DA2',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','52060','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','52060','18.80',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPASVCD','52094','52094',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTYP','52094','XXX',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAPTYP','52094','URT',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCPAUTRT','52094','18.80',SYSDATE);


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (255, 'SacwisRev2', 'changes to account for CPA Sibling subsidies');                        
commit;
