--STGAP00017261 - Release(5.0) update codes_table decode values                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                            
update caps.codes_tables                                                                                                                                                                                                                                                                                    
set decode = 'Hearing Impaired - Diagnosed'                                                                                                                                                                                                                                                                 
where code_type = 'HVI1'                                                                                                                                                                                                                                                                                    
and code = '36';                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
update caps.codes_tables                                                                                                                                                                                                                                                                                    
set decode = 'Visually Impaired - Diagnosed'                                                                                                                                                                                                                                                                
where code_type = 'HVI1'                                                                                                                                                                                                                                                                                    
and code = '84';                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
insert into caps.schema_version(id_schema_version,application_version,comments)                                                                                                                                                                                                                             
            values (1142, 'SacwisRev5', 'Release 5.0 - DBCR 17261');                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                           
commit;