--STGAP00015673 - Release(3.41) Add ques text num to case_review_ques_lookup

--The attached script creates a new column in the case_review_ques_lookup table and 
--populates a decoded question number.  This number is more intuitive for business 
--purposes and uses the Item Number and the question sequence to create a new number
--such as 1.1, 1.2, 1.3, 1.4, etc.  The query below can be used to validate the 
--insert statements ran correctly.

alter table caps.case_review_ques_lookup add (txt_question_num  varchar2(20));

update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.1' where case_review_ques_lookup.CD_QUESTION = 'Q01';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.2' where case_review_ques_lookup.CD_QUESTION = 'Q02';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.3' where case_review_ques_lookup.CD_QUESTION = 'Q03';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.4' where case_review_ques_lookup.CD_QUESTION = 'Q04';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.5' where case_review_ques_lookup.CD_QUESTION = 'Q05';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.6' where case_review_ques_lookup.CD_QUESTION = 'Q06';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.6' where case_review_ques_lookup.CD_QUESTION = 'Q06';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.7' where case_review_ques_lookup.CD_QUESTION = 'Q07';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '1.8' where case_review_ques_lookup.CD_QUESTION = 'Q08';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '10.1' where case_review_ques_lookup.CD_QUESTION = 'Q81';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '10.2' where case_review_ques_lookup.CD_QUESTION = 'Q82';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '10.3' where case_review_ques_lookup.CD_QUESTION = 'Q83';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '10.4' where case_review_ques_lookup.CD_QUESTION = 'Q84';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '10.5' where case_review_ques_lookup.CD_QUESTION = 'Q85';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '10.6' where case_review_ques_lookup.CD_QUESTION = 'Q86';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '10.7' where case_review_ques_lookup.CD_QUESTION = 'Q87';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '11.1' where case_review_ques_lookup.CD_QUESTION = 'Q88';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '11.2' where case_review_ques_lookup.CD_QUESTION = 'Q89';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '11.3' where case_review_ques_lookup.CD_QUESTION = 'Q90';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '11.4' where case_review_ques_lookup.CD_QUESTION = 'Q91';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '11.5' where case_review_ques_lookup.CD_QUESTION = 'Q92';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '11.6' where case_review_ques_lookup.CD_QUESTION = 'Q93';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '12.1' where case_review_ques_lookup.CD_QUESTION = 'Q94';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '12.2' where case_review_ques_lookup.CD_QUESTION = 'Q95';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '12.3' where case_review_ques_lookup.CD_QUESTION = 'Q96';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '12.4' where case_review_ques_lookup.CD_QUESTION = 'Q97';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '13.1' where case_review_ques_lookup.CD_QUESTION = 'Q98';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '13.2' where case_review_ques_lookup.CD_QUESTION = 'Q99';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '13.3' where case_review_ques_lookup.CD_QUESTION = 'Q100';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '13.4' where case_review_ques_lookup.CD_QUESTION = 'Q101';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '13.5' where case_review_ques_lookup.CD_QUESTION = 'Q102';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '13.6' where case_review_ques_lookup.CD_QUESTION = 'Q103';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '13.7' where case_review_ques_lookup.CD_QUESTION = 'Q104';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.1' where case_review_ques_lookup.CD_QUESTION = 'Q105';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.2' where case_review_ques_lookup.CD_QUESTION = 'Q106';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.3' where case_review_ques_lookup.CD_QUESTION = 'Q107';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.4' where case_review_ques_lookup.CD_QUESTION = 'Q108';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.5' where case_review_ques_lookup.CD_QUESTION = 'Q109';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.6' where case_review_ques_lookup.CD_QUESTION = 'Q110';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.7' where case_review_ques_lookup.CD_QUESTION = 'Q111';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '14.8' where case_review_ques_lookup.CD_QUESTION = 'Q112';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '15.1' where case_review_ques_lookup.CD_QUESTION = 'Q113';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '15.2' where case_review_ques_lookup.CD_QUESTION = 'Q114';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '15.3' where case_review_ques_lookup.CD_QUESTION = 'Q115';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '15.4' where case_review_ques_lookup.CD_QUESTION = 'Q116';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '15.5' where case_review_ques_lookup.CD_QUESTION = 'Q117';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '15.6' where case_review_ques_lookup.CD_QUESTION = 'Q118';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '15.7' where case_review_ques_lookup.CD_QUESTION = 'Q119';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '16.1' where case_review_ques_lookup.CD_QUESTION = 'Q120';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '16.2' where case_review_ques_lookup.CD_QUESTION = 'Q121';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '16.3' where case_review_ques_lookup.CD_QUESTION = 'Q122';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '16.4' where case_review_ques_lookup.CD_QUESTION = 'Q123';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.1' where case_review_ques_lookup.CD_QUESTION = 'Q124';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.2' where case_review_ques_lookup.CD_QUESTION = 'Q125';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.3' where case_review_ques_lookup.CD_QUESTION = 'Q126';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.4' where case_review_ques_lookup.CD_QUESTION = 'Q127';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.5' where case_review_ques_lookup.CD_QUESTION = 'Q128';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.6' where case_review_ques_lookup.CD_QUESTION = 'Q129';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.7' where case_review_ques_lookup.CD_QUESTION = 'Q130';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.8' where case_review_ques_lookup.CD_QUESTION = 'Q131';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.9' where case_review_ques_lookup.CD_QUESTION = 'Q132';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.10' where case_review_ques_lookup.CD_QUESTION = 'Q133';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '17.11' where case_review_ques_lookup.CD_QUESTION = 'Q134';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.1' where case_review_ques_lookup.CD_QUESTION = 'Q135';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.2' where case_review_ques_lookup.CD_QUESTION = 'Q136';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.3' where case_review_ques_lookup.CD_QUESTION = 'Q137';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.4' where case_review_ques_lookup.CD_QUESTION = 'Q138';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.5' where case_review_ques_lookup.CD_QUESTION = 'Q139';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.6' where case_review_ques_lookup.CD_QUESTION = 'Q140';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.7' where case_review_ques_lookup.CD_QUESTION = 'Q172';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.7' where case_review_ques_lookup.CD_QUESTION = 'Q172';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.8' where case_review_ques_lookup.CD_QUESTION = 'Q173';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.9' where case_review_ques_lookup.CD_QUESTION = 'Q174';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '18.10' where case_review_ques_lookup.CD_QUESTION = 'Q175';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '19.1' where case_review_ques_lookup.CD_QUESTION = 'Q141';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '19.2' where case_review_ques_lookup.CD_QUESTION = 'Q142';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '19.3' where case_review_ques_lookup.CD_QUESTION = 'Q143';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '19.4' where case_review_ques_lookup.CD_QUESTION = 'Q144';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '19.5' where case_review_ques_lookup.CD_QUESTION = 'Q145';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '2.1' where case_review_ques_lookup.CD_QUESTION = 'Q09';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '2.2' where case_review_ques_lookup.CD_QUESTION = 'Q10';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '2.3' where case_review_ques_lookup.CD_QUESTION = 'Q11';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '2.4' where case_review_ques_lookup.CD_QUESTION = 'Q12';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '2.5' where case_review_ques_lookup.CD_QUESTION = 'Q13';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '20.1' where case_review_ques_lookup.CD_QUESTION = 'Q146';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '20.2' where case_review_ques_lookup.CD_QUESTION = 'Q147';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '20.3' where case_review_ques_lookup.CD_QUESTION = 'Q148';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '20.4' where case_review_ques_lookup.CD_QUESTION = 'Q149';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '20.5' where case_review_ques_lookup.CD_QUESTION = 'Q150';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '20.6' where case_review_ques_lookup.CD_QUESTION = 'Q151';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '20.7' where case_review_ques_lookup.CD_QUESTION = 'Q152';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '21.1' where case_review_ques_lookup.CD_QUESTION = 'Q153';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '21.2' where case_review_ques_lookup.CD_QUESTION = 'Q154';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '21.3' where case_review_ques_lookup.CD_QUESTION = 'Q155';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '21.4' where case_review_ques_lookup.CD_QUESTION = 'Q156';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '21.4' where case_review_ques_lookup.CD_QUESTION = 'Q156';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '21.5' where case_review_ques_lookup.CD_QUESTION = 'Q157';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '21.6' where case_review_ques_lookup.CD_QUESTION = 'Q158';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.1' where case_review_ques_lookup.CD_QUESTION = 'Q159';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.2' where case_review_ques_lookup.CD_QUESTION = 'Q160';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.3' where case_review_ques_lookup.CD_QUESTION = 'Q161';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.4' where case_review_ques_lookup.CD_QUESTION = 'Q162';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.5' where case_review_ques_lookup.CD_QUESTION = 'Q163';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.5' where case_review_ques_lookup.CD_QUESTION = 'Q163';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.6' where case_review_ques_lookup.CD_QUESTION = 'Q164';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '22.7' where case_review_ques_lookup.CD_QUESTION = 'Q165';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '23.1' where case_review_ques_lookup.CD_QUESTION = 'Q166';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '23.2' where case_review_ques_lookup.CD_QUESTION = 'Q167';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '23.3' where case_review_ques_lookup.CD_QUESTION = 'Q168';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '23.4' where case_review_ques_lookup.CD_QUESTION = 'Q169';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '23.4' where case_review_ques_lookup.CD_QUESTION = 'Q169';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '23.5' where case_review_ques_lookup.CD_QUESTION = 'Q170';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '23.6' where case_review_ques_lookup.CD_QUESTION = 'Q171';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '3.1' where case_review_ques_lookup.CD_QUESTION = 'Q14';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '3.2' where case_review_ques_lookup.CD_QUESTION = 'Q15';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '3.3' where case_review_ques_lookup.CD_QUESTION = 'Q16';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '3.4' where case_review_ques_lookup.CD_QUESTION = 'Q17';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '3.5' where case_review_ques_lookup.CD_QUESTION = 'Q18';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '3.6' where case_review_ques_lookup.CD_QUESTION = 'Q19';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.1' where case_review_ques_lookup.CD_QUESTION = 'Q20';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.2' where case_review_ques_lookup.CD_QUESTION = 'Q21';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.3' where case_review_ques_lookup.CD_QUESTION = 'Q22';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.3' where case_review_ques_lookup.CD_QUESTION = 'Q22';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.4' where case_review_ques_lookup.CD_QUESTION = 'Q23';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.4' where case_review_ques_lookup.CD_QUESTION = 'Q23';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.5' where case_review_ques_lookup.CD_QUESTION = 'Q24';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.6' where case_review_ques_lookup.CD_QUESTION = 'Q25';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.7' where case_review_ques_lookup.CD_QUESTION = 'Q26';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.7' where case_review_ques_lookup.CD_QUESTION = 'Q26';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.8' where case_review_ques_lookup.CD_QUESTION = 'Q27';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.9' where case_review_ques_lookup.CD_QUESTION = 'Q28';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.10' where case_review_ques_lookup.CD_QUESTION = 'Q29';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.11' where case_review_ques_lookup.CD_QUESTION = 'Q30';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.12' where case_review_ques_lookup.CD_QUESTION = 'Q31';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.13' where case_review_ques_lookup.CD_QUESTION = 'Q32';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.14' where case_review_ques_lookup.CD_QUESTION = 'Q33';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.15' where case_review_ques_lookup.CD_QUESTION = 'Q34';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.16' where case_review_ques_lookup.CD_QUESTION = 'Q35';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.17' where case_review_ques_lookup.CD_QUESTION = 'Q36';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.18' where case_review_ques_lookup.CD_QUESTION = 'Q37';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.19' where case_review_ques_lookup.CD_QUESTION = 'Q38';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.20' where case_review_ques_lookup.CD_QUESTION = 'Q39';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '4.21' where case_review_ques_lookup.CD_QUESTION = 'Q40';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '5.1' where case_review_ques_lookup.CD_QUESTION = 'Q41';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '5.2' where case_review_ques_lookup.CD_QUESTION = 'Q42';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '5.3' where case_review_ques_lookup.CD_QUESTION = 'Q43';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '5.4' where case_review_ques_lookup.CD_QUESTION = 'Q44';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '6.1' where case_review_ques_lookup.CD_QUESTION = 'Q45';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '6.2' where case_review_ques_lookup.CD_QUESTION = 'Q46';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '6.3' where case_review_ques_lookup.CD_QUESTION = 'Q47';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '6.4' where case_review_ques_lookup.CD_QUESTION = 'Q48';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.1' where case_review_ques_lookup.CD_QUESTION = 'Q49';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.2' where case_review_ques_lookup.CD_QUESTION = 'Q50';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.3' where case_review_ques_lookup.CD_QUESTION = 'Q51';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.4' where case_review_ques_lookup.CD_QUESTION = 'Q52';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.5' where case_review_ques_lookup.CD_QUESTION = 'Q53';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.6' where case_review_ques_lookup.CD_QUESTION = 'Q54';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.7' where case_review_ques_lookup.CD_QUESTION = 'Q55';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.8' where case_review_ques_lookup.CD_QUESTION = 'Q56';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.9' where case_review_ques_lookup.CD_QUESTION = 'Q57';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.10' where case_review_ques_lookup.CD_QUESTION = 'Q58';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.11' where case_review_ques_lookup.CD_QUESTION = 'Q59';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.12' where case_review_ques_lookup.CD_QUESTION = 'Q60';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.13' where case_review_ques_lookup.CD_QUESTION = 'Q61';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '7.14' where case_review_ques_lookup.CD_QUESTION = 'Q62';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '8.1' where case_review_ques_lookup.CD_QUESTION = 'Q63';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '8.2' where case_review_ques_lookup.CD_QUESTION = 'Q64';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '8.3' where case_review_ques_lookup.CD_QUESTION = 'Q65';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '8.4' where case_review_ques_lookup.CD_QUESTION = 'Q66';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '8.5' where case_review_ques_lookup.CD_QUESTION = 'Q67';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '8.6' where case_review_ques_lookup.CD_QUESTION = 'Q68';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.1' where case_review_ques_lookup.CD_QUESTION = 'Q69';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.2' where case_review_ques_lookup.CD_QUESTION = 'Q70';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.3' where case_review_ques_lookup.CD_QUESTION = 'Q71';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.4' where case_review_ques_lookup.CD_QUESTION = 'Q72';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.5' where case_review_ques_lookup.CD_QUESTION = 'Q73';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.5' where case_review_ques_lookup.CD_QUESTION = 'Q73';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.6' where case_review_ques_lookup.CD_QUESTION = 'Q74';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.7' where case_review_ques_lookup.CD_QUESTION = 'Q75';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.8' where case_review_ques_lookup.CD_QUESTION = 'Q76';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.9' where case_review_ques_lookup.CD_QUESTION = 'Q77';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.10' where case_review_ques_lookup.CD_QUESTION = 'Q78';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.11' where case_review_ques_lookup.CD_QUESTION = 'Q79';
update caps.case_review_ques_lookup set case_review_ques_lookup.txt_question_num = '9.12' where case_review_ques_lookup.CD_QUESTION = 'Q80';




insert into caps.schema_version(id_schema_version,application_version,comments)
            values (663, 'SacwisRev3', 'Release 3.41 - DBCR 15673');

 
commit;


