
-- Standard Alter Table SQL

ALTER TABLE CAPS.ADMIN_DTL MODIFY(CD_ADMIN_DTL_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.CAPS_RESOURCE MODIFY(CD_ELEM  VARCHAR2(10))
;
ALTER TABLE CAPS.CAPS_RESOURCE MODIFY(CD_MIDDLE  VARCHAR2(10))
;
ALTER TABLE CAPS.CAPS_RESOURCE MODIFY(CD_HIGH  VARCHAR2(10))
;
ALTER TABLE CAPS.CONTRACT_COUNTY MODIFY(CD_CNCNTY_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.CONTRACT_COUNTY_AUDIT MODIFY(CD_CNCNTY_AUD_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.CONTRACT_SERVICE MODIFY(CD_CNSVC_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.CONTRACT_SERVICE_AUDIT MODIFY(CD_CNSVC_AUD_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.COST_REIM_DTL MODIFY(CD_COST_REIM_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.CSUP_REFERRAL MODIFY(CD_SVC_CODE  VARCHAR2(6))
;
ALTER TABLE CAPS.DELVRD_SVC_DTL MODIFY(CD_SVC_DTL_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.EQUIVALENCY MODIFY(CD_EQUIV_SVC_DTL_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.FOSTER_CARE_RATE MODIFY(CD_FCARE_RATE_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.NON_EQUIVALENCY MODIFY(CD_NON_EQUIV_SVC_DTL_SVC  VARCHAR2(6))
;
ALTER TABLE CAPS.PLACEMENT MODIFY(CD_PLCMT_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.PPA_DELVRD_SVC MODIFY(CD_PPA_SVC_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.RESOURCE_CHRCTR MODIFY(CD_RSRC_CHAR_CATEG_RSRC  VARCHAR2(3))
;
ALTER TABLE CAPS.RESOURCE_CHRCTR MODIFY(CD_RSRC_CHAR_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.RESOURCE_CHRCTR ADD CD_RSRC_CHAR_SERVICE_TYPE VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.RESOURCE_HISTORY MODIFY(CD_ELEM  VARCHAR2(10))
;
ALTER TABLE CAPS.RESOURCE_HISTORY MODIFY(CD_MIDDLE  VARCHAR2(10))
;
ALTER TABLE CAPS.RESOURCE_HISTORY MODIFY(CD_HIGH  VARCHAR2(10))
;
ALTER TABLE CAPS.RESOURCE_HISTORY_AUDIT MODIFY(CD_ELEM  VARCHAR2(10))
;
ALTER TABLE CAPS.RESOURCE_HISTORY_AUDIT MODIFY(CD_MIDDLE  VARCHAR2(10))
;
ALTER TABLE CAPS.RESOURCE_HISTORY_AUDIT MODIFY(CD_HIGH  VARCHAR2(10))
;
ALTER TABLE CAPS.RESOURCE_SERVICE MODIFY(CD_RSRC_SVC_CATEG_RSRC  VARCHAR2(3))
;
ALTER TABLE CAPS.RESOURCE_SERVICE MODIFY(CD_RSRC_SVC_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.RESOURCE_SERVICE ADD CD_RSRC_SVC_SERVICE_TYPE VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.RSRC_LINK MODIFY(CD_RSRC_LINK_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.RSRC_LINK_HISTORY MODIFY(CD_RSRC_LINK_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.SERVICE_AUTHORIZATION MODIFY(CD_SVC_AUTH_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.SERVICE_AUTH_AUDIT MODIFY(CD_SVC_AUTH_AUD_SERVICE  VARCHAR2(6))
;
ALTER TABLE CAPS.SERVICE_PLAN_ITEM MODIFY(CD_SVC_PLAN_SVC  VARCHAR2(6))
;
ALTER TABLE CAPS.SVC_AUTH_DETAIL MODIFY(CD_SVC_AUTH_DTL_SVC  VARCHAR2(6))
;
ALTER TABLE CAPS.SVC_AUTH_DTL_AUDIT MODIFY(CD_SVC_AUTH_DTL_AUD_SVC  VARCHAR2(6))
;


-- Alter Trigger SQL
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_RESOURCE_CHRCTR
BEFORE INSERT
ON CAPS.RESOURCE_CHRCTR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy	NUMBER;
	CURSOR C1 (xID NUMBER) IS SELECT
		ID_RESOURCE,
	      	CD_RSRC_SVC_CATEG_RSRC,
	        CD_RSRC_SVC_CNTY,
	        CD_RSRC_SVC_PROGRAM,
	        CD_RSRC_SVC_REGION,
	        CD_RSRC_SVC_SERVICE,
	        CD_RSRC_SVC_STATE,
	        CD_RSRC_SVC_SERVICE_TYPE,
		SEQ_RESOURCE_CHRCTR.NEXTVAL
	FROM RESOURCE_SERVICE
	WHERE ID_RESOURCE_SERVICE=xID;
        xID_RESOURCE		NUMBER;
        xCD_RSRC_CHAR_CATEG_RSRC	VARCHAR2(3);
        xCD_RSRC_CHAR_CNTY	VARCHAR2(3);
        xCD_RSRC_CHAR_PROGRAM	VARCHAR2(2);
        xCD_RSRC_CHAR_REGION	VARCHAR2(2);
        xCD_RSRC_CHAR_SERVICE	VARCHAR2(6);
        xCD_RSRC_CHAR_STATE	VARCHAR2(2);
        xCD_RSRC_CHAR_SERVICE_TYPE VARCHAR2(1);
	RECORD_NOT_FOUND	EXCEPTION;
BEGIN
	OPEN C1(:new.ID_RESOURCE_SERVICE);
	FETCH C1 INTO	xID_RESOURCE,
			xCD_RSRC_CHAR_CATEG_RSRC,
        		xCD_RSRC_CHAR_CNTY,
		        xCD_RSRC_CHAR_PROGRAM,
		        xCD_RSRC_CHAR_REGION,
		        xCD_RSRC_CHAR_SERVICE,
		        xCD_RSRC_CHAR_STATE,
		        xCD_RSRC_CHAR_SERVICE_TYPE,
			dummy;
	IF C1%FOUND THEN
		--Always get the new values from table RESOURCE_SERVICE, regardless
		--what the user has put into these fields (because these fields are
		--denormalized, thus they must be the same as from the original table)
		:new.ID_RESOURCE		:= xID_RESOURCE;
		:new.CD_RSRC_CHAR_CATEG_RSRC	:= xCD_RSRC_CHAR_CATEG_RSRC;
		:new.CD_RSRC_CHAR_CNTY		:= xCD_RSRC_CHAR_CNTY;
		:new.CD_RSRC_CHAR_PROGRAM	:= xCD_RSRC_CHAR_PROGRAM;
		:new.CD_RSRC_CHAR_REGION	:= xCD_RSRC_CHAR_REGION;
		:new.CD_RSRC_CHAR_SERVICE	:= xCD_RSRC_CHAR_SERVICE;
		:new.CD_RSRC_CHAR_STATE		:= xCD_RSRC_CHAR_STATE;
		:new.CD_RSRC_CHAR_SERVICE_TYPE := xCD_RSRC_CHAR_SERVICE_TYPE;
	ELSE
		--must find record above; otherwise it is an error.
		RAISE RECORD_NOT_FOUND;
	END IF;
	CLOSE C1;
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:new.ID_RSRC_CHRCTR = 0) THEN
		:new.ID_RSRC_CHRCTR := dummy;
	END IF;
EXCEPTION
	WHEN OTHERS THEN RAISE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_RESOURCE_SERVICE
BEFORE UPDATE
ON CAPS.RESOURCE_SERVICE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	UPDATE RESOURCE_CHRCTR RC
	    SET    RC.CD_RSRC_CHAR_CATEG_RSRC = :new.CD_RSRC_SVC_CATEG_RSRC,
	           RC.CD_RSRC_CHAR_CNTY       = :new.CD_RSRC_SVC_CNTY,
	           RC.CD_RSRC_CHAR_PROGRAM    = :new.CD_RSRC_SVC_PROGRAM,
	           RC.CD_RSRC_CHAR_REGION     = :new.CD_RSRC_SVC_REGION,
	           RC.CD_RSRC_CHAR_SERVICE    = :new.CD_RSRC_SVC_SERVICE,
	           RC.CD_RSRC_CHAR_STATE      = :new.CD_RSRC_SVC_STATE,
	           RC.CD_RSRC_CHAR_SERVICE_TYPE = :new.CD_RSRC_SVC_SERVICE_TYPE
	    WHERE  RC.ID_RESOURCE_SERVICE     = :new.ID_RESOURCE_SERVICE;
END;
/

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };

-- change STGAP00001517
-- codes tables and schema change (this is attached)

UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CSVCCODE';
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','25200','25200 - Child Incidentals');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','25201','25201 - Child Board (Per Diem)');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','25204','25204 - Child Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','25210','25210 - Child Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','25217','25217 - Child Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','25300','25300 - Donation Funds Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45000','45000 - County Miscellaneous');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45001','45001 - County Board (Per Diem)');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45004','45004 - County Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45010','45010 - County Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45017','45017 - County Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45091','45091 - Mileage Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45092','45092 - School Pictures');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45093','45093 - Birthdays');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45094','45094 - Haircuts');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45095','45095 - Diapers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45096','45096 - School Supplies');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45097','45097 - Allowance');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45098','45098 - Christmas');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','45099','45099 - Meal Reimbursements for Case workers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46000','46000 - County Miscellaneous');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46001','46001 - County Board');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46004','46004 - County Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46010','46010 - County Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46017','46017 - County Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46091','46091 - Mileage Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46092','46092 - School Pictures');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46093','46093 - Birthdays');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46094','46094 - Haircuts');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46095','46095 - Diapers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46096','46096 - School Supplies');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46097','46097 - Allowance');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46098','46098 - Christmas');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','46099','46099 - Meal Reimbursements for Case workers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50101','50101 - Per Diem Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50102','50102 - Per Diem Special Add-on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50104','50104 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50105','50105 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50117','50117 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50201','50201 - Per Diem Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50202','50202 - Per Diem Special Add-on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50204','50204 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50205','50205 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50208','50208 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50217','50217 - Supp Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50301','50301 - Per Diem Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50302','50302 - Per Diem Special Add-on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50304','50304 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50305','50305 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50308','50308 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50311','50311 - Child Restraint (Car Seats)');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50317','50317 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50399','50399 - Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50411','50411 - Child Restraint Devices');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50501','50501 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50504','50504 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50600','50600 - Other Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50601','50601 - Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50604','50604 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50608','50608 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50699','50699 - Written Waiver Item');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50701','50701 - Regular Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50704','50704 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50708','50708 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50807','50807 - Monthly Supplement');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50813','50813 - Monthly Supplement');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50913','50913 - Monthly Supplement');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51100','51100 - Other CCFA Costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51112','51112 - Other Reimbursable Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51119','51119 -  Medical Exams');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51154','51154 - Psychological l Evaluations');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51217','51217 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51257','51257 - Adoptive Placement Reimbursement');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51260','51260 - Respite Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51277','51277 - Adoptive Placement Reimbursement Foster Parent Conversion');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51800','51800 - CCFA WA Other Costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51812','51812 - Other Reimbursable Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51880','51880 - Summer Enrichment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52060','52060 - Overnight Respite Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52094','52094 - Day Respite Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52149','52149 - Day Care services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52150','52150 - Counseling');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52151','52151 - Drug Screens');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52152','52152 - Substance Abuse Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52153','52153 - Medical/Dental Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52154','52154 - Psychological Evaluation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52211','52211 - Child Restraint Device');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52299','52299 - Written Waiver Item');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52519','52519 - Medical  Exams - Child');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52520','52520 - Medical  Exams - Adult');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52901','52901 - Per Diem Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52902','52902 - Special Add on per diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52904','52904 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52905','52905 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52908','52908 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52911','52911 - Child Restraint ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52917','52917 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52999','52999 - Written Waiver Item');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53000','53000 - Other Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53001','53001 - Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53004','53004 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53008','53008 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53011','53011 - Child Restraint Devices');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53099','53099 - Written Waiver Item');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53167','53167 - IMPACT Training Costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54201','54201 - Enhanced Relative Care Subsidy Payments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54204','54204 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54205','54205 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54207','54207 - Enhanced Relative Care Subsidy Payments - Undocumented Children');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54217','54217 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54796','54796 - Family FC Emergency Beds');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54797','54797 - IFC Emergency Beds');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55201','55201 - Enhanced Relative Care Subsidy Payments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55205','55205 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55207','55207 - Enhanced Relative Care Subsidy Payments - Undocumented Children');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55281','55281 - Subsidized Guardianship payments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55282','55282 - Subsidized Guardianship payments - Undocumented Children');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55301','55301 - Enhanced Relative Care Subsidy Payments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55305','55305 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55307','55307 - Enhanced Relative Care Subsidy Payments - Undocumented Children');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55381','55381 - Relative Care Subsidized Guardianship payments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55382','55382 - Subsidized Guardianship payments Undocumented Children');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56001','56001 - Per Diem Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56002','56002 - Per Diem Special Add on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56004','56004 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56005','56005 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56017','56017 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56100','56100 - Other Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56101','56101 - Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56104','56104 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56301','56301 - Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56304','56304 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56305','56305 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56317','56317 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56399','56399 - Per Diem Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56401','56401 - Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56402','56402 - Special Add on Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56404','56404 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56405','56405 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56417','56417 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56499','56499 - Per Diem Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56501','56501 - Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56502','56502 - Special Add on Per Diem');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56504','56504 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56505','56505 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56517','56517 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','56599','56599 - Per Diem Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57162','57162 - 24-Hour Crisis Intervention');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372','57372 - Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57401','57401 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57402','57402 - Per Diem Special Add on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57404','57404 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57405','57405 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57417','57417 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57499','57499 - Per Diem Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57501','57501 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57502','57502 - Per Diem Special Add on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57504','57504 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57505','57505 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57517','57517 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57599','57599 - Per Diem Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57600','57600 - Other Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57611','57611 - Child Restraint Devices');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57699','57699 - Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57701','57701 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57702','57702 - Per Diem Special Add on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57704','57704 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57705','57705 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57708','57708 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57717','57717 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57799','57799 - Per Diem Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57800','57800 - Other Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57811','57811 - Child Restraint Devices');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57899','57899 - Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57901','57901 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57902','57902 - Per Diem Special Add on');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57904','57904 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57905','57905 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57908','57908 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57911','57911 - Child Restraint Devices');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57917','57917 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57999','57999 - Written Waiver Item ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58580','58580 - Summer Enrichment/Safety');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58629','58629 - Adolescent Transitional Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58678','58678 - Transitional Living Related Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58770','58770 - Contract Study');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58886','58886 - Preventive Family Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60400','60400 - Other Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60411','60411 - Child Restraint Devices');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60499','60499 - Written Waiver');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60501','60501 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60601','60601 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60604','60604 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60608','60608 - In-Hospital Care');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60699','60699 - Written Waiver Item ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60701','60701 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60704','60704 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60801','60801 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60804','60804 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60901','60901 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60904','60904 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60905','60905 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60917','60917 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61001','61001 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61004','61004 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61005','61005 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61017','61017 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61101','61101 - Per Diem - Regular');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61104','61104 - Initial Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61105','61105 - Annual Clothing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','61117','61117 - Supplemental Supervision');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','69841','69841 - Emergency Benefits');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','77324','77324 - Family Preservation - Crisis Intervention Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','77373','77373 - Family Preservation - Placement Prevention');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','77474','77474 - Diversion and Family Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','78383','78383 - Intervention and Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','78457','78457 - Pre and Post Adoption and Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','78484','78484 - Adoption Promotion Activities');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','87324','87324 - Therapeutic and Crisis Intervention Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383','88383 - Interventions and Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88484','88484 - Professional Interventions and Adoption Support Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','501SB','501SB - Sibling Incentive');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','502SB','502SB - Sibling Incentive');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50300a','50300a - Birth Certificates');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50300b','50300b - Helmets ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50300c','50300c - Initial FFC Other');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50310a','50310a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50310b','50310b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50310c','50310c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50310d','50310d - Burial Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','503SB', '503SB - Sibling Incentive');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50400a','50400a - Birth Certificates');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50400b','50400b - Safety Helmets');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50400c','50400c - Putative Father Register Search');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50400d','50400d - Other');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50410a','50410a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50410b','50410b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50410c','50410c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50410d','50410d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','505A3','505A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','505L1','505L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','505L2','505L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','505L3','505L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','505L4','505L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','505L5','505L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','505L6','505L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50610a','50610a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50610b','50610b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50610c','50610c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50610d','50610d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','506A3','506A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','506L1','506L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','506L2','506L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','506L3','506L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','506L4','506L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','506L5','506L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','506L6','506L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50700a','50700a - Birth Certificates');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50700b','50700b - Helmets');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50700c','50700c - Other Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50710a','50710a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50710b','50710b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50710c','50710c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','50710d','50710d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','507A3','507A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','507L1','507L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','507L2','507L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','507L3','507L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','507L4','507L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','507L5','507L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','507L6','507L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51033a','51033a - Court Costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51033b','51033b - Attorney Fees');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51033c','51033c - Physicals for Adopting parents');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51033d','51033d - Travel and Lodging during pre placement period');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51033e','51033e - Adoption Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51033f','51033f - Other non-recurring costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129a','51129a - Health Check Screen');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129b','51129b - Psychological Evaluation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129c','51129c - Match Profile Instrument');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129d','51129d - Education Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129e','51129e - Family assessment - 1st Child');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129f','51129f - Family assessment - each additional child');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129g','51129g - Other Family/Relative Evaluation /Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129h','51129h - Adolescent Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129i','51129i - Partial Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129j','51129j - Relative Care assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51129k','51129k - Late CCFA Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51188a','51188a - Court Appearance -          Professional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51188b','51188b - Court Appearance -          Paraprofessional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','511A3','511A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','511L1','511L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','511L2','511L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','511L3','511L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','511L4','511L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','511L5','511L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51258a','51258a - Therapy');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51258b','51258b - Orthodontics');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51258c','51258c - Surgery');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51258d','51258d - Other Reimbursable Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51312a','51312a - Air Fare');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51312b','51312b - Lodgings');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51312c','51312c - Meals');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51312d','51312d - Other Costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51824a','51824a - Crisis Intervention Prevent Disruption - Professional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51824b','51824b - Crisis Intervention Prevent Disruption - Paraprofessional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51824c','51824c - Crisis Intervention Prevent Disruption - Mileage');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51847a','51847a - Crisis Intervention Behavior Mgmt - Professional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51847b','51847b - Crisis Intervention Behavior Mgmt - Paraprofessional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51847c','51847c - Crisis Intervention Behavior Management - Mileage');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51856a','51856a - Transportation - Escort');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51856b','51856b - Transportation - Mileage');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51871a','51871a - In-home Case Mgmt -         Contracted Rate');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51871b','51871b - In-Home Case Mgmt -          Paraprofessional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51871c','51871c - In-home Case Mgmt -  Life Book');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51888a','51888a - Court Appearance -          Professional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51888b','51888b - Court Appearance -          Paraprofessional');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51895a','51895a - In-home Intensive Treatment -           Clinical Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','51895b','51895b - In-Home Intensive Treatment -          Mileage');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52148a','52148a -  Rent');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52148b','52148b - Mortgage Payment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52148c','52148c - Utility Bills');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52148d','52148d - Utility Deposits');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52148e','52148e - Minor Home Repairs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52148f','52148f - Minor Legal Services for Guardianship');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52156a','52156a - Transportation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52156b','52156b - Meals, lodging for case plan');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52156c','52156c - Gasoline');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52156d','52156d - Minor Car Repairs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52200a','52200a - Birth Certificates');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52200b','52200b - Helmets');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52200c','52200c - Putative Father Registry Search');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52200d','52200d - Other Costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52200e','52200e - Over Night Costs in Hotels');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52210a','52210a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52210b','52210b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52210c','52210c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52210d','52210d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52910a','52910a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52910b','52910b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52910c','52910c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','52910d','52910d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','529SB','529SB - ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53010a','53010a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53010b','53010b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53010c','53010c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53010d','53010d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','530A3','530A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','530L1','530L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','530L2','530L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','530L3','530L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','530L4','530L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','530L5','530L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','530L6','530L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53106a','53106a - Support Services - Drug Screens');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53106b','53106b - Support Services - Physicals');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53106c','53106c - Support Services - Lab Tests');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53106d','53106d - Support Services - Background checks');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53106e','53106e - Environmental Inspections');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53106f','53106f - Septic Tanks Pumped');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53106g','53106g - Additional Training and IMPACT Materials');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53168a','53168a - Continued Parent Development');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53168b','53168b - CPR and First Aid Training');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','53168c','53168c - Annual Adoptive and Foster Parent Conference Costs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54210a','54210a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54210b','54210b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54210c','54210c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','54210d','54210d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55179a','55179a - Referral Fee');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55179b','55179b - Home Visits');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55179c','55179c - Case Management Fee');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','55179d','55179d - Travel Reimbursement');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','560SB','560SB - Sibling Incentive');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','561A3','561A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','561L1','561L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','561L2','561L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','561L3','561L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','561L4','561L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','561L5','561L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','561L6','561L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','563A3','563A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','563L1','563L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','563L2','563L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','563L3','563L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','563L4','563L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','563L5','563L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','563L6','563L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','564A3','564A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','564L1','564L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','564L2','564L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','564L3','564L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','564L4','564L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','564L5','564L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','564L6','564L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','565A3','565A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','565L1','565L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','565L2','565L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','565L3','565L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','565L4','565L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','565L5','565L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','565L6','565L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57129a','57129a - Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57129b','57129b - Missed Appointments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57129c','57129c - Written Closed Summary');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57161a','57161a - Family Therapy Sessions');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57161b','57161b - Missed Appointments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57161c','57161c - Home Visits');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57161d','57161d - Written Closed Summary');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57161e','57161e - Travel Reimbursement');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57161f','57161f - Case Management Fee');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57161g','57161g - Formal Evaluation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372a','57372a - Referral Processing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372b','57372b - Written Parenting Skills Material');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372c','57372c - Case Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372d','57372d - Missed Appointments');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372e','57372e - Travel Reimbursement');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372f','57372f - Child Care Services while parent participates in group parenting class');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57372g','57372g - Complete Group Parenting class Program');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57610a','57610a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57610b','57610b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57610c','57610c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57610d','57610d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57810a','57810a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57810b','57810b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57810c','57810c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','57810d','57810d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375a','58375a - Tuition, Registration, Fees');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375b','58375b - Books, Supplies, Tool and Equipment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375c','58375c - Room and Board');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375d','58375d - Personal Computers/Printers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375e','58375e - Tutoring');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375f','58375f - Testing and Test Preparation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375g','58375g - Stipends');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58375h','58375h - Transportation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475a','58475a - Tuition, Registration, Fees');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475b','58475b - Books, Supplies, Tool and Equipment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475c','58475c - Room and Board');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475d','58475d - Uniforms and Supplies');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475e','58475e - Driver''s Education');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475f','58475f - Tutoring');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475g','58475g - Testing and Test Preparation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475h','58475h - Stipends');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58475i','58475i - Transportation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576a','58576a - Summer and Evening School Fees');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576b','58576b - Skill Conferences, Training, Workshop');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576c','58576c - Expenses for Workshop');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576d','58576d - Personal Computers/Printers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576e','58576e - Tutoring');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576f','58576f - Graduation Fees');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576g','58576g - Non-essential Graduation fees ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576h','58576h - Driver''s Education');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576i','58576i - Enrichment Activities');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576j','58576j - Extra-Curricular Activities');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576k','58576k - Boy Scout/Girl Scouts');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576l','58576l - Transportation to ILP activities');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58576m','58576m - Support Groups');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58885a','58885a - Family Assessment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','58885b','58885b - Family Conference');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175a','59175a - Tuition, Registration, Fees');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175b','59175b - Books, Supplies, Tool and Equipment');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175c','59175c - Room and Board');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175d','59175d - Uniforms and Supplies');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175e','59175e - Personal Computers/Printers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175f','59175f - Tutoring');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175g','59175g - Stipends');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','59175h','59175h - Transportation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','595A3','595A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','595L1','595L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','595L2','595L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','595L3','595L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','595L4','595L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','595L5','595L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','595L6','595L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','596A3','596A3 - Assessment Level');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','596L1','596L1 - Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','596L2','596L2 - Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','596L3','596L3 - Level 3');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','596L4','596L4 - Level 4');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','596L5','596L5 - Level 5');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','596L6','596L6 - Level 6');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','597W1','597W1 - Wraparound Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','597W2','597W2 - Wraparound Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','598W1','598W1 - Wraparound Level 1');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','598W2','598W2 - Wraparound Level 2');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60410a','60410a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60410b','60410b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60410c','60410c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60410d','60410d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60600a','60600a - Birth Certificates');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60600b','60600b - Safety Helmets');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60600c','60600c - Putative Father Register Search');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60600d','60600d - Other');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60610a','60610a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60610b','60610b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60610c','60610c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60610d','60610d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60700a','60700a - Birth Certificates');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60700b','60700b - Safety Helmets');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60700c','60700c - Putative Father Register Search');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60700d','60700d - Other');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60710a','60710a - Unusual Medical');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60710b','60710b - Unusual Dental');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60710c','60710c - ICPC Interstate Travel');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','60710d','60710d - Burial Cost');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','774C9','774C9 - CPPC Expenses');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','87324a','87324a - Intensive Family Therapy');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','87324b','87324b - Family Counseling');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','87324c','87324c - Behavior Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','87324d','87324d - Family Crisis Intervention ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873R1','873R1 - Residential After-Care Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873R2a','873R2a - Comprehensive Discharge Panning');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873R3b','873R3b - Placement Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873R4c','873R4c - Intensive Case Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873R5d','873R5d - Therapeutic Counseling');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873R6e','873R6e - Behavior Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873R7f','873R7f - 24-hour Crisis Intervention');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','873S7','873S7 - Relative Caregiver Support Services ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5','874S5 - Parent Support Services Early Intervention::');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5a','874S5a - Short term Home Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5b','874S5b - Center Based Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5c','874S5c - Case Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5d','874S5d - Referral Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5e','874S5e - First time and Teen Parents');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5f','874S5f - Relative Caregivers');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5g','874S5g - Domestic Abuse Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S5h','874S5h - Substance abuse Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S6','874S6 - Parent Support Services Placement Prevention:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S6a','874S6a - Short term Home Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S6b','874S6b - Center Based Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S6c','874S6c - Home Visitation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S6d','874S6d - Case Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7','874S7 - Relative Caregiver Support:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7a','874S7a - Health Screenings Parent Education');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7b','874S7b - Peer Support');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7c','874S7c - Child and family Counseling');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7d','874S7d - Legal Consultation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7e','874S7e - Tutorial Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7f','874S7f - Transportation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S7g','874S7g - Housing Assistance');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S8','874S8 - Substance Abuse Treatment and Support Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S8a','874S8a - Intensive Case Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S8b','874S8b - Parenting Training');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S8c','874S8c - Addiction Counseling');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S8d','874S8d - In-Home Relapse Prevention');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S9','874S9 - Healthy Marriage and Co-Parenting Support Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S9a','874S9a - Marriage Education');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','874S9b','874S9b - Relationship Skills Programs');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383a','88383a - Family Conferencing');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383b','88383b - Family Mediation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383c','88383c - Psychological Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383d','88383d - Therapeutic support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383e','88383e - Crisis Stabilization');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383f','88383f - Transition Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88383g','88383g - Family Interventions');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S3a','883S3a - Family Access and Visitation Centers - Visits');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S3b','883S3b - Transportation for Visits');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S4a','883S4a - Post Substance Abuse Treatment ');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S4b','883S4b - Transitional Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S4c','883S4c - Parent and Child Enrichment Activities');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S4d','883S4d - Supervised Visitation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S4e','883S4e - Discipline Coaching');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','883S4f','883S4f - Behavior Management');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88484a','88484a - Family Mediation');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88484b','88484b - Child and Family therapy');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88484c','88484c - Psychological Support Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','88484d','88484d - Crisis Stabilization');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S1','884S1 - Foster Care Transitional Support Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S1a','884S1a - Adoption Placement Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S1b','884S1b - Support Groups');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S1c','884S1c - In-home Follow -up');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S1d','884S1d - Monitoring and Support');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S2','884S2 - Foster Care Emancipation Support Services:');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S2a','884S2a - Preparation for Transition Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S2b','884S2b - Managing Transition Services');
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) VALUES('CSVCCODE','884S2c','884S2c - Emancipation After Care and Follow up Services');

-- change STGAP00001521
DELETE FROM CAPS.CODES_TABLES CT WHERE CT.CODE_TYPE='CATOFSVC';
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '01', 'Adoption Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '02', 'Basic Needs');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '03', 'Counseling');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '04', 'Daycare');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '05', 'Education');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '06', 'Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '07', 'Hotline/Helpline');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '08', 'Law Enforcement');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '09', 'Legal');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '10', 'Medical');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '11', 'MOU/Contracts');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '12', 'Placement Providers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '13', 'Special Needs');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '14', 'Substance Abuse');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CATOFSVC', '15', 'Youth Development/ILP');

-- change STGAP00001523
UPDATE CAPS.METAPHOR
SET TXT_TAB = 'Child Life History'  
WHERE ID_TAB = 660 
AND TXT_TAB_CONSTANT = 'HSEGH_EVENTLIST';

UPDATE CAPS.TASK
SET TXT_TASK_DECODE = 'Child Life History'  
WHERE CD_TASK = '3210'AND 
CD_TASK_EVENT_TYPE ='HSG'; 

UPDATE CAPS.TASK
SET TXT_TASK_DECODE = 'Child Life History'  
WHERE CD_TASK = '8710'
AND CD_TASK_EVENT_TYPE ='HSG';  
 
UPDATE CAPS.CODES_TABLES 
SET DECODE ='Child Life History'
WHERE CODE_TYPE='CEVNTTYP'
AND CODE ='HSG';

-- change STGAP00001524

INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CATNDNCE','REG','Regularly Attends',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CATNDNCE','TRU','Truant',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CATNDNCE','NA','N/A',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CEDUCNED','LDR','Learning Disorders',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CEDUCNED','BDR','Behavioral Disorders',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CEDUCNED','PED','Psycho-Educational',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CEDUCNED','PTI','Part Time',sysdate);

-- change STGAP00001526
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CCTZNSTA','VES','Verified by Eligibility Specialist',SYSDATE);

-- change STGAP00001527
INSERT INTO CAPS.MESSAGE(NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) VALUES (60146, 'MSG_VERIF_REQ_IDENT_VERIF', 'Method of Verification(s) selected requires identity verification.  Document all identity verifications on the Person Identifiers Detail page.', 700, 500, 'N');

-- change STGAP00001530
--DELETE NEW STAGE PROGRESSION STAGE NAMES
DELETE FROM CAPS.STAGE_PROG WHERE CD_STAGE_PROG_STAGE IN ('FCF', 'FCC', 'ONG');
DELETE FROM CAPS.STAGE_PROG WHERE CD_STAGE_PROG_OPEN IN ('FCF', 'FCC', 'ONG');

-- change STGAP00001533
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPHNTYP','AF','After Hours', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPHNTYP','AC','Alternative Contact', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPHNTYP','CN','Contact', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPHNTYP','EM','Emergency', SYSDATE);
UPDATE CAPS.CODES_TABLES SET DT_END = NULL  WHERE CODE = 'FC' AND CODE_TYPE = 'CPHNTYP';

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (130, 'SacwisRev2', 'static updates, service code size change');
                         
commit;
