--STGAP00015800 - Release(3.5) PerCAPTA_CD/NF/SI Taskcodes and Metaphor and Codes

 --Per CAPTA

--Add row to METAPHOR table

 ALTER TABLE caps.Task
 MODIFY (txt_task_decode varchar2(55));


INSERT INTO caps.METAPHOR
(id_tab, txt_tab_url, txt_tab_constant, txt_tab,  dt_last_update )
VALUES
(1766, '/workload/EventSearch/displayEventList' ,       'CHLDDEATH_NRFAL_SERINJ_FOR_CASE_EVENTLIST' ,
'CD/NF/SI' ,    sysdate);



  --Task code for  Child Death/Near Fatality/Serious Injury in INT stage
INSERT INTO caps.task t
(t.CD_TASK,t.DT_LAST_UPDATE , t.CD_TASK_EVENT_STATUS, t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW,t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
 t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
 t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
 VALUES
('6110',sysdate,'COMP','CNS','CCMN51W','INT','CPS',
 '1', '1' ,'1',  '1','0',
 '0','1','Child Death/Near Fatality/Serious Injury Report','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CHLDDEATH_NRFAL_SERINJ_FOR_CASE_EVENTLIST',
 '/admin/OutputLaunch/displayInitOutputLaunch',3,'0','0','0');

 --Task code for  Child Death/Near Fatality/Serious Injury in INV stage
INSERT INTO caps.task t
(t.CD_TASK,t.DT_LAST_UPDATE , t.CD_TASK_EVENT_STATUS, t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW,t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
 t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
 t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
 VALUES
('6220',sysdate,'COMP','CNS','CCMN51W','INV','CPS',
 '1', '1' ,'1',  '1','0',
 '0','1','Child Death/Near Fatality/Serious Injury Report','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CHLDDEATH_NRFAL_SERINJ_FOR_CASE_EVENTLIST',
 '/admin/OutputLaunch/displayInitOutputLaunch',3,'0','0','0');




--Task code for Approve Child Death/Near Fatality/Serious Injury in FPR (Ongoing) stage
INSERT INTO caps.task t
(t.CD_TASK,t.DT_LAST_UPDATE , t.CD_TASK_EVENT_STATUS, t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW,t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
 t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
 t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
 VALUES
('6330',sysdate,'COMP','CNS','CCMN51W','FPR','CPS',
 '1', '1' ,'1',  '1','0',
 '0','1','Child Death/Near Fatality/Serious Injury Report','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CHLDDEATH_NRFAL_SERINJ_FOR_CASE_EVENTLIST',
 '/admin/OutputLaunch/displayInitOutputLaunch',3,'0','0','0');

 --Task code for  Child Death/Near Fatality/Serious Injury in SUB (FCC) stage
INSERT INTO caps.task t
(t.CD_TASK,t.DT_LAST_UPDATE , t.CD_TASK_EVENT_STATUS, t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW,t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
 t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
 t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
 VALUES
('6440',sysdate,'COMP','CNS','CCMN51W','SUB','CPS',
 '1', '1' ,'1',  '1','0',
 '0','1','Child Death/Near Fatality/Serious Injury Report','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CHLDDEATH_NRFAL_SERINJ_FOR_CASE_EVENTLIST',
 '/admin/OutputLaunch/displayInitOutputLaunch',3,'0','0','0');

 --Task code for  Child Death/Near Fatality/Serious Injury in ADO stage
INSERT INTO caps.task t
(t.CD_TASK,t.DT_LAST_UPDATE , t.CD_TASK_EVENT_STATUS, t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW,t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
 t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
 t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
 VALUES
('6550',sysdate,'COMP','CNS','CCMN51W','ADO','CPS',
 '1', '1' ,'1',  '1','0',
 '0','1','Child Death/Near Fatality/Serious Injury Report','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CHLDDEATH_NRFAL_SERINJ_FOR_CASE_EVENTLIST',
 '/admin/OutputLaunch/displayInitOutputLaunch',3,'0','0','0');


   --Task code for Approve Child Death/Near Fatality/Serious Injury in PFC stage
INSERT INTO caps.task t
(t.CD_TASK,t.DT_LAST_UPDATE , t.CD_TASK_EVENT_STATUS, t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW,t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
 t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
 t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
 VALUES
('6660',sysdate,'COMP','CNS','CCMN51W','PFC','CPS',
 '1', '1' ,'1',  '1','0',
 '0','1','Child Death/Near Fatality/Serious Injury Report','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CHLDDEATH_NRFAL_SERINJ_FOR_CASE_EVENTLIST',
 '/admin/OutputLaunch/displayInitOutputLaunch',3,'0','0','0');

  --Task code for Approve Child Death/Near Fatality/Serious Injury in SUB (FCC) stage
INSERT INTO caps.task t
(t.CD_TASK,t.DT_LAST_UPDATE , t.CD_TASK_EVENT_TYPE, t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
t.CD_TASK_TOP_WINDOW, t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
 t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
 t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
 VALUES
('6400',sysdate,'APP','SUB','CPS',
 'CCMN65W','0', '1' ,'1',  '0','0',
 '0','0','Approve Child Death/Near Fatality/Serious Injury Report','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CHLDDEATH_NRFATALITY_SERINJ_FOR_CASE_EVENTLIST',
 '/admin/OutputLaunch/displayInitOutputLaunch',0,'0','0','0');

insert into caps.codes_tables (code_type, code, decode )
values('CEVNTDOC' , 'CNS' , 'csc32o00');

insert into caps.codes_tables (code_type, code, decode)
values ( 'CEVNTTBL', 'CNS', 'HSEGH_NARR');

insert into caps.codes_tables (code_type, code, decode )
values('CEVNTAPV' , 'CNS' , '6400');

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (752, 'SacwisRev3', 'Release 3.5 - DBCR 15800');


commit;



