
-- Sequence Alter SQL

CREATE SEQUENCE CAPS.SEQ_CONTACT_CBX
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


-- Standard Alter Table SQL

ALTER TABLE CAPS.CAPS_RESOURCE ADD CD_RSRC_ADDR_SMILEUPD_ST VARCHAR2(8)     NULL
;
ALTER TABLE CAPS.CONTACT ADD ID_CONTACT_TCM_CLIENT NUMBER(16)     NULL
;
ALTER TABLE CAPS.CONTACT ADD CD_CONTACT_TCM_ELIGIBLE VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.CONTACT ADD CD_CONTACT_TCM_MED_SVCS VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.RESOURCE_HISTORY ADD CD_RSRC_ADDR_SMILEUPD_ST VARCHAR2(8)     NULL
;
ALTER TABLE CAPS.RESOURCE_HISTORY_AUDIT ADD CD_RSRC_ADDR_SMILEUPD_ST VARCHAR2(8)     NULL
;
ALTER TABLE CAPS.TCM_CLAIM ADD ID_EVENT NUMBER(16)     NULL
;

-- Drop Referencing Constraint SQL

ALTER TABLE CAPS.ADPT_SUB_EVENT_LINK DROP CONSTRAINT FK_ADPT_SUB_EVENT_LNK_SUB
;
ALTER TABLE CAPS.SUB_ELIG_NARR DROP CONSTRAINT FK_SUB_ELIG_NARR
;

-- Drop Constraint, Rename and Create Table SQL

ALTER TABLE CAPS.ADOPTION_SUBSIDY DROP CONSTRAINT FK_ADPT_SUBSIDY_PAYEE
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY DROP CONSTRAINT FK_ADPT_SUBSIDY_PERS
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY DROP CONSTRAINT FK_ADPT_SUBSIDY_PLCMT
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY DROP PRIMARY KEY DROP INDEX
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_2
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_3
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_4
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_1
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY RENAME TO ADOPTION_S_03152007215708000
;
CREATE TABLE CAPS.ADOPTION_SUBSIDY
(
    ID_ADPT_SUB              NUMBER(16)    NOT NULL,
    DT_LAST_UPDATE           DATE          NOT NULL,
    ID_ADPT_SUB_PERSON       NUMBER(16)    NOT NULL,
    ID_ADPT_SUB_PAYEE        NUMBER(16)    NOT NULL,
    ID_PLCMT_EVENT           NUMBER(16)        NULL,
    AMT_ADPT_SUB             NUMBER(6,2)       NULL,
    CD_ADPT_SUB_CLOSE_RSN    VARCHAR2(2)       NULL,
    CD_ADPT_SUB_DETERM       VARCHAR2(2)       NULL,
    DT_ADPT_SUB_AGREE_RETN   DATE              NULL,
    DT_ADPT_SUB_AGREE_SENT   DATE              NULL,
    DT_ADPT_SUB_APP_RETURNED DATE              NULL,
    DT_ADPT_SUB_APP_SENT     DATE              NULL,
    DT_ADPT_SUB_APPRVD       DATE              NULL,
    DT_ADPT_SUB_EFFECTIVE    DATE              NULL,
    DT_ADPT_SUB_END          DATE              NULL,
    DT_ADPT_SUB_LAST_INVC    DATE              NULL,
    IND_ADPT_SUB_THIRD_PARTY CHAR(1)           NULL,
    IND_ADPT_SUB_PROCESS     CHAR(1)           NULL,
    TXT_ADPT_SUB_RSN         VARCHAR2(300)     NULL,
    IND_SAU_CONF             VARCHAR2(1)       NULL,
    IND_SPCL_ASST_APPRVL     VARCHAR2(1)       NULL,
    AMT_SPCL_ASST_REQ        NUMBER(6,2)       NULL,
    CD_SPCL_ASST_TYPE        VARCHAR2(3)       NULL,
    TXT_SPCL_ASST_SPECIFY    VARCHAR2(40)      NULL,
    TXT_SPCL_ASST_CMNTS      VARCHAR2(300)     NULL,
    DT_RENWL_EFF_BEGIN       DATE              NULL,
    DT_RENWL_EFF_END         DATE              NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
GRANT DELETE ON CAPS.ADOPTION_SUBSIDY TO CAPSBAT
;
GRANT INSERT ON CAPS.ADOPTION_SUBSIDY TO CAPSBAT
;
GRANT SELECT ON CAPS.ADOPTION_SUBSIDY TO CAPSBAT
;
GRANT UPDATE ON CAPS.ADOPTION_SUBSIDY TO CAPSBAT
;
GRANT DELETE ON CAPS.ADOPTION_SUBSIDY TO CAPSON
;
GRANT INSERT ON CAPS.ADOPTION_SUBSIDY TO CAPSON
;
GRANT SELECT ON CAPS.ADOPTION_SUBSIDY TO CAPSON
;
GRANT UPDATE ON CAPS.ADOPTION_SUBSIDY TO CAPSON
;
GRANT SELECT ON CAPS.ADOPTION_SUBSIDY TO OPERATOR
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_1
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_2
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_3
;
DROP INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_4
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY_AUDIT RENAME TO ADOPTION_S_03152007215709000
;
CREATE TABLE CAPS.ADOPTION_SUBSIDY_AUDIT
(
    ID_ADPT_SUB_AUD          NUMBER(16)    NOT NULL,
    DT_LAST_UPDATE           DATE          NOT NULL,
    ID_ADPT_AUD_PERSON       NUMBER(16)    NOT NULL,
    ID_ADPT_AUD_PAYEE        NUMBER(16)    NOT NULL,
    ID_PLCMT_EVENT           NUMBER(16)        NULL,
    AMT_ADPT_AUD             NUMBER(6,2)       NULL,
    CD_ADPT_AUD_CLOSE_RSN    VARCHAR2(2)       NULL,
    CD_ADPT_AUD_DETERM       VARCHAR2(2)       NULL,
    DT_ADPT_AUD_AGREE_RETN   DATE              NULL,
    DT_ADPT_AUD_AGREE_SENT   DATE              NULL,
    DT_ADPT_AUD_APP_RETURNED DATE              NULL,
    DT_ADPT_AUD_APP_SENT     DATE              NULL,
    DT_ADPT_AUD_APPRVD       DATE              NULL,
    DT_ADPT_AUD_EFFECTIVE    DATE              NULL,
    DT_ADPT_AUD_END          DATE              NULL,
    DT_ADPT_AUD_LAST_INVC    DATE              NULL,
    IND_ADPT_AUD_THIRD_PARTY CHAR(1)           NULL,
    IND_ADPT_AUD_PROCESS     CHAR(1)           NULL,
    TXT_ADPT_AUD_RSN         VARCHAR2(300)     NULL,
    IND_SAU_CONF             VARCHAR2(1)       NULL,
    IND_SPCL_ASST_APPRVL     VARCHAR2(1)       NULL,
    AMT_SPCL_ASST_REQ        NUMBER(6,2)       NULL,
    CD_SPCL_ASST_TYPE        VARCHAR2(3)       NULL,
    TXT_SPCL_ASST_SPECIFY    VARCHAR2(40)      NULL,
    TXT_SPCL_ASST_CMNTS      VARCHAR2(300)     NULL,
    DT_RENWL_EFF_BEGIN       DATE              NULL,
    DT_RENWL_EFF_END         DATE              NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
GRANT DELETE ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSBAT
;
GRANT INSERT ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSBAT
;
GRANT SELECT ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSBAT
;
GRANT UPDATE ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSBAT
;
GRANT DELETE ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSON
;
GRANT INSERT ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSON
;
GRANT SELECT ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSON
;
GRANT UPDATE ON CAPS.ADOPTION_SUBSIDY_AUDIT TO CAPSON
;
GRANT SELECT ON CAPS.ADOPTION_SUBSIDY_AUDIT TO OPERATOR
;
CREATE TABLE CAPS.CONTACT_CBX
(
    ID_CONTACT_CBX   NUMBER(16)  NOT NULL,
    DT_LAST_UPDATE   DATE        NOT NULL,
    ID_CONTACT_EVENT NUMBER(16)  NOT NULL,
    CD_CBX_CODE_TYPE VARCHAR2(8)     NULL,
    CD_CONTACT_CBX   VARCHAR2(3)     NULL,
    CONSTRAINT PK549
    PRIMARY KEY (ID_CONTACT_CBX)
    USING INDEX STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE CAPS.CONTACT_CBX IS
'Non-static table linking multiple checkbox code values to a single contact record'
;
COMMENT ON COLUMN CAPS.CONTACT_CBX.DT_LAST_UPDATE IS
'Date of insert or last update'
;
CREATE TABLE CAPS.YOUTH_DETAIL
(
    ID_PERSON             NUMBER(16)    NOT NULL,
    DT_LAST_UPDATE        DATE          NOT NULL,
    ADDR_GED_ADDR_1       VARCHAR2(30)      NULL,
    ADDR_GED_ADDR_2       VARCHAR2(30)      NULL,
    ADDR_GED_ADDR_CITY    VARCHAR2(20)      NULL,
    ADDR_GED_ADDR_STATE   VARCHAR2(2)       NULL,
    ADDR_GED_ADDR_ZIP     VARCHAR2(10)      NULL,
    CD_ACAD_TRACK         VARCHAR2(3)       NULL,
    CD_CLASSIF            VARCHAR2(3)       NULL,
    CD_EDU_GOAL           VARCHAR2(3)       NULL,
    CD_PAR_STAT           VARCHAR2(3)       NULL,
    DT_EMNC_DISC          DATE              NULL,
    DT_GED_EXP_PROG_COMP  DATE              NULL,
    DT_GED_PROG_COMP      DATE              NULL,
    DT_SCH_GRAD           DATE              NULL,
    DT_POST_EXP_GRAD      DATE              NULL,
    DT_POST_GRAD          DATE              NULL,
    IND_EMP_SVC           VARCHAR2(1)       NULL,
    IND_GED_PROG          VARCHAR2(1)       NULL,
    IND_HEALTH_SVC        VARCHAR2(1)       NULL,
    IND_LIFE_SKILLS       VARCHAR2(1)       NULL,
    IND_SCH_GRAD          VARCHAR2(1)       NULL,
    NBR_GED_FAX           VARCHAR2(10)      NULL,
    NBR_GED_PHONE         VARCHAR2(10)      NULL,
    NBR_POST_CUMM_GPA     NUMBER(6)         NULL,
    NBR_POST_CURR_GPA     NUMBER(6)         NULL,
    NBR_POST_REQ_CRED     NUMBER(4)         NULL,
    NBR_POST_REQ_EAR      NUMBER(4)         NULL,
    NBR_SCH_CREDIT_EARNED NUMBER(4)         NULL,
    NBR_SCH_CREDIT_REQD   NUMBER(4)         NULL,
    NBR_SCH_CURR_GPA      NUMBER(6)         NULL,
    NBR_SCH_CUM_GPA       NUMBER(6)         NULL,
    NM_GED_PROG           VARCHAR2(20)      NULL,
    NM_INST               VARCHAR2(50)      NULL,
    NM_SCH                VARCHAR2(50)      NULL,
    TXT_AREA_STUDY        VARCHAR2(20)      NULL,
    TXT_EMNC_DISC         VARCHAR2(300)     NULL,
    TXT_EMP_SVC           VARCHAR2(300)     NULL,
    TXT_HLTH_SVC          VARCHAR2(300)     NULL,
    TXT_LIFE_SKILLS       VARCHAR2(300)     NULL,
    TXT_SCH_CMMTS         VARCHAR2(300)     NULL,
    CONSTRAINT PK_YOUTH_DETAIL
    PRIMARY KEY (ID_PERSON)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE CAPS.YOUTH_DETAIL IS
'This table hold Youth Develpment information for children 14 and older (formerly known as WTLP Detail).
'
;
COMMENT ON COLUMN CAPS.YOUTH_DETAIL.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON CAPS.YOUTH_DETAIL TO CAPSBAT
;
GRANT INSERT ON CAPS.YOUTH_DETAIL TO CAPSBAT
;
GRANT SELECT ON CAPS.YOUTH_DETAIL TO CAPSBAT
;
GRANT UPDATE ON CAPS.YOUTH_DETAIL TO CAPSBAT
;
GRANT DELETE ON CAPS.YOUTH_DETAIL TO CAPSON
;
GRANT INSERT ON CAPS.YOUTH_DETAIL TO CAPSON
;
GRANT SELECT ON CAPS.YOUTH_DETAIL TO CAPSON
;
GRANT UPDATE ON CAPS.YOUTH_DETAIL TO CAPSON
;
GRANT SELECT ON CAPS.YOUTH_DETAIL TO OPERATOR
;

-- Insert Data SQL

ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO CAPS.ADOPTION_SUBSIDY(
                                  ID_ADPT_SUB,
                                  DT_LAST_UPDATE,
                                  ID_ADPT_SUB_PERSON,
                                  ID_ADPT_SUB_PAYEE,
                                  ID_PLCMT_EVENT,
                                  AMT_ADPT_SUB,
                                  CD_ADPT_SUB_CLOSE_RSN,
                                  CD_ADPT_SUB_DETERM,
                                  DT_ADPT_SUB_AGREE_RETN,
                                  DT_ADPT_SUB_AGREE_SENT,
                                  DT_ADPT_SUB_APP_RETURNED,
                                  DT_ADPT_SUB_APP_SENT,
                                  DT_ADPT_SUB_APPRVD,
                                  DT_ADPT_SUB_EFFECTIVE,
                                  DT_ADPT_SUB_END,
                                  DT_ADPT_SUB_LAST_INVC,
                                  IND_ADPT_SUB_THIRD_PARTY,
                                  IND_ADPT_SUB_PROCESS,
                                  TXT_ADPT_SUB_RSN,
                                  IND_SAU_CONF,
                                  IND_SPCL_ASST_APPRVL,
                                  AMT_SPCL_ASST_REQ,
                                  CD_SPCL_ASST_TYPE,
                                  TXT_SPCL_ASST_SPECIFY,
                                  TXT_SPCL_ASST_CMNTS,
                                  DT_RENWL_EFF_BEGIN,
                                  DT_RENWL_EFF_END
                                 )
                           SELECT 
                                  ID_ADPT_SUB,
                                  DT_LAST_UPDATE,
                                  ID_ADPT_SUB_PERSON,
                                  ID_ADPT_SUB_PAYEE,
                                  ID_PLCMT_EVENT,
                                  AMT_ADPT_SUB,
                                  CD_ADPT_SUB_CLOSE_RSN,
                                  CD_ADPT_SUB_DETERM,
                                  DT_ADPT_SUB_AGREE_RETN,
                                  DT_ADPT_SUB_AGREE_SENT,
                                  DT_ADPT_SUB_APP_RETURNED,
                                  DT_ADPT_SUB_APP_SENT,
                                  DT_ADPT_SUB_APPRVD,
                                  DT_ADPT_SUB_EFFECTIVE,
                                  DT_ADPT_SUB_END,
                                  DT_ADPT_SUB_LAST_INVC,
                                  IND_ADPT_SUB_THIRD_PARTY,
                                  IND_ADPT_SUB_PROCESS,
                                  TXT_ADPT_SUB_RSN,
                                  IND_SAU_CONF,
                                  IND_SPCL_ASST_APPRVL,
                                  AMT_SPCL_ASST_REQ,
                                  CD_SPCL_ASST_TYPE,
                                  TXT_SPCL_ASST_SPECIFY,
                                  TXT_SPCL_ASST_CMNTS,
                                  DT_RENWL_EFF_BEGIN,
                                  DT_RENWL_EFF_END
                             FROM CAPS.ADOPTION_S_03152007215708000 
;
COMMIT
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY LOGGING
;
ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO CAPS.ADOPTION_SUBSIDY_AUDIT(
                                        ID_ADPT_SUB_AUD,
                                        DT_LAST_UPDATE,
                                        ID_ADPT_AUD_PERSON,
                                        ID_ADPT_AUD_PAYEE,
                                        ID_PLCMT_EVENT,
                                        AMT_ADPT_AUD,
                                        CD_ADPT_AUD_CLOSE_RSN,
                                        CD_ADPT_AUD_DETERM,
                                        DT_ADPT_AUD_AGREE_RETN,
                                        DT_ADPT_AUD_AGREE_SENT,
                                        DT_ADPT_AUD_APP_RETURNED,
                                        DT_ADPT_AUD_APP_SENT,
                                        DT_ADPT_AUD_APPRVD,
                                        DT_ADPT_AUD_EFFECTIVE,
                                        DT_ADPT_AUD_END,
                                        DT_ADPT_AUD_LAST_INVC,
                                        IND_ADPT_AUD_THIRD_PARTY,
                                        IND_ADPT_AUD_PROCESS,
                                        TXT_ADPT_AUD_RSN,
                                        IND_SAU_CONF,
                                        IND_SPCL_ASST_APPRVL,
                                        AMT_SPCL_ASST_REQ,
                                        CD_SPCL_ASST_TYPE,
                                        TXT_SPCL_ASST_SPECIFY,
                                        TXT_SPCL_ASST_CMNTS,
                                        DT_RENWL_EFF_BEGIN,
                                        DT_RENWL_EFF_END
                                       )
                                 SELECT 
                                        ID_ADPT_SUB_AUD,
                                        DT_LAST_UPDATE,
                                        ID_ADPT_AUD_PERSON,
                                        ID_ADPT_AUD_PAYEE,
                                        ID_PLCMT_EVENT,
                                        AMT_ADPT_AUD,
                                        CD_ADPT_AUD_CLOSE_RSN,
                                        CD_ADPT_AUD_DETERM,
                                        DT_ADPT_AUD_AGREE_RETN,
                                        DT_ADPT_AUD_AGREE_SENT,
                                        DT_ADPT_AUD_APP_RETURNED,
                                        DT_ADPT_AUD_APP_SENT,
                                        DT_ADPT_AUD_APPRVD,
                                        DT_ADPT_AUD_EFFECTIVE,
                                        DT_ADPT_AUD_END,
                                        DT_ADPT_AUD_LAST_INVC,
                                        IND_ADPT_AUD_THIRD_PARTY,
                                        IND_ADPT_AUD_PROCESS,
                                        TXT_ADPT_AUD_RSN,
                                        IND_SAU_CONF,
                                        IND_SPCL_ASST_APPRVL,
                                        AMT_SPCL_ASST_REQ,
                                        CD_SPCL_ASST_TYPE,
                                        TXT_SPCL_ASST_SPECIFY,
                                        TXT_SPCL_ASST_CMNTS,
                                        DT_RENWL_EFF_BEGIN,
                                        DT_RENWL_EFF_END
                                   FROM CAPS.ADOPTION_S_03152007215709000 
;
COMMIT
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY_AUDIT LOGGING
;

-- Add Constraint SQL

ALTER TABLE CAPS.ADOPTION_SUBSIDY ADD CONSTRAINT PK_ADOPTION_SUBSIDY
PRIMARY KEY (ID_ADPT_SUB)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 1M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;

-- Add Indexes SQL

CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_2
    ON CAPS.ADOPTION_SUBSIDY(DT_ADPT_SUB_END)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_3
    ON CAPS.ADOPTION_SUBSIDY(ID_ADPT_SUB_PAYEE)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_4
    ON CAPS.ADOPTION_SUBSIDY(ID_PLCMT_EVENT)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_1
    ON CAPS.ADOPTION_SUBSIDY(ID_ADPT_SUB_PERSON)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_1
    ON CAPS.ADOPTION_SUBSIDY_AUDIT(ID_ADPT_AUD_PERSON)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_2
    ON CAPS.ADOPTION_SUBSIDY_AUDIT(ID_ADPT_AUD_PAYEE)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_3
    ON CAPS.ADOPTION_SUBSIDY_AUDIT(ID_PLCMT_EVENT)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADOPTION_SUBSIDY_AUDIT_4
    ON CAPS.ADOPTION_SUBSIDY_AUDIT(ID_ADPT_SUB_AUD)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

-- Add Dependencies SQL
/
DROP TRIGGER CAPS.TIBR_ADOPTION_SUBSIDY
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_ADOPTION_SUBSIDY
BEFORE INSERT
ON CAPS.ADOPTION_SUBSIDY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy number;
BEGIN
  IF (:NEW.ID_ADPT_SUB IS NULL OR :new.ID_ADPT_SUB = 0)
  THEN
                SELECT SEQ_ADOPTION_SUBSIDY.NEXTVAL INTO dummy  FROM DUAL;
    :new.ID_ADPT_SUB := dummy;
  END IF;
  :new.DT_LAST_UPDATE := SYSDATE;
  insert into ADOPTION_SUBSIDY_AUDIT (
          ID_ADPT_SUB_AUD,
          ID_ADPT_AUD_PERSON,
          ID_ADPT_AUD_PAYEE,
          ID_PLCMT_EVENT,
          DT_LAST_UPDATE,
          AMT_ADPT_AUD,
          CD_ADPT_AUD_CLOSE_RSN,
          CD_ADPT_AUD_DETERM,
          DT_ADPT_AUD_AGREE_RETN,
          DT_ADPT_AUD_AGREE_SENT,
          DT_ADPT_AUD_APP_RETURNED,
          DT_ADPT_AUD_APP_SENT,
          DT_ADPT_AUD_APPRVD ,
          DT_ADPT_AUD_EFFECTIVE,
          DT_ADPT_AUD_END,
          DT_ADPT_AUD_LAST_INVC,
          IND_ADPT_AUD_THIRD_PARTY,
          IND_ADPT_AUD_PROCESS,
          TXT_ADPT_AUD_RSN,
          IND_SAU_CONF,
          IND_SPCL_ASST_APPRVL,
          AMT_SPCL_ASST_REQ,
          CD_SPCL_ASST_TYPE,
          TXT_SPCL_ASST_SPECIFY,
          TXT_SPCL_ASST_CMNTS,
          DT_RENWL_EFF_BEGIN,
          DT_RENWL_EFF_END
  ) VALUES (
    :new.ID_ADPT_SUB,
    :new.ID_ADPT_SUB_PERSON,
    :new.ID_ADPT_SUB_PAYEE,
    :new.ID_PLCMT_EVENT,
    :new.DT_LAST_UPDATE,
    :new.AMT_ADPT_SUB,
    :new.CD_ADPT_SUB_CLOSE_RSN,
    :new.CD_ADPT_SUB_DETERM,
    :new.DT_ADPT_SUB_AGREE_RETN,
    :new.DT_ADPT_SUB_AGREE_SENT,
    :new.DT_ADPT_SUB_APP_RETURNED,
    :new.DT_ADPT_SUB_APP_SENT,
    :new.DT_ADPT_SUB_APPRVD,
    :new.DT_ADPT_SUB_EFFECTIVE,
    :new.DT_ADPT_SUB_END,
    :new.DT_ADPT_SUB_LAST_INVC,
    :new.IND_ADPT_SUB_THIRD_PARTY,
    :new.IND_ADPT_SUB_PROCESS,
    :new.TXT_ADPT_SUB_RSN,
    :new.IND_SAU_CONF,
      :new.IND_SPCL_ASST_APPRVL,
      :new.AMT_SPCL_ASST_REQ,
      :new.CD_SPCL_ASST_TYPE,
      :new.TXT_SPCL_ASST_SPECIFY,
      :new.TXT_SPCL_ASST_CMNTS,
      :new.DT_RENWL_EFF_BEGIN,
      :new.DT_RENWL_EFF_END
  );
END;
/
/
DROP TRIGGER CAPS.TUBR_ADOPTION_SUBSIDY
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_ADOPTION_SUBSIDY
BEFORE UPDATE
ON CAPS.ADOPTION_SUBSIDY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
        ----------------------------------------------------------
  -- SIR #22028 08/22/96 GLOORJW only write to the shadow
  -- table if any of the following variables have changed
  -- while updating the ADOPTION_SUBSIDY table:
  --     Type       CD_ADPT_SUB_DETERM,
  --     Amount     AMT_ADPT_SUB,
  --     Start Date DT_ADPT_SUB_EFFECTIVE,
  --     End Date   DT_ADPT_SUB_END
  --     :old = old or previous value on ADOPTION_SUBSIDY table
  --     :new = new or current value on ADOPTION_SUBSIDY table
        ----------------------------------------------------------
        IF (:new.CD_ADPT_SUB_DETERM    <> :old.CD_ADPT_SUB_DETERM    OR
      :new.AMT_ADPT_SUB          <> :old.AMT_ADPT_SUB          OR
      :new.DT_ADPT_SUB_EFFECTIVE <> :old.DT_ADPT_SUB_EFFECTIVE OR
      :new.DT_ADPT_SUB_END       <> :old.DT_ADPT_SUB_END)
  THEN
             insert into ADOPTION_SUBSIDY_AUDIT (
          ID_ADPT_SUB_AUD,
          ID_ADPT_AUD_PERSON,
          ID_ADPT_AUD_PAYEE,
          ID_PLCMT_EVENT,
          DT_LAST_UPDATE,
          AMT_ADPT_AUD,
          CD_ADPT_AUD_CLOSE_RSN,
          CD_ADPT_AUD_DETERM,
          DT_ADPT_AUD_AGREE_RETN,
          DT_ADPT_AUD_AGREE_SENT,
          DT_ADPT_AUD_APP_RETURNED,
          DT_ADPT_AUD_APP_SENT,
          DT_ADPT_AUD_APPRVD ,
          DT_ADPT_AUD_EFFECTIVE,
          DT_ADPT_AUD_END,
          DT_ADPT_AUD_LAST_INVC,
          IND_ADPT_AUD_THIRD_PARTY,
          IND_ADPT_AUD_PROCESS,
          TXT_ADPT_AUD_RSN,
          IND_SAU_CONF,
          IND_SPCL_ASST_APPRVL,
          AMT_SPCL_ASST_REQ,
          CD_SPCL_ASST_TYPE,
          TXT_SPCL_ASST_SPECIFY,
          TXT_SPCL_ASST_CMNTS,
          DT_RENWL_EFF_BEGIN,
          DT_RENWL_EFF_END
      ) VALUES (
    :new.ID_ADPT_SUB,
    :new.ID_ADPT_SUB_PERSON,
    :new.ID_ADPT_SUB_PAYEE,
    :new.ID_PLCMT_EVENT,
    :new.DT_LAST_UPDATE,
    :new.AMT_ADPT_SUB,
    :new.CD_ADPT_SUB_CLOSE_RSN,
    :new.CD_ADPT_SUB_DETERM,
    :new.DT_ADPT_SUB_AGREE_RETN,
    :new.DT_ADPT_SUB_AGREE_SENT,
    :new.DT_ADPT_SUB_APP_RETURNED,
    :new.DT_ADPT_SUB_APP_SENT,
    :new.DT_ADPT_SUB_APPRVD,
    :new.DT_ADPT_SUB_EFFECTIVE,
    :new.DT_ADPT_SUB_END,
    :new.DT_ADPT_SUB_LAST_INVC,
    :new.IND_ADPT_SUB_THIRD_PARTY,
    :new.IND_ADPT_SUB_PROCESS,
    :new.TXT_ADPT_SUB_RSN,
    :new.IND_SAU_CONF,
      :new.IND_SPCL_ASST_APPRVL,
      :new.AMT_SPCL_ASST_REQ,
      :new.CD_SPCL_ASST_TYPE,
      :new.TXT_SPCL_ASST_SPECIFY,
      :new.TXT_SPCL_ASST_CMNTS,
      :new.DT_RENWL_EFF_BEGIN,
      :new.DT_RENWL_EFF_END
      );
        END IF;
  ------------------------------------------------------
  -- End SIR 22028
  ------------------------------------------------------
END;
/
/
DROP TRIGGER CAPS.TIBR_ADOPTION_SUBSIDY_AUDIT
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_ADOPTION_SUBSIDY_AUDIT
BEFORE INSERT
ON CAPS.ADOPTION_SUBSIDY_AUDIT
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
DROP TRIGGER CAPS.TUBR_ADOPTION_SUBSIDY_AUDIT
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_ADOPTION_SUBSIDY_AUDIT
BEFORE UPDATE
ON CAPS.ADOPTION_SUBSIDY_AUDIT
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/

-- Alter Index SQL

CREATE INDEX CAPS.IND_ADO_INFO_FAMILY_2
    ON CAPS.ADO_INFO_FAMILY(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADO_INFO_FAMILY_1
    ON CAPS.ADO_INFO_FAMILY(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ALLEG_EVIDENCE_1
    ON CAPS.ALLEG_EVIDENCE(ID_ALLEGATION)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ATTENDEES_2
    ON CAPS.ATTENDEES(ID_LEGAL_ACT_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ATTENDEES_1
    ON CAPS.ATTENDEES(ID_ATTD_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_COLLEGE_EXAM_1
    ON CAPS.COLLEGE_EXAM(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_COST_REIM_DTL_2
    ON CAPS.COST_REIM_DTL(ID_COST_REIM_REVRSAL_ORIG)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_DILIGENT_SEARCH_3
    ON CAPS.DILIGENT_SEARCH(ID_STAGE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_DIVERSION_CONCLUSION_2
    ON CAPS.DIVERSION_CONCLUSION(ID_STAGE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_DIVERSION_CONCLUSION_1
    ON CAPS.DIVERSION_CONCLUSION(ID_CASE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_DOCUMENT_TEMPLATE_1
    ON CAPS.DOCUMENT_TEMPLATE(ID_DOCUMENT_TEMPLATE_TYPE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_EMPLOYEE_9
    ON CAPS.EMPLOYEE(ID_PERSON_MODIFIED_BY)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_EMP_SEC_CLASS_LINK_3
    ON CAPS.EMP_SEC_CLASS_LINK(ID_PERSON_MODIFIED_BY)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FACILITY_LICENSE_TYPE_1
    ON CAPS.FACILITY_LICENSE_TYPE(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FAMILY_PLAN_3
    ON CAPS.FAMILY_PLAN(ID_EVENT_RISK_ASSMT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FAMILY_SERVICE_REFERRAL_2
    ON CAPS.FAMILY_SERVICE_REFERRAL(ID_PERSON_CREATE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FAMILY_SERVICE_REFERRAL_1
    ON CAPS.FAMILY_SERVICE_REFERRAL(ID_PERSON_ASSIGNED)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCCP_FAMILY_1
    ON CAPS.FCCP_FAMILY(ID_CASE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCE_EXPENDITURES_2
    ON CAPS.FCE_EXPENDITURES(ID_FCE_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCE_EXPENDITURES_3
    ON CAPS.FCE_EXPENDITURES(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCE_EXPENDITURES_4
    ON CAPS.FCE_EXPENDITURES(ID_PERSON_CARE_RECEIVE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCE_EXPENDITURES_1
    ON CAPS.FCE_EXPENDITURES(ID_FCE_ELIGIBILITY)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCE_REVIEW_6
    ON CAPS.FCE_REVIEW(ID_CURRENT_PLACEMENT_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCE_REVIEW_7
    ON CAPS.FCE_REVIEW(ID_PLACEMENT_RATE_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FMIS_BREAKOUT_2
    ON CAPS.FMIS_BREAKOUT(ID_INVOICE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FMIS_BREAKOUT_3
    ON CAPS.FMIS_BREAKOUT(ID_SVC_AUTH_DTL)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FMIS_BREAKOUT_1
    ON CAPS.FMIS_BREAKOUT(ID_CONTRACT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_HOME_APPLICANT_CBX_1
    ON CAPS.HOME_APPLICANT_CBX(ID_HOME_APPLICANT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_HOME_APPLICANT_INFO_1
    ON CAPS.HOME_APPLICANT_INFO(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_INCOMING_DETAIL_6
    ON CAPS.INCOMING_DETAIL(ID_INCOMING_SUP)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_INCOMING_DETAIL_7
    ON CAPS.INCOMING_DETAIL(ID_REFERRED_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_LEGAL_ACTION_CRT_LANG_1
    ON CAPS.LEGAL_ACTION_CRT_LANG(ID_LEGAL_ACT_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_MESSAGE_DEST_LINK_1
    ON CAPS.MESSAGE_DEST_LINK(ID_ERROR_LIST_DEST)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_NEEDS_OUTCOMES_1
    ON CAPS.NEEDS_OUTCOMES(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_NEEDS_OUTCOMES_DETAIL_1
    ON CAPS.NEEDS_OUTCOMES_DETAIL(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PAYMENT_OF_CARE_2
    ON CAPS.PAYMENT_OF_CARE(ID_RBWO_REV_APRV)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PAYMENT_OF_CARE_3
    ON CAPS.PAYMENT_OF_CARE(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PAYMENT_OF_CARE_4
    ON CAPS.PAYMENT_OF_CARE(ID_SO_APRV)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PAYMENT_OF_CARE_5
    ON CAPS.PAYMENT_OF_CARE(ID_SPV_PACKET_APRV)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PAYMENT_OF_CARE_1
    ON CAPS.PAYMENT_OF_CARE(ID_CM_PACKET_COMP)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PERSON_ELIGIBILITY_DTL_2
    ON CAPS.PERSON_ELIGIBILITY_DETAIL(ID_PERS_ELIG_DTL_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PERSON_ELIGIBILITY_DTL_1
    ON CAPS.PERSON_ELIGIBILITY_DETAIL(ID_PERS_ELIG)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PGM_LCNSRE_TYPS_1
    ON CAPS.PGM_LCNSRE_TYPS(ID_FLOC)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLACEMENT_9
    ON CAPS.PLACEMENT(ID_CONTACT_WRKR)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLACEMENT_0
    ON CAPS.PLACEMENT(ID_WAIVER)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLACEMENT_REFERRAL_2
    ON CAPS.PLACEMENT_REFERRAL(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLACEMENT_REFERRAL_3
    ON CAPS.PLACEMENT_REFERRAL(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLACEMENT_REFERRAL_1
    ON CAPS.PLACEMENT_REFERRAL(ID_EMPLOYEE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLAN_GOAL_1
    ON CAPS.PLAN_GOAL(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLAN_PARTICIPANT_2
    ON CAPS.PLAN_PARTICIPANT(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLAN_PARTICIPANT_1
    ON CAPS.PLAN_PARTICIPANT(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PLAN_STEP_1
    ON CAPS.PLAN_STEP(ID_PLAN_GOAL)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_POLICY_LINK_1
    ON CAPS.POLICY_LINK(CD_TASK)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_POLICY_WAIVER_2
    ON CAPS.POLICY_WAIVER(ID_WVR_PRN_UNABLE_CNCT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_POLICY_WAIVER_3
    ON CAPS.POLICY_WAIVER(ID_WVR_PRY_CUST)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_POLICY_WAIVER_4
    ON CAPS.POLICY_WAIVER(ID_WVR_RSRC)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_POLICY_WAIVER_1
    ON CAPS.POLICY_WAIVER(ID_WVR_CASE_MGR)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PPA_DELVRD_SVC_3
    ON CAPS.PPA_DELVRD_SVC(ID_CONTRACT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PPA_DELVRD_SVC_4
    ON CAPS.PPA_DELVRD_SVC(ID_INVOICE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PPA_REPORT_4
    ON CAPS.PPA_REPORT(ID_PPA_INVOICE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PROTECTIVE_SERVICE_ALERT_2
    ON CAPS.PROTECTIVE_SERVICE_ALERT(ID_STAGE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PROTECTIVE_SERVICE_ALERT_1
    ON CAPS.PROTECTIVE_SERVICE_ALERT(ID_PSA_CASE_MANAGER)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PSA_PERSON_LINK_2
    ON CAPS.PSA_PERSON_LINK(ID_PROTECTIVE_SERVICE_ALERT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_PSA_PERSON_LINK_1
    ON CAPS.PSA_PERSON_LINK(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_RELATIVE_CARE_ASSMT_1
    ON CAPS.RELATIVE_CARE_ASSMT(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_REL_CARE_ASSMT_PERSON_2
    ON CAPS.RELATIVE_CARE_ASSMT_PERSON(ID_RCA_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_REL_CARE_ASSMT_PERSON_1
    ON CAPS.RELATIVE_CARE_ASSMT_PERSON(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SA_DRUG_EXPOSED_NEWBORNS_1
    ON CAPS.SA_DRUG_EXPOSED_NEWBORNS(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SA_REASONABLE_EFFORTS_2
    ON CAPS.SA_REASONABLE_EFFORTS(ID_PERSON_CHILD)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SA_REASONABLE_EFFORTS_1
    ON CAPS.SA_REASONABLE_EFFORTS(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SA_SAFETY_ASSESSMENT_1
    ON CAPS.SA_SAFETY_ASSESSMENT(ID_CASE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SA_SAFETY_FACTOR_2
    ON CAPS.SA_SAFETY_FACTOR(ID_PERSON_CARETAKER)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SA_SAFETY_FACTOR_3
    ON CAPS.SA_SAFETY_FACTOR(ID_PERSON_CHILD)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SA_SAFETY_FACTOR_1
    ON CAPS.SA_SAFETY_FACTOR(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SECURITY_CLASS_1
    ON CAPS.SECURITY_CLASS(ID_PERSON_MODIFIED_BY)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SP_PERSONS_RESPNSBL_2
    ON CAPS.SP_PERSONS_RESPNSBL(ID_SFTY_FCTR)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SP_PERSONS_RESPNSBL_1
    ON CAPS.SP_PERSONS_RESPNSBL(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SP_SAFETY_FACTORS_1
    ON CAPS.SP_SAFETY_FACTORS(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SP_SAFETY_PLAN_1
    ON CAPS.SP_SAFETY_PLAN(ID_CASE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_SVC_AUTH_VALID_1
    ON CAPS.SVC_AUTH_VALID(ID_SVC_AUTH)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_WTLP_PLAN_2
    ON CAPS.WTLP_PLAN(ID_YDP_COORD)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_WTLP_PLAN_1
    ON CAPS.WTLP_PLAN(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADO_INFO_1
    ON CAPS.ADO_INFO(ID_RESOURCE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_ADO_INFO_CBX_1
    ON CAPS.ADO_INFO_CBX(ID_EVENT)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.ADPT_SUB_EVENT_LINK ADD CONSTRAINT FK_ADPT_SUB_EVENT_LNK_SUB
FOREIGN KEY (ID_ADPT_SUB)
REFERENCES CAPS.ADOPTION_SUBSIDY (ID_ADPT_SUB)
ENABLE
;
ALTER TABLE CAPS.SUB_ELIG_NARR ADD CONSTRAINT FK_SUB_ELIG_NARR
FOREIGN KEY (ID_ADPT_SUB)
REFERENCES CAPS.ADOPTION_SUBSIDY (ID_ADPT_SUB)
ENABLE
;
ALTER TABLE CAPS.CONTACT_CBX 
    ADD FOREIGN KEY (ID_CONTACT_EVENT)
REFERENCES CAPS.CONTACT (ID_EVENT)
ENABLE
;
ALTER TABLE CAPS.YOUTH_DETAIL 
    ADD CONSTRAINT FK_YOUTH_DETAIL_PERSON
FOREIGN KEY (ID_PERSON)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.CONTACT ADD FOREIGN KEY (ID_CONTACT_TCM_CLIENT)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.TCM_CLAIM ADD CONSTRAINT FK_TCM_CLAIM_EVENT
FOREIGN KEY (ID_EVENT)
REFERENCES CAPS.EVENT (ID_EVENT)
ENABLE
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY ADD CONSTRAINT FK_ADPT_SUBSIDY_PAYEE
FOREIGN KEY (ID_ADPT_SUB_PAYEE)
REFERENCES CAPS.CAPS_RESOURCE (ID_RESOURCE)
ENABLE
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY ADD CONSTRAINT FK_ADPT_SUBSIDY_PERS
FOREIGN KEY (ID_ADPT_SUB_PERSON)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.ADOPTION_SUBSIDY ADD CONSTRAINT FK_ADPT_SUBSIDY_PLCMT
FOREIGN KEY (ID_PLCMT_EVENT)
REFERENCES CAPS.PLACEMENT (ID_PLCMT_EVENT)
ENABLE
;


-- Alter Trigger SQL
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_CAPS_RESOURCE
BEFORE UPDATE
ON CAPS.CAPS_RESOURCE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
  dummy2    NUMBER;

-- Similar to those triggers of table PERSON
-- Mike Bui 12-JUL-95

BEGIN

-- 05/26/2001 MITSCHCG Added for CLASS project SIR #15684
-- For resource type 70 check whether any of the following columns changed
-- and if changed set the dt_ccl_update to sysdate.

IF :NEW.CD_RSRC_FACIL_TYPE ='70' THEN

IF ((:OLD.CD_RSRC_FACIL_TYPE IS NULL AND :NEW.CD_RSRC_FACIL_TYPE IS NOT NULL)   OR
   (:OLD.CD_RSRC_FACIL_TYPE IS NOT NULL AND :NEW.CD_RSRC_FACIL_TYPE IS NULL)   OR
   (:OLD.CD_RSRC_FACIL_TYPE != :NEW.CD_RSRC_FACIL_TYPE))        OR
   ((:OLD.CD_RSRC_FA_HOME_STATUS IS NULL AND :NEW.CD_RSRC_FA_HOME_STATUS IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_STATUS IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_STATUS IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_STATUS != :NEW.CD_RSRC_FA_HOME_STATUS))        OR
   ((:OLD.CD_RSRC_CATEGORY IS NULL AND :NEW.CD_RSRC_CATEGORY IS NOT NULL)   OR
   (:OLD.CD_RSRC_CATEGORY IS NOT NULL AND :NEW.CD_RSRC_CATEGORY IS NULL)   OR
   (:OLD.CD_RSRC_CATEGORY != :NEW.CD_RSRC_CATEGORY))        OR
   ((:OLD.CD_RSRC_FA_HOME_TYPE_1 IS NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_1 IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_1 IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_1 IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_1 != :NEW.CD_RSRC_FA_HOME_TYPE_1))        OR
   ((:OLD.CD_RSRC_FA_HOME_TYPE_2 IS NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_2 IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_2 IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_2 IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_2 != :NEW.CD_RSRC_FA_HOME_TYPE_2))        OR
   ((:OLD.CD_RSRC_FA_HOME_TYPE_3 IS NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_3 IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_3 IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_3 IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_3 != :NEW.CD_RSRC_FA_HOME_TYPE_3))        OR
   ((:OLD.CD_RSRC_FA_HOME_TYPE_4 IS NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_4 IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_4 IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_4 IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_4 != :NEW.CD_RSRC_FA_HOME_TYPE_4))        OR
   ((:OLD.CD_RSRC_FA_HOME_TYPE_5 IS NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_5 IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_5 IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_5 IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_5 != :NEW.CD_RSRC_FA_HOME_TYPE_5))        OR
   ((:OLD.CD_RSRC_FA_HOME_TYPE_6 IS NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_6 IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_6 IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_6 IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_6 != :NEW.CD_RSRC_FA_HOME_TYPE_6))        OR
   ((:OLD.CD_RSRC_FA_HOME_TYPE_7 IS NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_7 IS NOT NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_7 IS NOT NULL AND :NEW.CD_RSRC_FA_HOME_TYPE_7 IS NULL)   OR
   (:OLD.CD_RSRC_FA_HOME_TYPE_7 != :NEW.CD_RSRC_FA_HOME_TYPE_7))        OR
   ((:OLD.CD_RSRC_REGION IS NULL AND :NEW.CD_RSRC_REGION IS NOT NULL)   OR
   (:OLD.CD_RSRC_REGION IS NOT NULL AND :NEW.CD_RSRC_REGION IS NULL)   OR
   (:OLD.CD_RSRC_REGION != :NEW.CD_RSRC_REGION))        OR
   ((:OLD.NM_RESOURCE IS NULL AND :NEW.NM_RESOURCE IS NOT NULL)   OR
   (:OLD.NM_RESOURCE IS NOT NULL AND :NEW.NM_RESOURCE IS NULL)   OR
   (:OLD.NM_RESOURCE != :NEW.NM_RESOURCE))        OR
   ((:OLD.NBR_RSRC_FACIL_CAPACITY IS NULL AND :NEW.NBR_RSRC_FACIL_CAPACITY IS NOT NULL)   OR
   (:OLD.NBR_RSRC_FACIL_CAPACITY IS NOT NULL AND :NEW.NBR_RSRC_FACIL_CAPACITY IS NULL)   OR
   (:OLD.NBR_RSRC_FACIL_CAPACITY != :NEW.NBR_RSRC_FACIL_CAPACITY))        OR
   ((:OLD.DT_RSRC_CLOSE IS NULL AND :NEW.DT_RSRC_CLOSE IS NOT NULL)   OR
   (:OLD.DT_RSRC_CLOSE IS NOT NULL AND :NEW.DT_RSRC_CLOSE IS NULL)   OR
   (:OLD.DT_RSRC_CLOSE != :NEW.DT_RSRC_CLOSE))        OR
   ((:OLD.DT_RSRC_CERT IS NULL AND :NEW.DT_RSRC_CERT IS NOT NULL)   OR
   (:OLD.DT_RSRC_CERT IS NOT NULL AND :NEW.DT_RSRC_CERT IS NULL)   OR
   (:OLD.DT_RSRC_CERT != :NEW.DT_RSRC_CERT))        OR
   ((:OLD.ADDR_RSRC_ST_LN_1 IS NULL AND :NEW.ADDR_RSRC_ST_LN_1 IS NOT NULL)   OR
   (:OLD.ADDR_RSRC_ST_LN_1 IS NOT NULL AND :NEW.ADDR_RSRC_ST_LN_1 IS NULL)   OR
   (:OLD.ADDR_RSRC_ST_LN_1 != :NEW.ADDR_RSRC_ST_LN_1))        OR
   ((:OLD.ADDR_RSRC_ST_LN_2 IS NULL AND :NEW.ADDR_RSRC_ST_LN_2 IS NOT NULL)   OR
   (:OLD.ADDR_RSRC_ST_LN_2 IS NOT NULL AND :NEW.ADDR_RSRC_ST_LN_2 IS NULL)   OR
   (:OLD.ADDR_RSRC_ST_LN_2 != :NEW.ADDR_RSRC_ST_LN_2))        OR
   ((:OLD.ADDR_RSRC_CITY IS NULL AND :NEW.ADDR_RSRC_CITY IS NOT NULL)   OR
   (:OLD.ADDR_RSRC_CITY IS NOT NULL AND :NEW.ADDR_RSRC_CITY IS NULL)   OR
   (:OLD.ADDR_RSRC_CITY != :NEW.ADDR_RSRC_CITY))        OR
   ((:OLD.CD_RSRC_STATE IS NULL AND :NEW.CD_RSRC_STATE IS NOT NULL)   OR
   (:OLD.CD_RSRC_STATE IS NOT NULL AND :NEW.CD_RSRC_STATE IS NULL)   OR
   (:OLD.CD_RSRC_STATE != :NEW.CD_RSRC_STATE))        OR
   ((:OLD.ADDR_RSRC_ZIP IS NULL AND :NEW.ADDR_RSRC_ZIP IS NOT NULL)   OR
   (:OLD.ADDR_RSRC_ZIP IS NOT NULL AND :NEW.ADDR_RSRC_ZIP IS NULL)   OR
   (:OLD.ADDR_RSRC_ZIP != :NEW.ADDR_RSRC_ZIP))        OR
   ((:OLD.CD_RSRC_CNTY IS NULL AND :NEW.CD_RSRC_CNTY IS NOT NULL)   OR
   (:OLD.CD_RSRC_CNTY IS NOT NULL AND :NEW.CD_RSRC_CNTY IS NULL)   OR
   (:OLD.CD_RSRC_CNTY != :NEW.CD_RSRC_CNTY))        OR
   ((:OLD.NBR_RSRC_PHN IS NULL AND :NEW.NBR_RSRC_PHN IS NOT NULL)     OR
   (:OLD.NBR_RSRC_PHN IS NOT NULL AND :NEW.NBR_RSRC_PHN IS NULL)     OR
   (:OLD.NBR_RSRC_PHN != :NEW.NBR_RSRC_PHN))            OR
   ((:OLD.NBR_RSRC_PHONE_EXT IS NULL AND :NEW.NBR_RSRC_PHONE_EXT IS NOT NULL)   OR
   (:OLD.NBR_RSRC_PHONE_EXT IS NOT NULL AND :NEW.NBR_RSRC_PHONE_EXT IS NULL)   OR
   (:OLD.NBR_RSRC_PHONE_EXT != :NEW.NBR_RSRC_PHONE_EXT))        OR
   ((:OLD.NBR_RSRC_FM_AGE_MAX IS NULL AND :NEW.NBR_RSRC_FM_AGE_MAX IS NOT NULL)   OR
   (:OLD.NBR_RSRC_FM_AGE_MAX IS NOT NULL AND :NEW.NBR_RSRC_FM_AGE_MAX IS NULL)   OR
   (:OLD.NBR_RSRC_FM_AGE_MAX != :NEW.NBR_RSRC_FM_AGE_MAX))        OR
   ((:OLD.NBR_RSRC_FM_AGE_MIN IS NULL AND :NEW.NBR_RSRC_FM_AGE_MIN IS NOT NULL)   OR
   (:OLD.NBR_RSRC_FM_AGE_MIN IS NOT NULL AND :NEW.NBR_RSRC_FM_AGE_MIN IS NULL)   OR
   (:OLD.NBR_RSRC_FM_AGE_MIN != :NEW.NBR_RSRC_FM_AGE_MIN))        OR
   ((:OLD.NBR_RSRC_MA_AGE_MAX IS NULL AND :NEW.NBR_RSRC_MA_AGE_MAX IS NOT NULL)   OR
   (:OLD.NBR_RSRC_MA_AGE_MAX IS NOT NULL AND :NEW.NBR_RSRC_MA_AGE_MAX IS NULL)   OR
   (:OLD.NBR_RSRC_MA_AGE_MAX != :NEW.NBR_RSRC_MA_AGE_MAX))        OR
   ((:OLD.NBR_RSRC_MA_AGE_MIN IS NULL AND :NEW.NBR_RSRC_MA_AGE_MIN IS NOT NULL)   OR
   (:OLD.NBR_RSRC_MA_AGE_MIN IS NOT NULL AND :NEW.NBR_RSRC_MA_AGE_MIN IS NULL)   OR
   (:OLD.NBR_RSRC_MA_AGE_MIN != :NEW.NBR_RSRC_MA_AGE_MIN)) OR
   ((:OLD.CD_RSRC_ADDR_SMILEUPD_ST IS NULL AND :NEW.CD_RSRC_ADDR_SMILEUPD_ST IS NOT NULL)   OR
   (:OLD.CD_RSRC_ADDR_SMILEUPD_ST IS NOT NULL AND :NEW.CD_RSRC_ADDR_SMILEUPD_ST IS NULL)   OR
   (:OLD.CD_RSRC_ADDR_SMILEUPD_ST != :NEW.CD_RSRC_ADDR_SMILEUPD_ST))
                    THEN
  :NEW.DT_CCL_UPDATE := SYSDATE;
END IF;

END IF;


  :NEW.DT_LAST_UPDATE := SYSDATE;
  :NEW.NM_RSRC_NAME_INDEX := SUBSTR(:NEW.NM_RESOURCE,0,2);
  --insert into table RESOURCE_HISTORY if field :new.IND_RSRC_WRITE_HIST is 'Y':
  IF NVL(:NEW.IND_RSRC_WRITE_HIST,'N') = 'Y' THEN

  --dbms_output.put_line('0');
  -- 1st: set END DATE of previous record:
  UPDATE RESOURCE_HISTORY  RH
  SET    RH.DT_RSHS_END    = :NEW.DT_LAST_UPDATE
  WHERE  RH.ID_RESOURCE    = :NEW.ID_RESOURCE
  AND    RH.ID_RESOURCE_HISTORY  =
    (SELECT MAX(RH2.ID_RESOURCE_HISTORY)
    FROM   RESOURCE_HISTORY RH2
    WHERE  RH2.ID_RESOURCE= :NEW.ID_RESOURCE
    AND    RH2.DT_RSHS_END = '12/31/4712');

  -- now insert a new record into RESOURCE_HISTORY using data from the OLD record
  -- (not from the NEW record) of CAPS_RESOURCE.  This is different with that
  -- update trigger of table PERSON

  -- Get next sequence value:
  SELECT SEQ_RESOURCE_HISTORY.NEXTVAL INTO dummy2 FROM DUAL;

  --dbms_output.put_line('1 '||TO_CHAR(dummy2) ||' ' ||
  --to_char(:new.dt_last_update) || ' ' ||
  --to_char(:new.id_resource) );
  INSERT INTO RESOURCE_HISTORY (
    ID_RESOURCE_HISTORY,
    DT_RSHS_EFFECTIVE,
    DT_RSHS_END,
    ID_RESOURCE,
    DT_LAST_UPDATE,
    ID_CASE,
    ADDR_RSHS_ST_LN_1,
    ADDR_RSHS_ST_LN_2,
    ADDR_RSHS_CITY,
    ADDR_RSHS_ATTN,
    CD_RSHS_STATE,
    ADDR_RSHS_ZIP,
    CD_RSHS_CNTY,
    NM_RSHS_RESOURCE,
    NM_RSHS_CONTACT,
    CD_RSHS_TYPE,
    CD_RSHS_HUB,
    CD_RSHS_CAMPUS_TYPE,
    NBR_RSHS_PHN,
    NBR_RSHS_CAMPUS_NBR,
    CD_RSHS_MAINTAINER,
    CD_RSHS_SCH_DIST,
    CD_RSHS_OWNERSHIP,
    CD_RSHS_STATUS,
    NM_RSHS_LAST_UPDATE,
    IND_RSHS_TRANSPORT,
    CD_RSHS_FACIL_TYPE,
    NBR_RSHS_FACIL_ACCLAIM,
    CD_RSHS_CERT_BY,
    CD_RSHS_OPER_BY,
    CD_RSHS_SETTING,
    DT_RSHS_CERT,
    DT_RSHS_CLOSE,
    CD_RSHS_PAYMENT,
    NBR_RSHS_FACIL_CAPACITY,
    ID_RSHS_FA_HOME_STAGE,
    ID_RSHS_FA_HOME_EVENT,
    CD_RSHS_CATEGORY,
    CD_RSHS_ETHNICITY,
    CD_RSHS_LANGUAGE,
    CD_RSHS_MARITAL_STATUS,
    CD_RSHS_REGION,
    CD_RSHS_RELIGION,
    CD_RSHS_RESPITE,
    CD_RSHS_RECMND_REOPEN,
    CD_RSHS_FA_HOME_TYPE1,
    CD_RSHS_FA_HOME_TYPE2,
    CD_RSHS_FA_HOME_TYPE3,
    CD_RSHS_FA_HOME_TYPE4,
    CD_RSHS_FA_HOME_TYPE5,
    CD_RSHS_FA_HOME_TYPE6,
    CD_RSHS_FA_HOME_TYPE7,
                CD_RSHS_MHMR_COMP_CODE,
    CD_RSHS_INVOL_CLOSURE,
    CD_RSHS_CLOSURE_RSN,
    CD_RSHS_FA_HOME_STATUS,
    DT_RSHS_MARRIAGE,
    IND_RSHS_CARE_PROV,
    IND_RSHS_EMERG_PLACE,
    IND_RSHS_INACTIVE,
    NBR_RSHS_INT_CHILDREN,
    NBR_RSHS_INT_FE_AGE_MAX,
    NBR_RSHS_INT_FE_AGE_MIN,
    NBR_RSHS_INT_MA_AGE_MAX,
    NBR_RSHS_INT_MA_AGE_MIN,
    NBR_RSHS_ANNUAL_INCOME,
    NBR_RSHS_FM_AGE_MAX,
    NBR_RSHS_FM_AGE_MIN,
    NBR_RSHS_MA_AGE_MAX,
    NBR_RSHS_MA_AGE_MIN,
    NBR_RSHS_PHONE_EXT,
    NBR_RSHS_VID,
                NBR_RSHS_OPEN_SLOTS,
    CD_RSHS_SOURCE_INQUIRY,
    TXT_RSHS_ADDR_CMNTS,
    TXT_RSHS_COMMENTS,
                DT_CCL_UPDATE,
    CD_RSRC_MHMR_SITE,
    IND_RSRC_CONTRACTED,
    NM_LEGAL,
    NM_RSRC_CONTACT_TITLE,
    NBR_RSRC_NTNL_PROVIDER,
    ADDR_RSRC_EMAIL,
    ADDR_RSRC_WEBSITE,
    CD_SCHOOL_TYPE,
    CD_PAYMENT_DELIVERY,
    TXT_SPEC_CERT,
    CD_EXCHANGE_STAT,
    IND_WAIVER,
    CD_SCH_DIST,
    CD_ELEM,
    CD_MIDDLE,
    CD_HIGH,
    DT_FOST_MANUAL,
    DT_FOST_BILL,
    IND_SPECIFIC_CHILD,
    DT_LIC_BEGIN,
    DT_LIC_END,
    TXT_CLOSURE_COMM,
    NDFCS_CERT_ENTITY,
    IND_RSRC_NONDFCS,
    IND_CURR_HM_STDY_EXSTS,
    IND_PREV_FAM_STDY_RQSTD,
    RSRC_OTH_SPC_CERTF,
    CD_RSRC_ADDR_SMILEUPD_ST
  ) VALUES (
    dummy2,
    :NEW.DT_LAST_UPDATE,
    NULL,
    :NEW.ID_RESOURCE,
    SYSDATE,
    :NEW.ID_CASE,
    :NEW.ADDR_RSRC_ST_LN_1,
    :NEW.ADDR_RSRC_ST_LN_2,
    :NEW.ADDR_RSRC_CITY,
    :NEW.ADDR_RSRC_ATTN,
    :NEW.CD_RSRC_STATE,
    :NEW.ADDR_RSRC_ZIP,
    :NEW.CD_RSRC_CNTY,
    :NEW.NM_RESOURCE,
    :NEW.NM_RSRC_CONTACT,
    :NEW.CD_RSRC_TYPE,
    :NEW.CD_RSRC_HUB,
    :NEW.CD_RSRC_CAMPUS_TYPE,
    :NEW.NBR_RSRC_PHN,
    :NEW.NBR_RSRC_CAMPUS_NBR,
    :NEW.CD_RSRC_MAINTAINER,
    :NEW.CD_RSRC_SCH_DIST,
    :NEW.CD_RSRC_OWNERSHIP,
    :NEW.CD_RSRC_STATUS,
    :NEW.NM_RSRC_LAST_UPDATE,
    :NEW.IND_RSRC_TRANSPORT,
    :NEW.CD_RSRC_FACIL_TYPE,
    :NEW.NBR_RSRC_FACIL_ACCLAIM,
    :NEW.CD_RSRC_CERT_BY,
    :NEW.CD_RSRC_OPER_BY,
    :NEW.CD_RSRC_SETTING,
    :NEW.DT_RSRC_CERT,
    :NEW.DT_RSRC_CLOSE,
    :NEW.CD_RSRC_PAYMENT,
    :NEW.NBR_RSRC_FACIL_CAPACITY,
    :NEW.ID_RSRC_FA_HOME_STAGE,
    :NEW.ID_RSRC_FA_HOME_EVENT,
    :NEW.CD_RSRC_CATEGORY,
    :NEW.CD_RSRC_ETHNICITY,
    :NEW.CD_RSRC_LANGUAGE,
    :NEW.CD_RSRC_MARITAL_STATUS,
    :NEW.CD_RSRC_REGION,
    :NEW.CD_RSRC_RELIGION,
    :NEW.CD_RSRC_RESPITE,
    :NEW.CD_RSRC_RECMND_REOPEN,
    :NEW.CD_RSRC_FA_HOME_TYPE_1,
    :NEW.CD_RSRC_FA_HOME_TYPE_2,
    :NEW.CD_RSRC_FA_HOME_TYPE_3,
    :NEW.CD_RSRC_FA_HOME_TYPE_4,
    :NEW.CD_RSRC_FA_HOME_TYPE_5,
    :NEW.CD_RSRC_FA_HOME_TYPE_6,
    :NEW.CD_RSRC_FA_HOME_TYPE_7,
                :NEW.CD_RSRC_MHMR_COMP_CODE,
    :NEW.CD_RSRC_INVOL_CLOSURE,
    :NEW.CD_RSRC_CLOSURE_RSN,
    :NEW.CD_RSRC_FA_HOME_STATUS,
    :NEW.DT_RSRC_MARRIAGE,
    :NEW.IND_RSRC_CARE_PROV,
    :NEW.IND_RSRC_EMERG_PLACE,
    :NEW.IND_RSRC_INACTIVE,
    :NEW.NBR_RSRC_INT_CHILDREN,
    :NEW.NBR_RSRC_INT_FE_AGE_MAX,
    :NEW.NBR_RSRC_INT_FE_AGE_MIN,
    :NEW.NBR_RSRC_INT_MA_AGE_MAX,
    :NEW.NBR_RSRC_INT_MA_AGE_MIN,
    :NEW.NBR_RSRC_ANNUAL_INCOME,
    :NEW.NBR_RSRC_FM_AGE_MAX,
    :NEW.NBR_RSRC_FM_AGE_MIN,
    :NEW.NBR_RSRC_MA_AGE_MAX,
    :NEW.NBR_RSRC_MA_AGE_MIN,
    :NEW.NBR_RSRC_PHONE_EXT,
    :NEW.NBR_RSRC_VID,
                :NEW.NBR_RSRC_OPEN_SLOTS,
    :NEW.CD_RSRC_SOURCE_INQUIRY,
    :NEW.TXT_RSRC_ADDR_CMNTS,
    :NEW.TXT_RSRC_COMMENTS,
                :NEW.DT_CCL_UPDATE,
    :NEW.CD_RSRC_MHMR_SITE,
    :NEW.IND_RSRC_CONTRACTED,
    :NEW.NM_LEGAL,
    :NEW.NM_RSRC_CONTACT_TITLE,
    :NEW.NBR_RSRC_NTNL_PROVIDER,
    :NEW.ADDR_RSRC_EMAIL,
    :NEW.ADDR_RSRC_WEBSITE,
    :NEW.CD_SCHOOL_TYPE,
    :NEW.CD_PAYMENT_DELIVERY,
    :NEW.TXT_SPEC_CERT,
    :NEW.CD_EXCHANGE_STAT,
    :NEW.IND_WAIVER,
    :NEW.CD_SCH_DIST,
    :NEW.CD_ELEM,
    :NEW.CD_MIDDLE,
    :NEW.CD_HIGH,
    :NEW.DT_FOST_MANUAL,
    :NEW.DT_FOST_BILL,
    :NEW.IND_SPECIFIC_CHILD,
    :NEW.DT_LIC_BEGIN,
    :NEW.DT_LIC_END,
    :NEW.TXT_CLOSURE_COMM,
    :New.NDFCS_CERT_ENTITY,
    :New.IND_RSRC_NONDFCS,
    :New.IND_CURR_HM_STDY_EXSTS,
    :New.IND_PREV_FAM_STDY_RQSTD,
    :New.RSRC_OTH_SPC_CERTF,
    :New.CD_RSRC_ADDR_SMILEUPD_ST);
END IF;


END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_CAPS_RESOURCE
BEFORE INSERT
ON CAPS.CAPS_RESOURCE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
  dummy2    NUMBER;

-- Similar to those triggers of table PERSON
-- Mike Bui 12-JUL-95

BEGIN

-- 05/26/2001 MITSCHCG Added for CLASS project SIR #15684

IF :NEW.CD_RSRC_FACIL_TYPE = '70' THEN
  :NEW.DT_CCL_UPDATE := SYSDATE;
END IF;
--
  :NEW.DT_LAST_UPDATE := SYSDATE;
  :NEW.NM_RSRC_NAME_INDEX := SUBSTR(:NEW.NM_RESOURCE,0,2);
  IF :NEW.ID_RESOURCE=0 THEN
  SELECT SEQ_CAPS_RESOURCE.NEXTVAL INTO dummy  FROM DUAL;
  :NEW.ID_RESOURCE := dummy;
  END IF;

  BEGIN
    SELECT  ID_CASE
    INTO    :NEW.ID_CASE
    FROM    STAGE
    WHERE    ID_STAGE = :NEW.ID_RSRC_FA_HOME_STAGE;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQL%NOTFOUND THEN
        :NEW.ID_CASE := NULL;
      END IF;
  END;

  --insert into table RESOURCE_HISTORY if field :new.IND_RSRC_WRITE_HIST is 'Y':
   IF NVL(:NEW.IND_RSRC_WRITE_HIST,'N') = 'Y' THEN

  -- Get next sequence value:
  SELECT SEQ_RESOURCE_HISTORY.NEXTVAL INTO dummy2 FROM DUAL;

  INSERT INTO RESOURCE_HISTORY (
    ID_RESOURCE_HISTORY,
    DT_RSHS_EFFECTIVE,
    DT_RSHS_END,
    ID_RESOURCE,
    DT_LAST_UPDATE,
    ID_CASE,
    ADDR_RSHS_ST_LN_1,
    ADDR_RSHS_ST_LN_2,
    ADDR_RSHS_CITY,
    ADDR_RSHS_ATTN,
    CD_RSHS_STATE,
    ADDR_RSHS_ZIP,
    CD_RSHS_CNTY,
    NM_RSHS_RESOURCE,
    NM_RSHS_CONTACT,
    CD_RSHS_TYPE,
    CD_RSHS_HUB,
    CD_RSHS_CAMPUS_TYPE,
    NBR_RSHS_PHN,
    NBR_RSHS_CAMPUS_NBR,
    CD_RSHS_MAINTAINER,
    CD_RSHS_SCH_DIST,
    CD_RSHS_OWNERSHIP,
    CD_RSHS_STATUS,
    NM_RSHS_LAST_UPDATE,
    IND_RSHS_TRANSPORT,
    CD_RSHS_FACIL_TYPE,
    NBR_RSHS_FACIL_ACCLAIM,
    CD_RSHS_CERT_BY,
    CD_RSHS_OPER_BY,
    CD_RSHS_SETTING,
    DT_RSHS_CERT,
    DT_RSHS_CLOSE,
    CD_RSHS_PAYMENT,
    NBR_RSHS_FACIL_CAPACITY,
    ID_RSHS_FA_HOME_STAGE,
    ID_RSHS_FA_HOME_EVENT,
    CD_RSHS_CATEGORY,
    CD_RSHS_ETHNICITY,
    CD_RSHS_LANGUAGE,
    CD_RSHS_MARITAL_STATUS,
    CD_RSHS_REGION,
    CD_RSHS_RELIGION,
    CD_RSHS_RESPITE,
    CD_RSHS_RECMND_REOPEN,
    CD_RSHS_FA_HOME_TYPE1,
    CD_RSHS_FA_HOME_TYPE2,
    CD_RSHS_FA_HOME_TYPE3,
    CD_RSHS_FA_HOME_TYPE4,
    CD_RSHS_FA_HOME_TYPE5,
    CD_RSHS_FA_HOME_TYPE6,
    CD_RSHS_FA_HOME_TYPE7,
                CD_RSHS_MHMR_COMP_CODE,
    CD_RSHS_INVOL_CLOSURE,
    CD_RSHS_CLOSURE_RSN,
    CD_RSHS_FA_HOME_STATUS,
    DT_RSHS_MARRIAGE,
    IND_RSHS_CARE_PROV,
    IND_RSHS_EMERG_PLACE,
    IND_RSHS_INACTIVE,
    NBR_RSHS_INT_CHILDREN,
    NBR_RSHS_INT_FE_AGE_MAX,
    NBR_RSHS_INT_FE_AGE_MIN,
    NBR_RSHS_INT_MA_AGE_MAX,
    NBR_RSHS_INT_MA_AGE_MIN,
    NBR_RSHS_ANNUAL_INCOME,
    NBR_RSHS_FM_AGE_MAX,
    NBR_RSHS_FM_AGE_MIN,
    NBR_RSHS_MA_AGE_MAX,
    NBR_RSHS_MA_AGE_MIN,
    NBR_RSHS_PHONE_EXT,
    NBR_RSHS_VID,
                NBR_RSHS_OPEN_SLOTS,
    CD_RSHS_SOURCE_INQUIRY,
    TXT_RSHS_ADDR_CMNTS,
    TXT_RSHS_COMMENTS,
    DT_CCL_UPDATE,
    CD_RSRC_MHMR_SITE,
    IND_RSRC_CONTRACTED,
    NM_LEGAL,
    NM_RSRC_CONTACT_TITLE,
    NBR_RSRC_NTNL_PROVIDER,
    ADDR_RSRC_EMAIL,
    ADDR_RSRC_WEBSITE,
    CD_SCHOOL_TYPE,
    CD_PAYMENT_DELIVERY,
    TXT_SPEC_CERT,
    CD_EXCHANGE_STAT,
    IND_WAIVER,
    CD_SCH_DIST,
    CD_ELEM,
    CD_MIDDLE,
    CD_HIGH,
    DT_FOST_MANUAL,
    DT_FOST_BILL,
    IND_SPECIFIC_CHILD,
    DT_LIC_BEGIN,
    DT_LIC_END,
    TXT_CLOSURE_COMM,
    NDFCS_CERT_ENTITY,
    IND_RSRC_NONDFCS,
    IND_CURR_HM_STDY_EXSTS,
    IND_PREV_FAM_STDY_RQSTD,
    RSRC_OTH_SPC_CERTF,
    CD_RSRC_ADDR_SMILEUPD_ST)
 VALUES (
    dummy2,
    :NEW.DT_LAST_UPDATE,
    NULL,
    :NEW.ID_RESOURCE,
    SYSDATE,
    :NEW.ID_CASE,
    :NEW.ADDR_RSRC_ST_LN_1,
    :NEW.ADDR_RSRC_ST_LN_2,
    :NEW.ADDR_RSRC_CITY,
    :NEW.ADDR_RSRC_ATTN,
    :NEW.CD_RSRC_STATE,
    :NEW.ADDR_RSRC_ZIP,
    :NEW.CD_RSRC_CNTY,
    :NEW.NM_RESOURCE,
    :NEW.NM_RSRC_CONTACT,
    :NEW.CD_RSRC_TYPE,
    :NEW.CD_RSRC_HUB,
    :NEW.CD_RSRC_CAMPUS_TYPE,
    :NEW.NBR_RSRC_PHN,
    :NEW.NBR_RSRC_CAMPUS_NBR,
    :NEW.CD_RSRC_MAINTAINER,
    :NEW.CD_RSRC_SCH_DIST,
    :NEW.CD_RSRC_OWNERSHIP,
    :NEW.CD_RSRC_STATUS,
    :NEW.NM_RSRC_LAST_UPDATE,
    :NEW.IND_RSRC_TRANSPORT,
    :NEW.CD_RSRC_FACIL_TYPE,
    :NEW.NBR_RSRC_FACIL_ACCLAIM,
    :NEW.CD_RSRC_CERT_BY,
    :NEW.CD_RSRC_OPER_BY,
    :NEW.CD_RSRC_SETTING,
    :NEW.DT_RSRC_CERT,
    :NEW.DT_RSRC_CLOSE,
    :NEW.CD_RSRC_PAYMENT,
    :NEW.NBR_RSRC_FACIL_CAPACITY,
    :NEW.ID_RSRC_FA_HOME_STAGE,
    :NEW.ID_RSRC_FA_HOME_EVENT,
    :NEW.CD_RSRC_CATEGORY,
    :NEW.CD_RSRC_ETHNICITY,
    :NEW.CD_RSRC_LANGUAGE,
    :NEW.CD_RSRC_MARITAL_STATUS,
    :NEW.CD_RSRC_REGION,
    :NEW.CD_RSRC_RELIGION,
    :NEW.CD_RSRC_RESPITE,
    :NEW.CD_RSRC_RECMND_REOPEN,
    :NEW.CD_RSRC_FA_HOME_TYPE_1,
    :NEW.CD_RSRC_FA_HOME_TYPE_2,
    :NEW.CD_RSRC_FA_HOME_TYPE_3,
    :NEW.CD_RSRC_FA_HOME_TYPE_4,
    :NEW.CD_RSRC_FA_HOME_TYPE_5,
    :NEW.CD_RSRC_FA_HOME_TYPE_6,
    :NEW.CD_RSRC_FA_HOME_TYPE_7,
                :NEW.CD_RSRC_MHMR_COMP_CODE,
    :NEW.CD_RSRC_INVOL_CLOSURE,
    :NEW.CD_RSRC_CLOSURE_RSN,
    :NEW.CD_RSRC_FA_HOME_STATUS,
    :NEW.DT_RSRC_MARRIAGE,
    :NEW.IND_RSRC_CARE_PROV,
    :NEW.IND_RSRC_EMERG_PLACE,
    :NEW.IND_RSRC_INACTIVE,
    :NEW.NBR_RSRC_INT_CHILDREN,
    :NEW.NBR_RSRC_INT_FE_AGE_MAX,
    :NEW.NBR_RSRC_INT_FE_AGE_MIN,
    :NEW.NBR_RSRC_INT_MA_AGE_MAX,
    :NEW.NBR_RSRC_INT_MA_AGE_MIN,
    :NEW.NBR_RSRC_ANNUAL_INCOME,
    :NEW.NBR_RSRC_FM_AGE_MAX,
    :NEW.NBR_RSRC_FM_AGE_MIN,
    :NEW.NBR_RSRC_MA_AGE_MAX,
    :NEW.NBR_RSRC_MA_AGE_MIN,
    :NEW.NBR_RSRC_PHONE_EXT,
    :NEW.NBR_RSRC_VID,
                :NEW.NBR_RSRC_OPEN_SLOTS,
    :NEW.CD_RSRC_SOURCE_INQUIRY,
    :NEW.TXT_RSRC_ADDR_CMNTS,
    :NEW.TXT_RSRC_COMMENTS,
    :NEW.DT_CCL_UPDATE,
    :NEW.CD_RSRC_MHMR_SITE,
    :NEW.IND_RSRC_CONTRACTED,
    :NEW.NM_LEGAL,
    :New.NM_RSRC_CONTACT_TITLE,
    :New.NBR_RSRC_NTNL_PROVIDER,
    :New.ADDR_RSRC_EMAIL,
    :New.ADDR_RSRC_WEBSITE,
    :New.CD_SCHOOL_TYPE,
    :New.CD_PAYMENT_DELIVERY,
    :New.TXT_SPEC_CERT,
    :New.CD_EXCHANGE_STAT,
    :New.IND_WAIVER,
    :New.CD_SCH_DIST,
    :New.CD_ELEM,
    :New.CD_MIDDLE,
    :New.CD_HIGH,
    :New.DT_FOST_MANUAL,
    :New.DT_FOST_BILL,
    :New.IND_SPECIFIC_CHILD,
    :New.DT_LIC_BEGIN,
    :New.DT_LIC_END,
    :New.TXT_CLOSURE_COMM,
    :New.NDFCS_CERT_ENTITY,
    :New.IND_RSRC_NONDFCS,
    :New.IND_CURR_HM_STDY_EXSTS,
    :New.IND_PREV_FAM_STDY_RQSTD,
    :New.RSRC_OTH_SPC_CERTF,
    :New.CD_RSRC_ADDR_SMILEUPD_ST);

   END IF;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_RESOURCE_HISTORY
BEFORE UPDATE
ON CAPS.RESOURCE_HISTORY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :NEW.DT_LAST_UPDATE := SYSDATE;

  IF :NEW.DT_RSHS_END IS NULL THEN
    :NEW.DT_RSHS_END := TO_DATE('12/31/4712','MM/DD/YYYY');
  END IF;

  INSERT INTO RESOURCE_HISTORY_AUDIT (
    ID_RESOURCE_HISTORY_AUD,
    ID_AUD_RESOURCE,
    DT_RSHS_AUD_EFFECTIVE,
    DT_RSHS_AUD_CLOSE,
    DT_LAST_UPDATE,
    ID_CASE,
    DT_RSHS_AUD_CERT,
    DT_RSHS_AUD_MARRIAGE,
    DT_RSHS_AUD_END,
    ADDR_RSHS_AUD_ST_LN_1,
    ADDR_RSHS_AUD_ST_LN_2,
    ADDR_RSHS_AUD_CITY,
    CD_RSHS_AUD_STATE,
    ADDR_RSHS_AUD_ZIP,
    ADDR_RSHS_AUD_ATTN,
    CD_RSHS_AUD_CNTY,
    CD_RSHS_AUD_INVOL_CLOSURE,
    CD_RSHS_AUD_CLOSURE_RSN,
    CD_RSHS_AUD_TYPE,
    CD_RSHS_AUD_HUB,
    CD_RSHS_AUD_CAMPUS_TYPE,
    CD_RSHS_AUD_SOURCE_INQUIRY,
    CD_RSHS_AUD_MAINTAINER,
    CD_RSHS_AUD_SCH_DIST,
    CD_RSHS_AUD_OWNERSHIP,
    CD_RSHS_AUD_STATUS,
    CD_RSHS_AUD_FACIL_TYPE,
    CD_RSHS_AUD_CERT_BY,
    CD_RSHS_AUD_OPER_BY,
    CD_RSHS_AUD_SETTING,
    CD_RSHS_AUD_PAYMENT,
    CD_RSHS_AUD_CATEGORY,
    CD_RSHS_AUD_ETHNICITY,
    CD_RSHS_AUD_LANGUAGE,
    CD_RSHS_AUD_MARITAL_STATUS,
    CD_RSHS_AUD_RECMND_REOPEN,
    CD_RSHS_AUD_REGION,
    CD_RSHS_AUD_RELIGION,
    CD_RSHS_AUD_RESPITE,
    CD_RSHS_AUD_FA_HOME_STATUS,
    CD_RSHS_AUD_FA_HOME_TYPE1,
    CD_RSHS_AUD_FA_HOME_TYPE2,
    CD_RSHS_AUD_FA_HOME_TYPE3,
    CD_RSHS_AUD_FA_HOME_TYPE4,
    CD_RSHS_AUD_FA_HOME_TYPE5,
    CD_RSHS_AUD_FA_HOME_TYPE6,
    CD_RSHS_AUD_FA_HOME_TYPE7,
                CD_RSHS_AUD_MHMR_COMP_CODE,
    ID_RSHS_AUD_FA_HOME_STAGE,
    ID_RSHS_AUD_FA_HOME_EVENT,
    IND_RSHS_AUD_CARE_PROV,
    IND_RSHS_AUD_INACTIVE,
    IND_RSHS_AUD_TRANSPORT,
    IND_RSHS_AUD_EMERG_PLACE,
    NM_RSHS_AUD_RESOURCE,
    NM_RSHS_AUD_CONTACT,
    NM_RSHS_AUD_LAST_UPDATE,
    NBR_RSHS_AUD_VID,
    NBR_RSHS_AUD_PHN,
    NBR_RSHS_AUD_FACIL_CAPACITY,
    NBR_RSHS_AUD_FACIL_ACCLAIM,
    NBR_RSHS_AUD_PHONE_EXT,
    NBR_RSHS_AUD_CAMPUS_NBR,
    NBR_RSHS_AUD_ANNUAL_INCOME,
    NBR_RSHS_AUD_FM_AGE_MAX,
    NBR_RSHS_AUD_FM_AGE_MIN,
    NBR_RSHS_AUD_MA_AGE_MAX,
    NBR_RSHS_AUD_MA_AGE_MIN,
    NBR_RSHS_AUD_INT_CHILDREN,
    NBR_RSHS_AUD_INT_FE_AGE_MAX ,
    NBR_RSHS_AUD_INT_FE_AGE_MIN,
    NBR_RSHS_AUD_INT_MA_AGE_MAX,
    NBR_RSHS_AUD_INT_MA_AGE_MIN,
    NBR_RSHS_AUD_OPEN_SLOTS,
    TXT_RSHS_AUD_ADDR_CMNTS,
    TXT_RSHS_AUD_COMMENTS,
    IND_RSHS_AUD_WRITE_AUDIT,
    DT_CCL_UPDATE,
    CD_RSRC_MHMR_SITE,
    IND_RSRC_CONTRACTED,
    NM_LEGAL,
    NM_RSRC_CONTACT_TITLE,
    NBR_RSRC_NTNL_PROVIDER,
    ADDR_RSRC_EMAIL,
    ADDR_RSRC_WEBSITE,
    CD_SCHOOL_TYPE,
    CD_PAYMENT_DELIVERY,
    TXT_SPEC_CERT,
    CD_EXCHANGE_STAT,
    IND_WAIVER,
    CD_SCH_DIST,
    CD_ELEM,
    CD_MIDDLE,
    CD_HIGH,
    DT_FOST_MANUAL,
    DT_FOST_BILL,
    IND_SPECIFIC_CHILD,
    DT_LIC_BEGIN,
    DT_LIC_END,
    TXT_CLOSURE_COMM,
    NDFCS_CERT_ENTITY,
    IND_RSRC_NONDFCS,
    IND_CURR_HM_STDY_EXSTS,
    IND_PREV_FAM_STDY_RQSTD,
    RSRC_OTH_SPC_CERTF,
    CD_RSRC_ADDR_SMILEUPD_ST
  ) VALUES (
    :NEW.ID_RESOURCE_HISTORY,
    :NEW.ID_RESOURCE,
    :NEW.DT_RSHS_EFFECTIVE,
    :NEW.DT_RSHS_CLOSE,
    :NEW.DT_LAST_UPDATE,
    :NEW.ID_CASE,
    :NEW.DT_RSHS_CERT,
    :NEW.DT_RSHS_MARRIAGE,
    :NEW.DT_RSHS_END,
    :NEW.ADDR_RSHS_ST_LN_1,
    :NEW.ADDR_RSHS_ST_LN_2,
    :NEW.ADDR_RSHS_CITY,
    :NEW.CD_RSHS_STATE,
    :NEW.ADDR_RSHS_ZIP,
    :NEW.ADDR_RSHS_ATTN,
    :NEW.CD_RSHS_CNTY,
    :NEW.CD_RSHS_INVOL_CLOSURE,
    :NEW.CD_RSHS_CLOSURE_RSN,
    :NEW.CD_RSHS_TYPE,
    :NEW.CD_RSHS_HUB,
    :NEW.CD_RSHS_CAMPUS_TYPE,
    :NEW.CD_RSHS_SOURCE_INQUIRY,
    :NEW.CD_RSHS_MAINTAINER,
    :NEW.CD_RSHS_SCH_DIST,
    :NEW.CD_RSHS_OWNERSHIP,
    :NEW.CD_RSHS_STATUS,
    :NEW.CD_RSHS_FACIL_TYPE,
    :NEW.CD_RSHS_CERT_BY,
    :NEW.CD_RSHS_OPER_BY,
    :NEW.CD_RSHS_SETTING,
    :NEW.CD_RSHS_PAYMENT,
    :NEW.CD_RSHS_CATEGORY,
    :NEW.CD_RSHS_ETHNICITY,
    :NEW.CD_RSHS_LANGUAGE,
    :NEW.CD_RSHS_MARITAL_STATUS,
    :NEW.CD_RSHS_RECMND_REOPEN,
    :NEW.CD_RSHS_REGION,
    :NEW.CD_RSHS_RELIGION,
    :NEW.CD_RSHS_RESPITE,
    :NEW.CD_RSHS_FA_HOME_STATUS,
    :NEW.CD_RSHS_FA_HOME_TYPE1,
    :NEW.CD_RSHS_FA_HOME_TYPE2,
    :NEW.CD_RSHS_FA_HOME_TYPE3,
    :NEW.CD_RSHS_FA_HOME_TYPE4,
    :NEW.CD_RSHS_FA_HOME_TYPE5,
    :NEW.CD_RSHS_FA_HOME_TYPE6,
    :NEW.CD_RSHS_FA_HOME_TYPE7,
                :NEW.CD_RSHS_MHMR_COMP_CODE,
    :NEW.ID_RSHS_FA_HOME_STAGE,
    :NEW.ID_RSHS_FA_HOME_EVENT,
    :NEW.IND_RSHS_CARE_PROV,
    :NEW.IND_RSHS_INACTIVE,
    :NEW.IND_RSHS_TRANSPORT,
    :NEW.IND_RSHS_EMERG_PLACE,
    :NEW.NM_RSHS_RESOURCE,
    :NEW.NM_RSHS_CONTACT,
    :NEW.NM_RSHS_LAST_UPDATE,
    :NEW.NBR_RSHS_VID,
    :NEW.NBR_RSHS_PHN,
    :NEW.NBR_RSHS_FACIL_CAPACITY,
    :NEW.NBR_RSHS_FACIL_ACCLAIM,
    :NEW.NBR_RSHS_PHONE_EXT,
    :NEW.NBR_RSHS_CAMPUS_NBR,
    :NEW.NBR_RSHS_ANNUAL_INCOME,
    :NEW.NBR_RSHS_FM_AGE_MAX,
    :NEW.NBR_RSHS_FM_AGE_MIN,
    :NEW.NBR_RSHS_MA_AGE_MAX,
    :NEW.NBR_RSHS_MA_AGE_MIN,
    :NEW.NBR_RSHS_INT_CHILDREN,
    :NEW.NBR_RSHS_INT_FE_AGE_MAX,
    :NEW.NBR_RSHS_INT_FE_AGE_MIN,
    :NEW.NBR_RSHS_INT_MA_AGE_MAX,
    :NEW.NBR_RSHS_INT_MA_AGE_MIN,
    :NEW.NBR_RSHS_OPEN_SLOTS,
    :NEW.TXT_RSHS_ADDR_CMNTS,
    :NEW.TXT_RSHS_COMMENTS,
    :NEW.IND_RSHS_WRITE_AUDIT,
    :NEW.DT_CCL_UPDATE,
    :NEW.CD_RSRC_MHMR_SITE,
    :NEW.IND_RSRC_CONTRACTED,
    :NEW.NM_LEGAL,
    :NEW.NM_RSRC_CONTACT_TITLE,
    :NEW.NBR_RSRC_NTNL_PROVIDER,
    :NEW.ADDR_RSRC_EMAIL,
    :NEW.ADDR_RSRC_WEBSITE,
    :NEW.CD_SCHOOL_TYPE,
    :NEW.CD_PAYMENT_DELIVERY,
    :NEW.TXT_SPEC_CERT,
    :NEW.CD_EXCHANGE_STAT,
    :NEW.IND_WAIVER,
    :NEW.CD_SCH_DIST,
    :NEW.CD_ELEM,
    :NEW.CD_MIDDLE,
    :NEW.CD_HIGH,
    :NEW.DT_FOST_MANUAL,
    :NEW.DT_FOST_BILL,
    :NEW.IND_SPECIFIC_CHILD,
    :NEW.DT_LIC_BEGIN,
    :NEW.DT_LIC_END,
    :NEW.TXT_CLOSURE_COMM,
    :NEW.NDFCS_CERT_ENTITY,
    :NEW.IND_RSRC_NONDFCS,
    :NEW.IND_CURR_HM_STDY_EXSTS,
    :NEW.IND_PREV_FAM_STDY_RQSTD,
    :New.RSRC_OTH_SPC_CERTF,
    :New.CD_RSRC_ADDR_SMILEUPD_ST
  );
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_RESOURCE_HISTORY
BEFORE INSERT
ON CAPS.RESOURCE_HISTORY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
  dummy2    NUMBER;
  dummy_date  DATE;

BEGIN

-- 05/26/2001 MITSCHCG Added column DT_CCL_UPDATE for CLASS project SIR #15684

  :NEW.DT_LAST_UPDATE := SYSDATE;

  IF (:NEW.ID_RESOURCE_HISTORY = 0) OR
       (:NEW.ID_RESOURCE_HISTORY IS NULL) THEN
    SELECT  SEQ_RESOURCE_HISTORY.NEXTVAL
    INTO    dummy
    FROM    DUAL;
    :NEW.ID_RESOURCE_HISTORY := dummy;
  END IF;

  IF :NEW.DT_RSHS_END IS NULL THEN
    :NEW.DT_RSHS_END := TO_DATE('12/31/4712','MM/DD/YYYY');
  END IF;

  IF :NEW.ID_CASE  IS NULL THEN
    BEGIN
      SELECT  ID_CASE
      INTO    :NEW.ID_CASE
      FROM    STAGE
      WHERE    ID_STAGE = :NEW.ID_RSHS_FA_HOME_STAGE;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQL%NOTFOUND THEN
          :NEW.ID_CASE := NULL;
        END IF;
    END;
  END IF;

  INSERT INTO RESOURCE_HISTORY_AUDIT (
    ID_RESOURCE_HISTORY_AUD,
    ID_AUD_RESOURCE,
    DT_RSHS_AUD_EFFECTIVE,
    DT_RSHS_AUD_CLOSE,
    DT_LAST_UPDATE,
    ID_CASE,
    DT_RSHS_AUD_CERT ,
    DT_RSHS_AUD_MARRIAGE,
    DT_RSHS_AUD_END,
    ADDR_RSHS_AUD_ST_LN_1,
    ADDR_RSHS_AUD_ST_LN_2,
    ADDR_RSHS_AUD_CITY,
    CD_RSHS_AUD_STATE,
    ADDR_RSHS_AUD_ZIP,
    ADDR_RSHS_AUD_ATTN,
    CD_RSHS_AUD_CNTY,
    CD_RSHS_AUD_INVOL_CLOSURE,
    CD_RSHS_AUD_CLOSURE_RSN,
    CD_RSHS_AUD_TYPE,
    CD_RSHS_AUD_HUB,
    CD_RSHS_AUD_CAMPUS_TYPE,
    CD_RSHS_AUD_SOURCE_INQUIRY,
    CD_RSHS_AUD_MAINTAINER,
    CD_RSHS_AUD_SCH_DIST,
    CD_RSHS_AUD_OWNERSHIP,
    CD_RSHS_AUD_STATUS,
    CD_RSHS_AUD_FACIL_TYPE,
    CD_RSHS_AUD_CERT_BY,
    CD_RSHS_AUD_OPER_BY,
    CD_RSHS_AUD_SETTING,
    CD_RSHS_AUD_PAYMENT,
    CD_RSHS_AUD_CATEGORY,
    CD_RSHS_AUD_ETHNICITY,
    CD_RSHS_AUD_LANGUAGE,
    CD_RSHS_AUD_MARITAL_STATUS,
    CD_RSHS_AUD_RECMND_REOPEN,
    CD_RSHS_AUD_REGION,
    CD_RSHS_AUD_RELIGION,
    CD_RSHS_AUD_RESPITE,
    CD_RSHS_AUD_FA_HOME_STATUS,
    CD_RSHS_AUD_FA_HOME_TYPE1   ,
    CD_RSHS_AUD_FA_HOME_TYPE2,
    CD_RSHS_AUD_FA_HOME_TYPE3,
    CD_RSHS_AUD_FA_HOME_TYPE4   ,
    CD_RSHS_AUD_FA_HOME_TYPE5,
    CD_RSHS_AUD_FA_HOME_TYPE6,
    CD_RSHS_AUD_FA_HOME_TYPE7,
                CD_RSHS_AUD_MHMR_COMP_CODE,
    ID_RSHS_AUD_FA_HOME_STAGE,
    ID_RSHS_AUD_FA_HOME_EVENT,
    IND_RSHS_AUD_CARE_PROV,
    IND_RSHS_AUD_INACTIVE,
    IND_RSHS_AUD_TRANSPORT,
    IND_RSHS_AUD_EMERG_PLACE,
    NM_RSHS_AUD_RESOURCE,
    NM_RSHS_AUD_CONTACT,
    NM_RSHS_AUD_LAST_UPDATE,
    NBR_RSHS_AUD_VID,
    NBR_RSHS_AUD_PHN,
    NBR_RSHS_AUD_FACIL_CAPACITY,
    NBR_RSHS_AUD_FACIL_ACCLAIM,
    NBR_RSHS_AUD_PHONE_EXT,
    NBR_RSHS_AUD_CAMPUS_NBR,
    NBR_RSHS_AUD_ANNUAL_INCOME,
    NBR_RSHS_AUD_FM_AGE_MAX,
    NBR_RSHS_AUD_FM_AGE_MIN,
    NBR_RSHS_AUD_MA_AGE_MAX,
    NBR_RSHS_AUD_MA_AGE_MIN,
    NBR_RSHS_AUD_INT_CHILDREN,
    NBR_RSHS_AUD_INT_FE_AGE_MAX ,
    NBR_RSHS_AUD_INT_FE_AGE_MIN,
    NBR_RSHS_AUD_INT_MA_AGE_MAX,
    NBR_RSHS_AUD_INT_MA_AGE_MIN,
    NBR_RSHS_AUD_OPEN_SLOTS,
    TXT_RSHS_AUD_ADDR_CMNTS,
    TXT_RSHS_AUD_COMMENTS,
    IND_RSHS_AUD_WRITE_AUDIT,
    DT_CCL_UPDATE,
    CD_RSRC_MHMR_SITE,
    IND_RSRC_CONTRACTED,
    NM_LEGAL,
    NM_RSRC_CONTACT_TITLE,
    NBR_RSRC_NTNL_PROVIDER,
    ADDR_RSRC_EMAIL,
    ADDR_RSRC_WEBSITE,
    CD_SCHOOL_TYPE,
    CD_PAYMENT_DELIVERY,
    TXT_SPEC_CERT,
    CD_EXCHANGE_STAT,
    IND_WAIVER,
    CD_SCH_DIST,
    CD_ELEM,
    CD_MIDDLE,
    CD_HIGH,
    DT_FOST_MANUAL,
    DT_FOST_BILL,
    IND_SPECIFIC_CHILD,
    DT_LIC_BEGIN,
    DT_LIC_END,
    TXT_CLOSURE_COMM,
    NDFCS_CERT_ENTITY,
    IND_RSRC_NONDFCS,
    IND_CURR_HM_STDY_EXSTS,
    IND_PREV_FAM_STDY_RQSTD,
    RSRC_OTH_SPC_CERTF,
    CD_RSRC_ADDR_SMILEUPD_ST
  ) VALUES (
    :NEW.ID_RESOURCE_HISTORY,
    :NEW.ID_RESOURCE,
    :NEW.DT_RSHS_EFFECTIVE,
    :NEW.DT_RSHS_CLOSE,
    :NEW.DT_LAST_UPDATE,
    :NEW.ID_CASE,
    :NEW.DT_RSHS_CERT,
    :NEW.DT_RSHS_MARRIAGE,
    :NEW.DT_RSHS_END,
    :NEW.ADDR_RSHS_ST_LN_1,
    :NEW.ADDR_RSHS_ST_LN_2,
    :NEW.ADDR_RSHS_CITY,
    :NEW.CD_RSHS_STATE,
    :NEW.ADDR_RSHS_ZIP,
    :NEW.ADDR_RSHS_ATTN,
    :NEW.CD_RSHS_CNTY,
    :NEW.CD_RSHS_INVOL_CLOSURE,
    :NEW.CD_RSHS_CLOSURE_RSN,
    :NEW.CD_RSHS_TYPE,
    :NEW.CD_RSHS_HUB,
    :NEW.CD_RSHS_CAMPUS_TYPE,
    :NEW.CD_RSHS_SOURCE_INQUIRY,
    :NEW.CD_RSHS_MAINTAINER,
    :NEW.CD_RSHS_SCH_DIST,
    :NEW.CD_RSHS_OWNERSHIP,
    :NEW.CD_RSHS_STATUS,
    :NEW.CD_RSHS_FACIL_TYPE,
    :NEW.CD_RSHS_CERT_BY,
    :NEW.CD_RSHS_OPER_BY,
    :NEW.CD_RSHS_SETTING,
    :NEW.CD_RSHS_PAYMENT,
    :NEW.CD_RSHS_CATEGORY,
    :NEW.CD_RSHS_ETHNICITY,
    :NEW.CD_RSHS_LANGUAGE,
    :NEW.CD_RSHS_MARITAL_STATUS,
    :NEW.CD_RSHS_RECMND_REOPEN,
    :NEW.CD_RSHS_REGION,
    :NEW.CD_RSHS_RELIGION,
    :NEW.CD_RSHS_RESPITE,
    :NEW.CD_RSHS_FA_HOME_STATUS,
    :NEW.CD_RSHS_FA_HOME_TYPE1,
    :NEW.CD_RSHS_FA_HOME_TYPE2,
    :NEW.CD_RSHS_FA_HOME_TYPE3,
    :NEW.CD_RSHS_FA_HOME_TYPE4,
    :NEW.CD_RSHS_FA_HOME_TYPE5,
    :NEW.CD_RSHS_FA_HOME_TYPE6,
    :NEW.CD_RSHS_FA_HOME_TYPE7,
                :NEW.CD_RSHS_MHMR_COMP_CODE,
    :NEW.ID_RSHS_FA_HOME_STAGE,
    :NEW.ID_RSHS_FA_HOME_EVENT,
    :NEW.IND_RSHS_CARE_PROV,
    :NEW.IND_RSHS_INACTIVE,
    :NEW.IND_RSHS_TRANSPORT,
    :NEW.IND_RSHS_EMERG_PLACE,
    :NEW.NM_RSHS_RESOURCE,
    :NEW.NM_RSHS_CONTACT,
    :NEW.NM_RSHS_LAST_UPDATE,
    :NEW.NBR_RSHS_VID,
    :NEW.NBR_RSHS_PHN,
    :NEW.NBR_RSHS_FACIL_CAPACITY,
    :NEW.NBR_RSHS_FACIL_ACCLAIM,
    :NEW.NBR_RSHS_PHONE_EXT,
    :NEW.NBR_RSHS_CAMPUS_NBR,
    :NEW.NBR_RSHS_ANNUAL_INCOME,
    :NEW.NBR_RSHS_FM_AGE_MAX,
    :NEW.NBR_RSHS_FM_AGE_MIN,
    :NEW.NBR_RSHS_MA_AGE_MAX,
    :NEW.NBR_RSHS_MA_AGE_MIN,
    :NEW.NBR_RSHS_INT_CHILDREN,
    :NEW.NBR_RSHS_INT_FE_AGE_MAX,
    :NEW.NBR_RSHS_INT_FE_AGE_MIN,
    :NEW.NBR_RSHS_INT_MA_AGE_MAX,
    :NEW.NBR_RSHS_INT_MA_AGE_MIN,
    :NEW.NBR_RSHS_OPEN_SLOTS,
    :NEW.TXT_RSHS_ADDR_CMNTS,
    :NEW.TXT_RSHS_COMMENTS,
    :NEW.IND_RSHS_WRITE_AUDIT ,
    :NEW.DT_CCL_UPDATE,
    :NEW.CD_RSRC_MHMR_SITE,
    :NEW.IND_RSRC_CONTRACTED,
    :NEW.NM_LEGAL,
    :NEW.NM_RSRC_CONTACT_TITLE,
    :NEW.NBR_RSRC_NTNL_PROVIDER,
    :NEW.ADDR_RSRC_EMAIL,
    :NEW.ADDR_RSRC_WEBSITE,
    :NEW.CD_SCHOOL_TYPE,
    :NEW.CD_PAYMENT_DELIVERY,
    :NEW.TXT_SPEC_CERT,
    :NEW.CD_EXCHANGE_STAT,
    :NEW.IND_WAIVER,
    :NEW.CD_SCH_DIST,
    :NEW.CD_ELEM,
    :NEW.CD_MIDDLE,
    :NEW.CD_HIGH,
    :NEW.DT_FOST_MANUAL,
    :NEW.DT_FOST_BILL,
    :NEW.IND_SPECIFIC_CHILD,
    :NEW.DT_LIC_BEGIN,
    :NEW.DT_LIC_END,
    :NEW.TXT_CLOSURE_COMM,
    :NEW.NDFCS_CERT_ENTITY,
    :NEW.IND_RSRC_NONDFCS,
    :NEW.IND_CURR_HM_STDY_EXSTS,
    :NEW.IND_PREV_FAM_STDY_RQSTD,
    :New.RSRC_OTH_SPC_CERTF,
    :New.CD_RSRC_ADDR_SMILEUPD_ST
  );
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_CONTACT_CBX
BEFORE UPDATE
ON CAPS.CONTACT_CBX
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_CONTACT_CBX
BEFORE INSERT
ON CAPS.CONTACT_CBX
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:NEW.ID_CONTACT_CBX IS NULL OR :new.ID_CONTACT_CBX = 0) THEN
		SELECT	SEQ_CONTACT_CBX.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_CONTACT_CBX := dummy;
	END IF;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_YOUTH_DETAIL
BEFORE UPDATE
ON CAPS.YOUTH_DETAIL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_YOUTH_DETAIL
BEFORE INSERT
ON CAPS.YOUTH_DETAIL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/

drop table CAPS.ADOPTION_S_03152007215709000;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };

-- change STGAP00001708
INSERT INTO CAPS.METAPHOR (ID_TAB,TXT_TAB_URL,TXT_TAB_CONSTANT,TXT_TAB ) 
     VALUES (1505,'/person/YouthDetail/displayYouthDetail','YOUTH_DETAIL','Youth Detail');
     
-- change STGAP00001709     
update caps.message set TXT_MESSAGE ='You must complete  Date Approved on the page before saving.'
where TXT_MESSAGE_NAME ='MSG_ADPT_SUB_DETAIL_INCOMPLETE';

-- change STGAP00001710
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CFAMOUT','FAP','Family Preservation',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CFAMOUT','GUA','Guardianship',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CFAMOUT','REU','Reunification',SYSDATE);

-- change STGAP00001713
INSERT INTO CAPS.CODES_TABLES (code_type, code, DECODE, dt_last_update) VALUES ('CCNTCCBX', 'CTCMPROG', 'TCM Eligible Programs', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (code_type, code, DECODE, dt_last_update) VALUES ('CCNTCCBX', 'CTCMSVCS', 'TCM Medical Services', SYSDATE);

-- change STGAP00001714
UPDATE CAPS.codes_tables set dt_end=sysdate WHERE code_type='CPLMNTYP';
--CATTEMP
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CATTEMP','ATT','Attempted',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CATTEMP','RCT','Actual',sysdate);
--CPLMNTYP
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','PRN','Parent',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','REP','Relative - Paid',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','REU','Relative - Unpaid',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','RFH','Relative Foster Home',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','DFH','DFCS Family Foster Home',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','CFH','CPA Family Foster Home',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','IFH','CCI Family Foster Home',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','ADH','Adoptive Home',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','EMS','Emergency Shelter',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','GRH','Group Home',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','CCI','Child Care Institution',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','SFH','Specialized Foster Home',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','LAF','ILP/Aftercare',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','ICR','ICPC - Relative',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','ICF','ICPC - Foster',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','ICA','ICPC - Adoptive',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','HOS','Hospital',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','RNA','Runaway',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','YDC','YDC/RYDC',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','OTR','Other Resource',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CPLMNTYP','OTP','Other Person',sysdate);
--CTMPLTYP
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CTMPLTYP','EMG','Emergency',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CTMPLTYP','VOL','Voluntary',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CTMPLTYP','COR','Concurrent',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CTMPLTYP','RED','Respite Day',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CTMPLTYP','REN','Respite Night',sysdate);
-- CRSNPLTG
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','NER','Not enough room/beds in foster home (ORS Blue Book, regulations page 1134)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','CMB','Children maybe sexualized and already experimenting with each other',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','OCA','Older children who acted as parents for younger siblings often challenge foster parents and interfere with their siblings adjustment',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','NEH','Not enough homes willing to take large numbers of siblings (four and more)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','TMM','Too much money to subsidize state in financial care of children',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','DFF','Difficulty finding families for large sibling groups',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','CPS','Combined problems of siblings are too severe for one set of parents',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','CMC','Case Managers concerns about placing children in large families',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','CNI','Child needs individual attention',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','OSC','Older sibling is caregiver for younger sibling',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','SCR','Sibling conflict/ rivalry /jealousy',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','OSV','One sibling victimizes another sibling',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','SEF','Siblings enters foster care at different times (and foster home with one sibling won''t/can''t accept placement)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','SNP','Sibling are not placed together because the foster parents do not want to foster such a wide age range (zero - 18)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','FPC','Foster parent prefers a certain gender',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','SNF','Size of the foster parent home does not allow foster parent to take the sibling group',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','RCB','Rules concerning having boys and girls in same bedroom',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','SUN','Size of sibling group makes placement unpractical notwithstanding diligent effort',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','PSA','Past incidents of sibling abuse creating a situation in which they cannot live together w/o intervention and treatment',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','SEN','One sibling has such exceptional needs that can only be met by a specialized placement or facility',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRSNPLTG','XXX','Other',sysdate);
-- CCCFARNU
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CCCFARNU','LOF','Lack of funding',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CCCFARNU','NOA','No opening available',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CCCFARNU','KST','To keep siblings together',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CCCFARNU','RPA','Relative placement available',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CCCFARNU','OTH','Other',sysdate);
-- CRMRSNAT
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','CMC','Cannot meet the childs needs',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','FTC','Full to capacity',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','CHB','Childs behavior',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','PHC','Past history with child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','LOS','Lack of space',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','LOR','Lack of resources',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','CTR','Certification requirements',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','FCI','Foster caregiver issues',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','HUI','Home under investigation',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','HUC','Home under corrective action',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','RTH','Race/Ethnicity',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','REL','Religion',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAT','XXX','Other',sysdate);
-- CRMRSNAC
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','RFU','Reunification',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CPO','Child placed with other relatives',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','LCL','Level of Care lowered',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','LCR','Level of Care raised',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','ATG','Achieved therapeutic goal(s)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CIA','Child placed in adoptive setting',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CWS','Child placed with siblings',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CHP','Child hospitalized',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CDB','Childs behavior',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CTR','Caretaker requested',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CRR','Child ran away',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','RSP','Refused to stay in placement',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CUO','Court ordered',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CEM','Child emancipated',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CTM','Caretaker moved',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','PLC','Placement closed',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','RDU','Removed due to risk of abuse',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','AGU','Aged out',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','FUA','Facility under adverse action',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','CDE','Child death',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','ADI','Adoption disruption',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','TYD','Transfer to other agency/YDC',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','GUD','Guardianship',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','ADF','Adoption finalized',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','RTH','Race/Ethnicity',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','REL','Religion',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CRMRSNAC','OER','Other',sysdate);
-- CAFCARS
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','01','Reunification',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','02','Live w/Other Relative',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','03','Adoption finalized',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','04','Emancipation',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','05','Guardianship',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','06','Transfer to another agency',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','07','Runaway',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CAFCARS','08','Death of Child',sysdate);

-- change STGAP00001716
INSERT INTO CAPS.METAPHOR ( ID_TAB, TXT_TAB_URL, 
  TXT_TAB_CONSTANT, TXT_TAB) 
VALUES(775, '/investigation/DiversionCnclsn/displayDiversionCnclsn',
  'DIVERSION_CONCLUSION_DIV_DVRSONCONCLSION', 'Diversion Conclusion');

-- change STGAP00001719
INSERT INTO CAPS.CODES_TABLES (code_type, code, DECODE, dt_last_update) VALUES ('CTCMSTAT', 'NBL', 'Not Billed', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (code_type, code, DECODE, dt_last_update) VALUES ('CTCMSTAT', 'VOD', 'Void', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (code_type, code, DECODE, dt_last_update) VALUES ('CTCMSTAT', 'REJ', 'Rejected', SYSDATE);

-- change STGAP00001720
update caps.metaphor m set m.TXT_TAB = 'Placement<br>Provider Detail' 
where m.ID_TAB=490 and m.TXT_TAB_CONSTANT='FACILITY_DETAIL_FACILITY';

update caps.metaphor m set m.TXT_TAB = 'Placement Provider Detail' 
where m.ID_TAB=500 and m.TXT_TAB_CONSTANT='FACILITY_DETAIL_3_FACILITY';

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (137, 'SacwisRev2', 'static updates, lots of indexes, schema changes w/ new tables');
                         
commit;

