--STGAP00015802 - Release(3.43) MR-62: Add Task codes for Approve Contact Standard

 --Task code for Approve Contact Standards in Foster Care Family stage
 INSERT INTO caps.task t
 (t.CD_TASK,t.DT_LAST_UPDATE,t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW, t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.CD_TASK_TOP_WINDOW, t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
  t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
  t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
  VALUES
 ('6545',sysdate,'APP','NULL','FSU','CPS',
  'NULL', '0','1','1','0','0',
  '0','0','Approve Contact Standards','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CONTACT_STANDARDS_EVENTLIST',
  '/contacts/ContactStandards/displayContactStandards',0,'0','0','0');

 --Task code for Approve Contact Standards in Ongoing stage
  INSERT INTO caps.task t
 (t.CD_TASK,t.DT_LAST_UPDATE,t.CD_TASK_EVENT_TYPE, t.CD_TASK_LIST_WINDOW, t.CD_TASK_STAGE, t.CD_TASK_STAGE_PROGRAM,
 t.CD_TASK_TOP_WINDOW, t.IND_TASK_EVENT_CREATE, t.IND_TASK_EVENT_NAVIG, t.IND_TASK_MULTIPLE_INSTANCE, t.IND_TASK_NEW_USING, t.IND_TASK_NU_ACROSS_CASE,
  t.IND_TASK_RTRV_PRIOR_STAGE, t.IND_TASK_SHOW_IN_LIST, t.TXT_TASK_DECODE, t.TXT_1ST_TAB, t.TXT_2ND_TAB, t.TXT_3RD_TAB,
  t.TXT_EVENT_DETAIL_URL, t.IND_TASK_CODE_PREFER, t.IND_TASK_NEW_CASE_TODO_ENABLE, t.IND_TASK_FORCE_EVENT_LINK, t.IND_STAGE_CLOSURE)
  VALUES
 ('7026',sysdate,'APP','NULL','FPR','CPS',
  'NULL', '0','1','1','0','0',
  '0','0','Approve Contact Standards','CASE_CASESEARCH','CONTACTS_SUMMARIES_CONTACTSEARCH','CONTACT_STANDARDS_EVENTLIST',
 '/contacts/ContactStandards/displayContactStandards',0,'0','0','0');


 UPDATE CAPS.TASK SET IND_TASK_NEW_USING = '1' WHERE CD_TASK IN ('6540', '7025');


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (754, 'SacwisRev3', 'Release 3.43 - DBCR 15802');

commit;

