
drop sequence caps.seq_message;

CREATE SEQUENCE CAPS.SEQ_MESSAGE
    START WITH 21000
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

--change 143 R1/R2
UPDATE CAPS.CODES_TABLES 
SET DT_END = NULL 
WHERE CODE_TYPE = 'CSRCRPTR' 
AND 
CODE IN ('UH', 'XX', 'AB', 'AG', 'AT', 'BY', 'CR', 'DA', 'DR', 'EM', 'FI', 'FV', 'GC', 'GU', 'IN', 'MF', 'MH','NN', 
          'OS', 'PA', 'PP', 'PR', 'PY', 'SA', 'SO', 'SP', 'TP', 'CA', 'SF', 'JG', 'SG', 'AA', 'AF'); 
          
--change 144 R1/R2
DELETE CAPS.CODES_TABLES WHERE CODE_TYPE = 'CSRCRPTR' AND code IN ('SV', 'DS');

--change 145 R2 ONLY
insert into caps.codes_tables 
(code_type, code, decode) 
values 
( 'CFAROLE ','CONT', 'Contracted'); 

insert into caps.codes_tables 
(code_type, code, decode) 
values 
('CFAROLE','DFST','DFCS Foster Parent'); 

insert into caps.codes_tables 
(code_type, code, decode) 
values 
('CFAROLE','DSTF','DFCS Staff');

--change 146 R1/R2
UPDATE CAPS.CODES_TABLES 
SET DT_END = '1/1/2006' 
WHERE CODE_TYPE = 'CSRCRPTR' 
AND 
CODE IN ('HC', 'ONM', 'TAN', 'RLS', 'PO', 'AM', 'CP', 'CW','DH','DN','NC','PH','UK','BF','BM','LW');

--change 147 R1/R2
INSERT INTO CAPS.CODES_TABLES VALUES('CSRCRPTR', 'PPO', 'Parole/Probtn Ofcr', NULL, SYSDATE);

--change 148 R1/R2
UPDATE CAPS.CODES_TABLES 
SET DECODE = 'Atty/Gua Ad Litem' 
WHERE code = 'GX' AND CODE_TYPE = 'CSRCRPTR'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE = 'DHR Staff' 
WHERE code = 'SF' AND CODE_TYPE = 'CSRCRPTR';

-- change 149 R2 ONLY
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CSECATTR', 'EM', 'Protective Service Alert', SYSDATE);

update caps.codes_tables 
set decode = 'Records Check' 
where code_type = 'CSECATTR' 
and code = 'BD';

-- change 150 R1/R2
UPDATE CAPS.CODES_TABLES 
SET code = 'PAP' 
WHERE DECODE = 'Precond. Adop. Par' AND CODE_TYPE = 'CRELVICT';

UPDATE CAPS.CODES_TABLES 
SET DECODE = 'Paramour' 
WHERE CODE = 'PP' AND CODE_TYPE = 'CRELVICT';

UPDATE CAPS.CODES_TABLES 
SET dt_end = NULL 
WHERE CODE = 'PP' AND CODE_TYPE = 'CRELVICT';

UPDATE CAPS.CODES_TABLES 
SET code = 'PPO' 
WHERE DECODE = 'Parole/Probtn Ofcr.' AND CODE_TYPE = 'CRELVICT';

UPDATE CAPS.CODES_TABLES 
SET dt_end = '1/1/2006' 
WHERE CODE_TYPE = 'CRELVICT' AND CODE IN ('VL', 'FC', 'PF','LF','BF','LC','BM');

-- change 151 R2 ONLY
-- STATUS
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'AINQ', 'Inquiry');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'BAPP', 'Applicant (Pre-Service Training)');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'CPFA', 'Pending Full Approval');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'DPSA', 'Pending Special Approval');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'EPTA', 'Pending Temporary Approval');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'FAFA', 'Approved (Full) - Active');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'GASA', 'Approved (Special) - Active');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'HATA', 'Approved (Temp) - Active');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'IPCL', 'Pending Closure');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'JCSD', 'Closed');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CFAHMSTA', 'KWTL', 'Waitlist');
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '010' AND DECODE='Inquiry';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '020' AND DECODE='Recruit';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '030' AND DECODE='Applicant';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '040' AND DECODE='Approved - Active';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '050' AND DECODE='Approved - Inactive';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '060' AND DECODE='Pending Approval';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '070' AND DECODE='Closed';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '080' AND DECODE='Pending Closure';
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE= 'CFAHMSTA' AND CODE= '090' AND DECODE='Closed - Duplicate';
-- REGIONS
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CREGIONS', '13', 'Region 13');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CREGIONS', '14', 'Region 14');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CREGIONS', '15', 'Region 15');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CREGIONS', '16', 'Region 16');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CREGIONS', '17', 'Region 17');
INSERT INTO CAPS.CODES_TABLES ( CODE_TYPE, CODE, DECODE ) VALUES( 'CREGIONS', 'TOS', 'Out Of State');
UPDATE CAPS.CODES_TABLES  SET DT_END= NULL WHERE CODE_TYPE= 'CREGIONS' AND CODE= '98' AND DECODE= 'Statewide' ;
-- CATEGORY
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'CCI', 'Child Caring Institution');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'CPA', 'Child Placing Agency');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'CON', 'Home Conversion');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'RNP', 'Relative (No Payment)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'RAD', 'Relative Adopt');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'RCS', 'Relative Care Subsidy');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'RER', 'Relative Enhanced Relative Rate');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'RFO', 'Relative Foster');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'RTF', 'Relative TANF');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CFACATEG', 'SGP', 'Subsidized Guardianship');

UPDATE CAPS.CODES_TABLES SET DECODE= 'Adoptive' WHERE CODE_TYPE= 'CFACATEG' AND CODE= 'A';
UPDATE CAPS.CODES_TABLES SET DECODE= 'Foster' WHERE CODE_TYPE= 'CFACATEG' AND CODE= 'F';
UPDATE CAPS.CODES_TABLES SET DECODE= 'Foster/Adopt (Legal Risk)' WHERE CODE_TYPE= 'CFACATEG' AND CODE= 'L';
UPDATE CAPS.CODES_TABLES SET DECODE= 'ICPC' WHERE CODE_TYPE= 'CFACATEG' AND CODE= 'I';

UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE='CFACATEG' AND CODE='K'; 
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE WHERE CODE_TYPE='CFACATEG' AND CODE='G'; 

--HOMETYPE
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CDFAHTP1', 'BAS', 'Basic');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CDFAHTP2', 'EMG', 'Emergency');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CDFAHTP3', 'MED', 'Medically Fragile');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CDFAHTP4', 'RES', 'Respite');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CDFAHTP5', 'SFC', 'Specialized Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CDFAHTP6', 'THR', 'Therapeutic');
--SCHOOL DISTRICT
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'APC', 'Appling County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'ATC', 'Atkinson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'APS', 'Atlanta Public Schools');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BAC', 'Bacon County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BAK', 'Baker County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BAL', 'Baldwin County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BAN', 'Banks County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BAR', 'Barrow County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BAT', 'Bartow County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BEN', 'Ben Hill County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BER', 'Berrien County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BIB', 'Bibb County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BLE', 'Bleckley County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BRA', 'Brantley County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BRE', 'Bremen City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BRP', 'Brooks County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BRY', 'Bryan County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BUF', 'Buford City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BUL', 'Bulloch County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BUR', 'Burke County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'BUT', 'Butts County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAH', 'Calhoun City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAL', 'Calhoun County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAM', 'Camden County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAN', 'Candler County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAO', 'Carroll County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAR', 'Carrollton City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAS', 'Cartersville City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CAT', 'Catoosa County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CCA', 'Ccat');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CHA', 'Charlton County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CHH', 'Chatham-Savannah County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CHO', 'Chattahoochee County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CHT', 'Chattooga County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CHE', 'Cherokee County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CHI', 'Chickamauga City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CLA', 'Clarke County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CLY', 'Clay County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CLT', 'Clayton County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CLI', 'Clinch County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'COB', 'Cobb County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'COF', 'Coffee County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'COI', 'Colquitt County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'COL', 'Columbia County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'COM', 'Commerce City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'COO', 'Cook County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'COW', 'Coweta County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CRA', 'Crawford County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'CRI', 'Crisp County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DAD', 'Dade County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DAL', 'Dalton City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DAW', 'Dawson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DEA', 'Decatur City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DEC', 'Decatur County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DEK', 'Dekalb County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DOD', 'Dodge County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DOO', 'Dooly County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DOT', 'Dougherty County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DOU', 'Douglas County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'DUB', 'Dublin City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'EAR', 'Early County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'ECH', 'Echols County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'EFF', 'Effingham County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'ELB', 'Elbert County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'EMA', 'Emanuel County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'EVA', 'Evans County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'FAN', 'Fannin County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'FAY', 'Fayette County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'FLO', 'Floyd County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'FOR', 'Forsyth County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'FRA', 'Franklin County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'FUL', 'Fulton County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GAI', 'Gainesville City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GIL', 'Gilmer County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GLA', 'Glascock County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GLY', 'Glynn County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GOR', 'Gordon County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GRA', 'Grady County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GRE', 'Greene County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'GWI', 'Gwinnett County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HAB', 'Habersham County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HAL', 'Hall County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HAN', 'Hancock County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HAR', 'Haralson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HAS', 'Harris County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HAT', 'Hart County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HEA', 'Heard County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HEN', 'Henry County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'HOU', 'Houston County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'IRW', 'Irwin County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JAC', 'Jackson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JAS', 'Jasper County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JED', 'Jeff Davis County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JEF', 'Jefferson City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JEN', 'Jefferson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JES', 'Jenkins County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JOH', 'Johnson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'JON', 'Jones County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LAM', 'Lamar County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LAN', 'Lanier County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LAU', 'Laurens County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LEE', 'Lee County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LIB', 'Liberty County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LIN', 'Lincoln County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LON', 'Long County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LOW', 'Lowndes County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'LUM', 'Lumpkin County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MAC', 'Macon County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MAD', 'Madison County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MAI', 'Marietta City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MAR', 'Marion County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MCD', 'McDuffie County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MCI', 'McIntosh County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MER', 'Meriwether County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MIL', 'Miller County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MIT', 'Mitchell County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MOE', 'Monroe County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MOG', 'Montgomery County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MOR', 'Morgan County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MUR', 'Murray County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'MUS', 'Muscogee County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'NEW', 'Newton County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'OCO', 'Oconee County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'OGL', 'Oglethorpe County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PAU', 'Paulding County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PEA', 'Peach County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PEL', 'Pelham City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PIC', 'Pickens County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PIE', 'Pierce County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PIK', 'Pike County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'POL', 'Polk County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PUL', 'Pulaski County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'PUT', 'Putnam County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'QUI', 'Quitman County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'RAB', 'Rabun County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'RAN', 'Randolph County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'RIC', 'Richmond County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'ROC', 'Rockdale County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'ROM', 'Rome City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'SCH', 'Schley County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'SCR', 'Screven County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'SEM', 'Seminole County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'SOC', 'Social Circle City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'SPA', 'Spalding County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'STA', 'State Schools');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'STE', 'Stephens County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'STW', 'Stewart County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'SUM', 'Sumter County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TAB', 'Talbot County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TAL', 'Taliaferro County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TAT', 'Tattnall County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TAY', 'Taylor County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TEL', 'Telfair County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TER', 'Terrell County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'THO', 'Thomas County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'THU', 'Thomaston-Upson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'THS', 'Thomasville City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TIF', 'Tift County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TOO', 'Toombs County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TOW', 'Towns County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TRE', 'Treutlen County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TRI', 'Trion City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TRO', 'Troup County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TUR', 'Turner County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'TWI', 'Twiggs County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'UNI', 'Union County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'VAL', 'Valdosta City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'VID', 'Vidalia City');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WAK', 'Walker County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WAL', 'Walton County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WAE', 'Ware County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WAR', 'Warren County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WAS', 'Washington County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WAY', 'Wayne County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WEB', 'Webster County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WHE', 'Wheeler County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WHI', 'White County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WHT', 'Whitfield County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WIC', 'Wilcox County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WIK', 'Wilkes County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WIL', 'Wilkinson County');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES( 'CSCHDSTR', 'WOR', 'Worth County');

-- change 152 R2 Only
update CAPS.MESSAGE set TXT_MESSAGE = 'Prepared Date must be filled to submit for approval.' where NBR_MESSAGE = 5062 and TXT_MESSAGE_NAME = 'MSG_SVC_CMPLTD_NOT_FLLD';

insert into CAPS.MESSAGE(NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) values (60058, 'MSG_SVC_FAM_REV_NOT_FLLD', 'Date Reviewed with Family must be filled to submit for approval.', 500, 700, 'N'); 

insert into CAPS.MESSAGE(NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, 
IND_BATCH) values (60059, 'MSG_RISK_AS_REQ', 'A Risk Reassessment must be completed and approved before the Family Plan can be Saved and Submitted.', 500, 700, 'N');


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (105, 'SacwisRev2', 'static updates');
                         
commit;
