-- Change STGAP00006338
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRELCODE','51824c','51824c - Crisis Intervention Prevent Disruption - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRELCODE','51847c','51847c - Crisis Intervention Behavior Management - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRELCODE','51856b','51856b - Transportation - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRELCODE','51895b','51895b - In-Home Intensive Treatment - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRELCODE','52156a','52156a - Transportation',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRELCODE','55179d','55179d - Travel Reimbursement',SYSDATE);

-- Change STGAP00006340
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CMILEAGE','51824c','51824c - Crisis Intervention Prevent Disruption - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CMILEAGE','51847c','51847c - Crisis Intervention Behavior Management - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CMILEAGE','51856b','51856b - Transportation - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CMILEAGE','51895b','51895b - In-Home Intensive Treatment - Mileage',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CMILEAGE','52156a','52156a - Transportation',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CMILEAGE','55179d','55179d - Travel Reimbursement',SYSDATE);

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (258, 'SacwisRev2', 'static table updates');                        
commit;