--STGAP00016166 - Release(4.3) Adding new fields for the Safety Resource Assessme

ALTER TABLE CAPS.SAFETY_RESOURCE ADD TXT_COMMENTS VARCHAR2(300)     NULL
;


COMMENT ON COLUMN CAPS.SAFETY_RESOURCE.TXT_COMMENTS IS
'Denial reasons comments'
;

ALTER TABLE CAPS.SAFETY_RESOURCE ADD IND_RECOMMENDATION VARCHAR2(1)     NULL
;

COMMENT ON COLUMN CAPS.SAFETY_RESOURCE.IND_RECOMMENDATION IS
'Safety Resource Recommendation Radio buttons'
;

ALTER TABLE CAPS.SAFETY_RESOURCE ADD CD_DENIAL_REASON VARCHAR2(3)     NULL
;

COMMENT ON COLUMN CAPS.SAFETY_RESOURCE.CD_DENIAL_REASON IS
'Denial Reason Dropdown'
;

--BACKOUT
--ALTER TABLE CAPS.SAFETY_RESOURCE DROP COLUMN TXT_COMMENTS;
--ALTER TABLE CAPS.SAFETY_RESOURCE DROP COLUMN IND_RECOMMENDATION;
--ALTER TABLE CAPS.SAFETY_RESOURCE DROP COLUMN CD_DENIAL_REASON;


INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CSRPLDEN', 'RCH', 'Records Check History', SYSDATE);


INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CSRPLDEN', 'CHI', 'Criminal History', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CSRPLDEN', 'HNC', 'Home is Not Compliant', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CSRPLDEN', 'RWR', 'Resource Withdrew Request', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CSRPLDEN', 'HDM', 'Home Does Not Meet Needs of Children', SYSDATE);

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (1032, 'SacwisRev4', 'Release 4.3 - DBCR 16166');

commit;



