-- DBCR STGAP00009361 - Financial Code Updates for Releaes 2.5

-- End date ICSP 600 series codes entered in error

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE WHERE CODE_TYPE = 'CSVCCODE' 
AND SUBSTR(CODE,1,5) IN ('60501','60601','60701','60801','61201','61501')
AND SUBSTR(CODE,6,1) IN ('k','l');

-- Correct additional contract decodes for CPA's

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-Base WO', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601')
AND SUBSTR(CODE,6,1) = 'b';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-Max WO', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601')
AND SUBSTR(CODE,6,1) = 'c';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-SBWO', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601')
AND SUBSTR(CODE,6,1) = 'd';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-SMWO', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601')
AND SUBSTR(CODE,6,1) = 'e';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-SMFWO', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601')
AND SUBSTR(CODE,6,1) = 'f';

--Update service decodes for wraparound to ICSP

UPDATE CAPS.CODES_TABLES SET DECODE = '597W1 - ICSP1', DT_LAST_UPDATE = SYSDATE WHERE CODE_TYPE = 'CSVCCODE' AND CODE = '597W1';
UPDATE CAPS.CODES_TABLES SET DECODE = '597W2 - ICSP2', DT_LAST_UPDATE = SYSDATE WHERE CODE_TYPE = 'CSVCCODE' AND CODE = '597W2';
UPDATE CAPS.CODES_TABLES SET DECODE = '598W1 - ICSP1', DT_LAST_UPDATE = SYSDATE WHERE CODE_TYPE = 'CSVCCODE' AND CODE = '598W1';
UPDATE CAPS.CODES_TABLES SET DECODE = '598W2 - ICSP2', DT_LAST_UPDATE = SYSDATE WHERE CODE_TYPE = 'CSVCCODE' AND CODE = '598W2';

UPDATE CAPS.CODES_TABLES SET DECODE = '597 - ICSP Parental Custody' WHERE
CODE = '597' AND CODE_TYPE = 'CPRGCODE';

UPDATE CAPS.CODES_TABLES SET DECODE = '597 - ICSP Parental Custody' WHERE
CODE = '597' AND CODE_TYPE = 'CPRGAREA';

UPDATE CAPS.CODES_TABLES SET DECODE = '597 - ICSP Parental Custody' WHERE
CODE = '597' AND CODE_TYPE = 'CPROGCDE';

UPDATE CAPS.CODES_TABLES SET DECODE = '597 - ICSP Parental Custody' WHERE
CODE = '597' AND CODE_TYPE = 'CPRGCOD1';

UPDATE CAPS.CODES_TABLES SET DECODE = '598 - ICSP DFCS Custody' WHERE
CODE = '598' AND CODE_TYPE = 'CPRGCODE';

UPDATE CAPS.CODES_TABLES SET DECODE = '598 - ICSP DFCS Custody' WHERE
CODE = '598' AND CODE_TYPE = 'CPRGAREA';

UPDATE CAPS.CODES_TABLES SET DECODE = '598 - ICSP DFCS Custody' WHERE
CODE = '598' AND CODE_TYPE = 'CPROGCDE';

UPDATE CAPS.CODES_TABLES SET DECODE = '598 - ICSP DFCS Custody' WHERE
CODE = '598' AND CODE_TYPE = 'CPRGCOD1';

--Insert rows into CLSRU lookup table to match new legal statuses

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CLSRU','NCS','X',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CLSRU','NDJ','X',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CLSRU','DJA','X',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CLSRU','JCP','X',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CLSRU','JCT','X',SYSDATE);

--Address travel reimbursement for Homestead, Parent Aide and new 518 Mileage Code

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CMILEAGE','57161e','57161e - Travel Reimbursement',SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CMILEAGE','57372e','57372e - Travel Reimbursement',SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CMILEAGE','51871p','51871p - Mileage',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CRELCODE','57161e','57161e - Travel Reimbursement',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CRELCODE','57372e','57372e - Travel Reimbursement',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CRELCODE','51871p','51871p - Mileage',SYSDATE);

--New services insert for Codes Tables

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CSVCCODE','51871p','51871p - Mileage',SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CSVCCODE','52148g','52148g - Furniture',SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CSVCCODE','57372i','57372i - Purposeful Home Visit',SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CFLSVLNK','57372i','573',SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CFLSVLNK','51871p','518',SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES
('CFLSVLNK','52148g','521',SYSDATE);

-- EQUIVALENCY Insert for new service codes

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, 
CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, 
NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES 
(0,'48','52148g','521','ALL','ALL','52148g',TO_DATE('07/01/2008','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, 
CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, 
NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES 
(0,'71','51871p','518','ALL','ALL','51871p',TO_DATE('07/01/2008','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV, CD_EQUIV_FUNDING_STREAM, CD_EQUIV_OBJ_ALW, CD_EQUIV_PAC, 
CD_EQUIV_STAGE, CD_EQUIV_STAGE_TYPE, CD_EQUIV_SVC_DTL_SERVICE, DT_EQUIV_START_DATE, DT_EQUIV_END_DATE, 
NBR_EQUIV_OBJ_ALW, NBR_EQUIV_OBJ_CERT, NBR_EQUIV_OBJ_PURE) VALUES 
(0,'72','57372i','573','ALL','ALL','57372i',TO_DATE('07/01/2008','MM/DD/YYYY'),TO_DATE('12/31/4712','MM/DD/YYYY'), 1,0,0);

-- Un end date records in CPRGCOD1 to display on Service Authorization

UPDATE CAPS.CODES_TABLES SET DT_END = NULL, DT_LAST_UPDATE = SYSDATE WHERE
CODE_TYPE = 'CPRGCOD1' AND CODE IN ('504','576','531');


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (349, 'SacwisRev2', 'DBCR 9361');
commit;