--STGAP00013552 - INVOICE_OUTBOUND - Add NBR_INV_PROVIDER

--Note:  no impact to ado conversion

--See attached database change request form.  Per MR-39 STGAP00013482 a provider invoice id 
--is required for the SHINES to SMILES invoice interface.  This request is to add this field 
--to the INVOICE_OUTBOUND table.

alter table sacwisifc.invoice_outbound add (NBR_INV_PROVIDER varchar2(12));
comment on column sacwisifc.invoice_outbound.NBR_INV_PROVIDER is 'Provider Invoice ID';


--STGAP00013556 - STGAP00012833 DBCRs

--Note:  no impact to ado conversion


UPDATE CAPS.CODES_TABLES SET DECODE = 'Survey for Investigation' 
WHERE CODE = 'INV' AND CODE_TYPE = 'CSURSTG';

UPDATE CAPS.CODES_TABLES SET DECODE = 'Survey for Intake' 
WHERE CODE = 'INT' AND CODE_TYPE = 'CSURSTG';

INSERT into CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE ,DT_LAST_UPDATE) 
VALUES ('CSECATTR', 'PL', 'Case Review',SYSDATE);

-- Refresh Survey table starts here

DELETE FROM CAPS.CASE_REVIEW_SURVEY;

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q01');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q01');


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q02');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q02');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INT', 'Q02');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q02');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q03');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q03');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INT', 'Q03');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q03');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q04');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q04');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INT', 'Q04');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q04');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q05');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q05');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INT', 'Q05');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q05');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q06');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q06');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INT', 'Q06');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q06');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q07');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q07');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INT', 'Q07');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q07');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q08');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q08');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INT', 'Q08');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q08');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q09');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q09');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q10');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q10');  

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q11');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q11');   

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q12');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q12');   

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q13');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q13');    


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q14');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q14');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q14');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q14');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q15');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q15');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q15');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q15');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q15');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q16');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q16');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q16');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q16');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q16');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q17');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q17');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q17');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q17');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q17');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q18');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q18');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q18');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q18');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q18');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q19');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q19');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q19');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q19');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q19');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q20');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q20');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q20');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q20');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q21');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q21');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q21');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q21');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q21');	


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q22');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q22');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q22');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q22');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q22');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q23');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q23');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q23');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q23');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q23');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q24');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q24');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q24');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q24');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q24');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q25');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q25');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q25');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q25');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q25');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q26');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q26');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q26');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q26');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q26');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q27');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q27');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q27');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q27');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q27');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q28');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q28');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q28');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q28');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q28');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q29');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q29');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q29');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q29');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q29');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q30');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q30');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q30');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q30');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q30');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q31');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q31');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q31');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q31');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q31');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q32');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q32');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q32');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q32');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q32');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q33');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q33');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q33');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q33');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q33');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q34');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q34');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q34');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q34');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q34');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q35');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q35');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q35');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q35');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q35');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q36');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q36');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q36');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q36');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q36');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q37');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q37');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q37');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q37');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q37');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q38');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q38');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q38');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q38');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q38');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q39');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q39');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q39');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q39');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q39');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q40');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q40');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q40');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q40');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'DIV', 'Q40');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q41');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q41');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q42');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q42');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q43');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q43');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q44');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q44');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q45');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q45');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q46');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q46');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q47');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q47');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q48');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q48');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q49');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q49');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q50');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q50');		

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q51');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q51');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q52');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q52');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q53');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q53');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q54');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q54');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q55');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q55');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q56');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q56');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q57');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q57');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q58');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q58');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q59');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q59');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q60');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q60');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q61');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q61');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q62');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q62');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q63');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q63');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q64');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q64');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q65');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q65');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q66');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q66');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q67');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q67');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q68');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q68');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q69');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q69');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q70');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q70');		

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q71');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q71');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q72');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q72');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q73');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q73');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q74');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q74');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q75');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q75');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q76');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q76');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q77');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q77');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q78');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q78');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q79');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q79');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q80');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q80');		

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q81');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q81');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q82');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q82');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q83');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q83');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q84');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q84');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q85');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q85');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q86');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q86');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q87');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q87');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q88');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q88');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q89');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q89');			


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q90');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q90');		

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q91');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q91');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q92');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q92');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q93');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q93');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q94');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q94');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q95');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q95');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q96');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q96');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q97');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q97');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q98');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q98');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q99');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q99');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q100');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q100');		

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q101');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q101');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q102');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q102');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q103');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q103');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q104');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q104');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q105');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q105');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q106');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q106');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q107');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q107');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q108');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q108');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q109');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q109');


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q110');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q110');		

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q111');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q111');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q112');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q112');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q113');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q113');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q114');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q114');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q115');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q115');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q116');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q116');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q116');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q117');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q117');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q117');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q118');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q118');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q119');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q119');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q120');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q120');		

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q121');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q121');	

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q122');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q122');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q123');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q123');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q124');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q124');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q124');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q125');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q125');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q125');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q126');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q126');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q126');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q127');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q127');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q127');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q128');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q128');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q128');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q129');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q129');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q129');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q130');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q130');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q130');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q131');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q131');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q131');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q132');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q132');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q132');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q133');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q133');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q133');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q134');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q134');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q134');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q135');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q135');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q135');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q136');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q136');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q136');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q137');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q137');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q137');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q138');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q138');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q138');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q139');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q139');


INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q140');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q140');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q140');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q141');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q141');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q141');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q142');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q142');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q142');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q143');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q143');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q143');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q144');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q144');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q144');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q145');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q145');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q145');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q146');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q146');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q146');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q147');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q147');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q147');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q148');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q148');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q148');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q149');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q149');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q149');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q150');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q150');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q150');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q151');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q151');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q151');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q152');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q152');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q152');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q153');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q153');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q153');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q154');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q154');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q154');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q154');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q155');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q155');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q155');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q156');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q156');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q156');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q157');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q157');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q157');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q158');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q158');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q158');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q159');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q159');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q159');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q160');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q160');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q160');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q160');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q161');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q161');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q161');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q162');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q162');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q162');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q162');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q163');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q163');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q163');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q164');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q164');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q164');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q165');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q165');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q165');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q166');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q166');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q166');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'INV', 'Q167');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q167');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q167');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q167');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q168');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q168');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q168');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q169');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q169');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q169');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q170');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q170');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q170');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'FPR', 'Q171');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'SUB', 'Q171');

INSERT INTO CAPS.CASE_REVIEW_SURVEY (ID_CASE_REVIEW_SURVEY, DT_LAST_UPDATE, CD_SURVEY_TYPE, CD_SURVEY_CODE ,CD_QUESTION) 
VALUES (0, SYSDATE,'CSURSTG', 'ADO', 'Q171');


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (463, 'SacwisRev3', 'Release 3.1 - DBCRs 13552,13556');

commit;


