
-- Standard Alter Table SQL

ALTER TABLE CAPS.EXT_DOCUMENTATION ADD IND_EXT_DOC_SIGNED VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.EXT_DOCUMENTATION ADD DT_EXT_DOC_UPLOADED DATE     NULL
;
ALTER TABLE CAPS.EXT_DOCUMENTATION ADD TXT_EXT_DOC BLOB     NULL
LOB(TXT_EXT_DOC) STORE AS 
(
    TABLESPACE DATA01
    ENABLE STORAGE IN ROW
    NOCACHE
    )
;
ALTER TABLE CAPS.EXT_DOCUMENTATION ADD TXT_FILE_NAME VARCHAR2(300)     NULL
;
ALTER TABLE CAPS.EXT_DOCUMENTATION ADD TXT_FORMAT_TYPE VARCHAR2(80)     NULL
;
ALTER TABLE CAPS.FAMILY_PLAN_TASK ADD TXT_PROGRESS VARCHAR2(500)     NULL
;
ALTER TABLE CAPS.INCOMING_DETAIL ADD CD_SPCL_CIRCUMSTANCES VARCHAR2(3)     NULL
;
ALTER TABLE CAPS.INCOMING_DETAIL ADD ID_REFERRED_RESOURCE NUMBER(16)     NULL
;
ALTER TABLE CAPS.PERSON_DTL ADD IND_LEGAL_CUSTODY VARCHAR2(1)     NULL
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.INCOMING_DETAIL ADD CONSTRAINT FK_INC_DET_REF_RSC
FOREIGN KEY (ID_REFERRED_RESOURCE)
REFERENCES CAPS.CAPS_RESOURCE (ID_RESOURCE)
ENABLE
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };


--215 R1 and R2
update caps.codes_tables 
set decode = 'Historical (> 6 months)' 
where code = 'HIS' 
and code_type = 'CSCNOTRN';

--216 R1 and R2
update caps.codes_tables 
set code = 'NM' 
where code = 'ONM' 
and code_type = 'CSRCRPTR'; 

update caps.codes_tables 
set code = 'TN' 
where code = 'TAN' 
and code_type = 'CSRCRPTR'; 

update caps.codes_tables 
set code = 'RL' 
where code = 'RLS' 
and code_type = 'CSRCRPTR'; 

update caps.codes_tables 
set code = 'PB' 
where code = 'PPO' 
and code_type = 'CSRCRPTR'; 

update caps.codes_tables 
set code = 'PT' 
where code = 'PAP' 
and code_type = 'CRPTRINT';

--217 R1 and R2
update caps.codes_tables
set code = 'PT'
where code = 'PAP'
and code_type = 'CRELVICT';

update caps.codes_tables
set code = 'PB'
where code = 'PPO'
and code_type = 'CRELVICT';

-- change 224 R2/R1

UPDATE CAPS.CODES_TABLES SET DT_END = to_date('01/01/2006','MM/DD/YYYY') 
WHERE CODE = 'AOC' AND CODE_TYPE = 'CSTAGES'; 

UPDATE CAPS.CODES_TABLES SET DT_END = to_date('01/01/2006','MM/DD/YYYY') 
WHERE CODE = 'SUB' AND CODE_TYPE = 'CSTAGES'; 

UPDATE CAPS.CODES_TABLES SET DT_END = to_date('01/01/2006','MM/DD/YYYY') 
WHERE CODE = 'SVC' AND CODE_TYPE = 'CSTAGES'; 

-- change 210 R2 Only
INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME, 
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) 
VALUES(SYSDATE,60064,'MSG_UNIT_REQUIRED','The Unit field is required when no person ID is Entered', 
700,500,'N'); 

INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME, 
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) 
VALUES(SYSDATE,60065,'MSG_VIEW_UNIT','You can only view your unit', 
700,500,'N'); 

INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME, 
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) 
VALUES(SYSDATE,60066,'MSG_CONDITIONALLY_REQUIRED','At least one conditionally required must be filled out', 
700,500,'N');

-- change 211 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCLRSN','LRE','Reunification efforts continue', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCLRSN','LPC','Plan for permanent custody to relative', SYSDATE); 

-- change 212 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PEL','Exceed licensed capacity',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P2C','More than 2 children under age of 2',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P6C','More than 6 children under age of 16',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PNB','Non bedroom sleeping space',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PDC','Foster parent is an in-home day care provider',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','POT','Other',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PLO','More than 2 children receiving LOC',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PUR','Unreadable fingerprints',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PIM','IMPACT Training',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PPA','Pending approval for over a year',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PCS','Child sleeping in caregiver''s bedroom over the age of 1',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P3C','More than 3 children per bedroom',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P5C','Child over age 5 and different sex',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PUP','Unrelated person residing in home',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','PSP','Swimming pool',SYSDATE);

-- change 213 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWJTF','PMS','Maintain Sibling Group',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWJTF','PNA','N/A',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWJTF','PRF','Relative Foster Home',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWJTF','PUL','Unable to locate other placement',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWJTF','PPP','Previous placement',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWJTF','PSN','Special needs of child',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWJTF','PEP','Emergency placement',SYSDATE); 

-- change 218 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCJTF','IMS','Maintain sibling group',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCJTF','INA','N/A',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCJTF','IUP','Unable to locate other placement',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCJTF','IPP','Previous placement',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCJTF','ISN','Special needs of child',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCJTF','IEP','Emergency placement',SYSDATE);

-- change 219 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCRSN','IC6','Child in institutional placement under the age of 6',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCRSN','I12','Child in institutional placement under the age of 12',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWLCRSN','IFI','Financial',SYSDATE);

-- change 223 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','79','79 - Prevention Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','80','80 - Summer Enrichment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','85','85 - Intensive Family Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','86','86 - Preventive Family Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','88','88 - Court Appearances',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','94','94 - Day Respite Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','95','95 - In-Home Intensive Treatment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','99','99 - Written Waiver Item',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','A3','A3 - Assesment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','NA','NA - Non Applicable',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','W1','W1 - Level1',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','W2','W2 - Level2',SYSDATE);

-- change 225 R2 ONLY
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','HS','High School Diploma/GED'); 
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','VC','Vocational Certificate');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','VL','Vocational License');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','AD','Associate’s Degree');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','BD','Bachelor’s Degree');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','HD','Higher Degree');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','NA','None of the above');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CHIGHEDU','DC','Declined');

-- change 227 R2 ONLY
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','01','10'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','02','10');

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','03','10');

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','04','6'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','05','6');

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','06','6');

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','07','4'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','08','4'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','09','2'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','10','2'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','11','0'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','12','0'); 

INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE, CODE, DECODE) VALUES 
('CFAYRTRN','NA','10');

-- change 228 R2 ONLY
UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE WHERE CODE_TYPE = 'CSVCCODE';

-- change 229 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','001','001 - Other Costs',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','041','041 - Initial Clothing',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','051','051 - Annual Clothing',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','061','061 - Support Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','081','081 - In-Hospital Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','101','101 - Unusual Medical',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','102','102 - Burial',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','111','111 - Child Restraint Device',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','121','121 - Other Reimbursable Costs',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','171','171 - Supplemental Supervision',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','191','191 - Medical Exams (CCFA/Child)',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','201','201 - Medical Exams - Adult',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','241','241 - Crisis Intervention Prevent Disruption',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','291','291 - Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','292','292 - Health Check Screen',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','293','293 - Psychological Evaluation',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','294','294 - Match Profile Instrument',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','295','295 - Education',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','296','296 - Family Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','297','297 - Other Family/Relative Evaluation/Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','298','298 - Adolescent Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','299','299 - Partial Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','29A','29A - Relative Care Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','29B','29B - Late CCFA Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','471','471 - Crisis Intervention Behavior Management',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','481','481 - Rent',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','482','482 - Mortgage Payment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','483','483 - Utility',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','484','484 - Home Repairs',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','485','485 - Minor Legal Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','491','491 - Day Care Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','501','501 - Counseling',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','511','511 - Drug Screens',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','521','521 - Substance Abuse',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','531','531 - Medical/Dental Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','541','541 - Psychological Evaluation',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','561','561 - Transportation',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','611','611 - Homestead Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','621','621 - Crisis Intervention Payment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','671','671 - IMPACT',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','681','681 - Continued Parent Development',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','711','711 - In Home Case Management',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','721','721 - Parent Aide Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','791','791 - Prevention Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','801','801 - Summer Enrichment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','851','851 - Intensive Family Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','861','861 - Preventive Family Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','881','881 - Court Appearances',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','941','941 - Day Respite Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','951','951 - In-Home Intensive Treatment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','991','991 - Written Waiver Item',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','A31','A31 - Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','NA1','NA1 - Non Applicable',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','W11','W11 - Level 1',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSVCCODE','W21','W21 - Level 2',SYSDATE);

-- change 230 R2 and R1
update CAPS.MESSAGE 
 set TXT_MESSAGE = 'Please enter a password with a maximum of 20 characters.' 
    where NBR_MESSAGE = 30044 and TXT_MESSAGE_NAME = 'MSG_ARC_CONSTR_PSWD';
    
-- change 231 R2 ONLY
INSERT INTO CAPS.METAPHOR(ID_TAB,TXT_TAB_URL,TXT_TAB_CONSTANT,DT_LAST_UPDATE,TXT_TAB) 
VALUES(1470,'/financials/CountyBudgetLimit/displayCountyBudgetLimitSearch','COUNTY_BUDGET_LIMIT_SEARCH_COUNTYBUDGETLIMITSEARCH',SYSDATE,'County Budget Limit');

-- change 233 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPTYPE','MEM','Memorandum of Concern',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPTYPE','WKP','Work Plan',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPTYPE','REP','Written Reprimand',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPSTS','NEW','New',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPSTS','OPN','Open',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPSTS','CLS','Closed',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPMTHD','INP','In Person',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPMTHD','CRT','Certified Mail',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPMTHD','EML','E-mail',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CSAPMTHD','FAX','Fax',SYSDATE); 

-- change 234 R2 ONLY
INSERT INTO caps.CODES_TABLES VALUES ('CSPECCIR','SPN','Safe Place for Newborns',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CSPECCIR','PTC','Physician Taking Child into Custody',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CSPECCIR','JCN','Juvenile Court-No Maltreatment Alleged',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CSPECCIR','OHA','Other out of Home Arrangement',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CSPECCIR','SEC','Short-term Emergency Care',NULL,TO_DATE('08/30/2006','MM/DD/YYYY'));

-- change 236 R2 ONLY
INSERT INTO caps.CODES_TABLES VALUES ('CPROXRNG','05','5',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CPROXRNG','10','10',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CPROXRNG','20','20',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CPROXRNG','30','30',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CPROXRNG','40','40',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CPROXRNG','50','50',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CPROXRNG','XX','50+',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 

UPDATE caps.CODES_TABLES SET DECODE = 'Closed' WHERE CODE = '02' AND CODE_TYPE = 'CRSCSTAT'; 
INSERT INTO caps.CODES_TABLES VALUES ('CRSCSTAT','03','Inactive',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CRSCSTAT','04','Suspend',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 

UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '010' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '020' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '030' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '040' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '050' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '060' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '090' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '100' AND CODE_TYPE = 'CLVOFCRE'; 
UPDATE caps.CODES_TABLES SET DT_END = TO_DATE('01/01/2006','MM/DD/YYYY') WHERE CODE = '110' AND CODE_TYPE = 'CLVOFCRE'; 

INSERT INTO caps.CODES_TABLES VALUES ('CLVOFCRE','01','1',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CLVOFCRE','02','2',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CLVOFCRE','03','3',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CLVOFCRE','04','4',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CLVOFCRE','05','5',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CLVOFCRE','06','6',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 
INSERT INTO caps.CODES_TABLES VALUES ('CLVOFCRE','0A','A',NULL,TO_DATE('08/30/2006','MM/DD/YYYY')); 

-- change 240 R2 ONLY
insert into CAPS.MESSAGE (dt_last_update, nbr_message, txt_message_name, cd_source, cd_presentation, ind_batch, txt_message) 
values(sysdate, 60067, 'MSG_DATE_REQ', 700, 500, 'N', 'Date Hearing requested must be on or before Meeting Date');

insert into CAPS.MESSAGE (dt_last_update, nbr_message, txt_message_name, cd_source, cd_presentation, ind_batch, txt_message) 
values(sysdate, 60068, 'MSG_DATE_OUTCOME_DISCUSSED', 700, 500, 'N', 'Outcome Discussed must be after both Date Hearing Requested and Meeting Date');

-- change 243 R2 ONLY
INSERT INTO caps.CODES_TABLES VALUES ('CPAYDELI','CHK','Check',NULL,sysdate); 
INSERT INTO caps.CODES_TABLES VALUES ('CPAYDELI','DEP','Direct Deposit',NULL,sysdate); 

-- change 244 R2 ONLY
UPDATE CAPS.CODES_TABLES SET code = 'XXX' 
WHERE code_type = 'CREMFRHR' 
AND DECODE = 'Other Conservatorship';

-- change 245 R2 ONLY
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGCPS', 'RSC', 'Request For Shelter Care', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLHECOT', 'CSP', 'Child Support', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLHECOT', 'DIV', 'Divorce', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLHECOT', 'IJR', 'Immediate Judicial Review', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLHECOT', 'IPR', 'Immediate Permanency Review', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLHECOT', 'LES', 'Legal Separation', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLHECOT', 'PAT', 'Paternity', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLHECOT', 'SHC', 'Shelter Care', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'ADJ', 'Adjudicated Deliquent', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'APA', 'Appeal Approved', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'APD', 'Appeal Denied', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'CYR', 'Custody Reinstated', SYSDATE); 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Custody Transferred To Non Relative' 
WHERE code_type='CLEGLOUT' AND code='CYT'; 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'CTR', 'Custody Transferred To Relative', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'IAP', 'Initial Authorization for Placement', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'JAC', 'Judge Approved Case Plan', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'JDN', 'Judge Did Not Approve Case Plan', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'NCP', 'No Change In Placement', SYSDATE); 

UPDATE CAPS.CODES_TABLES 
SET DECODE='TPR Granted - Perm Custody to DHR', 
    code='TPC' 
WHERE code_type='CLEGLOUT' AND code='TPG'; 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'TPS', 'TPR Granted - Perm Custody to Specified Relative for Adoption', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CLEGLOUT', 'TPT', 'TPR Granted - Perm Custody to a 3rd Party', SYSDATE); 
 
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CCRTTYPE', 'APL', 'Appellate', SYSDATE); 
 
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CCRTLANG', 'CWC', 'Contrary To The Welfare Of The Child', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CCRTLANG', 'RPR', 'Reasonable Efforts To Prevent Removal', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CCRTLANG', 'RFP', 'Reasonable Efforts To Finalize Permanency', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CCRTLANG', 'RCF', 'Reasonable Efforts To Reunify the Child and Family', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES 
('CCRTLANG', 'RNN', 'Reasonable Efforts Not Necessary', SYSDATE);

-- change 246 R2 ONLY
UPDATE CAPS.CODES_TABLES SET DECODE = '45 Day Investigation Waiver' WHERE CODE = 'WIV' AND CODE_TYPE = 'CWVRTYP';

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (114, 'SacwisRev2', 'static updates, add columns to INCOMING_DETAIL, PERSON_DTL, EXT_DOCUMENTATION, and FAMILY_PLAN_TASK');                         
commit;
