--STGAP00015812 - Release(3.43) MR-62: Add Rename remove table

drop table CAPS.CONTACT_FOR;

DROP SEQUENCE caps.SEQ_PARENT_CONTACT_RULE;

alter table caps.PARENT_CONTACT_RULE rename to CONTACT_RULE;

ALTER TABLE caps.CONTACT_RULE rename column ID_PARENT_CONTACT_RULE to ID_CONTACT_RULE;

ALTER TABLE CAPS.CONTACT_RULE RENAME CONSTRAINT PK_PARENT_CONTACT_RULE TO PK_CONTACT_RULE;

ALTER INDEX caps.IND_PARENT_CONTACT_RULE_1 RENAME TO IND_CONTACT_RULE_1;

ALTER INDEX caps.IND_PARENT_CONTACT_RULE_2 RENAME TO IND_CONTACT_RULE_2;

ALTER TABLE caps.CONTACT_RULE rename column CD_PARENTAL_ROLE to CD_PERSON_ROLE;

comment on column CAPS.CONTACT_RULE.CD_PERSON_ROLE is 'Records the code for the role of the person' ;


CREATE TABLE CAPS.CONTACT_FOR
(ID_CHILD Number(16,0) not null,
ID_CONTACT_RULE Number(16,0) not null,
DT_LAST_UPDATE Date not null,
IND_CONTACT_FOR Varchar2(1),
CONSTRAINT PK_CONTACT_FOR PRIMARY KEY(ID_CHILD,ID_CONTACT_RULE)  using index tablespace index01,
CONSTRAINT FK_CONTACT_FOR_PERSON FOREIGN KEY (ID_CHILD)
   REFERENCES CAPS.PERSON(ID_PERSON),
CONSTRAINT FK_CONTACT_FOR_RULE FOREIGN KEY (ID_CONTACT_RULE)
 REFERENCES CAPS.CONTACT_RULE(ID_CONTACT_RULE)
 ) tablespace data01;

create index caps.IND_CONTACT_FOR_1 on CAPS.CONTACT_FOR(ID_CHILD) tablespace index01;

comment on column CAPS.CONTACT_FOR.ID_CHILD is 'Composite Primary Key' ;
comment on column CAPS.CONTACT_FOR.ID_CONTACT_RULE is 'Composite Primary Key' ;
comment on column CAPS.CONTACT_FOR.DT_LAST_UPDATE is 'Used to record the last updated date' ;
comment on column CAPS.CONTACT_FOR.IND_CONTACT_FOR is 'Indicates a child that the contact is for' ;

drop trigger caps.TUBR_PARENT_CONTACT_RULE;
drop trigger caps.TIBR_PARENT_CONTACT_RULE;
CREATE SEQUENCE  CAPS.SEQ_CONTACT_RULE  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

grant select on CAPS.SEQ_CONTACT_RULE  to capsbat,capson,ops$datafix,shinesdm;

grant select,update,insert,delete on caps.CONTACT_FOR to capson,capsbat,ops$datafix;
grant select on caps.CONTACT_FOR to operator,shinesdm;

/
CREATE OR REPLACE TRIGGER CAPS.TUBR_CONTACT_FOR
BEFORE UPDATE
ON CAPS.CONTACT_FOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
        :new.DT_LAST_UPDATE := SYSDATE;
END;
/

/
CREATE OR REPLACE TRIGGER CAPS.TIBR_CONTACT_FOR
BEFORE INSERT
ON CAPS.CONTACT_FOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
   :NEW.DT_LAST_UPDATE := sysdate;
END;
/


/
CREATE OR REPLACE TRIGGER CAPS.TUBR_CONTACT_RULE
BEFORE UPDATE
ON CAPS.CONTACT_RULE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
        :new.DT_LAST_UPDATE := SYSDATE;
END;
/

/
CREATE OR REPLACE TRIGGER CAPS.TIBR_CONTACT_RULE
BEFORE INSERT
ON CAPS.CONTACT_RULE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
   dummy number;
BEGIN
:NEW.DT_LAST_UPDATE := sysdate;
  if :NEW.ID_CONTACT_RULE=0 then
    SELECT SEQ_CONTACT_RULE.NEXTVAL INTO dummy  FROM DUAL;
    :NEW.ID_CONTACT_RULE := dummy;
  end if;
END;
/

drop table CAPS.CHILD_CONTACT_RULE;

ALTER TABLE CAPS.TASK ADD (IND_TASK_DELETE Varchar2(1));

comment on column CAPS.TASK.IND_TASK_DELETE is 'Indicates if events associated with the task can be deleted' ;

UPDATE CAPS.TASK SET IND_TASK_DELETE = '1' WHERE CD_TASK IN ('6540', '7025');

INSERT INTO CAPS.CODES_TABLES VALUES('CPARROLE', 'CHL', 'Child', NULL, SYSDATE);

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (761, 'SacwisRev3', 'Release 3.43 - DBCR 15812');

commit;


