--STGAP00016000 - Release(4.0) Record Check conversion SQL

--1.       Change all Records Checks in SHINES with a type of GBI Sex Offender Registry to a Records Check type of Sexual Offender Registry

--2.       Change all Records Checks in SHINES with a type of Internal System Search to a Records Check type of GA SHINES

--3.       For all Records Checks in SHINES with a type of Prior CPS History, add three identical Records Check entries with a type of IDS Online Master Index, IDS Placement Central, and Protective Services Data System


update caps.records_check set cd_rec_check_check_type='SR'
where cd_rec_check_check_type='SO' ;

update caps.records_check set cd_rec_check_check_type='GS'
where cd_rec_check_check_type='IS' ;

insert into caps.records_check
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,CD_REC_CHECK_CHECK_TYPE,
CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,
IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,
DT_RECCHK_FP_CARD_RETURN,DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,
IND_RECCHK_FPCHK_RESULT,IND_RECCHK_RECMNDATN)
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'IM',
r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,
r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,
r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,
r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.caps_case c
where r.cd_rec_check_check_type='PH' and
r.id_case=c.id_case and
(c.dt_case_closed is null or c.dt_case_closed=to_date('12/31/4712', 'MM/DD/YYYY'));

insert into caps.records_check
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,
CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,
DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,
IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,
DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,
IND_RECCHK_RECMNDATN)
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'IC',
r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,
r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,
r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,
r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.caps_case c
where r.cd_rec_check_check_type='PH' and
r.id_case=c.id_case and
(c.dt_case_closed is null or c.dt_case_closed=to_date('12/31/4712', 'MM/DD/YYYY'));

insert into caps.records_check
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,
CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,
DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,
IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,
DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,
IND_RECCHK_RECMNDATN)
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'PS',
r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,
r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,
r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,
r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.caps_case c
where r.cd_rec_check_check_type='PH' and
r.id_case=c.id_case and
(c.dt_case_closed is null or c.dt_case_closed=to_date('12/31/4712', 'MM/DD/YYYY'));



insert into caps.schema_version(id_schema_version,application_version,comments)
            values (904, 'SacwisRev4', 'Release 4.0 - DBCR 16000');

commit;



