--STGAP00015894 - Release(N/A) Update TUBR_PORTAL_USER trigger

--Updating TUBR_PORTAL_USER trigger

grant select on caps.person to capson;
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_PORTAL_USER 
BEFORE UPDATE
ON CAPS.PORTAL_USER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

BEGIN
  :NEW.DT_LAST_UPDATE := SYSDATE;
  
  IF( :NEW.TXT_PASSWORD <> :OLD.TXT_PASSWORD )
  THEN
    :NEW.DT_LAST_PASSWD_RESET := SYSDATE;
  END IF;

  insert into PORTAL_USER_AUDIT(
        ID_USER,
  DT_LAST_UPDATE,
  NM_USER_FIRST,
  NM_USER_MIDDLE,
  NM_USER_LAST,
  NM_USER_FULL,
  TXT_TITLE,
  TXT_USER_EMAIL,
  NBR_USER_PHONE,
  NBR_USER_PHONE_EXTENSION,
        ADDR_USER_ADDR_ZIP,
        CD_USER_ADDR_STATE,
        ADDR_USER_ADDR_CITY,
        ADDR_USER_ADDR_ST_LN_1,
        ADDR_USER_ADDR_ST_LN_2,
        CD_USER_ADDR_COUNTY,
        CD_REQUEST_TYPE,
        TXT_OTHER,
        TXT_PASSWORD,
        IND_USER_AGREEMENT,
        IND_ADMIN_AGREEMENT,
        CD_STATUS,
        CD_QUESTION_1,
        CD_QUESTION_2,
        CD_QUESTION_3,
        TXT_ANSWER_1,
  TXT_ANSWER_2,
        TXT_ANSWER_3,
        DT_LAST_PASSWD_RESET,
        IND_PASSWD_TEMP,
        NBR_FAILED_LOGIN_ATTEMPTS,
        ID_SHINES_PERSON_MODIFIED_BY,
        ID_PORTAL_PERSON_MODIFIED_BY,
  TABLE_ACTION
    ) values (
        :NEW.ID_USER,
  :NEW.DT_LAST_UPDATE,
  :NEW.NM_USER_FIRST,
  :NEW.NM_USER_MIDDLE,
  :NEW.NM_USER_LAST,
  :NEW.NM_USER_FULL,
  :NEW.TXT_TITLE,
  :NEW.TXT_USER_EMAIL,
  :NEW.NBR_USER_PHONE,
  :NEW.NBR_USER_PHONE_EXTENSION,
        :NEW.ADDR_USER_ADDR_ZIP,
        :NEW.CD_USER_ADDR_STATE,
        :NEW.ADDR_USER_ADDR_CITY,
        :NEW.ADDR_USER_ADDR_ST_LN_1,
        :NEW.ADDR_USER_ADDR_ST_LN_2,
        :NEW.CD_USER_ADDR_COUNTY,
        :NEW.CD_REQUEST_TYPE,
        :NEW.TXT_OTHER,
        :NEW.TXT_PASSWORD,
        :NEW.IND_USER_AGREEMENT,
        :NEW.IND_ADMIN_AGREEMENT,
        :NEW.CD_STATUS,
        :NEW.CD_QUESTION_1,
        :NEW.CD_QUESTION_2,
        :NEW.CD_QUESTION_3,
        :NEW.TXT_ANSWER_1,
  :NEW.TXT_ANSWER_2,
        :NEW.TXT_ANSWER_3,
        :NEW.DT_LAST_PASSWD_RESET,
        :NEW.IND_PASSWD_TEMP,
        :NEW.NBR_FAILED_LOGIN_ATTEMPTS,
        :NEW.ID_SHINES_PERSON_MODIFIED_BY,
        :NEW.ID_PORTAL_PERSON_MODIFIED_BY,
        'UPDATE'
    );
END;

/


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (820, 'SacwisRev3', 'Release N/A - DBCR 15894');

commit;


