-- INSERTING INTO METAPHOR for Foster Home Conversion --

INSERT INTO CAPS.METAPHOR ( ID_TAB, TXT_TAB_URL, TXT_TAB_CONSTANT, TXT_TAB, DT_LAST_UPDATE) 
VALUES (1675, '/workload/EventSearch/displayEventList', 'HOMEINFRMTN_HOME_CONVERSION_3', 'Foster Home Conversion List', SYSDATE); 


-- INSERTING into TASK for Foster Home Conversion  --

Insert into CAPS.TASK 
(CD_TASK,DT_LAST_UPDATE,CD_TASK_EVENT_STATUS,CD_TASK_EVENT_TYPE,CD_TASK_LIST_WINDOW,CD_TASK_PRIOR,CD_TASK_STAGE,CD_TASK_STAGE_PROGRAM,CD_TASK_TOP_WINDOW,IND_TASK_DETAIL_ENABLE,IND_TASK_EVENT_CREATE,IND_TASK_EVENT_NAVIG,IND_TASK_LIST_ENABLE,IND_TASK_MULTIPLE_INSTANCE,IND_TASK_NEW_ENABLE,IND_TASK_NEW_USING,
IND_TASK_NU_ACROSS_CASE,IND_TASK_RTRV_PRIOR_STAGE,IND_TASK_SHOW_IN_LIST,IND_TASK_TODO_ENABLE,TXT_TASK_DECODE,TXT_1ST_TAB,TXT_2ND_TAB,TXT_3RD_TAB,
TXT_EVENT_DETAIL_URL,IND_TASK_CODE_PREFER,IND_TASK_NEW_CASE_TODO_ENABLE,IND_TASK_FORCE_EVENT_LINK,IND_STAGE_CLOSURE) 
values ('9997',sysdate,'COMP','HCN','CCMN51W',null,'FAD','CPS','CSUB09C',null,'1','1',null,'1',null,'1','0','0','1',null,'Home Conversion','CASE_CASESEARCH','HOME_INFORMATION_HOMEINFRMTN','HOMEINFRMTN_HOME_CONVERSION_3','/fad/HomeConversion/displayHomeConversion','3','1','0','0');

Insert into CAPS.task 
(CD_TASK,DT_LAST_UPDATE,CD_TASK_EVENT_STATUS,CD_TASK_EVENT_TYPE,CD_TASK_LIST_WINDOW,CD_TASK_PRIOR,CD_TASK_STAGE,CD_TASK_STAGE_PROGRAM,CD_TASK_TOP_WINDOW,IND_TASK_DETAIL_ENABLE,IND_TASK_EVENT_CREATE,IND_TASK_EVENT_NAVIG,IND_TASK_LIST_ENABLE,IND_TASK_MULTIPLE_INSTANCE,IND_TASK_NEW_ENABLE,IND_TASK_NEW_USING,
IND_TASK_NU_ACROSS_CASE,IND_TASK_RTRV_PRIOR_STAGE,IND_TASK_SHOW_IN_LIST,IND_TASK_TODO_ENABLE,TXT_TASK_DECODE,TXT_1ST_TAB,TXT_2ND_TAB,TXT_3RD_TAB,TXT_EVENT_DETAIL_URL
,IND_TASK_CODE_PREFER,IND_TASK_NEW_CASE_TODO_ENABLE,IND_TASK_FORCE_EVENT_LINK,IND_STAGE_CLOSURE) 
values ('9998',sysdate,null,'APP',null,null,'ADO','CPS','CCMN65W',null,'0','1',null,'1',null,'0','0','0','0',null,'Approve Child Life History Check List','CASE_CASESEARCH','HOME_INFORMATION_HOMEINFRMTN','HOMEINFRMTN_HOME_CONVERSION_3','/fad/HomeConversion/displayHomeConversion','0','0','0','0');

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (368, 'SacwisRev2', 'Release 2.6 - DBCR 9778');

commit;


