
-- Standard Alter Table SQL

ALTER TABLE CAPS.FOSTER_CARE_RATE ADD CD_AGE_RANGE VARCHAR2(3)     NULL
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD TXT_REASON_SPEC_WAIVER VARCHAR2(300)     NULL
;

-- Alter Index SQL

CREATE INDEX CAPS.IND_FOSTER_CARE_RATE_1
    ON CAPS.FOSTER_CARE_RATE(CD_FCARE_RATE_SERVICE,CD_AGE_RANGE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };


-- change STGAP00001807
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'FEL', 'IV-E Language');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'CUS', 'Custody');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'SSI', 'SSI');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'AGE', 'Age');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'NAP', 'Non IV-E Approved Placement');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'INR', 'Income/Resources');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'DEP', 'Deprivation');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CELIGCHG', 'OTH', 'Other');

-- change STGAP00001825
INSERT INTO CAPS.MESSAGE
(id_message, nbr_message, txt_message_name, 
txt_message)
VALUES (0, 60233, 'MSG_FCE_TXT_RML_MONTHS', 'You indicated medical assistance was needed for the child within the 3 months prior to removal. The Months are required.');

-- change STGAP00001827
update caps.codes_tables
set dt_end = to_date('01/01/2006', 'MM/DD/YYYY')
where code in ('QAS','SRI','VIP','VLT','ARF','CBS','COM','CRA','DVP','HSG','MDH')
and code_type = 'CEVNTTYP';

-- change STGAP00001832
insert into caps.codes_tables  (code_type,code,decode) values ('CNUMTYPE','IDS #','*');

-- change STGAP00001833
Insert into CAPS.TASK
  (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, IND_TASK_TODO_ENABLE, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
Values
  ('1044', SYSDATE, 'APP', 'INT', 'ALL', 'CCMN65W', ' ', '0', '1', '0', '0', '0', '0', '0', ' ', 'Approve Intake Report (Special Request) ', 'INTAKE_INTAKE', 'INTAKE_ACTIONS_INTAKEACTIONS', '/intake/CallInformation/displayCallInformation', 0, '0', '0', '1');

Insert into CAPS.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
   (NULL, SYSDATE, 'INT', 'IC', 'CPS', '1', 'SUB', 'STG', 'COMP', 'Intake Stage Closed');
  
Insert into CAPS.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
   (NULL, SYSDATE, 'SUB', 'IC', 'CPS', '1', 'SUB', 'STG', 'NEW', 'Foster Care Child Stage Opened');

Insert into CAPS.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
   (NULL, SYSDATE, 'INT', 'PA', 'CPS', '1', 'PAD', 'STG', 'COMP', 'Intake Stage Closed');

Insert into CAPS.STAGE_PROG
  (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
  (NULL, SYSDATE, 'PAD', 'PA', 'CPS', '1', 'PAD', 'STG', 'NEW', 'Post Adoption Stage Opened');

Insert into CAPS.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
   (NULL, SYSDATE, 'INT', 'PF', 'CPS', '1', 'PFC', 'STG', 'COMP', 'Intake Stage Closed');

Insert into CAPS.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
   (NULL, SYSDATE, 'PFC', 'PF', 'CPS', '1', 'PFC', 'STG', 'NEW', 'Post Foster Care Stage Opened');
      
Insert into CAPS.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
   (NULL, SYSDATE, 'INT', 'NI', 'CPS', '1', 'SUB', 'STG', 'COMP', 'Intake Stage Closed');   
   
Insert into CAPS.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_OPEN, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
Values
   (NULL, SYSDATE, 'SUB', 'NI', 'CPS', '1', 'SUB', 'STG', 'NEW', 'Foster Care Child Stage Opened');   

-- change STGAP00001835
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P3H','More than 3 foster children in home', SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P6H','Child 6 or under in congregate care', SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P33','More than 3 children under 3', SYSDATE);

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWPWRSN','P12','Child under 12 in congregate care', SYSDATE);

-- change STGAP00001836

truncate table caps.foster_care_rate;

insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'50101','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'50101','612',to_date('12/31/4712', 'MM/DD/YYYY'), to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values 
 (18.25 ,'50101','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'50201','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'50201','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'50201','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'50301','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'50301','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'50301','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'52901','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'52901','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'52901','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'55001','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'55001','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'55001','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'55007','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'55007','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'55007','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55081','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55081','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55081','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55082','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55082','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55082','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'56001','005', to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'56001','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'56001','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'57401','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'57401','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'57401','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'57501','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'57501','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'57501','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'57701','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'57701','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'57701','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'57901','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'57901','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'57901','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'60901','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'60901','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'60901','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'61001','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'61001','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'61001','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (14.18 ,'61101','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (16.00 ,'61101','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (18.25 ,'61101','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'54201','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'54201','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'54201','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'54207','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'54207','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'54207','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'55201','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'55201','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'55201','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'55207','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'55207','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'55207','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55281','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55281','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55281','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55282','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55282','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55282','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'55301','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'55301','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'55301','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (340.20 ,'55307','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (384.00 ,'55307','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (438.00 ,'55307','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55381','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55381','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55381','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55382','005',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55382','612',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));
insert into caps.foster_care_rate (AMT_FCARE_RT_UNIT_RATE,CD_FCARE_RATE_SERVICE,CD_AGE_RANGE,DT_FCARE_RT_END,DT_FCARE_RT_START)
values
 (300.00 ,'55382','13P',to_date('12/31/4712', 'MM/DD/YYYY'),to_date('1/1/2007', 'MM/DD/YYYY'));

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (144, 'SacwisRev2', 'static updates, schema changes');
                         
commit;                         
