
-- Standard Alter Table SQL

ALTER TABLE CAPS.POLICY_WAIVER ADD MNTH_WVR_CTCT NUMBER(2)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD YR_WVR_CTCT NUMBER(4)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD TXT_WVR_OTHER VARCHAR2(30)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD ID_WVR_PRN_UNABLE_CNCT NUMBER(16)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CD_WVR_AUTH_COUNTY VARCHAR2(3)     NULL
;
COMMENT ON COLUMN CAPS.POLICY_WAIVER.CD_WVR_AUTH_COUNTY IS
'County Code'
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CD_WVR_PMT_COUNTY VARCHAR2(3)     NULL
;
COMMENT ON COLUMN CAPS.POLICY_WAIVER.CD_WVR_PMT_COUNTY IS
'County Code'
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CD_WVR_UAS_CD VARCHAR2(3)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CD_WVR_ENT_CD VARCHAR2(2)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD DT_WVR_BEGIN DATE     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD DT_WVR_END DATE     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD ID_WVR_PRY_CUST NUMBER(16)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD ID_WVR_RSRC NUMBER(16)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CD_WVR_SVC_DESC VARCHAR2(3)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD AMT_WVR NUMBER(13,2)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD NBR_WVR_UNIT NUMBER(4)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CD_WVR_JUSTIFICATION VARCHAR2(3)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD TXT_WVR_CAPACITY VARCHAR2(2)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD TXT_SLP_ARNGMTS VARCHAR2(300)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER ADD AMT_APP_PRDM NUMBER(13,2)     NULL
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.POLICY_WAIVER ADD CONSTRAINT FK_WVR_PRN_UNABLE_CNCT
FOREIGN KEY (ID_WVR_PRN_UNABLE_CNCT)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CONSTRAINT FK_WVR_PRY_CUST_PERS
FOREIGN KEY (ID_WVR_PRY_CUST)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.POLICY_WAIVER ADD CONSTRAINT FK_WVR_RSRC
FOREIGN KEY (ID_WVR_RSRC)
REFERENCES CAPS.CAPS_RESOURCE (ID_RESOURCE)
ENABLE
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };

-- change 241 R2 ONLY - continuation of 165
-- ORNTNTSTATUS
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CORNTNST', 'APP', 'Appointment Requested', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CORNTNST', 'ATT', 'Attended', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CORNTNST', 'DNS', 'Did Not Show', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CORNTNST', 'NOT', 'Not Interested', SYSDATE);
--  PRESRVTRN
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CPRSVCTR', 'ATT', 'Attended', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CPRSVCTR', 'DNS', 'Did Not Show', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CPRSVCTR', 'NOT', 'Not Interested', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CPRSVCTR', 'RES', 'Rescheduled', SYSDATE);
-- INVCLOSURE
UPDATE CAPS.CODES_TABLES SET DECODE= 'Involuntary', DT_LAST_UPDATE=SYSDATE WHERE CODE_TYPE= 'CFACLSTP' AND CODE= 'I' AND DECODE= 'Involuntary Closure';
UPDATE CAPS.CODES_TABLES SET DECODE= 'Voluntary', DT_LAST_UPDATE=SYSDATE WHERE CODE_TYPE= 'CFACLSTP' AND CODE= 'V' AND DECODE= 'Voluntary Closure';
-- REASON
UPDATE CAPS.CODES_TABLES  SET DT_END=SYSDATE, DT_LAST_UPDATE=SYSDATE WHERE CODE_TYPE= 'CFACLOSE';

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'ADO', 'Adoption', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'ARR', 'Arrest of foster parent.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'BOT', 'Burn Out', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'CAA', 'Child or parent is available for adoptive placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'CPS', 'Child Protective Service (CPS)', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'CTH', 'Child turned 18 and left home.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'CNP', 'Closed-No Placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'CPC', 'County placed child or family on hold for an identified regular adoptive placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'ERP', 'End of relative placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'DNW', 'Families were consistently saying they did not want to take any placements when called by case manager in their attempt to make placements.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'FCS', 'Family and/or child selected', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'MTR', 'Family did not get mandatory training requirements.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'MRC', 'Family Moves/Relocates/Change in circumstances', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'FRC', 'Family requested closure due to marital problems.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'FHP', 'Foster Care/Home Policy Violation', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'NPR', 'Foster parents decided to no longer serve for personal reasons.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'HDD', 'Health/Deceased', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'ICC', 'ICPC case closed due to supervision of children by adoption planning.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'NRY', 'Not ready', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'OTR', 'Other issues regarding safety and well-being', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'OFC', 'Out for consideration', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'PFP', 'Plan foster parent placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'PFA', 'Plan foster/adopt placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'PRA', 'Plan relative adoptive placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'PRF', 'Plan relative foster adoptive placement', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'PFO', 'Prefers to foster only.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'RTT', 'Requested transfer to another agency.', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFACLOSE', 'FNA', 'When the family is not amenable to change, correction or DFCS intervention', SYSDATE);

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (115, 'SacwisRev2', 'static updates, add columns to policy waiver');
                         
commit;

