
-- Standard Alter Table SQL

ALTER TABLE CAPS.LEGAL_ACTION ADD IND_UP_PREV_ACT VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.LEGAL_ACTION ADD IND_COMPLETE VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.PERSON ADD CD_MATCH_TYPE VARCHAR2(3)     NULL
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };

-- change 30
update caps.codes_tables set dt_end=null 
where code_type = 'CPM' or code_type = 'CME' or code_type ='OTH';

-- change 34
UPDATE caps.codes_tables 
SET dt_end = TO_DATE('01/01/2006','MM/DD/YYYY') 
WHERE code IN ('CA','CF','CI','CJ','DC','FF','FG','FI','FJ','FL','FM','AJ','CN') 
AND code_type = 'CSECATTR'; 

UPDATE caps.codes_tables 
SET dt_end = TO_DATE('01/01/2006','MM/DD/YYYY') 
WHERE code IN ('AD','AE','AF','AL','AN','AQ','AR','AS','AT','AU','AV','AW','AX','AY','AZ','BA','BB', 
'BC','BD','BE','BF','CB','CC','CD','CE','CG','CH','CL','CM','CO','CP','CX','DB','EB','FH') 
AND code_type = 'CSECATTR'; 

DELETE FROM caps.emp_sec_class_link 
WHERE cd_security_class_name <> 'ALL'; 

DELETE FROM caps.security_class 
WHERE cd_security_class_name <> 'ALL'; 

UPDATE caps.security_class 
SET txt_security_class_profil = '11111111111111111111111000100' 
WHERE cd_security_class_name = 'ALL'; 

INSERT INTO caps.security_class 
(cd_security_class_name, dt_last_update, txt_security_class_profil, ind_restrict, id_person_modified_by) 
VALUES 
('NONE', SYSDATE, '00000000000000000000000000000', 'N', 1); 

INSERT INTO caps.security_class 
(cd_security_class_name, dt_last_update, txt_security_class_profil, ind_restrict, id_person_modified_by) 
VALUES 
('CASE_MANAGER', SYSDATE, '00001000000000000000100000000', 'N', 1); 

INSERT INTO caps.security_class 
(cd_security_class_name, dt_last_update, txt_security_class_profil, ind_restrict, id_person_modified_by) 
VALUES 
('SUPERVISOR', SYSDATE, '10111011010100000110100000000', 'N', 1); 

INSERT INTO caps.security_class 
(cd_security_class_name, dt_last_update, txt_security_class_profil, ind_restrict, id_person_modified_by) 
VALUES 
('ALL_SECURITY', SYSDATE, '11111111111111111111111000110', 'Y', 1); 


INSERT INTO caps.emp_sec_class_link 
(dt_last_update,cd_security_class_name,id_person,id_person_modified_by) 
VALUES 
(SYSDATE, 'ALL_SECURITY', 931, 1); 

INSERT INTO caps.emp_sec_class_link 
(dt_last_update,cd_security_class_name,id_person,id_person_modified_by) 
VALUES 
(SYSDATE, 'ALL', 931, 1); 

INSERT INTO caps.emp_sec_class_link 
(dt_last_update,cd_security_class_name,id_person,id_person_modified_by) 
VALUES 
(SYSDATE, 'ALL_SECURITY', 6375, 1); 

-- change 36
INSERT INTO caps.metaphor 
(id_tab, txt_tab_url, txt_tab_constant, txt_tab, dt_last_update) 
VALUES 
(365, '/contacts/ProtectiveServiceAlert/displayProtectiveServiceAlert', 'PROTECTIVE_SERVICE_ALERT','Protective Service Alert', SYSDATE); 

INSERT INTO caps.metaphor 
(id_tab, txt_tab_url, txt_tab_constant, txt_tab, dt_last_update) 
VALUES 
(1183, '/workload/EventSearch/displayEventList', 'SAFETY_ASSESSMENT_EVENTLIST','Safety Assessment', SYSDATE); 

INSERT INTO caps.metaphor 
(id_tab, txt_tab_url, txt_tab_constant, txt_tab, dt_last_update) 
VALUES 
(355, '/contacts/ContactSearchListDetail/displayContactSearchList', 'CONTACTS_SUMMARIES_CONTACTSEARCH_3RD','Contact Search List', SYSDATE); 

INSERT INTO caps.TASK 
(cd_task, 
dt_last_update, 
cd_task_event_type, 
cd_task_stage, 
cd_task_stage_program, 
ind_task_event_create, 
ind_task_event_navig, 
ind_task_multiple_instance, 
ind_task_new_using, 
INd_task_nu_across_case, 
ind_task_rtrv_prior_stage, 
ind_task_show_in_list, 
txt_task_decode, 
txt_1ST_tab, 
txt_2nd_tab, 
txt_3rd_tab, 
txt_event_detail_url, 
ind_task_code_prefer) 
VALUES 
('2285', 
SYSDATE, 
'ASM', 
'INV', 
'CPS', 
1, 
1, 
1, 
0, 
0, 
0, 
1, 
'Safety Assessment', 
'CASE_CASESEARCH', 
'RISK_ASSESSMENT_RISKASSMT', 
'SAFETY_ASSESSMENT_EVENTLIST', 
'/assessment/SafetyAssessment/displaySafetyAssessment', 
3); 

UPDATE caps.TASK 
SET txt_2nd_tab = 'PERSON_PERSONLIST', 
txt_3rd_tab = 'MEDICAL_MENTAL_ASSESSMENT_EVENTLIST' 
WHERE cd_task = 2280; 

UPDATE caps.metaphor 
SET txt_filter_path = 'gov.georgia.dhr.dfcs.sacwis.web.metaphor.PersonDtlShowTab', 
id_tab = 1085 
WHERE id_tab = 890; 

UPDATE caps.metaphor 
SET txt_tab_url = '/workload/EventSearch/displayEventList', 
txt_tab_constant = 'POLICY_WAIVER_EVENTLIST' 
WHERE id_tab = 1450; 

UPDATE caps.TASK 
SET ind_task_code_prefer = 3 
WHERE cd_task = 2320; 

-- Change 33
-- DELETE ONLY THE ENDED CODES THAT HAVE A MATCH IN THE NEW ONE
DELETE FROM CAPS.CODES_TABLES
WHERE CODE_TYPE = 'CCNTPURP'
AND CODE IN (
	SELECT CODE
	FROM CAPS.CODES_TABLES
	WHERE code_type = 'CCNTPURP'
	AND CODE IN (
		 	 	SELECT 'B' || code
		 	 	FROM CAPS.CODES_TABLES
			 	WHERE code_type = 'CCNTPURP'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL
			   UNION
			   SELECT 'D' || code
			   FROM CAPS.CODES_TABLES
			   WHERE code_type = 'CCNTPURP'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL
			   UNION
			   SELECT 'K' || code
			   FROM CAPS.CODES_TABLES
			   WHERE code_type = 'CCNTPURP'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL)
	AND DT_END IS NOT NULL)
AND DT_END IS NOT NULL;

-- DELETE ALL THE NEW CODES THAT HAVE NOT BEEN ENDED
DELETE FROM CAPS.CODES_TABLES
WHERE code_type = 'CCNTPURP'
AND DT_END IS NULL;

-- RE-INSERT THE NEW CODES
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CDR','Child Daily Routine', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CPL','Child Preparation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CPR','Parent Child Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CRP','Child Religious Practices', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CRT','Court Action', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CSA','Child Special Skills/Achievements', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CVS','Collateral', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','DIL','Diligent Search', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FAC','Facility Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FMI','Family Moves During Investigation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FTM','Family Team Meeting', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','HAS','Home Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','HOM','Home Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','LAW','Law Enforcement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','LEG','Legal Trial Preparation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','MDT','MDT', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','MED','MED', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','NOT','Notification', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PCN','Placement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PCV','Parent Child Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PPL','Pre-Placement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','RAS','Risk Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','RVW','Review', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SCS','School Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SIS','Special Investigation – 48 Hour Staffing', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SNR','SI Home Visit – Child in Non-Residential Facility', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SPA','SI Home Visit – Child in Private Agency', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SPP','SI School Visit – Children in Private or Public School', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SRF','SI Home Visit – Child in Residential Facility', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SSO','SI Home Visit – Child in State Operated Home', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','STF','Staffed Case', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SUP','Supervisor Review', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','XSI','Special Investigation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','XXX','Other', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

-- PREFIX THE NEW CODES WITH THE B KEY CODE
UPDATE CAPS.CODES_TABLES 
SET code = 'B' || code
WHERE code_type = 'CCNTPURP'
AND LENGTH(code) = 3
AND dt_end IS NULL;

-- RE-INSERT THE NEW CODES
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CDR','Child Daily Routine', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CPL','Child Preparation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CPR','Parent Child Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CRP','Child Religious Practices', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CRT','Court Action', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CSA','Child Special Skills/Achievements', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CVS','Collateral', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','DIL','Diligent Search', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FAC','Facility Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FMI','Family Moves During Investigation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FTM','Family Team Meeting', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','HAS','Home Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','HOM','Home Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','LAW','Law Enforcement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','LEG','Legal Trial Preparation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','MDT','MDT', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','MED','MED', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','NOT','Notification', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PCN','Placement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PCV','Parent Child Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PPL','Pre-Placement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','RAS','Risk Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','RVW','Review', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SCS','School Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SIS','Special Investigation – 48 Hour Staffing', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SNR','SI Home Visit – Child in Non-Residential Facility', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SPA','SI Home Visit – Child in Private Agency', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SPP','SI School Visit – Children in Private or Public School', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SRF','SI Home Visit – Child in Residential Facility', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SSO','SI Home Visit – Child in State Operated Home', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','STF','Staffed Case', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SUP','Supervisor Review', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','XSI','Special Investigation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','XXX','Other', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

-- PREFIX THE NEW CODES WITH THE D KEY CODE
UPDATE CAPS.CODES_TABLES 
SET code = 'D' || code
WHERE code_type = 'CCNTPURP'
AND LENGTH(code) = 3
AND dt_end IS NULL;

-- RE-INSERT THE NEW CODES
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CDR','Child Daily Routine', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CPL','Child Preparation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CPR','Parent Child Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CRP','Child Religious Practices', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CRT','Court Action', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CSA','Child Special Skills/Achievements', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','CVS','Collateral', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','DIL','Diligent Search', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FAC','Facility Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FMI','Family Moves During Investigation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','FTM','Family Team Meeting', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','HAS','Home Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','HOM','Home Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','LAW','Law Enforcement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','LEG','Legal Trial Preparation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','MDT','MDT', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','MED','MED', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','NOT','Notification', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PCN','Placement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PCV','Parent Child Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','PPL','Pre-Placement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','RAS','Risk Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','RVW','Review', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SCS','School Visit', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SIS','Special Investigation – 48 Hour Staffing', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SNR','SI Home Visit – Child in Non-Residential Facility', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SPA','SI Home Visit – Child in Private Agency', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SPP','SI School Visit – Children in Private or Public School', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SRF','SI Home Visit – Child in Residential Facility', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SSO','SI Home Visit – Child in State Operated Home', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','STF','Staffed Case', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','SUP','Supervisor Review', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','XSI','Special Investigation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTPURP','XXX','Other', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

-- PREFIX THE NEW CODES WITH THE D KEY CODE
UPDATE CAPS.CODES_TABLES 
SET code = 'K' || code
WHERE code_type = 'CCNTPURP'
AND LENGTH(code) = 3
AND dt_end IS NULL;

DELETE FROM CAPS.CODES_TABLES
WHERE CODE_TYPE = 'COTHCNCT'
AND CODE IN (
	SELECT CODE
	FROM CAPS.CODES_TABLES
	WHERE code_type = 'COTHCNCT'
	AND CODE IN (
		 	 	SELECT 'B' || code
		 	 	FROM CAPS.CODES_TABLES
			 	WHERE code_type = 'COTHCNCT'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL
			   UNION
			   SELECT 'D' || code
			   FROM CAPS.CODES_TABLES
			   WHERE code_type = 'COTHCNCT'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL
			   UNION
			   SELECT 'K' || code
			   FROM CAPS.CODES_TABLES
			   WHERE code_type = 'COTHCNCT'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL)
	AND DT_END IS NOT NULL)
AND DT_END IS NOT NULL;

--DELETE ALL EXISTING NON ENDED CODES AND ENDED 4 LETTER CODES ENDING WITH EDU AND PREFIXED WITH KEY B/D/K 
DELETE FROM CAPS.CODES_TABLES
WHERE code_type = 'COTHCNCT'
AND (DT_END IS NULL 
	OR (LENGTH(CODE) = 4
	   AND DT_END IS NOT NULL
	   AND (  CODE = 'B' || 'EDU'
	   	   OR CODE = 'D' || 'EDU'
		   OR CODE = 'K' || 'EDU')));
		   
-- RE-INSERT THE NEW CODES
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','ADP','Adoptive Parent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CAS','CASA', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CNS','Counselor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','COR','Coroner', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CRT','Court', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','DCP','Day Care Provider', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','DHR','DHR Staff', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','EDU','Educator', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','EMP','Employer', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FAC','Facility Director/Supervisor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FIW','FIW Worker', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FOS','Foster Parent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','GAL','GAL', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','INC','Indian Custodian', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','IND','Indian Tribe/Council', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','JUV','Juvenile Probation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LAW','Law Enforcement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LEG','Legal', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LIC','Licensing Authority', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MED','Medical', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MHE','Mental Hlth Examiner', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MHM','MHMR Director', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','OFF','State Office', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','ORS','ORS Staff', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','PRV','Service Provider', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SAG','SAAG', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SCH','School Board', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SCL','School Counselor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SOI','Secretary of the Interior', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SPR','School Principal', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SUP','Superintendent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SSW','School Social Worker', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','TCH','Teacher', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','THR','Therapist', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','XXX','Other', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

UPDATE CAPS.CODES_TABLES 
SET code = 'B' || code
WHERE code_type = 'COTHCNCT'
AND LENGTH(code) = 3
AND dt_end IS NULL;

-- RE-INSERT THE NEW CODES
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','ADP','Adoptive Parent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CAS','CASA', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CNS','Counselor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','COR','Coroner', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CRT','Court', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','DCP','Day Care Provider', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','DHR','DHR Staff', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','EDU','Educator', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','EMP','Employer', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FAC','Facility Director/Supervisor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FIW','FIW Worker', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FOS','Foster Parent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','GAL','GAL', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','INC','Indian Custodian', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','IND','Indian Tribe/Council', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','JUV','Juvenile Probation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LAW','Law Enforcement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LEG','Legal', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LIC','Licensing Authority', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MED','Medical', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MHE','Mental Hlth Examiner', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MHM','MHMR Director', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','OFF','State Office', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','ORS','ORS Staff', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','PRV','Service Provider', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SAG','SAAG', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SCH','School Board', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SCL','School Counselor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SOI','Secretary of the Interior', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SPR','School Principal', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SUP','Superintendent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SSW','School Social Worker', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','TCH','Teacher', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','THR','Therapist', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','XXX','Other', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

UPDATE CAPS.CODES_TABLES 
SET code = 'D' || code
WHERE code_type = 'COTHCNCT'
AND LENGTH(code) = 3
AND dt_end IS NULL;

-- RE-INSERT THE NEW CODES
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','ADP','Adoptive Parent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CAS','CASA', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CNS','Counselor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','COR','Coroner', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','CRT','Court', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','DCP','Day Care Provider', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','DHR','DHR Staff', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','EDU','Educator', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','EMP','Employer', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FAC','Facility Director/Supervisor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FIW','FIW Worker', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','FOS','Foster Parent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','GAL','GAL', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','INC','Indian Custodian', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','IND','Indian Tribe/Council', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','JUV','Juvenile Probation', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LAW','Law Enforcement', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LEG','Legal', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','LIC','Licensing Authority', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MED','Medical', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MHE','Mental Hlth Examiner', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','MHM','MHMR Director', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','OFF','State Office', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','ORS','ORS Staff', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','PRV','Service Provider', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SAG','SAAG', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SCH','School Board', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SCL','School Counselor', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SOI','Secretary of the Interior', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SPR','School Principal', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SUP','Superintendent', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','SSW','School Social Worker', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','TCH','Teacher', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','THR','Therapist', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('COTHCNCT','XXX','Other', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

UPDATE CAPS.CODES_TABLES 
SET code = 'K' || code
WHERE code_type = 'COTHCNCT'
AND LENGTH(code) = 3
AND dt_end IS NULL;


DELETE FROM CAPS.CODES_TABLES
WHERE CODE_TYPE = 'CCNTCTYP'
AND CODE IN (
	SELECT CODE
	FROM CAPS.CODES_TABLES
	WHERE code_type = 'CCNTCTYP'
	AND CODE IN (
		 	 	SELECT 'A' || code
		 	 	FROM CAPS.CODES_TABLES
			 	WHERE code_type = 'CCNTCTYP'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL
			   UNION
			   SELECT 'D' || code
			   FROM CAPS.CODES_TABLES
			   WHERE code_type = 'CCNTCTYP'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL
			   UNION
			   SELECT 'K' || code
			   FROM CAPS.CODES_TABLES
			   WHERE code_type = 'CCNTCTYP'
			   AND LENGTH(code) = 3
			   AND DT_END IS NULL)
	AND DT_END IS NOT NULL)
AND DT_END IS NOT NULL;

DELETE FROM CAPS.CODES_TABLES
WHERE code_type = 'CCNTCTYP'
AND DT_END IS NULL;

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','REG','Contact', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','SRA','Safety Resource Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','TRN','Transfer Summary', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

UPDATE CAPS.CODES_TABLES 
SET code = 'A' || code
WHERE code_type = 'CCNTCTYP'
AND LENGTH(code) = 3
AND dt_end IS NULL;

-- insert all base code for code type
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','REG','Contact', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','SRA','Safety Resource Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','TRN','Transfer Summary', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

-- Prefix the base code with a Key code (D)
UPDATE CAPS.CODES_TABLES 
SET code = 'D' || code
WHERE code_type = 'CCNTCTYP'
AND LENGTH(code) = 3
AND dt_end IS NULL;

-- insert all base code for code type
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','REG','Contact', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','SRA','Safety Resource Assessment', TO_DATE('9/8/2006', 'MM/DD/YYYY'));
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CCNTCTYP','TRN','Transfer Summary', TO_DATE('9/8/2006', 'MM/DD/YYYY'));

-- Prefix the base code with a Key code (K)
UPDATE CAPS.CODES_TABLES 
SET code = 'K' || code
WHERE code_type = 'CCNTCTYP'
AND LENGTH(code) = 3
AND dt_end IS NULL;


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (14, 'SacwisRev1', 'Add fields to PERSON and LEGAL_ACTION, codes_tables and metaphore updates.');
                         
commit;
