
-- Standard Alter Table SQL

ALTER TABLE CAPS.CONTRACT_COUNTY MODIFY(NBR_CNCNTY_LINE_ITEM  NUMBER(4))
;
ALTER TABLE CAPS.CONTRACT_COUNTY_AUDIT MODIFY(NBR_CNCNTY_AUD_LINE_ITEM  NUMBER(4))
;
ALTER TABLE CAPS.CONTRACT_SERVICE MODIFY(NBR_CNSVC_LINE_ITEM  NUMBER(4))
;
ALTER TABLE CAPS.CONTRACT_SERVICE_AUDIT MODIFY(NBR_CNSVC_AUD_LINE_ITEM  NUMBER(4))
;
ALTER TABLE CAPS.INITIAL_MEDICAID_APP ADD NM_EMPLOYEE_NAME VARCHAR2(50)     NULL
;
ALTER TABLE CAPS.SPECIAL_NEEDS_DETERMINATION RENAME COLUMN CD_REASON_SPECIAL_REQUEST TO IND_REASON_SPECIAL_REQUEST
;
ALTER TABLE CAPS.SPECIAL_NEEDS_DETERMINATION ADD IND_SPCL_RATE_ADO_APPR VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.SPECIAL_NEEDS_DETERMINATION ADD IND_SPCL_RATE_REQ_CHILD VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.SPECIAL_NEEDS_DETERMINATION ADD IND_SPCL_SER_REQ_CHILD VARCHAR2(1)     NULL
;

-- INTERFACE SCHEMA
ALTER TABLE SACWISIFC.INVOICE_OUTBOUND MODIFY(ID_CLIENT   NULL)
;


-- Drop Constraint, Rename and Create Table SQL

CREATE TABLE CAPS.CASE_BUDGET_LIMIT_WAIVER
(
    ID_WAIVER      NUMBER(16)  NOT NULL,
    ID_CASE        NUMBER(16)  NOT NULL,
    DT_LAST_UPDATE DATE        NOT NULL,
    CD_SVC_CODE    VARCHAR2(6)     NULL,
    CONSTRAINT PK_CASE_BUDGET_LIMIT_WAIVER
    PRIMARY KEY (ID_WAIVER)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE CAPS.CASE_BUDGET_LIMIT_WAIVER IS
'Contains Budget limits for Waivers by case.'
;
COMMENT ON COLUMN CAPS.CASE_BUDGET_LIMIT_WAIVER.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSBAT
;
GRANT INSERT ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSBAT
;
GRANT SELECT ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSBAT
;
GRANT UPDATE ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSBAT
;
GRANT DELETE ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSON
;
GRANT INSERT ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSON
;
GRANT SELECT ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSON
;
GRANT UPDATE ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO CAPSON
;
GRANT SELECT ON CAPS.CASE_BUDGET_LIMIT_WAIVER TO OPERATOR
;
CREATE TABLE CAPS.FCCP_DTL_FORM_NARR
(
    ID_STAGE             NUMBER(16) NOT NULL,
    DT_LAST_UPDATE       DATE       NOT NULL,
    ID_CASE              NUMBER(16)     NULL,
    NARRATIVE            LONG RAW       NULL,
    ID_DOCUMENT_TEMPLATE NUMBER(16)     NULL,
    CONSTRAINT PK_FCCP_DTL_FORM_NARR
    PRIMARY KEY (ID_STAGE)
    USING INDEX TABLESPACE INDEX01
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 1M
                        NEXT 1M
                        MINEXTENTS 1
                        MAXEXTENTS UNLIMITED
                        PCTINCREASE 0
                        BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE CAPS.FCCP_DTL_FORM_NARR IS
'Narrative to contain the Home Study Comments and description.'
;
GRANT DELETE ON CAPS.FCCP_DTL_FORM_NARR TO CAPSBAT
;
GRANT INSERT ON CAPS.FCCP_DTL_FORM_NARR TO CAPSBAT
;
GRANT SELECT ON CAPS.FCCP_DTL_FORM_NARR TO CAPSBAT
;
GRANT UPDATE ON CAPS.FCCP_DTL_FORM_NARR TO CAPSBAT
;
GRANT DELETE ON CAPS.FCCP_DTL_FORM_NARR TO CAPSON
;
GRANT INSERT ON CAPS.FCCP_DTL_FORM_NARR TO CAPSON
;
GRANT SELECT ON CAPS.FCCP_DTL_FORM_NARR TO CAPSON
;
GRANT UPDATE ON CAPS.FCCP_DTL_FORM_NARR TO CAPSON
;
GRANT SELECT ON CAPS.FCCP_DTL_FORM_NARR TO OPERATOR
;

-- Alter Index SQL

CREATE INDEX CAPS.CASE_IND_BUDGET_LIM_WAIVER_1
    ON CAPS.CASE_BUDGET_LIMIT_WAIVER(ID_CASE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCCP_DTL_FORM_NARR_1
    ON CAPS.FCCP_DTL_FORM_NARR(ID_CASE)
TABLESPACE INDEX01
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.CASE_BUDGET_LIMIT_WAIVER 
    ADD CONSTRAINT FK_CASE_BUDG_LIM_WAIVER_CASE
FOREIGN KEY (ID_CASE)
REFERENCES CAPS.CAPS_CASE (ID_CASE)
ENABLE
;
ALTER TABLE CAPS.CASE_BUDGET_LIMIT_WAIVER 
    ADD CONSTRAINT FK_CS_BUDG_LIM_WAIVER_POL_WVR
FOREIGN KEY (ID_WAIVER)
REFERENCES CAPS.POLICY_WAIVER (ID_WVR_EVENT)
ENABLE
;
ALTER TABLE CAPS.FCCP_DTL_FORM_NARR 
    ADD CONSTRAINT FK_FCCP_DT_FRM_NARR_STAGE
FOREIGN KEY (ID_STAGE)
REFERENCES CAPS.STAGE (ID_STAGE)
ENABLE
;

-- Alter Trigger SQL
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_CASE_BUDGET_LIMIT_WAIVER
BEFORE UPDATE
ON CAPS.CASE_BUDGET_LIMIT_WAIVER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_CASE_BUDGET_LIMIT_WAIVER
BEFORE INSERT
ON CAPS.CASE_BUDGET_LIMIT_WAIVER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_FCCP_DTL_FORM_NARR
BEFORE UPDATE
ON CAPS.FCCP_DTL_FORM_NARR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_FCCP_DTL_FORM_NARR
BEFORE INSERT
ON CAPS.FCCP_DTL_FORM_NARR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	SELECT	ID_CASE
	INTO		:new.ID_CASE
	FROM		STAGE
	WHERE		ID_STAGE = :new.ID_STAGE;
EXCEPTION
	WHEN OTHERS THEN
		IF SQL%NOTFOUND THEN
			:new.ID_CASE := NULL;
		END IF;
END;
/

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00002000
UPDATE CAPS.CODES_TABLES SET DT_END = NULL
WHERE code_type = 'CRPTRINT' 
AND CODE = 'SR';

insert into caps.codes_tables (code_type, code, decode, dt_last_update)
values ('CSRCRPTR', 'SR', 'Step-Child', sysdate);

insert into caps.codes_tables (code_type, code, decode, dt_last_update)
values ('CRELVICT', 'SR', 'Step-Child', sysdate);

-- change STGAP00002002
insert into caps.codes_tables (code_type, code, decode, dt_last_update)
values ('CSRCRPTR','SH', 'School Personnel', sysdate);

insert into caps.codes_tables (code_type, code, decode, dt_last_update)
values ('CRPTRINT','SH', 'School Personnel', sysdate);

insert into caps.codes_tables (code_type, code, decode, dt_last_update)
values ('CRELCOL2','SH', 'School Personnel', sysdate);

insert into caps.codes_tables (code_type, code, decode, dt_last_update)
values ('CRELVICT','SH', 'School Personnel', sysdate);

update caps.codes_tables
set decode = 'Secondary Caretaker'
where code = 'SC'
and code_type = 'CSRCRPTR';

update caps.codes_tables
set decode = 'Secondary Caretaker'
where code = 'SC'
and code_type = 'CRPTRINT';

update caps.codes_tables
set decode = 'Secondary Caretaker'
where code = 'SC'
and code_type = 'CRELCOL2';

update caps.codes_tables
set decode = 'Secondary Caretaker'
where code = 'SC'
and code_type = 'CRELVICT';

-- change STGAP00002025
UPDATE CAPS.CODES_TABLES SET CODE = 'JA' WHERE CODE = 'JAC' AND CODE_TYPE = 'CERTIFBY';
UPDATE CAPS.CODES_TABLES SET CODE = 'CR' WHERE CODE = 'CAR' AND CODE_TYPE = 'CERTIFBY';
UPDATE CAPS.CODES_TABLES SET CODE = 'CA' WHERE CODE = 'COA' AND CODE_TYPE = 'CERTIFBY';
UPDATE CAPS.CODES_TABLES SET CODE = 'QL' WHERE CODE = 'CQL' AND CODE_TYPE = 'CERTIFBY';
UPDATE CAPS.CODES_TABLES SET CODE = 'TH' WHERE CODE = 'OTH' AND CODE_TYPE = 'CERTIFBY';

-- change STGAP00002044
UPDATE CAPS.TASK SET TXT_3RD_TAB = 'RISK_REASSESSMENTS_EVENTLIST' WHERE CD_TASK = '7385';

-- change STGAP00002046
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60312, 'SSM_CON_REQ_UNIT','Requested units should be 1 for variable unit rate payment type',500,700,'N');
  
-- change STGAP00002047
-- Update messages for Contract Period Detail
UPDATE CAPS.MESSAGE SET txt_message='The Early Term date must be before or the same as the Term date.' WHERE txt_message_name='SSM_CON_CLOSE_BEF_SAM_TER';
UPDATE CAPS.MESSAGE SET txt_message='The Start date must be before the Early Term or Term date.' WHERE txt_message_name='SSM_CON_START_BEFORE_TERM';

-- change STGAP00002049
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','50913','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','50813','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','50807','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51217','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51260','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51257','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51277','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51258a','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51258b','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51258c','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51258d','REC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLADPT','51033','NONREC',SYSDATE);

-- change STGAP00002050
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','AFS','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','CTD','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','ILP','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','JCD','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NAF','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NCT','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NCD','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NCO','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NTT','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NCE','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NGP','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NPC','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','NPR','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','PCT','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','PVL','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','STE','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','TCT','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CLSRU','TVL','X',SYSDATE);

-- change STGAP00002051
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CCITRU','AMR','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CCITRU','PTR','X',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CCITRU','TMR','U',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CCITRU','VIS','X',SYSDATE);

-- change STGAP00002052
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','REP','REL',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','NRP','REL',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','RFH','DFC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','DFH','DFC',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','CFH','CPA',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','IFH','CCL',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','EMS','CCL',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','GRH','CCL',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','CCL','CCL',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','SFH','CCL',SYSDATE); 
INSERT INTO CAPS.CODES_TABLES 
(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CPLCMTRU','ICF','CCL',SYSDATE); 

-- change STGAP00002064 
UPDATE CAPS.MESSAGE SET txt_message='Please enter a Resource and Person ID to validate.' WHERE txt_message_name='MSG_FOSTER_NOT_VALIDATED';

-- change STGAP00002065
update CAPS.MESSAGE set TXT_MESSAGE_NAME = 'MSG_FP_UPDATE_APRV' where NBR_MESSAGE = 60242;

-- change STGAP00002066
INSERT INTO CAPS.TASK ( CD_TASK,CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE,
CD_TASK_LIST_WINDOW, CD_TASK_PRIOR, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW,IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_ENABLE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE,
IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, IND_TASK_TODO_ENABLE, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK,
IND_STAGE_CLOSURE ) VALUES ( '9500','', 'WTL', '', NULL, 'PFC', 'CPS', '', NULL, '1', '1', NULL, '1', NULL, '1', '0', '0', '1', NULL, 'WTLP', 'CASE_CASESEARCH', 'CHILD_PLANS_EVENTLIST'
, 'WTLP_EVENTLIST', '/subcare/WTLP/displayWTLP', 3, '0', '0', '0');

-- change STGAP00002067
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CMEETTYP','FLG','FTM For Legal Guardianship',SYSDATE);

-- change STGAP00002069
update caps.task
set ind_task_code_prefer = '3'
where cd_task = 9525;

delete from caps.task
where cd_task = '3070';

delete from caps.task
where cd_task = '8580';

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (161, 'SacwisRev2', 'static updates, schema changes');
commit;

