
-- Sequence Alter SQL
CREATE SEQUENCE CAPS.SEQ_PSA_PERSON_LINK
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- Standard Alter Table SQL

ALTER TABLE CAPS.RECORDS_CHECK ADD DT_REC_CHECK_CRIM_REL_REC DATE     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD IND_RECCHK_FPCARD VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD IND_RECCHK_LIVE_SCAN VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD DT_RECCHK_FP_CARD_GIVEN DATE     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD DT_RECCHK_FP_CARD_RETURN DATE     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD DT_RECCHK_LS_PERFORMED DATE     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD DT_RECCHK_LSRESULT_REC DATE     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD IND_RECCHK_REFUSE_INV_CLRNCE VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD IND_RECCHK_FPCHK_RESULT VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.RECORDS_CHECK ADD IND_RECCHK_RECMNDATN VARCHAR2(1)     NULL
;

-- Drop Referencing Constraint SQL

-- Drop Constraint, Rename and Create Table SQL

CREATE TABLE CAPS.PSA_PERSON_LINK
(
    ID_PSA_PERSON_LINK          NUMBER(16) NOT NULL,
    DT_LAST_UPDATE              DATE       NOT NULL,
    ID_PROTECTIVE_SERVICE_ALERT NUMBER(16) NOT NULL,
    ID_PERSON                   NUMBER(16) NOT NULL,
    DT_ACTIVATED                DATE           NULL,
    DT_DEACTIVATED              DATE           NULL,
    CONSTRAINT PK_PSA_PERSON_LINK
    PRIMARY KEY (ID_PSA_PERSON_LINK)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON COLUMN CAPS.PSA_PERSON_LINK.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON CAPS.PSA_PERSON_LINK TO CAPSBAT
;
GRANT INSERT ON CAPS.PSA_PERSON_LINK TO CAPSBAT
;
GRANT SELECT ON CAPS.PSA_PERSON_LINK TO CAPSBAT
;
GRANT UPDATE ON CAPS.PSA_PERSON_LINK TO CAPSBAT
;
GRANT DELETE ON CAPS.PSA_PERSON_LINK TO CAPSON
;
GRANT INSERT ON CAPS.PSA_PERSON_LINK TO CAPSON
;
GRANT SELECT ON CAPS.PSA_PERSON_LINK TO CAPSON
;
GRANT UPDATE ON CAPS.PSA_PERSON_LINK TO CAPSON
;
GRANT SELECT ON CAPS.PSA_PERSON_LINK TO OPERATOR
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.PSA_PERSON_LINK 
    ADD CONSTRAINT FK_PSA_PERSON_LINK_PERSON
FOREIGN KEY (ID_PERSON)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.PSA_PERSON_LINK 
    ADD CONSTRAINT FK_PSA_PERSON_LINK_PSA
FOREIGN KEY (ID_PROTECTIVE_SERVICE_ALERT)
REFERENCES CAPS.PROTECTIVE_SERVICE_ALERT (ID_PROTECTIVE_SERVICE_ALERT)
ENABLE
;

-- Alter Trigger SQL
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_PSA_PERSON_LINK
BEFORE UPDATE
ON CAPS.PSA_PERSON_LINK
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_PSA_PERSON_LINK
BEFORE INSERT
ON CAPS.PSA_PERSON_LINK
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:new.ID_PSA_PERSON_LINK is null OR :new.ID_PSA_PERSON_LINK = 0) THEN
		SELECT	SEQ_PSA_PERSON_LINK.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_PSA_PERSON_LINK := dummy;
	END IF;
END;
/

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };

--change 134 - R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) 
VALUES('CCHKTYPE','VSR','Vital Statistics Record'); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) 
VALUES('CCHKTYPE','SVS','SAVE System'); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) 
VALUES('CCHKTYPE','PCH','Prior CPS History'); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE) 
VALUES('CCHKTYPE','911','911 Check');

--change 136 - R2 ONLY
UPDATE CAPS.CODES_TABLES 
SET DECODE='Corrective Action Plan' 
WHERE code_type='CEVNTTYP' 
AND CODE='CRA'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Development Plan' 
WHERE code_type='CEVNTTYP' 
AND CODE='DVP'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Foster Care Redetermination' 
WHERE code_type='CEVNTTYP' 
AND CODE='FCR'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Payment of Care' 
WHERE code_type='CEVNTTYP' 
AND CODE='LOC'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Removal' 
WHERE code_type='CEVNTTYP' 
AND CODE='REM'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Service Authorization' 
WHERE code_type='CEVNTTYP' 
AND CODE='AUT'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Waiver' 
WHERE code_type='CEVNTTYP' 
AND CODE='VRN'; 

UPDATE CAPS.CODES_TABLES 
SET DECODE='Child Plan' 
WHERE code_type='CEVNTTYP' 
AND CODE='CSP'; 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'ADO', 'Adoption Information' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'CLH', 'Child Life History' ,SYSDATE );  

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'FFP', 'Family Foster Plan' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'FPL', 'Family Plan' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'FSR', 'Family Service Referral' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'NED', 'Needs and Outcomes' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'REL', 'Relative Care Assessment' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CEVNTTYP', 'TMR', 'Team Meeting Review' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CSTAGES', 'ONG', 'CPS Ongoing' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CSTAGES', 'AFC', 'Aftercare' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CSTAGES', 'FCC', 'Foster Care Child' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CSTAGES', 'FCF', 'Foster Care Family' ,SYSDATE ); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CSTAGES', 'PFC', 'Post Foster Care' ,SYSDATE ); 

-- change 137 R1/R2
UPDATE CAPS.CODES_TABLES SET DT_END = NULL WHERE CODE = 'SW' AND CODE_TYPE = 'CPHNTYP';

-- change 138 R1/R2
UPDATE CAPS.CODES_TABLES SET DT_END = TO_DATE('08/30/2006','MM/DD/YYYY') WHERE CODE = 'CDD' AND CODE_TYPE = 'CSPECREQ'; 
UPDATE CAPS.CODES_TABLES SET DT_END = TO_DATE('08/30/2006','MM/DD/YYYY') WHERE CODE = 'CAC' AND CODE_TYPE = 'CSPECREQ'; 
UPDATE CAPS.CODES_TABLES SET DT_END = TO_DATE('08/30/2006','MM/DD/YYYY') WHERE CODE = 'CLE' AND CODE_TYPE = 'CSPECREQ'; 
UPDATE CAPS.CODES_TABLES SET DT_END = TO_DATE('08/30/2006','MM/DD/YYYY') WHERE CODE = 'CST' AND CODE_TYPE = 'CSPECREQ'; 
UPDATE CAPS.CODES_TABLES SET DT_END = TO_DATE('08/30/2006','MM/DD/YYYY') WHERE CODE = 'CIC' AND CODE_TYPE = 'CSPECREQ'; 

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (103, 'SacwisRev2', 'New PSA_PERSON_LINK table, static updates');

commit;

