-- Release 2.5 

-- Standard Alter Table SQL

ALTER TABLE CAPS.EDUCATIONAL_HISTORY ADD TXT_SCH_REC_ON_FILE_CMNT VARCHAR2(500)     NULL
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00009104 
Insert into caps.MESSAGE (ID_MESSAGE,DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) values (0,sysdate,60428,'MSG_REC_NOT_INFILE_EDU_EXPL_REQ','Provide comments on why the school records are not in the child''s file.',700,500,'N');
Insert into caps.MESSAGE (ID_MESSAGE,DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) values (0,sysdate,60429,'MSG_SCH_CHNG_EXPL_REQ','Provide comments on school change due to placement change',760,500,'N');

-- change STGAP00009111
INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60430, 'MSG_SRP_DEL', 'A Safety Resource cannot be deleted unless all Child records are deleted', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60431, 'MSG_SRP_OVERLAP_1', 'Start date of the Safety Resource Placement cannot overlap the end date of the previous Safety Resource placement for child %s(%id).', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60432, 'MSG_SRP_OVERLAP_2', 'End date of the Safety Resource Placement cannot overlap the Start date of the next Safety Resource placement for child %s(%id).', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60433, 'MSG_SRP_START_EBEFORE_END', 'End Date cannot be before Start Date.', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60434, 'MSG_SRP_CUSTODY_REMOVAL', 'End Date cannot be after the Custody removal date for child %s(%id).', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60435, 'MSG_SRP_ONG_CLOSE', 'Ongoing cannot be closed while there is an open Safety Resource Placement.', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60436, 'MSG_SRP_CUSTODY_REM', 'The child is in a non-end dated safety resource placement.  End date safety resource placement before performing custody removal.', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60437, 'MSG_SRP_INV_CNCLSN', 'Investigation cannot be closed with a reason other than Risk Indicated - Open for Services when there is an Open Safety Resource Placement.', 700, 500, 'N');

INSERT INTO caps.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES (60438, 'MSG_SRP_PERSON_DELETE', 'The person is involved in a Safety Resource Placement and cannot be deleted.', 700, 500, 'N');

-- change STGAP00009117
-- Update CPA POC dropdown

UPDATE CAPS.CODES_TABLES SET DECODE = 'NTF', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CRBPROGA' AND CODE = 'g';

UPDATE CAPS.CODES_TABLES SET DECODE = 'MAAC', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CRBPROGA' AND CODE = 'h';

UPDATE CAPS.CODES_TABLES SET DECODE = 'PRTF', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGA' AND CODE = 'i';

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGA' AND CODE = 'j';

-- Update CCI POC drodown

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGI' AND CODE = 'd';

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGI' AND CODE = 'n';

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGI' AND CODE = 'm';

UPDATE CAPS.CODES_TABLES SET DECODE = 'PRTF', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGI' AND CODE = 'j';

UPDATE CAPS.CODES_TABLES SET DECODE = 'ICSP1', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGI' AND CODE = 'k';

UPDATE CAPS.CODES_TABLES SET DECODE = 'ICSP2', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRBPROGI' AND CODE = 'l';

-- Update CPA Contract

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-NTF', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601') 
AND SUBSTR(CODE,6,1) = 'g';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-MAAC', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601') 
AND SUBSTR(CODE,6,1) = 'h';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-PRTF', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601') 
AND SUBSTR(CODE,6,1) = 'i';

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60901','61001','61101','61301','61401','61601') 
AND SUBSTR(CODE,6,1) = 'j';

-- Update CCI Contract

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60501','60601','60701','60801','61201','61501') 
AND SUBSTR(CODE,6,1) = 'd';

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60501','60601','60701','60801','61201','61501') 
AND SUBSTR(CODE,6,1) = 'n';

UPDATE CAPS.CODES_TABLES SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60501','60601','60701','60801','61201','61501') 
AND SUBSTR(CODE,6,1) = 'm';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-PRTF', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60501','60601','60701','60801','61201','61501') 
AND SUBSTR(CODE,6,1) = 'j';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-ICSP1', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60501','60601','60701','60801','61201','61501') 
AND SUBSTR(CODE,6,1) = 'k';

UPDATE CAPS.CODES_TABLES SET DECODE = CODE||'-Per Diem-ICSP2', DT_LAST_UPDATE = SYSDATE 
WHERE CODE_TYPE = 'CSVCCODE' AND SUBSTR(CODE,1,5) IN ('60501','60601','60701','60801','61201','61501') 
AND SUBSTR(CODE,6,1) = 'l';


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (331, 'SacwisRev2', 'static table updates, new field for educational_history');                        
commit;
