--STGAP00014543 - Add Population Type to Youth Report Detail Table

alter table CAPS.YOUTH_REPORT_DTL add (CD_POPULATION_TYPE  varchar2(1));


--STGAP00014524 - MR-034 New Code type needed for Rerate batch

--Need new code types for Prior Period Adjustment (Rerate) batch program.

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','501','IV-E',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','502','IV-B',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','503','IN',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','529','IV-B Undocumented',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','560','IV-E Voluntary',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','574','IV-E',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','575','IV-E Voluntary',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','577','IV-B',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','579','IN',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','605','IV-E',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','606','IV-B',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','607','IN',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','608','IV-E Voluntary',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','609','IV-E',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','610','IV-B',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','611','IN',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','252','RF',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','460','CNTY',SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CUASELIG','450','CNTY',SYSDATE);



--STGAP00014533 - DBCR - PerSTGAP00014315 MR-033 new rows to fosterc

--Per MR - 033 STGAP00014315
--Add new rows to Foster_Care_Rate as per the table in CFIN04B Relative Care Invoicing Batch Design.

     insert into caps.foster_care_rate fcr
     (cd_fcare_rate_service, cd_age_range, amt_fcare_rt_unit_rate,
      dt_fcare_rt_end, dt_fcare_rt_start)
     values
     ('55399', '005', 88.82, '06/30/2010', '07/01/2009');

       insert into caps.foster_care_rate fcr
     (cd_fcare_rate_service, cd_age_range, amt_fcare_rt_unit_rate,
      dt_fcare_rt_end, dt_fcare_rt_start)
     values
     ('55399', '612', 100.38, '06/30/2010', '07/01/2009');

     insert into caps.foster_care_rate fcr
     (cd_fcare_rate_service, cd_age_range, amt_fcare_rt_unit_rate,
      dt_fcare_rt_end, dt_fcare_rt_start)
     values
     ('55399', '13P', 114.37, '06/30/2010', '07/01/2009');


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (489, 'SacwisRev3', 'Release 3.2 - DBCRs 14524,14533,14543');

commit;


