-- Date Created : Friday, April 20, 2007 18:07:58
-- Target DBMS : Oracle 10g
--

-- 
-- SEQUENCE: SACWISIFC.SEQ_ADOPT_TPR_OUTBOUND 
--

CREATE SEQUENCE SACWISIFC.SEQ_ADOPT_TPR_OUTBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_ADOPT_TPR_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_ADOPT_TPR_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_ADOPT_TPR_OUTBOUND TO CAPSBAT
;


-- 
-- SEQUENCE: SACWISIFC.SEQ_AGENCY_CUSTODIAL_PARENTS 
--

CREATE SEQUENCE SACWISIFC.SEQ_AGENCY_CUSTODIAL_PARENTS
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_AGENCY_CUSTODIAL_PARENTS TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_AGENCY_CUSTODIAL_PARENTS TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_AGENCY_CUSTODIAL_PARENTS TO CAPSBAT
;


-- 
-- SEQUENCE: SACWISIFC.SEQ_CHILDSUP_REF_OUTBOUND 
--

CREATE SEQUENCE SACWISIFC.SEQ_CHILDSUP_REF_OUTBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_CHILDSUP_REF_OUTBOUND TO CAPSBAT
;


-- 
-- SEQUENCE: SACWISIFC.SEQ_CSUP_CHILDLFTCARE_OUTBOUND 
--

CREATE SEQUENCE SACWISIFC.SEQ_CSUP_CHILDLFTCARE_OUTBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_CSUP_CHILDLFTCARE_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_CSUP_CHILDLFTCARE_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_CSUP_CHILDLFTCARE_OUTBOUND TO CAPSBAT
;


-- 
-- SEQUENCE: SACWISIFC.SEQ_CSUP_PARENT_OUTBOUND 
--

CREATE SEQUENCE SACWISIFC.SEQ_CSUP_PARENT_OUTBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_CSUP_PARENT_OUTBOUND TO CAPSBAT
;


-- 
-- TABLE: SACWISIFC.ADOPT_TPR_OUTBOUND 
--

CREATE TABLE SACWISIFC.ADOPT_TPR_OUTBOUND(
    ID_ADOPT_TPR_OUTBOUND    NUMBER(16, 0)    NOT NULL,
    DT_LAST_UPDATE           DATE             NOT NULL,
    INTERFACE_STATUS         VARCHAR2(3)      NOT NULL,
    DT_PROCESS               DATE,
    CD_ERROR                 VARCHAR2(10),
    ID_INITIATOR             NUMBER(16, 0)    NOT NULL,
    DT_ADOPTTPR_REQUESTED    DATE,
    NBR_CHILD_CRS_ID         NUMBER(9, 0)     NOT NULL,
    NBR_NCP_CRS_ID           NUMBER(9, 0)     NOT NULL,
    DT_TPR_FINALIZED         DATE,
    DT_ADOPT_FINALIZED       DATE,
    ID_CASE                  NUMBER(16, 0)    NOT NULL,
    CONSTRAINT PK_ADOPT_TPR_OUTBOUND PRIMARY KEY (ID_ADOPT_TPR_OUTBOUND)
    USING INDEX
TABLESPACE INDEX01
)
TABLESPACE DATA01
;



GRANT DELETE ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.ADOPT_TPR_OUTBOUND TO OPERATOR
;
GRANT DELETE ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.ADOPT_TPR_OUTBOUND TO CAPSBAT
;

-- 
-- TABLE: SACWISIFC.AGENCY_CUSTODIAL_PARENTS 
--

CREATE TABLE SACWISIFC.AGENCY_CUSTODIAL_PARENTS(
    ID_AGENCY_CUSTODIAL_PARENTS    NUMBER(16, 0)    NOT NULL,
    DT_LAST_UPDATE                 DATE             NOT NULL,
    CD_COUNTY                      VARCHAR2(3)      NOT NULL,
    NM_PERSON_LAST                 VARCHAR2(22),
    NM_PERSON_FIRST                VARCHAR2(12),
    NM_PERSON_MIDDLE               VARCHAR2(12),
    CD_PERSON_SEX                  VARCHAR2(1)      NOT NULL,
    CD_ETHNICITY                   VARCHAR2(2)      NOT NULL,
    CD_RACE                        VARCHAR2(2)      NOT NULL,
    NBR_CRS_ID                     NUMBER(9, 0),
    NBR_NCP_CRS_ID                 NUMBER(9, 0),
    CONSTRAINT PK_AGENCY_CUSTODIAL_PARENTS PRIMARY KEY (ID_AGENCY_CUSTODIAL_PARENTS)
    USING INDEX
TABLESPACE INDEX01
)
TABLESPACE DATA01
;



GRANT DELETE ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSON
;
GRANT INSERT ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSON
;
GRANT SELECT ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSON
;
GRANT UPDATE ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSON
;
GRANT SELECT ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO OPERATOR
;
GRANT DELETE ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPS
;
GRANT INSERT ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPS
;
GRANT SELECT ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPS
;
GRANT UPDATE ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPS
;
GRANT DELETE ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS TO CAPSBAT
;

-- 
-- TABLE: SACWISIFC.CHILDSUP_REF_OUTBOUND 
--

CREATE TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND(
    ID_CHILDSUP_REF_OUTBOUND        NUMBER(16, 0)    NOT NULL,
    DT_LAST_UPDATE                  DATE             NOT NULL,
    INTERFACE_STATUS                VARCHAR2(3)      NOT NULL,
    DT_PROCESS                      DATE,
    CD_ERROR                        VARCHAR2(10),
    ID_INITIATOR                    NUMBER(16, 0)    NOT NULL,
    SHINES_LOGON_SHORT              VARCHAR2(8),
    DT_CSUP_REQUESTED               DATE,
    ID_CASE                         NUMBER(16, 0)    NOT NULL,
    ID_STAGE                        NUMBER(16, 0)    NOT NULL,
    ID_CHILD                        NUMBER(16, 0)    NOT NULL,
    NBR_CHILD_CRS_ID                NUMBER(9, 0)     NOT NULL,
    IND_CHILD_PATERNITY_EST         VARCHAR2(1),
    NBR_PER_DIEM                    NUMBER(6, 2),
    NBR_PER_MONTH                   NUMBER(6, 2),
    DT_EFF_PER_DIEM                 DATE,
    IND_CHILD_SUPPORT_ORDER         VARCHAR2(1),
    CD_MED_COA                      VARCHAR2(2),
    ID_NONCUST_PARENT               NUMBER(16, 0)    NOT NULL,
    NBR_NONCUST_CRS_ID              NUMBER(9, 0)     NOT NULL,
    ADDR_NONCUST_ADDR_ST_LN_1       VARCHAR2(30),
    ADDR_NONCUST_ADDR_ST_LN_2       VARCHAR2(30),
    ADDR_NONCUST_ADDR_CITY          VARCHAR2(20),
    CD_NONCUST_ADDR_STATE           VARCHAR2(2),
    ADDR_NONCUST_ADDR_ZIP           VARCHAR2(10),
    TXT_INC_RSRC_DESC               VARCHAR2(80),
    TXT_INC_RSRC_SRC_ADDR_ST_LN1    VARCHAR2(30),
    TXT_INC_RSRC_SRC_ADDR_ST_LN2    VARCHAR2(30),
    TXT_INC_RSRC_SRC_ADDR_CITY      VARCHAR2(20),
    TXT_INC_RSRC_SRC_ADDR_STATE     VARCHAR2(2),
    TXT_INC_RSRC_SRC_ADDR_ZIP       VARCHAR2(10),
    IND_SSI_NONCUST                 VARCHAR2(1),
    CD_NONCUST_MARITAL_STATUS       VARCHAR2(2),
    ID_AGENCY_CUSTODIAL_PARENTS     NUMBER(16, 0)    NOT NULL,
    NBR_CUST_CRS_ID                 NUMBER(9, 0),
    CD_COUNTY                       VARCHAR2(3),
    ID_OFFICE                       NUMBER(16, 0),
    NM_OFFICE_NAME                  VARCHAR2(15),
    NM_CASEMANAGER_FIRST            VARCHAR2(12),
    NM_CASEMANAGER_MIDDLE           VARCHAR2(12),
    NM_CASEMANAGER_LAST             VARCHAR2(22),
    NBR_CASEMANAGER_PHONE           VARCHAR2(10),
    NBR_CASEMANAGER_FAX             VARCHAR2(10),
    ADDR_CASEMAN_ADDR_ST_LN_1       VARCHAR2(30),
    ADDR_CASEMAN_ADDR_ST_LN_2       VARCHAR2(30),
    ADDR_CASEMAN_ADDR_CITY          VARCHAR2(20),
    CD_CASEMAN_ADDR_STATE           VARCHAR2(2),
    ADDR_CASEMAN_ADDR_ZIP           VARCHAR2(10),
    CONSTRAINT PK_CHILDSUP_REF PRIMARY KEY (ID_CHILDSUP_REF_OUTBOUND)
    USING INDEX
TABLESPACE INDEX01
)
TABLESPACE DATA01
;



GRANT DELETE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO OPERATOR
;
GRANT DELETE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.CHILDSUP_REF_OUTBOUND TO CAPSBAT
;

-- 
-- TABLE: SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND 
--

CREATE TABLE SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND(
    ID_CSUP_CHLDLFTCARE_OUTBOUND    NUMBER(16, 0)    NOT NULL,
    DT_LAST_UPDATE                  DATE             NOT NULL,
    INTERFACE_STATUS                VARCHAR2(3)      NOT NULL,
    DT_PROCESS                      DATE,
    CD_ERROR                        VARCHAR2(10),
    ID_INITIATOR                    NUMBER(16, 0)    NOT NULL,
    DT_CHILDHOME_REQUESTED          DATE,
    NBR_CHILD_CRS_ID                NUMBER(9, 0)     NOT NULL,
    DT_LEFT_CARE                    DATE,
    CD_REASON_CODE                  VARCHAR2(2),
    ID_CASE                         NUMBER(16, 0)    NOT NULL,
    NM_FULL_NAME                    VARCHAR2(30),
    ADDR_PLCMT_CITY                 VARCHAR2(20),
    ADDR_PLCMT_LN1                  VARCHAR2(30),
    ADDR_PLCMT_LN2                  VARCHAR2(30),
    ADDR_PLCMT_ST                   VARCHAR2(2),
    ADDR_PLCMT_ZIP                  VARCHAR2(10),
    NBR_PLCMT_TELEPHONE             VARCHAR2(10),
    CONSTRAINT PK_CSUP_CHILDHOME_OUTBOUND PRIMARY KEY (ID_CSUP_CHLDLFTCARE_OUTBOUND)
    USING INDEX
TABLESPACE INDEX01
)
TABLESPACE DATA01
;


GRANT DELETE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO OPERATOR
;
GRANT DELETE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND TO CAPSBAT
;

-- 
-- TABLE: SACWISIFC.CSUP_PARENT_OUTBOUND 
--

CREATE TABLE SACWISIFC.CSUP_PARENT_OUTBOUND(
    ID_CSUP_PARENT_OUTBOUND         NUMBER(16, 0)    NOT NULL,
    DT_LAST_UPDATE                  DATE             NOT NULL,
    INTERFACE_STATUS                VARCHAR2(3)      NOT NULL,
    DT_PROCESS                      DATE,
    CD_ERROR                        VARCHAR2(10),
    ID_INITIATOR                    NUMBER(16, 0)    NOT NULL,
    DT_CSUPPAR_REQUESTED            DATE,
    NBR_CHILD_CRS_ID                NUMBER(9, 0)     NOT NULL,
    NBR_NONCUST_CRS_ID              NUMBER(9, 0)     NOT NULL,
    NM_NONCUST_LAST                 VARCHAR2(22),
    NM_NONCUST_FIRST                VARCHAR2(12),
    NM_NONCUST_MIDDLE               VARCHAR2(12),
    NBR_NONCUST_NUMBER              VARCHAR2(15),
    CD_CRS_NONCUST_RACE             VARCHAR2(1),
    DT_NONCUST_DOB                  DATE,
    IND_SSI_NONCUST                 VARCHAR2(1),
    ADDR_NONCUST_ADDR_ST_LN_1       VARCHAR2(30),
    ADDR_NONCUST_ADDR_ST_LN_2       VARCHAR2(30),
    ADDR_NONCUST_ADDR_CITY          VARCHAR2(20),
    CD_NONCUST_ADDR_STATE           VARCHAR2(2),
    ADDR_NONCUST_ADDR_ZIP           VARCHAR2(10),
    NBR_NONCUST_PHONE               VARCHAR2(10),
    TXT_INC_RSRC_DESC               VARCHAR2(80),
    TXT_INC_RSRC_SRC_ADDR_ST_LN1    VARCHAR2(30),
    TXT_INC_RSRC_SRC_ADDR_ST_LN2    VARCHAR2(30),
    TXT_INC_RSRC_SRC_ADDR_CITY      VARCHAR2(20),
    TXT_INC_RSRC_SRC_ADDR_STATE     VARCHAR2(2),
    TXT_INC_RSRC_SRC_ADDR_ZIP       VARCHAR2(10),
    ID_CASE                         NUMBER(16, 0)    NOT NULL,
    NBR_PER_DIEM                    NUMBER(6, 2),
    NBR_PER_MONTH                   NUMBER(6, 2),
    DT_EFF_PER_DIEM                 DATE,
    CD_MED_CLASS_ASST               VARCHAR2(3),
    NM_CASEMAN_LAST                 VARCHAR2(22),
    NM_CASEMAN_FIRST                VARCHAR2(12),
    NM_CASEMAN_MIDDLE               VARCHAR2(12),
    ADDR_CASEMAN_ADDR_ST_LN_1       VARCHAR2(30),
    ADDR_CASEMAN_ADDR_ST_LN_2       VARCHAR2(30),
    ADDR_CASEMAN_ADDR_CITY          VARCHAR2(20),
    CD_CASEMAN_ADDR_STATE           VARCHAR2(2),
    ADDR_CASEMAN_ADDR_ZIP           VARCHAR2(10),
    NBR_CASEMAN_PHONE               VARCHAR2(10),
    NBR_CASEMAN_FAX                 VARCHAR2(10),
    CONSTRAINT PK_CSUP_PARENT_OUTBOUND PRIMARY KEY (ID_CSUP_PARENT_OUTBOUND)
)
TABLESPACE DATA01
;



GRANT DELETE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO OPERATOR
;
GRANT DELETE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.CSUP_PARENT_OUTBOUND TO CAPSBAT
;

-- 
-- INDEX: SACWISIFC.IND_AGENCY_CUST_PARENTS_2 
--

CREATE INDEX SACWISIFC.IND_AGENCY_CUST_PARENTS_2 ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS(NBR_CRS_ID)
TABLESPACE INDEX01
;
-- 
-- INDEX: SACWISIFC.IND_AGENCY_CUST_PARENTS_1 
--

CREATE INDEX SACWISIFC.IND_AGENCY_CUST_PARENTS_1 ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS(NBR_NCP_CRS_ID)
TABLESPACE INDEX01
;
-- 
-- TABLE: SACWISIFC.CHILDSUP_REF_OUTBOUND 
--

ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND ADD CONSTRAINT FK_AG_CUST_PAR_CSUP_REF 
    FOREIGN KEY (ID_AGENCY_CUSTODIAL_PARENTS)
    REFERENCES SACWISIFC.AGENCY_CUSTODIAL_PARENTS(ID_AGENCY_CUSTODIAL_PARENTS)
;


-- 
-- TRIGGER: SACWISIFC.TIBR_ADOPT_TPR_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_ADOPT_TPR_OUTBOUND
BEFORE INSERT
ON SACWISIFC.ADOPT_TPR_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:NEW.ID_ADOPT_TPR_OUTBOUND IS NULL OR :new.ID_ADOPT_TPR_OUTBOUND = 0) THEN
		SELECT	SEQ_ADOPT_TPR_OUTBOUND.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_ADOPT_TPR_OUTBOUND := dummy;
	END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: SACWISIFC.TUBR_ADOPT_TPR_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_ADOPT_TPR_OUTBOUND
BEFORE UPDATE
ON SACWISIFC.ADOPT_TPR_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: SACWISIFC.TIBR_AGENCY_CUSTODIAL_PARENTS 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_AGENCY_CUSTODIAL_PARENTS
BEFORE INSERT
ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:NEW.ID_AGENCY_CUSTODIAL_PARENTS IS NULL OR :new.ID_AGENCY_CUSTODIAL_PARENTS = 0) THEN
		SELECT	SEQ_AGENCY_CUSTODIAL_PARENTS.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_AGENCY_CUSTODIAL_PARENTS := dummy;
	END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: SACWISIFC.TUBR_AGENCY_CUSTODIAL_PARENTS 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_AGENCY_CUSTODIAL_PARENTS
BEFORE UPDATE
ON SACWISIFC.AGENCY_CUSTODIAL_PARENTS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: SACWISIFC.TIBR_CHILDSUP_REF_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_CHILDSUP_REF_OUTBOUND
BEFORE INSERT
ON SACWISIFC.CHILDSUP_REF_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:NEW.ID_CHILDSUP_REF_OUTBOUND IS NULL OR :new.ID_CHILDSUP_REF_OUTBOUND = 0) THEN
		SELECT	SEQ_CHILDSUP_REF_OUTBOUND.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_CHILDSUP_REF_OUTBOUND := dummy;
	END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: SACWISIFC.TUBR_CHILDSUP_REF_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_CHILDSUP_REF_OUTBOUND
BEFORE UPDATE
ON SACWISIFC.CHILDSUP_REF_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: TIBR_CSUP_CHLDLFTCARE_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_CSUP_CHLDLFTCARE_OUTBOUND
BEFORE INSERT
ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:NEW.ID_CSUP_CHLDLFTCARE_OUTBOUND IS NULL OR :new.ID_CSUP_CHLDLFTCARE_OUTBOUND = 0) THEN
		SELECT	SEQ_CSUP_CHILDLFTCARE_OUTBOUND.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_CSUP_CHLDLFTCARE_OUTBOUND := dummy;
	END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: TUBR_CSUP_CHLDLFTCARE_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_CSUP_CHLDLFTCARE_OUTBOUND
BEFORE UPDATE
ON SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: SACWISIFC.TIBR_CSUP_PARENT_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_CSUP_PARENT_OUTBOUND
BEFORE INSERT
ON SACWISIFC.CSUP_PARENT_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:NEW.ID_CSUP_PARENT_OUTBOUND IS NULL OR :new.ID_CSUP_PARENT_OUTBOUND = 0) THEN
		SELECT	SEQ_CSUP_PARENT_OUTBOUND.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_CSUP_PARENT_OUTBOUND := dummy;
	END IF;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- 
-- TRIGGER: TUBR_CSUP_PARENT_OUTBOUND 
--
/
-- BEGIN PL/SQL BLOCK (do not remove this line) -------------------------------- 
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_CSUP_PARENT_OUTBOUND
BEFORE UPDATE
ON SACWISIFC.CSUP_PARENT_OUTBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END; 
-- END PL/SQL BLOCK (do not remove this line) ---------------------------------- 
/ 

-- Create Synonyms
create synonym CAPS.ADOPT_TPR_OUTBOUND for SACWISIFC.ADOPT_TPR_OUTBOUND;
create synonym CAPS.AGENCY_CUSTODIAL_PARENTS for SACWISIFC.AGENCY_CUSTODIAL_PARENTS;
create synonym CAPS.CHILDSUP_REF_OUTBOUND for SACWISIFC.CHILDSUP_REF_OUTBOUND;
create synonym CAPS.CSUP_CHILDLEFTCARE_OUTBOUND for SACWISIFC.CSUP_CHILDLEFTCARE_OUTBOUND;
create synonym CAPS.CSUP_PARENT_OUTBOUND for SACWISIFC.CSUP_PARENT_OUTBOUND;


-- Standard Alter Table SQL

ALTER TABLE CAPS.CHILD_SUPPORT ADD NBR_COUNTY_CRS_ID NUMBER(9)     NULL
;
COMMENT ON COLUMN CAPS.CHILD_SUPPORT.NBR_COUNTY_CRS_ID IS
'This is the Client Identifier obtained from CRS (Client Repository System) which is used in state of Georgia applications.'
;
ALTER TABLE CAPS.CHILD_SUPPORT ADD NBR_NCP_CRS_ID NUMBER(9)     NULL
;
COMMENT ON COLUMN CAPS.CHILD_SUPPORT.NBR_NCP_CRS_ID IS
'This is the Client Identifier obtained from CRS (Client Repository System) which is used in state of Georgia applications.'
;
ALTER TABLE CAPS.CHILD_SUPPORT ADD NBR_CHECK NUMBER(10)     NULL
;
COMMENT ON COLUMN CAPS.CHILD_SUPPORT.NBR_CHECK IS
'The number of the check associated with a payment'
;
ALTER TABLE CAPS.INCOME_AND_RESOURCES ADD AU_NUMBER NUMBER(9)     NULL
;
ALTER TABLE CAPS.INCOME_AND_RESOURCES ADD AU_STATUS VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.INCOME_AND_RESOURCES ADD CASE_LOAD_NUMBER VARCHAR2(4)     NULL
;
ALTER TABLE CAPS.INCOME_AND_RESOURCES ADD CD_PROGRAM_TYPE VARCHAR2(2)     NULL
;
ALTER TABLE CAPS.POLICY_WAIVER MODIFY(CD_WVR_SVC_DESC  VARCHAR2(6))
;



{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00002033
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60310, 'MSG_CRS_ID_NOT_FND','Please assign a CRS ID to the client via the Person Detail page',500,700,'N');

-- change STGAP00002035
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60311, 'MSG_INV_WVR_SVCDESC'
,'Units must be specified for this service',760,500,'N');

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (160, 'SacwisRev2', 'static updates, STARS schema, other table changes');  
                         
commit;
