
-- Standard Alter Table SQL

ALTER TABLE CAPS.ADO_INFO_CBX ADD CD_CBX_CODE_TYPE VARCHAR2(8)     NULL
;
ALTER TABLE CAPS.FCE_APPLICATION ADD IND_PROOF_CHILD_ID_SENT_ES VARCHAR2(1)     NULL
;
ALTER TABLE CAPS.FCE_APPLICATION ADD DT_PROOF_CHILD_ID_SENT_ES DATE     NULL
;
ALTER TABLE CAPS.FCE_APPLICATION ADD TXT_PROOF_CHILD_ID_SENT_ES VARCHAR2(300)     NULL
;
ALTER TABLE CAPS.FCE_APPLICATION ADD DT_PROOF_PREGNANCY_SENT_ES DATE     NULL
;
ALTER TABLE CAPS.FCE_APPLICATION ADD TXT_EMPLOYEE_COMMENTS VARCHAR2(300)     NULL
;

-- Drop Referencing Constraint SQL


-- Drop Constraint, Rename and Create Table SQL

ALTER TABLE CAPS.FCE_THIRD_PARTY_INSURANCE DROP CONSTRAINT FK_FCE_3RD_PART_INS_APP
;
ALTER TABLE CAPS.FCE_THIRD_PARTY_INSURANCE DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE CAPS.FCE_THIRD_PARTY_INSURANCE RENAME TO FCE_THIRD__02212007170002000
;
CREATE TABLE CAPS.FCE_THIRD_PARTY_INSURANCE
(
    ID_FCE_APPLICATION NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE     DATE         NOT NULL,
    IND_CHILD_COVERAGE VARCHAR2(1)      NULL,
    CD_TYPE            VARCHAR2(3)      NULL,
    NM_COMPANY         VARCHAR2(50)     NULL,
    NBR_POLICY         VARCHAR2(20)     NULL,
    NBR_GROUP          VARCHAR2(20)     NULL,
    ADDR_STREET_LN1    VARCHAR2(30)     NULL,
    ADDR_STREET_LN2    VARCHAR2(30)     NULL,
    ADDR_CITY          VARCHAR2(20)     NULL,
    ADDR_STATE         VARCHAR2(2)      NULL,
    ADDR_ZIP           VARCHAR2(10)     NULL,
    NBR_PHONE          VARCHAR2(10)     NULL,
    DT_BEGIN           DATE             NULL,
    DT_END             DATE             NULL,
    NM_EMPLOYER        VARCHAR2(50)     NULL,
    NM_EMPLOYEE_NAME   VARCHAR2(50)     NULL,
    IND_AUTH_RELEASE   VARCHAR2(1)      NULL,
    IND_AUTH_ASSIGN    VARCHAR2(1)      NULL,
    DT_AUTH_RELEASE    DATE             NULL,
    DT_AUTH_ASSIGN     DATE             NULL,
    IND_CHANGE_CANCEL  VARCHAR2(1)      NULL,
    DT_CHANGE_CANCEL   DATE             NULL,
    NM_POLICY_HOLDER   VARCHAR2(50)     NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE CAPS.FCE_THIRD_PARTY_INSURANCE IS
'Foster Care table documenting if the child had other insurance'
;
COMMENT ON COLUMN CAPS.FCE_THIRD_PARTY_INSURANCE.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSBAT
;
GRANT INSERT ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSBAT
;
GRANT SELECT ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSBAT
;
GRANT UPDATE ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSBAT
;
GRANT DELETE ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSON
;
GRANT INSERT ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSON
;
GRANT SELECT ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSON
;
GRANT UPDATE ON CAPS.FCE_THIRD_PARTY_INSURANCE TO CAPSON
;
GRANT SELECT ON CAPS.FCE_THIRD_PARTY_INSURANCE TO OPERATOR
;
ALTER TABLE CAPS.PAYMENT_OF_CARE DROP CONSTRAINT FK_PAYMENT_OF_CARE_RESOURCE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE DROP CONSTRAINT FK_PAYMT_OF_CARE_EVENT
;
ALTER TABLE CAPS.PAYMENT_OF_CARE DROP CONSTRAINT FK_POC_CM_PACK_CMP_PERSON
;
ALTER TABLE CAPS.PAYMENT_OF_CARE DROP CONSTRAINT FK_POC_RBWO_REV_AP_PERSON
;
ALTER TABLE CAPS.PAYMENT_OF_CARE DROP CONSTRAINT FK_POC_SO_APRV_PERSON
;
ALTER TABLE CAPS.PAYMENT_OF_CARE DROP CONSTRAINT FK_POC_SPV_PACK_APRV_PERSON
;
ALTER TABLE CAPS.PAYMENT_OF_CARE DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE CAPS.PAYMENT_OF_CARE RENAME TO PAYMENT_OF_02212007170003000
;
CREATE TABLE CAPS.PAYMENT_OF_CARE
(
    ID_POC_EVENT       NUMBER(16)    NOT NULL,
    DT_LAST_UPDATE     DATE          NOT NULL,
    CD_POC_TYPE        VARCHAR2(3)       NULL,
    DT_START           DATE          NOT NULL,
    DT_END             DATE              NULL,
    DT_TERMINATE       DATE              NULL,
    NBR_PER_DIEM       NUMBER(6,2)       NULL,
    NBR_SPEC_PER_DIEM  NUMBER(4,2)       NULL,
    IND_CONCURRENT     VARCHAR2(1)       NULL,
    TXT_CONCUR_P_DIEM  VARCHAR2(300)     NULL,
    TXT_SPEC_PER_DIEM  VARCHAR2(300)     NULL,
    IND_RBWO_TYPE      VARCHAR2(1)       NULL,
    CD_RBWO            VARCHAR2(2)       NULL,
    DT_PACKET_COMP     DATE              NULL,
    ID_CM_PACKET_COMP  NUMBER(16)        NULL,
    DT_PACKET_APRV     DATE              NULL,
    ID_SPV_PACKET_APRV NUMBER(16)        NULL,
    DT_PACKET_SENT     DATE              NULL,
    DT_STAFF_COMPL     DATE              NULL,
    DT_SO_RESP         DATE              NULL,
    ID_SO_APRV         NUMBER(16)        NULL,
    DT_RBWO_APRV       DATE              NULL,
    ID_RBWO_REV_APRV   NUMBER(16)        NULL,
    DT_RBWO_SUM_REV    DATE              NULL,
    ID_RESOURCE        NUMBER(16)    NOT NULL,
    IND_RCS_TYPE       VARCHAR2(1)       NULL,
    DT_AGREEMENT       DATE              NULL,
    DT_ANN_REVIEW      DATE              NULL,
    DT_COURT           DATE              NULL,
    IND_INCOME         VARCHAR2(1)       NULL,
    IND_TERMINATE      VARCHAR2(1)       NULL,
    IND_SUSPEND        VARCHAR2(1)       NULL,
    TXT_TERMINATE      VARCHAR2(300)     NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE CAPS.PAYMENT_OF_CARE IS
'Records details of a client''s payment of care details for paid placements'
;
COMMENT ON COLUMN CAPS.PAYMENT_OF_CARE.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON CAPS.PAYMENT_OF_CARE TO CAPSBAT
;
GRANT INSERT ON CAPS.PAYMENT_OF_CARE TO CAPSBAT
;
GRANT SELECT ON CAPS.PAYMENT_OF_CARE TO CAPSBAT
;
GRANT UPDATE ON CAPS.PAYMENT_OF_CARE TO CAPSBAT
;
GRANT DELETE ON CAPS.PAYMENT_OF_CARE TO CAPSON
;
GRANT INSERT ON CAPS.PAYMENT_OF_CARE TO CAPSON
;
GRANT SELECT ON CAPS.PAYMENT_OF_CARE TO CAPSON
;
GRANT UPDATE ON CAPS.PAYMENT_OF_CARE TO CAPSON
;
GRANT SELECT ON CAPS.PAYMENT_OF_CARE TO OPERATOR
;

-- Insert Data SQL

ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO CAPS.FCE_THIRD_PARTY_INSURANCE(
                                           ID_FCE_APPLICATION,
                                           DT_LAST_UPDATE,
                                           IND_CHILD_COVERAGE,
                                           CD_TYPE,
                                           NM_COMPANY,
                                           NBR_POLICY,
                                           NBR_GROUP,
                                           ADDR_STREET_LN1,
                                           ADDR_STREET_LN2,
                                           ADDR_CITY,
                                           ADDR_STATE,
                                           ADDR_ZIP,
                                           NBR_PHONE,
                                           DT_BEGIN,
                                           DT_END,
                                           NM_EMPLOYER,
                                           NM_EMPLOYEE_NAME,
                                           IND_AUTH_RELEASE,
                                           IND_AUTH_ASSIGN,
                                           DT_AUTH_RELEASE,
                                           DT_AUTH_ASSIGN,
                                           IND_CHANGE_CANCEL,
                                           DT_CHANGE_CANCEL,
                                           NM_POLICY_HOLDER
                                          )
                                    SELECT 
                                           ID_FCE_APPLICATION,
                                           DT_LAST_UPDATE,
                                           IND_CHILD_COVERAGE,
                                           CD_TYPE,
                                           NM_COMPANY,
                                           NBR_POLICY,
                                           NBR_GROUP,
                                           ADDR_STREET_LN1,
                                           ADDR_STREET_LN2,
                                           ADDR_CITY,
                                           ADDR_STATE,
                                           ADDR_ZIP,
                                           NBR_PHONE,
                                           DT_BEGIN,
                                           DT_END,
                                           NM_EMPLOYER,
                                           NM_EMPLOYEE_NAME,
                                           IND_AUTH_RELEASE,
                                           IND_AUTH_ASSIGN,
                                           DT_AUTH_RELEASE,
                                           DT_AUTH_ASSIGN,
                                           IND_CHANGE_CANCEL,
                                           DT_CHANGE_CANCEL,
                                           NULL
                                      FROM CAPS.FCE_THIRD__02212007170002000 
;
COMMIT
;
ALTER TABLE CAPS.FCE_THIRD_PARTY_INSURANCE LOGGING
;
ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO CAPS.PAYMENT_OF_CARE(
                                 ID_POC_EVENT,
                                 DT_LAST_UPDATE,
                                 CD_POC_TYPE,
                                 DT_START,
                                 DT_END,
                                 DT_TERMINATE,
                                 NBR_PER_DIEM,
                                 NBR_SPEC_PER_DIEM,
                                 IND_CONCURRENT,
                                 TXT_CONCUR_P_DIEM,
                                 TXT_SPEC_PER_DIEM,
                                 IND_RBWO_TYPE,
                                 CD_RBWO,
                                 DT_PACKET_COMP,
                                 ID_CM_PACKET_COMP,
                                 DT_PACKET_APRV,
                                 ID_SPV_PACKET_APRV,
                                 DT_PACKET_SENT,
                                 DT_STAFF_COMPL,
                                 DT_SO_RESP,
                                 ID_SO_APRV,
                                 DT_RBWO_APRV,
                                 ID_RBWO_REV_APRV,
                                 DT_RBWO_SUM_REV,
                                 ID_RESOURCE,
                                 IND_RCS_TYPE,
                                 DT_AGREEMENT,
                                 DT_ANN_REVIEW,
                                 DT_COURT,
                                 IND_INCOME,
                                 IND_TERMINATE,
                                 IND_SUSPEND,
                                 TXT_TERMINATE
                                )
                          SELECT 
                                 ID_POC_EVENT,
                                 DT_LAST_UPDATE,
                                 CD_POC_TYPE,
                                 DT_START,
                                 DT_END,
                                 DT_TERMINATE,
                                 NBR_PER_DIEM,
                                 NBR_SPEC_PER_DIEM,
                                 IND_CONCURRENT,
                                 TXT_CONCUR_P_DIEM,
                                 TXT_SPEC_PER_DIEM,
                                 IND_RBWO_TYPE,
                                 CD_RBWO,
                                 DT_PACKET_COMP,
                                 ID_CM_PACKET_COMP,
                                 DT_PACKET_APRV,
                                 ID_SPV_PACKET_APRV,
                                 DT_PACKET_SENT,
                                 DT_STAFF_COMPL,
                                 DT_SO_RESP,
                                 ID_SO_APRV,
                                 DT_RBWO_APRV,
                                 ID_RBWO_REV_APRV,
                                 DT_RBWO_SUM_REV,
                                 ID_RESOURCE,
                                 IND_RCS_TYPE,
                                 DT_AGREEMENT,
                                 DT_ANN_REVIEW,
                                 DT_COURT,
                                 IND_INCOME,
                                 IND_TERMINATE,
                                 IND_SUSPEND,
                                 TXT_TERMINATE
                            FROM CAPS.PAYMENT_OF_02212007170003000 
;
COMMIT
;
ALTER TABLE CAPS.PAYMENT_OF_CARE LOGGING
;

-- Add Constraint SQL

ALTER TABLE CAPS.FCE_THIRD_PARTY_INSURANCE ADD CONSTRAINT PK_FCE_THIRD_PARTY_INSURANCE
PRIMARY KEY (ID_FCE_APPLICATION)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 1M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD CONSTRAINT PK_PAYMENT_OF_CARE
PRIMARY KEY (ID_POC_EVENT)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 1M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;

-- Add Indexes SQL


-- Add Dependencies SQL
/
DROP TRIGGER CAPS.TIBR_FCE_THIRD_PARTY_INSURANCE
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_FCE_THIRD_PARTY_INSURANCE
BEFORE INSERT
ON CAPS.FCE_THIRD_PARTY_INSURANCE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
DROP TRIGGER CAPS.TUBR_FCE_THIRD_PARTY_INSURANCE
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_FCE_THIRD_PARTY_INSURANCE
BEFORE UPDATE
ON CAPS.FCE_THIRD_PARTY_INSURANCE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
DROP TRIGGER CAPS.TIBR_PAYMENT_OF_CARE
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_PAYMENT_OF_CARE
BEFORE INSERT
ON CAPS.PAYMENT_OF_CARE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
DROP TRIGGER CAPS.TUBR_PAYMENT_OF_CARE
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_PAYMENT_OF_CARE
BEFORE UPDATE
ON CAPS.PAYMENT_OF_CARE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/


-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.FCE_THIRD_PARTY_INSURANCE ADD CONSTRAINT FK_FCE_3RD_PART_INS_APP
FOREIGN KEY (ID_FCE_APPLICATION)
REFERENCES CAPS.FCE_APPLICATION (ID_FCE_APPLICATION)
ENABLE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD CONSTRAINT FK_PAYMENT_OF_CARE_RESOURCE
FOREIGN KEY (ID_RESOURCE)
REFERENCES CAPS.CAPS_RESOURCE (ID_RESOURCE)
ENABLE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD CONSTRAINT FK_PAYMT_OF_CARE_EVENT
FOREIGN KEY (ID_POC_EVENT)
REFERENCES CAPS.EVENT (ID_EVENT)
ENABLE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD CONSTRAINT FK_POC_CM_PACK_CMP_PERSON
FOREIGN KEY (ID_CM_PACKET_COMP)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD CONSTRAINT FK_POC_RBWO_REV_AP_PERSON
FOREIGN KEY (ID_RBWO_REV_APRV)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD CONSTRAINT FK_POC_SO_APRV_PERSON
FOREIGN KEY (ID_SO_APRV)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;
ALTER TABLE CAPS.PAYMENT_OF_CARE ADD CONSTRAINT FK_POC_SPV_PACK_APRV_PERSON
FOREIGN KEY (ID_SPV_PACKET_APRV)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;

DROP TABLE CAPS.PAYMENT_OF_02212007170003000;
DROP TABLE CAPS.FCE_THIRD__02212007170002000;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };

--change STGAP00001579  - the stuff I left out by accident
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '252', '252 - Children Restricted Funds');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '253', '253 - Donated Restricted Funds');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '450', '450 - County Funds - Foster Care Children under age 14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '460', '460 - County Funds - Foster Care Children 14 and over');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '501', '501 - IV-E Family Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '502', '502 - State Family Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '503', '503 - Initial Family Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '504', '504 - State Related Family Foster Care ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '505', '505 - IV-E Institutional Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '506', '506 - State Child Welfare - Institutional Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '507', '507 - Initial TANF Institutional Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '508', '508 - State Adoption Assistance');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '509', '509 - IV-E Adoption Assistance');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '510', '510 - Adoption Related State Expenses');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '511', '511 - Comprehensive child and Family assessment');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '512', '512 - Special Services Adoption Assistance');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '513', '513 - Return of Runaways');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '518', '518 - CCFA Wrap Around Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '520', '520 - Respite Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '521', '521 - PUP ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '522', '522 - State CW Family Foster Care ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '525', '525 - Medical Exams and Records');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '529', '529 - Undocumented Immigrant Children in Family Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '530', '530 - State undocumented Immigrant Children in IFC');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '531', '531 - Foster/Adoptive Parent Support Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '542', '542 - Enhanced Relative Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '547', '547 - Emergency Foster Care Beds');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '550', '550 - Non-Relative Subsidized Guardianship and Enhanced Subsidized Guardianship');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '551', '551 - Early Intervention and Prevention Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '552', '552 - Subsidized Guardianship and Enhanced Subsidized Guardianship');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '553', '553 - Relative Care Subsidy RCS');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '560', '560 - IV-E Voluntary Family Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '561', '561 - IV-E Voluntary Institutional Foster Care (CCI)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '563', '563 - Iv-E Privately Supervised Family Foster Care (CPA)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '564', '564 - IV-B Privately Supervised Family Foster Care (CPA)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '565', '565 - Initial Privately Supervised Family Foster Care (CPA)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '571', '571 - Homestead Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '573', '573 - Parent Aide Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '574', '574 - Specialized Foster Care - State Approved Per Diem Waivers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '575', '575 - IV-E Voluntary Specialized Foster Care - State Approve Per Diem Waivers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '576', '576 - State Related Specialized Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '577', '577 - IV-B Child Welfare Specialized Foster Care - State Approve Per Diem Waivers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '578', '578 - State Child Welfare Related Specialized Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '579', '579 - Initial Child Welfare Specialized Foster Care - State Approve Per Diem Waivers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '583', '583 - College Related Expenses');

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '25200', '252');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '25201', '252');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '25204', '252');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '25210', '252');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '25217', '252');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '25300', '253');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45000', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45001', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45004', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45010', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45017', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45091', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45092', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45093', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45094', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45095', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45096', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45097', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45098', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '45099', '450');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46000', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46001', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46004', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46010', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46017', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46091', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46092', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46093', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46094', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46095', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46096', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46097', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46098', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '46099', '460');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50101', '501');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50102', '501');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50104', '501');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50105', '501');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50117', '501');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50201', '502');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50202', '502');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50204', '502');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50205', '502');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50208', '502');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50217', '502');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50301', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50302', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50304', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50305', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50308', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50311', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50317', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50399', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50411', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50501', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50504', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50600', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50601', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50604', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50608', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50699', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50701', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50704', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50708', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50807', '508');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50813', '508');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50913', '509');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51100', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51112', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51119', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51154', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51217', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51257', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51260', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51277', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51800', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51812', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51880', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52060', '520');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52094', '520');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52149', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52150', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52151', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52152', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52153', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52154', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52211', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52299', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52519', '525');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52520', '525');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52901', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52902', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52904', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52905', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52908', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52911', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52917', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52999', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53000', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53001', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53004', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53008', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53011', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53099', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53167', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54201', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54204', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54205', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54207', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54217', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54796', '547');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54797', '547');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55201', '552');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55205', '552');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55207', '552');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55281', '552');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55282', '552');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55301', '553');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55305', '553');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55307', '553');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55381', '553');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55382', '553');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56001', '560');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56002', '560');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56004', '560');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56005', '560');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56017', '560');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56100', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56101', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56104', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56301', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56304', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56305', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56317', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56399', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56401', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56402', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56404', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56405', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56417', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56499', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56501', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56502', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56504', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56505', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56517', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '56599', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57162', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57401', '574');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57402', '574');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57404', '574');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57405', '574');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57417', '574');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57499', '574');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57501', '575');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57502', '575');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57504', '575');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57505', '575');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57517', '575');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57599', '575');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57600', '576');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57611', '576');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57699', '576');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57701', '577');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57702', '577');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57704', '577');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57705', '577');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57708', '577');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57717', '577');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57799', '577');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57800', '578');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57811', '578');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57899', '578');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57901', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57902', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57904', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57905', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57908', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57911', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57917', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57999', '579');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58580', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58629', '586');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58678', '586');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58770', '587');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58886', '588');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60400', '604');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60411', '604');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60499', '604');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60501', '605');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60601', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60604', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60608', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60699', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60701', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60704', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60801', '608');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60804', '608');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60901', '609');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60904', '609');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60905', '609');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60917', '609');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61001', '610');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61004', '610');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61005', '610');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61017', '610');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61101', '611');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61104', '611');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61105', '611');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '61117', '611');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '69841', '698');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '77324', '773');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '77373', '773');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '77474', '774');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '78383', '783');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '78457', '784');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '78484', '784');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '87324', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88484', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '501SB', '501');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '502SB', '502');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50300a', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50300b', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50300c', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50310a', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50310b', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50310c', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50310d', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '503SB            ', '503');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50400a', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50400b', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50400c', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50400d', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50410a', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50410b', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50410c', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50410d', '504');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '505A3', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '505L1', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '505L2', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '505L3', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '505L4', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '505L5', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '505L6', '505');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50610a', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50610b', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50610c', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50610d', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '506A3', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '506L1', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '506L2', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '506L3', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '506L4', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '506L5', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '506L6', '506');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50700a', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50700b', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50700c', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50710a', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50710b', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50710c', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '50710d', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '507A3', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '507L1', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '507L2', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '507L3', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '507L4', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '507L5', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '507L6', '507');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51033a', '510');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51033b', '510');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51033c', '510');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51033d', '510');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51033e', '510');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51033f', '510');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129a', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129b', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129c', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129d', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129e', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129f', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129g', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129h', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129i', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129j', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51129k', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51188a', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51188b', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '511A3', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '511L1', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '511L2', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '511L3', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '511L4', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '511L5', '511');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51258a', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51258b', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51258c', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51258d', '512');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51312a', '513');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51312b', '513');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51312c', '513');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51312d', '513');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51824a', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51824b', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51824c', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51847a', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51847b', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51847c', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51856a', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51856b', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51871a', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51871b', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51871c', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51888a', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51888b', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51895a', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '51895b', '518');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52148a', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52148b', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52148c', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52148d', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52148e', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52148f', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52156a', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52156b', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52156c', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52156d', '521');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52200a', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52200b', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52200c', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52200d', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52200e', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52210a', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52210b', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52210c', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52210d', '522');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52910a', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52910b', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52910c', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '52910d', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '529SB', '529');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53010a', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53010b', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53010c', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53010d', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '530A3', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '530L1', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '530L2', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '530L3', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '530L4', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '530L5', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '530L6', '530');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53106a', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53106b', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53106c', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53106d', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53106e', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53106f', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53106g', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53168a', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53168b', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '53168c', '531');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54210a', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54210b', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54210c', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '54210d', '542');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55179a', '551');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55179b', '551');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55179c', '551');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '55179d', '551');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '560SB', '560');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '561A3', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '561L1', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '561L2', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '561L3', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '561L4', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '561L5', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '561L6', '561');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '563A3', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '563L1', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '563L2', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '563L3', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '563L4', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '563L5', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '563L6', '563');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '564A3', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '564L1', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '564L2', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '564L3', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '564L4', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '564L5', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '564L6', '564');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '565A3', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '565L1', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '565L2', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '565L3', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '565L4', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '565L5', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '565L6', '565');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57129a', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57129b', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57129c', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57161a', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57161b', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57161c', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57161d', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57161e', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57161f', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57161g', '571');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372a', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372b', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372c', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372d', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372e', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372f', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57372g', '573');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57610a', '576');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57610b', '576');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57610c', '576');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57610d', '576');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57810a', '578');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57810b', '578');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57810c', '578');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '57810d', '578');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375a', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375b', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375c', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375d', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375e', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375f', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375g', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58375h', '583');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475a', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475b', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475c', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475d', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475e', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475f', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475g', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475h', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58475i', '584');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576a', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576b', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576c', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576d', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576e', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576f', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576g', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576h', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576i', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576j', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576k', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576l', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58576m', '585');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58885a', '588');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '58885b', '588');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175a', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175b', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175c', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175d', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175e', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175f', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175g', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '59175h', '591');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '595A3', '595');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '595L1', '595');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '595L2', '595');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '595L3', '595');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '595L4', '595');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '595L5', '595');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '595L6', '595');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '596A3', '596');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '596L1', '596');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '596L2', '596');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '596L3', '596');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '596L4', '596');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '596L5', '596');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '596L6', '596');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '597W1', '597');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '597W2', '597');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '598W1', '598');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '598W2', '598');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60410a', '604');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60410b', '604');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60410c', '604');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60410d', '604');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60600a', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60600b', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60600c', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60600d', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60610a', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60610b', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60610c', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60610d', '606');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60700a', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60700b', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60700c', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60700d', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60710a', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60710b', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60710c', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '60710d', '607');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '774C9', '774');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '87324a', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '87324b', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '87324c', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '87324d', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873R1', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873R2a', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873R3b', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873R4c', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873R5d', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873R6e', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873R7f', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '873S7', '873');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5a', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5b', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5c', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5d', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5e', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5f', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5g', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S5h', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S6', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S6a', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S6b', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S6c', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S6d', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7a', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7b', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7c', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7d', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7e', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7f', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S7g', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S8', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S8a', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S8b', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S8c', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S8d', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S9', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S9a', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '874S9b', '874');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383a', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383b', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383c', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383d', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383e', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383f', '883');

-- change STGAP00001606
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60165, 'MSG_FCE_TXT_AGE_SENT_YES' 
,'You have indicated proof of child''s age/birth is being provided to the Eligibility Specialist.  Please enter comments explaining what and how documents are being provided.',500,700,'N'); 

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60166, 'MSG_FCE_TXT_CITZ_DOC_SENT_YES' 
,'You have indicated proof of child''s Citizenship/Alien Status has been provided to the Eligibility Specialist.  Please enter comments explaining what and how documents are being provided.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60167, 'MSG_FCE_IDEN_DOC_SENT' 
,'You have indicated proof of child''s Identity has been provided to the Eligibility Specialist.  Please enter a date.',500,700,'N'); 

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60168, 'MSG_FCE_IDEN_DOC_SENT_YES' 
,'You have indicated proof of child''s Identity has been provided to the Eligibility Specialist.  Please enter comments explaining what and how documents are being provided.',500,700,'N'); 

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60169, 'MSG_FCE_TXT_IDEN_SENT' 
,'Please explain why the proof of child''s Identity is not being sent to the Eligibility Specialist in the comments box provided.',500,700,'N'); 

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60170, 'MSG_FCE_TXT_LEGAL_DOCS_SENT_YES' 
,'You have indicated legal documents have been provided to the Eligibility Specialist.  Please enter comments explaining what and how documents are being provided.',500,700,'N'); 

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60171, 'MSG_FCE_DT_PREG_SENT_YES' 
,'You have indicated verification of child''s pregnancy has been provided to the Eligibility Specialist.  Please enter a date.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60172, 'MSG_FCE_TXT_PREG_SENT' 
,'You have indicated verification of child''s pregnancy has been provided to the Eligibility Specialist.  Please enter comments explaining what and how documents are being provided.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60173, 'MSG_FCE_FICM_NOT_COMP_SECT' 
,'You have indicated that the Family Independence Case Manager was notified of the child''s removal.  Please complete the Family Independence Case Manager Notified Information section.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60174, 'MSG_FCE_COST_EXCEED_QUES_REQ' 
,'The question "Does the child''s cost of care exceed $853.00?" must be answered.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60175, 'MSG_FCE_OUT_HOME_QUES_REQ' 
,'The question "Is the child expected to be in out-of-home care for a short period of time?" must be answered.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60176, 'MSG_FCE_EMANCIPATION_QUES_REQ' 
,'The question "Is the child approaching emancipation?" must be answered.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60177, 'MSG_FCE_ADOPTION_QUES_REQ' 
,'The question "Is the child in the process of being adopted?" must be answered.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60178, 'MSG_FCE_NOC_COMMENTS_REQ' 
,'You have indicated this is a "Notification of Change".  Please enter comments detailing the change in circumstance.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60179, 'MSG_FCE_MES_PROG_ASST_NOT_FND' 
,'The county MES Program Assistant not located. Please contact your supervisor.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60180, 'MSG_FCE_VERIF_DISABL' 
,'Verification of disability required for person receiving care who is 12 years of age or older.',500,700,'N');

-- change STGAP00001607
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60181, 'MSG_FCE_DT_IDEN_DOC_SENT','You have indicated proof of child''s Identity has been provided to the Eligibility Specialist.  Please enter a date.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60182, 'MSG_FCE_TXT_IDEN_DOC_SENT_YES','You have indicated proof of child''s Identity has been provided to the Eligibility Specialist.  Please enter comments explaining what and how documents are being provided.',500,700,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60183, 'MSG_FCE_TXT_IDEN_DOC_SENT','Please explain why the proof of child''s Identity is not being sent to the Eligibility Specialist in the comments box provided.',500,700,'N');

-- change STGAP00001608
INSERT INTO CAPS.METAPHOR
(id_tab,
txt_tab_url,
txt_tab_constant,
txt_tab,
dt_last_update)
VALUES
(1550,
'/resource/PlacementReferralLog/displayPlacementReferralLog',
'PLACEMENT_REFERRAL_LOG',
'Placement Referral Log',
SYSDATE);

-- change STGAP00001610
UPDATE CAPS.MESSAGE  SET TXT_MESSAGE = 'A First Name has been entered in the ''Family Independence Case Manager Notified Information Section'', please enter a last name.' WHERE TXT_MESSAGE_NAME = 'MSG_WRKR_NOTIF_FIRST';
UPDATE CAPS.MESSAGE  SET TXT_MESSAGE = 'A Middle Name has been entered in the ''Family Independence Case Manager Notified Information Section'', please enter a First Name and a Last Name.' WHERE TXT_MESSAGE_NAME = 'MSG_WRKR_NOTIF_MIDDLE';
UPDATE CAPS.MESSAGE  SET TXT_MESSAGE = 'A Last Name has been entered in the ''Family Independence Case Manager Notified Information Section'', please enter a First Name.' WHERE TXT_MESSAGE_NAME = 'MSG_WRKR_NOTIF_LAST';
UPDATE CAPS.MESSAGE  SET TXT_MESSAGE = 'The question, "Was child support court ordered?" must be answered.' WHERE TXT_MESSAGE_NAME = 'MSG_CHILD_SUP_QUES_REQ';

-- change STGAP00001615
--Use existing CD_STAGE_PROG_OPEN to set open stage DIV
UPDATE CAPS.STAGE_PROG SET CD_STAGE_PROG_OPEN = 'DIV' WHERE CD_STAGE_PROG_STAGE = 'INT' 
AND CD_STAGE_PROG_RSN_CLOSE = 'DIV' AND CD_STAGE_PROG_PROGRAM = 'CPS' AND
CD_STAGE_PROG_OPEN = 'PAL';

--Remove all old progressions from INT to DIV
DELETE FROM CAPS.STAGE_PROG WHERE CD_STAGE_PROG_STAGE = 'INT' AND CD_STAGE_PROG_PROGRAM = 'CPS'
AND CD_STAGE_PROG_RSN_CLOSE = 'DIV' AND CD_STAGE_PROG_OPEN IN ('FSU', 'PAD', 'ADO', 'SUB', 'INV', 'FPR');

-- change STGAP00001618
INSERT INTO CAPS.METAPHOR
(id_tab,
txt_tab_url,
txt_tab_constant,
txt_tab,
dt_last_update)
VALUES
(1515,
'/workload/EventSearch/displayEventList',
'SAFETY_PLAN_EVENTLIST',
'Safety Plan',
SYSDATE);

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, 
IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, 
TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER)
 Values
   ('2275', TO_DATE('11/13/2006 11:26:40', 'MM/DD/YYYY HH24:MI:SS'), 'SPL', 'INV', 'CPS', '1', '1', '1', '0', '0', '0', '1', 'Safety Plan', 
'CASE_CASESEARCH', 'RISK_ASSESSMENT_RISKASSMT', 'SAFETY_PLAN_EVENTLIST', '/investigation/SafetyPlan/displaySafetyPlan', 2);

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, 
IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, 
TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL)
 Values
   ('2276', TO_DATE('11/13/2006 11:31:41', 'MM/DD/YYYY HH24:MI:SS'), 'APP', 'INV', 'CPS', '0', '1', '1', '0', '0', '0', '0', 'Approve Safety Plan', 
'CASE_CASESEARCH', 'RISK_ASSESSMENT_RISKASSMT', 'SAFETY_PLAN_EVENTLIST', '/investigation/SafetyPlan/displaySafetyPlan');

INSERT INTO caps.CODES_TABLES VALUES ('CEVNTTYP','SPL','Safety Plan',NULL,TO_DATE('01/01/2007','MM/DD/YYYY'));


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (134, 'SacwisRev2', 'static updates, fixes to FCE_THIRD_PARTY_INSURANCE and others');
                         
commit;
