truncate table caps.report_list;
truncate table caps.report_parameter;
delete from caps.reports;

-- Standard Alter Table SQL

ALTER TABLE CAPS.REPORTS MODIFY(TXT_RPT_FULL_NAME  VARCHAR2(50))
;
ALTER TABLE CAPS.REPORT_LIST MODIFY(TXT_RPT_GEN_NAME  VARCHAR2(100))
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'TCMContactsMadeUptoDate', '00', 7, 'A', 'TCM Contact Made Up to Date', 'ondport', 'L', 'W', 'A list of all foster care, adoption and ongoing cases with at least one TCM contact recorded for the month. Generated for a specific county and service month with an optional unit parameter.', 'TCM', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'FamilyPreservationMonthlyStatus', '00', 7, 'A', 'Family Preservation Monthly Status', 'ondport', 'P', 'W', 'Multiple statistics reported for ongoing cases in the county within the month. Generated for a specific case manager.', 'Administration', 'N');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'FamilyPreservationMonthlyStatistics', '00', 7, 'A', 'Family Preservation Monthly Statistics', 'ondport', 'P', 'W', 'Multiple statistics reported for ongoing cases in the county within the month. Generated for a specific county and service month with an optional unit parameter.', 'Administration', 'N');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'FosterCareMonthlyStatus', '00', 7, 'A', 'Foster Care Monthly Status', 'ondport', 'P', 'W', 'Multiple statistics reported for foster care cases in the county within the month. Generated for a specific case manager.', 'Administration', 'N');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'PendingApprovals', '00', 7, 'A', 'Pending Approvals', 'ondport', 'L', 'W', 'A list of all approval tasks awaiting authorization from a supervisor. Generated for a specific county with an optional unit parameter.', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'WorkloadReport', '00', 7, 'A', 'Assigned Workload', 'ondport', 'L', 'W', 'A printable version of the Assigned Workload page. Generated for a specific case manager.', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'PlacementLog', '00', 7, 'A', 'Placement Log', 'ondport', 'P', 'W', 'Current and historical placement information for a child on a case. Generated for a specific Stage ID.', 'Placement', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'CasesWithSafetyResources', '00', 7, 'A', 'Cases With Safety Resources', 'ondport', 'L', 'W', 'A list of all active investigation and ongoing cases with at least one safety resource. Generated for a specific county with an optional unit parameter.', 'Safety Resource', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'RBWOActivePlacements', '00', 7, 'A', 'RBWO Active Placements', 'ondport', 'L', 'W', 'A list of all children currently placed in Room and Board and Watchful Oversight (RBWO) placements. Generated for a specific county.', 'Placement', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'LegalCustodyLapse', '00', 7, 'A', 'Children With a Lapse in Legal Custody', 'ondport', 'L', 'W', 'A list of all children currently in foster care with an expired or undocumented court order expiration date. Generated for a specific county with an optional unit parameter.', 'Placement', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'PlacementList', '00', 7, 'A', 'Placement List', 'ondport', 'L', 'W', 'Current placement information for all children in foster care. Generated for a specific county with an optional unit parameter.', 'Placement', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'RedeterminationDue', '00', 7, 'A', 'Re-Determinations Due Within 45 Days', 'ondport', 'L', 'W', 'A list of children in foster care with a IV-E redetermination due within the next 45 days. Also includes cases without an eligibility review date entered. Generated for a specific county with an optional unit parameter.', 'Eligibility', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'InvestigationMonthlyStatus', '00', 7, 'A', 'Investigation Monthly Status', 'ondport', 'P', 'W', 'Multiple statistics reported for investigations in the county within the month. Generated for a specific case manager and service month.', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'InvestigationMonthlyStatistics', '00', 7, 'A', 'Investigation Monthly Statistics', 'ondport', 'P', 'W', 'Multiple statistics reported for investigations in the county within the month. Generated for a specific county and service month with an optional unit parameter.', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'CaseWorkerChildVisit', '00', 7, 'A', 'Case Worker Child Visit', 'ondport', 'L', 'W', 'A list of all contacts made during the month for children in foster care. Generated for a specific county with an optional unit parameter.', 'Placement', 'N');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'IntakeMonthlyStatistics', '00', 7, 'A', 'Intake Monthly Statistics', 'ondport', 'P', 'W', 'Multiple statistics reported for intakes received in the county within the month. Generated for a specific county and service month.', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'ImmigrantChildrenInFosterCare', '00', 7, 'A', 'Immigrant Children in Foster Care', 'ondport', 'L', 'W', 'A list of all non-US citizens currently in foster care. Generated for a specific county. ', 'Placement', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'InitialIVEDetermination', '00', 7, 'A', 'Initial IV-E Determination', 'ondport', 'L', 'W', 'Initial IV-E determination for children who entered foster care within the past 45 days. Generated for a specific county with an optional unit parameter.', 'Eligibility', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'OpenDiversionCases', '00', 7, 'A', 'Open Diversion Cases', 'ondport', 'P', 'W', 'A list of all open diversion cases. Generated for a specific county with an optional unit parameter.', 'Diversion', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'FosterCareDischarge', '00', 7, 'A', 'Foster Care Discharge', 'ondport', 'P', 'W', 'A list of all children discharged from foster care during the service month for a county. Generated for a specific county and service month.', 'Placement', 'N');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'OverStandardOfPromptness', '00', 7, 'A', 'Over Standard of Promptness', 'ondport', 'L', 'W', 'A list of all children in foster care without a IV-E determination completed within the 45 day window from the time the child entered care. Generated for a specific county with an optional unit parameter.', 'Eligibility', 'N');

insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'InitialIVEDetermination', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'IntakeMonthlyStatistics', '00', 1, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'IntakeMonthlyStatistics', '00', 2, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'InvestigationMonthlyStatus', '00', 1, 16, 'PERSONID', 'NUMBER', 'Y', 'Staff ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'InvestigationMonthlyStatus', '00', 2, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'InvestigationMonthlyStatistics', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'InvestigationMonthlyStatistics', '00', 2, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'InvestigationMonthlyStatistics', '00', 3, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'LegalCustodyLapse', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'LegalCustodyLapse', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'OpenDiversionCases', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'OpenDiversionCases', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'PendingApprovals', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'PendingApprovals', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'PlacementList', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'PlacementList', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'RBWOActivePlacements', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'RedeterminationDue', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'RedeterminationDue', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'TCMContactsMadeUptoDate', '00', 1, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'TCMContactsMadeUptoDate', '00', 2, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'TCMContactsMadeUptoDate', '00', 3, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'CasesWithSafetyResources', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'CasesWithSafetyResources', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FamilyPreservationMonthlyStatus', '00', 1, 16, 'PERSONID', 'NUMBER', 'Y', 'Staff ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FamilyPreservationMonthlyStatistics', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FamilyPreservationMonthlyStatistics', '00', 3, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FosterCareMonthlyStatus', '00', 1, 16, 'PERSONID', 'NUMBER', 'Y', 'Staff ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'WorkloadReport', '00', 1, 16, 'PERSONID', 'NUMBER', 'Y', 'Staff ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'PlacementLog', '00', 1, 16, 'PERSONID', 'NUMBER', 'Y', 'Placement Stage ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FosterCareDischarge', '00', 1, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FosterCareDischarge', '00', 2, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'OverStandardOfPromptness', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'OverStandardOfPromptness', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'CaseWorkerChildVisit', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'CaseWorkerChildVisit', '00', 2, 2, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'ImmigrantChildrenInFosterCare', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'InitialIVEDetermination', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (267, 'SacwisRev2', 'REPORT table shananigans');
commit;
