-- Add columns to PERSON/PERSON_ENC to support Adoption Enhancements 

--STGAP00010070 - Changes to data model for design finalization . This is the dbcr to hold all the changes related to design finalization for Adoptions.


alter table caps.person_enc add (IND_ADOPT_AFCARS_SENT VARCHAR2(1));
comment on column caps.person_enc.IND_ADOPT_AFCARS_SENT is 'Indicator if the child has been reported in the adoption afcars file.';

CREATE OR REPLACE VIEW CAPS.PERSON ("ID_PERSON", "DT_LAST_UPDATE", "CD_PERSON_SEX", "ADDR_PERSON_ST_LN_1", "ADDR_PERSON_CITY", "ADDR_PERSON_ZIP", "DT_PERSON_DEATH", "DT_PERSON_BIRTH", "CD_PERSON_RELIGION", "CD_PERSON_CHAR", "CD_PERSON_LIV_ARR", "CD_PERS_GUARD_CNSRV", "CD_PERSON_STATUS", "CD_PERSON_DEATH", "CD_PERSON_MARITAL_STATUS", "CD_PERSON_LANGUAGE", "CD_PERSON_ETHNIC_GROUP", "CD_PERSON_STATE", "CD_PERSON_COUNTY", "IND_PERSON_DOB_APPROX", "IND_PERS_CANCEL_HIST", "NBR_PERSON_AGE", "NBR_PERSON_PHONE", "NBR_PERSON_ID_NUMBER", "NM_PERSON_FIRST", "NM_PERSON_MIDDLE", "NM_PERSON_LAST", "NM_PERSON_FULL", "TXT_PERSON_OCCUPATION", "CD_PERSON_SUFFIX", "IND_AUTO_PERS_MERGE", "CD_DISASTER_RLF", "CD_PERSON_TITLE", "IND_PERSON_US_CITIZEN", "CD_PERSON_IMMIGRATION_STATUS", "CD_PERSON_COUNTRY_ORIGIN", "TXT_CHAR_CMNTS", "CD_PERS_NOT_YET_DIAG", "CD_PERSON_PROOF_CITIZENSHIP", "TXT_PERSON_OTHER_RELATIONSHIPS", "CD_MATCH_TYPE", "CD_SMILE_CLIENT", "TXT_IDS_NUMBER", "IND_PREV_ADOPTED", "IND_PRIVATE", "IND_PUBLIC", "IND_INTRNTL", "CD_ADOPT_STATE", "CD_ADOPT_COUNTY", "CD_ADOPT_CNTRY", "IND_ADOPT_DISLUTON", "TXT_PERSON_ADDL_CMNTS","DT_DISSOLUTION","DT_PREV_ADOPTION","TXT_NAME_OF_ADO_AGENCY","IND_ADOPT_FINALIZED","IND_ADOPT_AFCARS_SENT") AS 
  SELECT
ID_PERSON,
DT_LAST_UPDATE,
CD_PERSON_SEX,
ADDR_PERSON_ST_LN_1,
ADDR_PERSON_CITY,
ADDR_PERSON_ZIP,
DT_PERSON_DEATH ,
DT_PERSON_BIRTH,
CD_PERSON_RELIGION,
CD_PERSON_CHAR,
CD_PERSON_LIV_ARR,
CD_PERS_GUARD_CNSRV,
CD_PERSON_STATUS,
CD_PERSON_DEATH,
CD_PERSON_MARITAL_STATUS,
CD_PERSON_LANGUAGE,
CD_PERSON_ETHNIC_GROUP,
CD_PERSON_STATE,
CD_PERSON_COUNTY,
IND_PERSON_DOB_APPROX,
IND_PERS_CANCEL_HIST,
NBR_PERSON_AGE,
NBR_PERSON_PHONE,
CAST(CAPS.DECRYPT(NBR_PERSON_ID_NUMBER) AS VARCHAR2(15))  NBR_PERSON_ID_NUMBER,
NM_PERSON_FIRST,
NM_PERSON_MIDDLE,
NM_PERSON_LAST,
NM_PERSON_FULL,
TXT_PERSON_OCCUPATION,
CD_PERSON_SUFFIX,
IND_AUTO_PERS_MERGE,
CD_DISASTER_RLF,
CD_PERSON_TITLE,
IND_PERSON_US_CITIZEN,
CD_PERSON_IMMIGRATION_STATUS,
CD_PERSON_COUNTRY_ORIGIN,
TXT_CHAR_CMNTS,
CD_PERS_NOT_YET_DIAG,
CD_PERSON_PROOF_CITIZENSHIP,
TXT_PERSON_OTHER_RELATIONSHIPS,
CD_MATCH_TYPE,
CD_SMILE_CLIENT,
TXT_IDS_NUMBER,
IND_PREV_ADOPTED,
IND_PRIVATE,
IND_PUBLIC,
IND_INTRNTL,
CD_ADOPT_STATE,
CD_ADOPT_COUNTY,
CD_ADOPT_CNTRY,
IND_ADOPT_DISLUTON,
TXT_PERSON_ADDL_CMNTS,
DT_DISSOLUTION, 
DT_PREV_ADOPTION,
TXT_NAME_OF_ADO_AGENCY,
IND_ADOPT_FINALIZED,
IND_ADOPT_AFCARS_SENT
FROM CAPS.PERSON_ENC;
 

grant select on caps.person to capson,capsbat,operator,ops$datafix;
grant update on caps.person to capson,capsbat,ops$datafix;
grant insert on caps.person to capson,capsbat,ops$datafix;
grant delete on caps.person to capson,capsbat,ops$datafix;


/
create or replace TRIGGER CAPS.TISD_PERSON 
INSTEAD OF DELETE
ON CAPS.PERSON
REFERENCING OLD AS OLD
BEGIN
DELETE FROM CAPS.PERSON_ENC
WHERE ID_PERSON = :OLD.ID_PERSON
;
END;
/

/
create or replace TRIGGER CAPS.TISI_PERSON 
INSTEAD OF INSERT
ON CAPS.PERSON
REFERENCING NEW AS NEW
BEGIN
INSERT INTO CAPS.PERSON_ENC (
  ID_PERSON,
  DT_LAST_UPDATE,
  CD_PERSON_SEX,
  ADDR_PERSON_ST_LN_1,
  ADDR_PERSON_CITY,
  ADDR_PERSON_ZIP,
  DT_PERSON_DEATH,
  DT_PERSON_BIRTH,
  CD_PERSON_RELIGION,
  CD_PERSON_CHAR,
  CD_PERSON_LIV_ARR,
  CD_PERS_GUARD_CNSRV,
  CD_PERSON_STATUS,
  CD_PERSON_DEATH,
  CD_PERSON_MARITAL_STATUS,
  CD_PERSON_LANGUAGE,
  CD_PERSON_ETHNIC_GROUP,
  CD_PERSON_STATE,
  CD_PERSON_COUNTY,
  IND_PERSON_DOB_APPROX,
  IND_PERS_CANCEL_HIST,
  NBR_PERSON_AGE,
  NBR_PERSON_PHONE,
  NM_PERSON_FIRST,
  NM_PERSON_MIDDLE,
  NM_PERSON_LAST,
  NM_PERSON_FULL,
  TXT_PERSON_OCCUPATION,
  CD_PERSON_SUFFIX,
  IND_AUTO_PERS_MERGE,
  CD_DISASTER_RLF,
  CD_PERSON_TITLE,
  IND_PERSON_US_CITIZEN,
  CD_PERSON_IMMIGRATION_STATUS,
  CD_PERSON_COUNTRY_ORIGIN,
  TXT_CHAR_CMNTS,
  CD_PERS_NOT_YET_DIAG,
  CD_PERSON_PROOF_CITIZENSHIP,
  TXT_PERSON_OTHER_RELATIONSHIPS,
  CD_MATCH_TYPE,
  CD_SMILE_CLIENT,
  TXT_IDS_NUMBER,
  IND_PREV_ADOPTED,
  IND_PRIVATE,
  IND_PUBLIC,
  IND_INTRNTL,
  CD_ADOPT_STATE,
  CD_ADOPT_COUNTY,
  CD_ADOPT_CNTRY,
  IND_ADOPT_DISLUTON,
  TXT_PERSON_ADDL_CMNTS,
  DT_DISSOLUTION,
  DT_PREV_ADOPTION,
  TXT_NAME_OF_ADO_AGENCY,
  IND_ADOPT_FINALIZED,
  IND_ADOPT_AFCARS_SENT,
  NBR_PERSON_ID_NUMBER)
VALUES
(
:NEW.ID_PERSON,
:NEW.DT_LAST_UPDATE,
:NEW.CD_PERSON_SEX,
:NEW.ADDR_PERSON_ST_LN_1,
:NEW.ADDR_PERSON_CITY,
:NEW.ADDR_PERSON_ZIP,
:NEW.DT_PERSON_DEATH,
:NEW.DT_PERSON_BIRTH,
:NEW.CD_PERSON_RELIGION,
:NEW.CD_PERSON_CHAR,
:NEW.CD_PERSON_LIV_ARR,
:NEW.CD_PERS_GUARD_CNSRV,
:NEW.CD_PERSON_STATUS,
:NEW.CD_PERSON_DEATH,
:NEW.CD_PERSON_MARITAL_STATUS,
:NEW.CD_PERSON_LANGUAGE,
:NEW.CD_PERSON_ETHNIC_GROUP,
:NEW.CD_PERSON_STATE,
:NEW.CD_PERSON_COUNTY,
:NEW.IND_PERSON_DOB_APPROX,
:NEW.IND_PERS_CANCEL_HIST,
:NEW.NBR_PERSON_AGE,
:NEW.NBR_PERSON_PHONE,
:NEW.NM_PERSON_FIRST,
:NEW.NM_PERSON_MIDDLE,
:NEW.NM_PERSON_LAST,
:NEW.NM_PERSON_FULL,
:NEW.TXT_PERSON_OCCUPATION,
:NEW.CD_PERSON_SUFFIX,
:NEW.IND_AUTO_PERS_MERGE,
:NEW.CD_DISASTER_RLF,
:NEW.CD_PERSON_TITLE,
:NEW.IND_PERSON_US_CITIZEN,
:NEW.CD_PERSON_IMMIGRATION_STATUS,
:NEW.CD_PERSON_COUNTRY_ORIGIN,
:NEW.TXT_CHAR_CMNTS,
:NEW.CD_PERS_NOT_YET_DIAG,
:NEW.CD_PERSON_PROOF_CITIZENSHIP,
:NEW.TXT_PERSON_OTHER_RELATIONSHIPS,
:NEW.CD_MATCH_TYPE,
:NEW.CD_SMILE_CLIENT,
:NEW.TXT_IDS_NUMBER,
:NEW.IND_PREV_ADOPTED,
:NEW.IND_PRIVATE,
:NEW.IND_PUBLIC,
:NEW.IND_INTRNTL,
:NEW.CD_ADOPT_STATE,
:NEW.CD_ADOPT_COUNTY,
:NEW.CD_ADOPT_CNTRY,
:NEW.IND_ADOPT_DISLUTON,
:NEW.TXT_PERSON_ADDL_CMNTS,
:NEW.DT_DISSOLUTION,
:NEW.DT_PREV_ADOPTION,
:NEW.TXT_NAME_OF_ADO_AGENCY,
:NEW.IND_ADOPT_FINALIZED,
:NEW.IND_ADOPT_AFCARS_SENT,
ENCRYPT(:NEW.NBR_PERSON_ID_NUMBER) ) ;
END;
/


/
create or replace TRIGGER CAPS.TISU_PERSON 
INSTEAD OF UPDATE
ON CAPS.PERSON
REFERENCING NEW AS NEW OLD AS OLD
BEGIN
UPDATE CAPS.PERSON_ENC SET
  CD_PERSON_SEX = :NEW.CD_PERSON_SEX,
  ADDR_PERSON_ST_LN_1 = :NEW.ADDR_PERSON_ST_LN_1,
  ADDR_PERSON_CITY = :NEW.ADDR_PERSON_CITY,
  ADDR_PERSON_ZIP = :NEW.ADDR_PERSON_ZIP,
  DT_PERSON_DEATH = :NEW.DT_PERSON_DEATH,
  DT_PERSON_BIRTH = :NEW.DT_PERSON_BIRTH,
  CD_PERSON_RELIGION = :NEW.CD_PERSON_RELIGION,
  CD_PERSON_CHAR = :NEW.CD_PERSON_CHAR,
  CD_PERSON_LIV_ARR = :NEW.CD_PERSON_LIV_ARR,
  CD_PERS_GUARD_CNSRV = :NEW.CD_PERS_GUARD_CNSRV,
  CD_PERSON_STATUS = :NEW.CD_PERSON_STATUS,
  CD_PERSON_DEATH = :NEW.CD_PERSON_DEATH,
  CD_PERSON_MARITAL_STATUS = :NEW.CD_PERSON_MARITAL_STATUS,
  CD_PERSON_LANGUAGE = :NEW.CD_PERSON_LANGUAGE,
  CD_PERSON_ETHNIC_GROUP = :NEW.CD_PERSON_ETHNIC_GROUP,
  CD_PERSON_STATE = :NEW.CD_PERSON_STATE,
  CD_PERSON_COUNTY = :NEW.CD_PERSON_COUNTY,
  IND_PERSON_DOB_APPROX = :NEW.IND_PERSON_DOB_APPROX,
  IND_PERS_CANCEL_HIST = :NEW.IND_PERS_CANCEL_HIST,
  NBR_PERSON_AGE = :NEW.NBR_PERSON_AGE,
  NBR_PERSON_PHONE = :NEW.NBR_PERSON_PHONE,
  NM_PERSON_FIRST = :NEW.NM_PERSON_FIRST,
  NM_PERSON_MIDDLE = :NEW.NM_PERSON_MIDDLE,
  NM_PERSON_LAST = :NEW.NM_PERSON_LAST,
  NM_PERSON_FULL = :NEW.NM_PERSON_FULL,
  TXT_PERSON_OCCUPATION = :NEW.TXT_PERSON_OCCUPATION,
  CD_PERSON_SUFFIX = :NEW.CD_PERSON_SUFFIX,
  IND_AUTO_PERS_MERGE = :NEW.IND_AUTO_PERS_MERGE,
  CD_DISASTER_RLF = :NEW.CD_DISASTER_RLF,
  CD_PERSON_TITLE = :NEW.CD_PERSON_TITLE,
  IND_PERSON_US_CITIZEN = :NEW.IND_PERSON_US_CITIZEN,
  CD_PERSON_IMMIGRATION_STATUS = :NEW.CD_PERSON_IMMIGRATION_STATUS,
  CD_PERSON_COUNTRY_ORIGIN = :NEW.CD_PERSON_COUNTRY_ORIGIN,
  TXT_CHAR_CMNTS = :NEW.TXT_CHAR_CMNTS,
  CD_PERS_NOT_YET_DIAG = :NEW.CD_PERS_NOT_YET_DIAG,
  CD_PERSON_PROOF_CITIZENSHIP = :NEW.CD_PERSON_PROOF_CITIZENSHIP,
  TXT_PERSON_OTHER_RELATIONSHIPS = :NEW.TXT_PERSON_OTHER_RELATIONSHIPS,
  CD_MATCH_TYPE = :NEW.CD_MATCH_TYPE,
  CD_SMILE_CLIENT = :NEW.CD_SMILE_CLIENT,
  TXT_IDS_NUMBER = :NEW.TXT_IDS_NUMBER,
  IND_PREV_ADOPTED = :NEW.IND_PREV_ADOPTED,
  IND_PRIVATE = :NEW.IND_PRIVATE,
  IND_PUBLIC = :NEW.IND_PUBLIC,
  IND_INTRNTL = :NEW.IND_INTRNTL,
  CD_ADOPT_STATE = :NEW.CD_ADOPT_STATE,
  CD_ADOPT_COUNTY = :NEW.CD_ADOPT_COUNTY,
  CD_ADOPT_CNTRY = :NEW.CD_ADOPT_CNTRY,
  IND_ADOPT_DISLUTON = :NEW.IND_ADOPT_DISLUTON,
  TXT_PERSON_ADDL_CMNTS = :NEW.TXT_PERSON_ADDL_CMNTS,
  DT_DISSOLUTION=:NEW.DT_DISSOLUTION,
  DT_PREV_ADOPTION=:NEW.DT_PREV_ADOPTION,
  TXT_NAME_OF_ADO_AGENCY=:NEW.TXT_NAME_OF_ADO_AGENCY,
  IND_ADOPT_FINALIZED=:NEW.IND_ADOPT_FINALIZED,
  IND_ADOPT_AFCARS_SENT=:NEW.IND_ADOPT_AFCARS_SENT,
  NBR_PERSON_ID_NUMBER = CAPS.ENCRYPT(:NEW.NBR_PERSON_ID_NUMBER)
WHERE ID_PERSON = :OLD.ID_PERSON;
END;
/

alter table caps.EXCHANGE_HOME add (NBR_AGENCY_CONTRACT_CODE varchar2(3));
comment on column caps.exchange_home.nbr_agency_contract_code is 'Number of the agency''s contract code with the SAU.';

update CAPS.EXCHANGE_HOME set CD_SEV_MENTAL_RETARDATION = null;
alter table CAPS.EXCHANGE_HOME drop column CD_SEV_MENTAL_RETARDATION;
alter table CAPS.EXCHANGE_HOME add (CD_SEV_MENTAL_RETARDATION varchar2(2));

update caps.codes_tables
set decode = 'Child Hx of Sexual Abuse'
where code_type = 'CADBKRNF'
and code = '09';

alter table caps.adoption_subsidy add (ID_SPC_NEEDS_DET  NUMBER(16));
alter table caps.adoption_subsidy add constraint FK_ADO_SUB_SPC_NDS_DETER
   foreign key  (ID_SPC_NEEDS_DET) 
   references caps.special_needs_determination (id_event);

alter table caps.ADO_INFO_CBX_SENT drop constraint FK_CBX_SENT_ADO_INFO;
alter table caps.ADO_INFO_CBX_SENT rename column ID_ADO_INFO to ID_INFO_CHAR;
alter table caps.ADO_INFO_CBX_SENT add constraint FK_CBX_SENT_ADO_INFO foreign key
(ID_INFO_CHAR) references caps.ADO_INFO_CBX(ID_INFO_CHAR);

alter table caps.ADO_INFO add (IND_FP_ADO  varchar2(1));
comment on column caps.ADO_INFO.IND_FP_ADO is 'Yes or No Value to indicate if the foster parents intend to adopt the child.';

alter table caps.ADO_INFO add (TXT_COUNTY_CONS_COMMENT varchar2(300));
comment on column  caps.ADO_INFO.TXT_COUNTY_CONS_COMMENT is 'Field will be used by county to specified families that have been considered for adoption.' ;

update caps.codes_tables
set decode = 'Foster/Adoptive Parent'
where code = 'AF'
and code_type in ('CRELPRN2','CRELCOL2','CRPTRINT','CSRCRPTR','CRELVICT');

update caps.codes_tables
set decode = 'Adoptive Parent'
where code = 'PT'
and code_type in ('CRELVICT','CRPTRINT');

update caps.codes_tables
set dt_end = sysdate
where code in ('19', '201','200')
and code_type = 'CLNCHAR2';

alter table caps.EXCHANGE_CHILD add (TXT_BIRTH_NAME VARCHAR2(30));
comment on column caps.EXCHANGE_CHILD.TXT_BIRTH_NAME is 'Birth name of the child if there was a dissolution';

alter table caps.EXCHANGE_CHILD add (TXT_CHILD_IS_LINKED VARCHAR2(500));
comment on column caps.EXCHANGE_CHILD.TXT_CHILD_IS_LINKED is 'Comments for Child is Linked' ;

alter table caps.EXCHANGE_CHILD add (TXT_CHILD_PLACED_WITH       VARCHAR2(500));
comment on column caps.EXCHANGE_CHILD.TXT_CHILD_PLACED_WITH is 'Comments for Child is Placed With';

alter table caps.INITIAL_MEDICAID_APP add (TXT_ICAMA_COMMENTS   VARCHAR2 (300));
comment on column caps.INITIAL_MEDICAID_APP.TXT_ICAMA_COMMENTS is 'Inter-state comments';

alter table caps.NON_INCIDENT_AFCARS_INFO 
 add (IND_MENTAL_RETARDATION  VARCHAR2(1));
comment on column caps.NON_INCIDENT_AFCARS_INFO.IND_MENTAL_RETARDATION is 'Indicator if the child has the characteristic Mental Retardation';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (CD_SEV_MENTAL_RETARDATION  VARCHAR2(2));
comment on column caps.NON_INCIDENT_AFCARS_INFO.CD_SEV_MENTAL_RETARDATION  is 'Severity level of the characteristic Mental Retardation';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (IND_VISUAL_HEARING_IMP   VARCHAR2 (1));
comment on column caps.NON_INCIDENT_AFCARS_INFO.IND_VISUAL_HEARING_IMP  is 'Indicator if the child has the characteristic Visual or Hearing Impaired';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (CD_SEV_VISUAL_HEARING_IMP   VARCHAR2 (2));
comment on column caps.NON_INCIDENT_AFCARS_INFO.CD_SEV_VISUAL_HEARING_IMP  is 'Severity level of the characteristic Visual or Hearing Impaired';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (IND_PHYSICALLY_DISABLED  VARCHAR2(1));
comment on column caps.NON_INCIDENT_AFCARS_INFO.IND_PHYSICALLY_DISABLED  is 'Indicator if the child has the characteristic Physically Disabled';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (CD_SEV_PHYSICALLY_DISABLED   VARCHAR2(2));
comment on column caps.NON_INCIDENT_AFCARS_INFO.CD_SEV_PHYSICALLY_DISABLED is 'Severity level of the characteristic Physically Disabled';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (IND_EMOTIONALLY_DIST   VARCHAR2 (1));
comment on column caps.NON_INCIDENT_AFCARS_INFO.IND_EMOTIONALLY_DIST is 'Indicator if the child has the characteristic Emotionally Disturbed';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (CD_SEV_EMOTIONALLY_DIST   VARCHAR2(2));
comment on column caps.NON_INCIDENT_AFCARS_INFO.CD_SEV_EMOTIONALLY_DIST is 'Severity level of the characteristic Emotionally Disturbed';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (IND_OTHER_MED  VARCHAR2 (1));
comment on column caps.NON_INCIDENT_AFCARS_INFO.IND_OTHER_MED is 'Indicator if the child has the characteristic Other Medical Diagnosis';

alter table caps.NON_INCIDENT_AFCARS_INFO 
add (CD_SEV_OTHER_MED   VARCHAR2(2));
comment on column caps.NON_INCIDENT_AFCARS_INFO.CD_SEV_OTHER_MED  is 'Severity level of the characteristic Other Medical Diagnosis';


{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };
{ call dbms_utility.compile_schema('ORS') };

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (379, 'SacwisRev3', 'Release 3.0 - DBCR 10070');
commit;

