--STGAP00016084 - Release(4.2) -- MR-075  Update TIBR_RESOURCE_HISTORY trigger

-- MR-075 FA Home Reimbursability Enhancement DBCR
-- Update TIBR_RESOURCE_HISTORY trigger

grant select on caps.caps_case to operator;
/
  CREATE OR REPLACE TRIGGER CAPS.TIBR_RESOURCE_HISTORY 
BEFORE INSERT
ON CAPS.RESOURCE_HISTORY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
  dummy2    NUMBER;
  dummy_date  DATE;

BEGIN

-- 05/26/2001 MITSCHCG Added column DT_CCL_UPDATE for CLASS project SIR #15684

  :NEW.DT_LAST_UPDATE := SYSDATE;

  IF (:NEW.ID_RESOURCE_HISTORY = 0) OR
       (:NEW.ID_RESOURCE_HISTORY IS NULL) THEN
    SELECT  SEQ_RESOURCE_HISTORY.NEXTVAL
    INTO    dummy
    FROM    DUAL;
    :NEW.ID_RESOURCE_HISTORY := dummy;
  END IF;

  IF :NEW.DT_RSHS_END IS NULL THEN
    :NEW.DT_RSHS_END := TO_DATE('12/31/4712','MM/DD/YYYY');
  END IF;

  IF :NEW.ID_CASE  IS NULL THEN
    BEGIN
      SELECT  ID_CASE
      INTO    :NEW.ID_CASE
      FROM    STAGE
      WHERE    ID_STAGE = :NEW.ID_RSHS_FA_HOME_STAGE;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQL%NOTFOUND THEN
          :NEW.ID_CASE := NULL;
        END IF;
    END;
  END IF;

  INSERT INTO RESOURCE_HISTORY_AUDIT (
    ID_RESOURCE_HISTORY_AUDIT,
    ID_RESOURCE_HISTORY_AUD,
    ID_AUD_RESOURCE,
    DT_RSHS_AUD_EFFECTIVE,
    DT_RSHS_AUD_CLOSE,
    DT_LAST_UPDATE,
    ID_CASE,
    DT_RSHS_AUD_CERT ,
    DT_RSHS_AUD_MARRIAGE,
    DT_RSHS_AUD_END,
    ADDR_RSHS_AUD_ST_LN_1,
    ADDR_RSHS_AUD_ST_LN_2,
    ADDR_RSHS_AUD_CITY,
    CD_RSHS_AUD_STATE,
    ADDR_RSHS_AUD_ZIP,
    ADDR_RSHS_AUD_ATTN,
    CD_RSHS_AUD_CNTY,
    CD_RSHS_AUD_INVOL_CLOSURE,
    CD_RSHS_AUD_CLOSURE_RSN,
    CD_RSHS_AUD_TYPE,
    CD_RSHS_AUD_HUB,
    CD_RSHS_AUD_CAMPUS_TYPE,
    CD_RSHS_AUD_SOURCE_INQUIRY,
    CD_RSHS_AUD_MAINTAINER,
    CD_RSHS_AUD_SCH_DIST,
    CD_RSHS_AUD_OWNERSHIP,
    CD_RSHS_AUD_STATUS,
    CD_RSHS_AUD_FACIL_TYPE,
    CD_RSHS_AUD_CERT_BY,
    CD_RSHS_AUD_OPER_BY,
    CD_RSHS_AUD_SETTING,
    CD_RSHS_AUD_PAYMENT,
    CD_RSHS_AUD_CATEGORY,
    CD_RSHS_AUD_ETHNICITY,
    CD_RSHS_AUD_LANGUAGE,
    CD_RSHS_AUD_MARITAL_STATUS,
    CD_RSHS_AUD_RECMND_REOPEN,
    CD_RSHS_AUD_REGION,
    CD_RSHS_AUD_RELIGION,
    CD_RSHS_AUD_RESPITE,
    CD_RSHS_AUD_FA_HOME_STATUS,
    CD_RSHS_AUD_FA_HOME_TYPE1   ,
    CD_RSHS_AUD_FA_HOME_TYPE2,
    CD_RSHS_AUD_FA_HOME_TYPE3,
    CD_RSHS_AUD_FA_HOME_TYPE4,
    CD_RSHS_AUD_FA_HOME_TYPE5,
    CD_RSHS_AUD_FA_HOME_TYPE6,
    CD_RSHS_AUD_FA_HOME_TYPE7,
    CD_RSHS_AUD_MHMR_COMP_CODE,
    ID_RSHS_AUD_FA_HOME_STAGE,
    ID_RSHS_AUD_FA_HOME_EVENT,
    IND_RSHS_AUD_CARE_PROV,
    IND_RSHS_AUD_INACTIVE,
    IND_RSHS_AUD_TRANSPORT,
    IND_RSHS_AUD_EMERG_PLACE,
    NM_RSHS_AUD_RESOURCE,
    NM_RSHS_AUD_CONTACT,
    NM_RSHS_AUD_LAST_UPDATE,
    NBR_RSHS_AUD_VID,
    NBR_RSHS_AUD_PHN,
    NBR_RSHS_AUD_FACIL_CAPACITY,
    NBR_RSHS_AUD_FACIL_ACCLAIM,
    NBR_RSHS_AUD_PHONE_EXT,
    NBR_RSHS_AUD_CAMPUS_NBR,
    NBR_RSHS_AUD_ANNUAL_INCOME,
    NBR_RSHS_AUD_FM_AGE_MAX,
    NBR_RSHS_AUD_FM_AGE_MIN,
    NBR_RSHS_AUD_MA_AGE_MAX,
    NBR_RSHS_AUD_MA_AGE_MIN,
    NBR_RSHS_AUD_INT_CHILDREN,
    NBR_RSHS_AUD_INT_FE_AGE_MAX ,
    NBR_RSHS_AUD_INT_FE_AGE_MIN,
    NBR_RSHS_AUD_INT_MA_AGE_MAX,
    NBR_RSHS_AUD_INT_MA_AGE_MIN,
    NBR_RSHS_AUD_OPEN_SLOTS,
    TXT_RSHS_AUD_ADDR_CMNTS,
    TXT_RSHS_AUD_COMMENTS,
    IND_RSHS_AUD_WRITE_AUDIT,
    DT_CCL_UPDATE,
    CD_RSRC_MHMR_SITE,
    IND_RSRC_CONTRACTED,
    NM_LEGAL,
    NM_RSRC_CONTACT_TITLE,
    NBR_RSRC_NTNL_PROVIDER,
    ADDR_RSRC_EMAIL,
    ADDR_RSRC_WEBSITE,
    CD_SCHOOL_TYPE,
    CD_PAYMENT_DELIVERY,
    TXT_SPEC_CERT,
    CD_EXCHANGE_STAT,
    IND_WAIVER,
    CD_SCH_DIST,
    CD_ELEM,
    CD_MIDDLE,
    CD_HIGH,
    DT_FOST_MANUAL,
    DT_FOST_BILL,
    IND_SPECIFIC_CHILD,
    DT_LIC_BEGIN,
    DT_LIC_END,
    TXT_CLOSURE_COMM,
    NDFCS_CERT_ENTITY,
    IND_RSRC_NONDFCS,
    IND_CURR_HM_STDY_EXSTS,
    IND_PREV_FAM_STDY_RQSTD,
    RSRC_OTH_SPC_CERTF,
    IND_AFTER_HOURS,
    TXT_HM_PRG_INTEREST,
    NBR_RSRC_CONTACT_PHN,
    NBR_RSRC_CONTACT_PHONE_EXT,
    IND_IVE_REIMBURSABLE,
    DT_REIMBURSABLE_EFFECTIVE,
    DT_REIMBURSABLE_END
  ) VALUES (
    0,
    :NEW.ID_RESOURCE_HISTORY,
    :NEW.ID_RESOURCE,
    :NEW.DT_RSHS_EFFECTIVE,
    :NEW.DT_RSHS_CLOSE,
    :NEW.DT_LAST_UPDATE,
    :NEW.ID_CASE,
    :NEW.DT_RSHS_CERT,
    :NEW.DT_RSHS_MARRIAGE,
    :NEW.DT_RSHS_END,
    :NEW.ADDR_RSHS_ST_LN_1,
    :NEW.ADDR_RSHS_ST_LN_2,
    :NEW.ADDR_RSHS_CITY,
    :NEW.CD_RSHS_STATE,
    :NEW.ADDR_RSHS_ZIP,
    :NEW.ADDR_RSHS_ATTN,
    :NEW.CD_RSHS_CNTY,
    :NEW.CD_RSHS_INVOL_CLOSURE,
    :NEW.CD_RSHS_CLOSURE_RSN,
    :NEW.CD_RSHS_TYPE,
    :NEW.CD_RSHS_HUB,
    :NEW.CD_RSHS_CAMPUS_TYPE,
    :NEW.CD_RSHS_SOURCE_INQUIRY,
    :NEW.CD_RSHS_MAINTAINER,
    :NEW.CD_RSHS_SCH_DIST,
    :NEW.CD_RSHS_OWNERSHIP,
    :NEW.CD_RSHS_STATUS,
    :NEW.CD_RSHS_FACIL_TYPE,
    :NEW.CD_RSHS_CERT_BY,
    :NEW.CD_RSHS_OPER_BY,
    :NEW.CD_RSHS_SETTING,
    :NEW.CD_RSHS_PAYMENT,
    :NEW.CD_RSHS_CATEGORY,
    :NEW.CD_RSHS_ETHNICITY,
    :NEW.CD_RSHS_LANGUAGE,
    :NEW.CD_RSHS_MARITAL_STATUS,
    :NEW.CD_RSHS_RECMND_REOPEN,
    :NEW.CD_RSHS_REGION,
    :NEW.CD_RSHS_RELIGION,
    :NEW.CD_RSHS_RESPITE,
    :NEW.CD_RSHS_FA_HOME_STATUS,
    :NEW.CD_RSHS_FA_HOME_TYPE1,
    :NEW.CD_RSHS_FA_HOME_TYPE2,
    :NEW.CD_RSHS_FA_HOME_TYPE3,
    :NEW.CD_RSHS_FA_HOME_TYPE4,
    :NEW.CD_RSHS_FA_HOME_TYPE5,
    :NEW.CD_RSHS_FA_HOME_TYPE6,
    :NEW.CD_RSHS_FA_HOME_TYPE7,
    :NEW.CD_RSHS_MHMR_COMP_CODE,
    :NEW.ID_RSHS_FA_HOME_STAGE,
    :NEW.ID_RSHS_FA_HOME_EVENT,
    :NEW.IND_RSHS_CARE_PROV,
    :NEW.IND_RSHS_INACTIVE,
    :NEW.IND_RSHS_TRANSPORT,
    :NEW.IND_RSHS_EMERG_PLACE,
    :NEW.NM_RSHS_RESOURCE,
    :NEW.NM_RSHS_CONTACT,
    :NEW.NM_RSHS_LAST_UPDATE,
    :NEW.NBR_RSHS_VID,
    :NEW.NBR_RSHS_PHN,
    :NEW.NBR_RSHS_FACIL_CAPACITY,
    :NEW.NBR_RSHS_FACIL_ACCLAIM,
    :NEW.NBR_RSHS_PHONE_EXT,
    :NEW.NBR_RSHS_CAMPUS_NBR,
    :NEW.NBR_RSHS_ANNUAL_INCOME,
    :NEW.NBR_RSHS_FM_AGE_MAX,
    :NEW.NBR_RSHS_FM_AGE_MIN,
    :NEW.NBR_RSHS_MA_AGE_MAX,
    :NEW.NBR_RSHS_MA_AGE_MIN,
    :NEW.NBR_RSHS_INT_CHILDREN,
    :NEW.NBR_RSHS_INT_FE_AGE_MAX,
    :NEW.NBR_RSHS_INT_FE_AGE_MIN,
    :NEW.NBR_RSHS_INT_MA_AGE_MAX,
    :NEW.NBR_RSHS_INT_MA_AGE_MIN,
    :NEW.NBR_RSHS_OPEN_SLOTS,
    :NEW.TXT_RSHS_ADDR_CMNTS,
    :NEW.TXT_RSHS_COMMENTS,
    :NEW.IND_RSHS_WRITE_AUDIT ,
    :NEW.DT_CCL_UPDATE,
    :NEW.CD_RSRC_MHMR_SITE,
    :NEW.IND_RSRC_CONTRACTED,
    :NEW.NM_LEGAL,
    :NEW.NM_RSRC_CONTACT_TITLE,
    :NEW.NBR_RSRC_NTNL_PROVIDER,
    :NEW.ADDR_RSRC_EMAIL,
    :NEW.ADDR_RSRC_WEBSITE,
    :NEW.CD_SCHOOL_TYPE,
    :NEW.CD_PAYMENT_DELIVERY,
    :NEW.TXT_SPEC_CERT,
    :NEW.CD_EXCHANGE_STAT,
    :NEW.IND_WAIVER,
    :NEW.CD_SCH_DIST,
    :NEW.CD_ELEM,
    :NEW.CD_MIDDLE,
    :NEW.CD_HIGH,
    :NEW.DT_FOST_MANUAL,
    :NEW.DT_FOST_BILL,
    :NEW.IND_SPECIFIC_CHILD,
    :NEW.DT_LIC_BEGIN,
    :NEW.DT_LIC_END,
    :NEW.TXT_CLOSURE_COMM,
    :NEW.NDFCS_CERT_ENTITY,
    :NEW.IND_RSRC_NONDFCS,
    :NEW.IND_CURR_HM_STDY_EXSTS,
    :NEW.IND_PREV_FAM_STDY_RQSTD,
    :New.RSRC_OTH_SPC_CERTF,
    :New.IND_AFTER_HOURS,
    :New.TXT_HM_PRG_INTEREST,
    :New.NBR_RSRC_CONTACT_PHN,
    :New.NBR_RSRC_CONTACT_PHONE_EXT,
    :NEW.IND_IVE_REIMBURSABLE,
    :NEW.DT_REIMBURSABLE_EFFECTIVE,
    :NEW.DT_REIMBURSABLE_END
  );
END;
/





insert into caps.schema_version(id_schema_version,application_version,comments)
            values (973, 'SacwisRev4', 'Release 4.2 - DBCR 16084');

commit;

