--STGAP00015971 - Release(4.0) MR-072 Records Check DBCR

alter table CAPS.CW_CASE_ERRORS add TXT_CUSTOM_MESSAGE CLOB;
COMMENT ON COLUMN CAPS.CW_CASE_ERRORS.TXT_CUSTOM_MESSAGE IS
'Customized Error Message for Case Watch';


UPDATE CAPS.CODES_TABLES SET dt_end = SYSDATE WHERE CODE_TYPE= 'CCHKTYPE' AND CODE= 'VS';
UPDATE CAPS.CODES_TABLES SET dt_end = SYSDATE WHERE CODE_TYPE= 'CCHKTYPE' AND CODE= 'SV';
UPDATE CAPS.CODES_TABLES SET dt_end = SYSDATE WHERE CODE_TYPE= 'CCHKTYPE' AND CODE= 'PH';
UPDATE CAPS.CODES_TABLES SET dt_end = SYSDATE WHERE CODE_TYPE= 'CCHKTYPE' AND CODE= 'SO';
UPDATE CAPS.CODES_TABLES SET dt_end = SYSDATE WHERE CODE_TYPE= 'CCHKTYPE' AND CODE= 'IS';
UPDATE CAPS.CODES_TABLES SET dt_end = SYSDATE WHERE CODE_TYPE= 'CCHKTYPE' AND CODE= 'LE';

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CCHKTYPE','GS','GA SHINES', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CCHKTYPE','PS','Protective Services Data System', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CCHKTYPE','IM','IDS Online Master Index', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CCHKTYPE','IC','IDS Placement Central', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CCHKTYPE','SR','Sexual Offender Registry', SYSDATE);
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CCHKTYPE','GH','Georgia Health Partnership Portal', SYSDATE);


INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME, 
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) 
VALUES(SYSDATE,60765,'MSG_PREVENT_ADD_RECORDS_CHECK','A view search must be completed for %s before adding Records Check.', 
700,500,'N');

INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME, 
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) 
VALUES(SYSDATE,60766,'MSG_INT_RECORDS_CHECK_WARN','There is one or more Principal or Member of Primary Caretaker''s Household upon whom a Records Check has not been completed. Please click OK to Continue or Cancel to Add Records Check.', 
700,500,'N');

INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME, 
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) 
VALUES(SYSDATE,60767,'MSG_RECORDS_CHECK_REQ','There is one or more Principal or Member of Primary Caretaker''s Household upon whom a Records Check has not been completed.', 
700,500,'N');

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CCASEERR','CUS','Customized Message', SYSDATE);


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (877, 'SacwisRev4', 'Release 4.0 - DBCR 15971');

commit;

