--STGAP00015879 - Release(3.5) SMS47871 - Implement batch locks for Prior Period

INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList',SYSDATE,'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES
('PRPERIODADJ','gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization',SYSDATE,'N');

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (808, 'SacwisRev3', 'Release 3.5 - DBCR 15879');

commit;



