
-- change 159 R1/R2
UPDATE CAPS.CODES_TABLES SET DT_END = to_date('01/01/2006','MM/DD/YYYY') 
WHERE CODE = 'XR' AND CODE_TYPE = 'CSUFFIX';

--change 161 R2 ONLY
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CITEMLOC', 'CAS', 'Case File', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CITEMLOC', 'UPL', 'Uploaded', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CITEMLOC', 'FOS', 'Foster Home', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CITEMLOC', 'OTH', 'Other', SYSDATE);

-- change 162 R2 ONLY
update CAPS.MESSAGE set TXT_MESSAGE = 'Next Review Date cannot be before Plan Prepared date.' where NBR_MESSAGE = 5010 and TXT_MESSAGE_NAME = 'MSG_SVC_REVIEW_BEF_COMP_WARN'; 

update CAPS.MESSAGE set TXT_MESSAGE = 'Next Review Date cannot be more than 90 days from the Date Reviewed with Family.' where NBR_MESSAGE = 25110 and TXT_MESSAGE_NAME = 'MSG_FP_REV_WITHIN_THREE_MONTHS';

-- change 163 R2 ONLY
update CAPS.TASK set IND_TASK_NEW_USING = 1 where TXT_TASK_DECODE = 'Family Plan';

-- change 166 R2 ONLY
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CEXDOTYP', 'PA', 'PAD Information Services', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CEXDOTYP', 'FL', 'FAD Letter Of Intent', SYSDATE);

-- change 167 R2 ONLY
INSERT INTO CAPS.MESSAGE(NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) 
VALUES (60060, 'MSG_EXT_DOC_UPLOAD_CONFIRM', 'Uploading will replace the current uploaded document', 700, 500, 'N');

-- change 168 R2 ONLY
INSERT INTO caps.codes_tables (code_type, code, DECODE) VALUES ('CSIDEFAM', 'ML', 'Maternal');
INSERT INTO caps.codes_tables (code_type, code, DECODE) VALUES ('CSIDEFAM', 'PT', 'Paternal');
INSERT INTO caps.codes_tables (code_type, code, DECODE) VALUES ('CSIDEFAM', 'OT', 'Other');

-- change 169 R2 ONLY
UPDATE CAPS.CODES_TABLES SET CODE = 'COT', CODE_TYPE = 'CFAROLE' 
WHERE CODE_TYPE = 'CFAROLE ' AND CODE = 'CONT'; 

UPDATE CAPS.CODES_TABLES SET CODE = 'DFP' 
WHERE CODE_TYPE = 'CFAROLE' AND CODE = 'DFST'; 

UPDATE CAPS.CODES_TABLES SET CODE = 'DFS' 
WHERE CODE_TYPE = 'CFAROLE' AND CODE = 'DSTF'; 

-- change 171 R2 ONLY
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '01', 'January', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '02', 'February', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '03', 'March', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '04', 'April', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '05', 'May', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '06', 'June', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '07', 'July', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '08', 'August', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '09', 'September', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '10', 'October', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '11', 'November', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CMONTHS', '12', 'December', SYSDATE); 

-- change 172 R2 ONLY
INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CINSTYPE', 'PRV', 'Private', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CINSTYPE', 'MIL', 'Military', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CINSTYPE', 'GOV', 'Government', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES 
(code_type, code, DECODE, dt_last_update) 
VALUES ('CINSTYPE', 'GRP', 'Group', SYSDATE); 

-- change 173 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CWVRTYP','WCS','Contact Standards',sysdate); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CWVRTYP','WAS','Additional Services',sysdate); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CWVRTYP','WCL','Child Life History',sysdate); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CWVRTYP','WPW','Placement Waiver',sysdate); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) 
VALUES('CWVRTYP','WLC','Level of Care Provider',sysdate); 

-- change 175 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CYEAR','06','2006', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CYEAR','07','2007', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CYEAR','08','2008', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CYEAR','09','2009', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CYEAR','10','2010', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CYEAR','11','2011', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CYEAR','12','2012', SYSDATE); 

-- change 176 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','501','501 - IV-E Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','502','502 - State Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','503','503 - Initial Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','504','504 - State Related Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','505','505 - IV-E Institutional Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','506','506 - State Child Welfare - Institutional Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','507','507 - Initial Institutional Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','511','511 - Comprehensive Child and Family Assessment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','513','513 - Return of Runaways',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','518','518 - CCFA Wrap Around Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','520','520 - Respite Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','521','521 - PUP',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','522','522 - State CW Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','525','525 - Medical Exams and Records',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','529','529 - Illegal Immigrant Children in Family Foster Home',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','530','530 - State Illegal Immigrant Children in FC',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','531','531 - Foster/Adoptive Parent Support Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','542','542 - Enhanced Relative Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','551','551 - Early Intervention and Prevention Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','552','552 - Subsidized Guardianship and Enhanced Subsidized Guardianship',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','553','553 - Relative Care Subsidy RCS',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','560','560 - IV-E Voluntary Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','561','561 - IV-E Voluntary Institutional Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','563','563 - Illegal Immigrant Children in Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','564','564 - IV-B Privately Supervised Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','565','565 - Initial Privately Supervised Family Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','571','571 - Homestead Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','573','573 - Parent Aide Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','574','574 - Specialized Foster Care - State Approved Per Diem Waivers',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','576','576 - State Related Specialized Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','578','578 - State Child Welfare Related Specialized Foster Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','583','583 - Educational Related Expenses for Youth 21-25',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','584','584 - College/Vocational Related Expenses',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','585','585 - Educational and Enrichment Expenses',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','586','586 - Transitional Living Program',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','588','588 - Family Services (CPPC)',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','591','591 - Education and Training Voucher',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','597','597 - Wraparound Parental Custody',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','598','598 - Wraparound DFCS Custody',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','705','705 - IV-E Institutional CCI Treatment Cost',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','773','773 - PSSF - Crisis Intervention',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','774','774 - PSSF - Family Support Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','783','783 - PSSF - Time Limited Reunification',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','784','784 - PSSF - Adoption Promotion',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','873','873 - PSSF C/M Crisis Intervention',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','874','874 - PSSF - C/M Family Support',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','883','883 - PSSF - C/M Time Limited Reunification',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CPRGCODE','884','884 - PSSF - C/M Adoption Promotion',SYSDATE);

-- change 177 R2 ONLY
INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCSRSN','CIN','Incarcerated', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCSRSN','COS','Out Of State', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCSRSN','CWU','Whereabouts UnKnown', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCSRSN','CLM','Living in Motel', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCSRSN','COT','Other', SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CWCSRSN','CHO','Hospitalized', SYSDATE); 

-- change 178 R2/R1
update caps.MESSAGE set TXT_MESSAGE = 'A Date From and Date To has been entered; at least one of the following additional criteria must be entered; First Name and Last Name, City, County, or Region. ' 
    where NBR_MESSAGE = 3009 and TXT_MESSAGE_NAME = 'MSG_INT_INSUFF_PARMS';   
     
Insert into CAPS.MESSAGE 
  (ID_MESSAGE, DT_LAST_UPDATE, NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) 
Values 
  (0, sysdate, 60061, 'MSG_INT_INSUFF_PARMS_DEFAULT', 'Insufficient number of parameters for search. Please enter more parameters.', 700, 500, 'N');

-- change 179 R2/R1
UPDATE CAPS.CODES_TABLES 
SET DT_END = NULL 
WHERE CODE_TYPE = 'CSRCRPTR' AND CODE IN ('AM','CW','DH','DN','HC','LW','NC','ONM','PH','PO','RLS','TAN','UK');

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (108, 'SacwisRev2', 'static updates');
                         
commit;
