
-- Alter Index SQL

CREATE INDEX CAPS.IND_DILIGENT_SEARCH_2
    ON CAPS.DILIGENT_SEARCH(ID_CASE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_DILIGENT_SEARCH_1
    ON CAPS.DILIGENT_SEARCH(ID_PERSON_SEARCH,ID_PERSON_DETAIL)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_FCCP_CHILD_CBX_1
    ON CAPS.FCCP_CHILD_CBX(ID_EVENT,CD_CBX_CODE_TYPE)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX CAPS.IND_TRIBAL_1
    ON CAPS.TRIBAL(ID_PERSON)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };

--change STGAP00001579
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0091', 'Attorney');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0092', 'CASA');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0093', 'Child Support ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0094', 'Court related services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0095', 'Guardian Ad Liteum');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0096', 'Immigration Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0097', 'Judge');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0098', 'Legal Advocate');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0099', 'Legal Aid');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0910', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0911', 'Paternity Testing');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0912', 'Special Asst. Attorney General');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0081', 'City Police');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0082', 'County Police');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0083', 'County Sheriff');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0084', 'Department of Juvenile Justice');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0085', 'Drug Task Force');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0086', 'FBI');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0087', 'GBI');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0088', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0501', 'Alternative Schools');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0502', 'Early Intervention-School');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0503', 'Elementary');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0504', 'High School');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0505', 'Middle School');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0506', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0507', 'Post Secondary(College)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0508', 'Pre/Kindergarten');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0509', 'Tutoring');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0510', 'Vocational Training');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1501', 'Youth Development/ILP');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0301', 'Behavioral Management');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0302', 'Couns/Therapy-Family');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0303', 'Couns/Therapy-Group');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0304', 'Couns/Therapy-Individual');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0305', 'Crisis Intervention');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0306', 'Diagnostic Consultation');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0307', 'Home Based Therapy');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0308', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0309', 'Support Groups');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0310', 'Wrap-Around Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1001', 'Dentist/Dental Svs');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1002', 'Family Planning');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1003', 'Health Department');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1004', 'Hearing and Vision Screening');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1005', 'HIV/AIDS/STD Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1006', 'Hospitals');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1007', 'Immunizations');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1008', 'Occupational Therapy');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1009', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1010', 'Pediatrician/Dr. Office');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1011', 'Physical Therapy');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1012', 'Psychiatric Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1013', 'Speech Therapy');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1401', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1402', 'Substance Abuse Assessments');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1403', 'Substance Abuse Detoxication');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1404', 'Substance Abuse Education');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1405', 'Substance Abuse Intervention');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1406', 'Substance Abuse Lab Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1407', 'Substance Abuse-Family');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1408', 'Substance Abuse-Group');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1409', 'Substance Abuse-Ind.');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1410', 'Support Groups');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0401', 'Licensed ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0402', 'Licensed in-home');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0403', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0404', 'Unlicensed(in-home)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0201', 'Clothing');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0202', 'Domestic Violence (Non) Shelter');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0203', 'Employment Assistance');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0204', 'Financial Assistance');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0205', 'Food/Nutrition');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0206', 'Furniture');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0207', 'Homeless Shelters');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0208', 'Housing');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0209', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0210', 'Transportation');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0211', 'Utilities');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0212', 'Vocational Training');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0601', 'DFCS Foster Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0602', 'Emergency Foster Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0603', 'Non-DFCS Foster Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0604', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0605', 'Relative Care Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0606', 'Relative Foster Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0607', 'Respite Foster Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0101', 'Crisis Intervention');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0102', 'DFCS Adoption Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0103', 'DFCS Foster/Adoptive Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0104', 'Non-DFCS Adoption Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0105', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1101', 'CCFA');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1102', 'Child Life History/Life Books');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1103', 'CPPC (Family Services)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1104', 'Drug Screens');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1105', 'Early Intervention');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1106', 'Foster Home Conversion');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1107', 'Homestead Providers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1108', 'IMPACT ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1109', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1110', 'Parent Aide Providers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1111', 'PSSF Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1112', 'Pup Providers');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1113', 'Wrap Around Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1201', 'Child Caring Institute');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1202', 'Child Placing Agency');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1203', 'Emergency Shelters');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1204', 'Independent Living Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1205', 'Maternity Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1206', 'Mental Health Hospital');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1207', 'Mental Retardation Hospital');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1208', 'Non-Relative Subsidized Guardianship Homes');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1209', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1210', 'Therapeutic Camps');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1211', 'Therapeutic Hospitals');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1301', 'Early Childhood Intervention');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1302', 'Immigration');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1303', 'Interpreter/Translator');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1304', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '1305', 'Program Development/Delayed Children');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0701', 'Alcohol/Drug Abuse');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0702', 'Child Abuse Neglect');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0703', 'Domestic Violence');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0704', 'FA Home Recruitment');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0705', 'Other');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0706', 'Poison Control');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0707', 'Runaway');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVCCD', '0708', 'Suicide ');

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '584', '584 - College/Vocational Related Expenses');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '585', '585 - Educational and Enrichment Expenses');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '586', '586 - Transitional Living Program');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '587', '587 - Adoption Incentives - Second Grant ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '588', '588 - Family Services (CPPC)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '591', '591 - Education and Training Voucher ');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '595', '595 - CCI Parental Custody/Purchased Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '596', '596 - CPA Parental Custody/Purchased Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '597', '597 - Wraparound Parental Custody');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '598', '598 - Wraparound DFCS Custody');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '604', '604 - State Related Foster Care Expenses');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '605', '605 - IV-E Institutional Foster Care (CCI)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '606', '606 - State CW - Intuitional Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '607', '607 - Initial Institutional Foster Care');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '608', '608 - IV-E Voluntary Institutional Foster Care (CCI)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '609', '609 - IV-E Privately Supervised FFC (CPA)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '610', '610 - State Privately Supervised FFC (CPA)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '611', '611 - Initial TANF Privately Supervised FFC (CPA)');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '698', '698 - Emergency/ Disasters');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '773', '773 - PSSF - Crisis Intervention');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '774', '774 - PSSF - Family Support Services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '783', '783 - PSSF - Time Limited Reunification');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '784', '784 - PSSF - Adoption Promotion');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '873', '873 - PSSF - C/M Crisis Intervention');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '874', '874 - PSSF - C/M Family Support\');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '883', '883 - PSSF- C/M Time Limited Reunification');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CPROGCDE', '884', '884 - PSSF - C/M  Adoption Promotion');

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0901', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0902', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0903', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0904', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0905', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0906', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0907', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0908', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0909', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0910', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0911', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0912', '09');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0801', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0802', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0803', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0804', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0805', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0806', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0807', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0808', '08');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0501', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0502', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0503', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0504', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0505', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0506', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0507', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0508', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0509', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0510', '05');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1501', '15');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0301', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0302', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0303', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0304', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0305', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0306', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0307', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0308', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0309', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0310', '03');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1001', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1002', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1003', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1004', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1005', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1006', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1007', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1008', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1009', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1010', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1011', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1012', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1013', '10');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1401', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1402', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1403', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1404', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1405', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1406', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1407', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1408', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1409', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1410', '14');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0401', '04');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0402', '04');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0403', '04');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0404', '04');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0201', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0202', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0203', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0204', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0205', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0206', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0207', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0208', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0209', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0210', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0211', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0212', '02');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0601', '06');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0602', '06');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0603', '06');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0604', '06');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0605', '06');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0606', '06');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0607', '06');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0101', '01');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0102', '01');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0103', '01');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0104', '01');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0105', '01');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1101', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1102', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1103', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1104', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1105', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1106', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1107', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1108', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1109', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1110', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1111', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1112', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1113', '11');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1201', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1202', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1203', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1204', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1205', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1206', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1207', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1208', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1209', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1210', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1211', '12');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1301', '13');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1302', '13');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1303', '13');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1304', '13');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '1305', '13');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0701', '07');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0702', '07');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0703', '07');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0704', '07');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0705', '07');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0706', '07');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0707', '07');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CGLSVLNK', '0708', '07');

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88383g', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S3a', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S3b', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S4a', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S4b', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S4c', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S4d', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S4e', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '883S4f', '883');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88484a', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88484b', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88484c', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '88484d', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S1', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S1a', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S1b', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S1c', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S1d', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S2', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S2a', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S2b', '884');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CFLSVLNK', '884S2c', '884');
UPDATE CAPS.CODES_TABLES CT SET CT.DECODE='Business-Bill' WHERE CT.CODE='03'AND CT.CODE_TYPE='CRSCADDR';
UPDATE CAPS.CODES_TABLES CT SET CT.DECODE='Business-Mail' WHERE CT.CODE='04' AND CT.CODE_TYPE='CRSCADDR';
UPDATE CAPS.CODES_TABLES CT SET CT.DECODE='Facility' WHERE CT.CODE='05' AND CT.CODE_TYPE='CRSCADDR';
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CRSCADDR', '08', 'Emergency');

-- change STGAP00001580

INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAA','Child or Parent is Available for Adoptive Placement',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAB','County Placed Child or Family on Hold For an Identified Regular Adoptive Placement',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAC','Family and/or Child Selected',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAD','Not Ready',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAE','Long Term Foster Care ',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAF','Goal Not Adoption (Emancipation)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAG','In Regular Adoptive Placement ',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAH','In Foster Parent Adoptive Placement',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAI','In Foster/Adopt Placement',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAJ','In Relative Adoptive Placement',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAK','In Relative Foster Parent Adoptive Placement',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAL','Current Goal Reunification With Other Parent',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCNAV','AAM','Plan Independent Relative Custody',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','CON','Counseling',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','LBW','Lifebook Work',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','GBY','Goodbye Visit with Birth Parents',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','FFC','Foster Family Discussion with Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','CMC','Case Manager Discussion with Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','PPV','Pre-Placement Visits',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','PHO','Get Photographs of Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','PVC','Prepare Video of Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','MFC','Make Flyer of Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADCPAC','XXX','Other',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','MTN','My Turn Now',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','WED','Wednesdays Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','VIC','Video Conference',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','CAP','CAP Book/Website',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','HEG','Heart Gallery',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','AUS','AdoptUSKids',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','NEW','Newspaper Features',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACS','XXX','Other',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','PMM','Paper Matching Meeting',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','FMM','Family Matching Meeting',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','DVP','Display and Video Presentations',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','WWK','Wendys Wonderful Kids',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','ADA','Adopt America',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','NEF','Newspaper Features',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','NET','Networking',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADRACC','XXX','Other',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBREC','ROC','Resistance of Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBREC','SNC','Special Needs of Child',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBREC','RFA','Recruitment Funds Not Available',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBREC','CNF','Child Not Legally Free for Adoption',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBREC','XXX','Other',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','LAH','Lack of Adoptive Homes',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','BFC','Need to maintain Birth Family Connections ',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','FHC','Foster Home Conversion not Completed',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','LSG','Large Sibling Group',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','ATP','Appeal of TPR',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','CLH','Child Life History not Completed',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','RES','Resource not Identified ',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','SNC','Special Needs of Child(ren)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','ROC','Resistiveness of Child(ren)',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','OTP','TPR Overturned',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES('CADBPLA','XXX','Other',sysdate);

-- change STGAP00001582
INSERT INTO CAPS.MESSAGE
(id_message, nbr_message, txt_message_name, 
txt_message)
VALUES (0, 60158, 'MSG_DT_CRT_ACTION_REQ', 'Date Of Court Action must be entered when Court Mandated Closure is checked.');

-- change STGAP00001583
INSERT INTO CAPS.MESSAGE
(id_message, nbr_message, txt_message_name, 
txt_message)
VALUES (0, 60159, 'MSG_BUDGET_EXCEEDED', 'This service authorization exceed the currently budgeted amount for the entitlement code.');
INSERT INTO CAPS.MESSAGE
(id_message, nbr_message, txt_message_name, 
txt_message)
VALUES (0, 60160, 'MSG_WAIVER_REQUIRED', 'Waiver selection is necessary when the Waiver Required checkbox is selected.');
INSERT INTO CAPS.MESSAGE
(id_message, nbr_message, txt_message_name, 
txt_message)
VALUES (0, 60161, 'MSG_WAIVER_REQUIREMENTS','Selected resource does not match the resource requirements specified in the waiver.');

-- change STGAP00001585
-- CELYINTV
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CELYINTV','CLS','Closed-Low Risk, Substantiated',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CELYINTV','CLU','Closed-Unsubstantiated',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CELYINTV','SOD','Screened Out, Diversion',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CELYINTV','OCR','Open Case Reassessed as Low Risk and Closed',SYSDATE);

-- CPPOUTCM
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','APP','Prevented Placement',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','ADP','Did Not Prevent Placement',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','BSR','Successful Reunification',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','BUR','Unsuccessful Reunification',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','CIM','Improved',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','CNC','No Change',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','DDS','Diverted from Social Services',SYSDATE);
INSERT INTO CAPS.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPPOUTCM','DND','Not Diverted from Social Services',SYSDATE);

--change STGAP00001590
INSERT INTO CAPS.TASK
(cd_task, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, TXT_TASK_DECODE,
CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG,
IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE,
IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_1ST_TAB,
TXT_2ND_TAB, TXT_3RD_TAB,
TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE,
IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
VALUES
('6510', 'RSF', 'PFC', 'Restricted Funds',
'CPS', '1', '1',
'1', '0', '0',
'0', '1', 'CASE_CASESEARCH',
'PERSON_PERSONLIST', 'RESTRICTED_FUNDS',
'/financials/RestrictedFunds/taskDisplay', 3, '0',
'0', '0');
INSERT INTO CAPS.TASK
(cd_task, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, TXT_TASK_DECODE,
CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG,
IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE,
IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_1ST_TAB,
TXT_2ND_TAB, TXT_3RD_TAB,
TXT_EVENT_DETAIL_URL)
VALUES
('6520', 'APP', 'PFC', 'Approve Restricted Funds',
'CPS', '0', '1',
'1', '0', '0',
'0', '0', 'CASE_CASESEARCH',
'PERSON_PERSONLIST', 'RESTRICTED_FUNDS',
'/financials/RestrictedFunds/taskDisplay');

--change STGAP00001592
UPDATE CAPS.METAPHOR SET 
TXT_FILTER_PATH = 'gov.georgia.dhr.dfcs.sacwis.web.metaphor.FAPersonDetailShowTab'
WHERE id_tab = 1510;

--change STGAP00001594
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES ('CTCMSTAT','DND','Denied',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES ('CTCMSTAT','PAD','Paid',sysdate);
INSERT INTO CAPS.CODES_TABLES(code_type,code,decode,dt_last_update)VALUES ('CTCMSTAT','PND','Pending',sysdate);

--change STGAP00001595
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '1128', 'The Member ID is missing or invalid and the claim does not have an attachment');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2141', 'Member not found');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2143', 'Member not eligible');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2222', 'Member name mismatch');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2266', 'QMB member eligible for MCARE crossover only');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2712', 'Member has elected to receive hospice services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2714', 'Claim spans a member hospice segment');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2716', 'Member has elected to receive hospice services');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2723', 'Member name is missing or invalid');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2725', 'a conflict exists between the aid category (PeachCare - 790 thru 793 and the service received');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2727', 'Hospice certification pending');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2746', 'Claim exceeds filing time period - without attachment');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '2750', 'The date of birth entered on the claim does not match the date of birth on the member detail table');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '4117', 'Procedure/age conflict');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '4321', 'The procedure code is not covered');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '4354', 'Procedure does not contain a category of service pricing segment for the claim line date of service');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '4355', 'Procedure/age conflict for category of service');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '4908', 'Procedure requires price');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '5750', 'Member has primary insurance coverage - resubmit with COB');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '5761', 'Member has COB resource and the service or COB resource indicates pay and chase');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '6007', 'Procedures code not allowed for the same date of service as a complete health check screening');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES('CTCMDEN', '6029', 'Case management claim cannot be billed in the same calendar month as a paid claim form the same or another case management program');

--change STGAP00001596
UPDATE CAPS.TASK
SET ind_task_code_prefer=3
WHERE cd_task='3450'
OR cd_task='4430'
OR cd_task='7030'
OR cd_task='8920';

--change STGAP00001599
INSERT INTO CAPS.MESSAGE
(id_message, nbr_message, txt_message_name, 
txt_message)
VALUES (0, 60162, 'MSG_FIN_NO_STAFF', 'No Staff ID entered');
INSERT INTO CAPS.MESSAGE
(id_message, nbr_message, txt_message_name, 
txt_message)
VALUES (0, 60163, 'MSG_FIN_NO_UNIT_OR_STAFF', 'No Unit or Person Entered');

--change STGAP00001600
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION, IND_BATCH) 
  VALUES (60164, 'MSG_RSRC_DT_MED_REC_FUTURE_DT_REQ' 
,'Last Medical Records Check Date cannot be a future date',500,700,'N');

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (133, 'SacwisRev2', 'static updates, indexes');

commit;
