--STGAP00016014 - Release(4.1) MR-074: AFCARS Add CODES_TABLES, MESSAGE, PERSON

--MR-074: AFCARS Phase 1 Add New Columns in CAPS.PERSON

ALTER TABLE CAPS.PERSON ADD IND_SINGLE_PAR_ADOPT VARCHAR2(1);
COMMENT ON COLUMN CAPS.PERSON.IND_SINGLE_PAR_ADOPT IS 'Indicator whether single parent adoption or not';

ALTER TABLE CAPS.PERSON ADD CD_SINGLE_MOTHER_FATHER VARCHAR2(2);
COMMENT ON COLUMN CAPS.PERSON.CD_SINGLE_MOTHER_FATHER IS 'Code indicating whether a previous single parent adoption was single mother or single father';

  CREATE OR REPLACE VIEW CAPS.PERSON_ENC (ID_PERSON, DT_LAST_UPDATE, CD_PERSON_SEX, ADDR_PERSON_ST_LN_1, ADDR_PERSON_CITY, ADDR_PERSON_ZIP, DT_PERSON_DEATH, DT_PERSON_BIRTH, CD_PERSON_RELIGION, CD_PERSON_CHAR, CD_PERSON_LIV_ARR, CD_PERS_GUARD_CNSRV, CD_PERSON_STATUS, CD_PERSON_DEATH, CD_PERSON_MARITAL_STATUS, CD_PERSON_LANGUAGE, CD_PERSON_ETHNIC_GROUP, CD_PERSON_STATE, CD_PERSON_COUNTY, IND_PERSON_DOB_APPROX, IND_PERS_CANCEL_HIST, NBR_PERSON_AGE, NBR_PERSON_PHONE, NBR_PERSON_ID_NUMBER, NM_PERSON_FIRST, NM_PERSON_MIDDLE, NM_PERSON_LAST, NM_PERSON_FULL, TXT_PERSON_OCCUPATION, CD_PERSON_SUFFIX, IND_AUTO_PERS_MERGE, CD_DISASTER_RLF, CD_PERSON_TITLE, IND_PERSON_US_CITIZEN, CD_PERSON_IMMIGRATION_STATUS, CD_PERSON_COUNTRY_ORIGIN, TXT_CHAR_CMNTS, CD_PERS_NOT_YET_DIAG, CD_PERSON_PROOF_CITIZENSHIP, TXT_PERSON_OTHER_RELATIONSHIPS, CD_MATCH_TYPE, CD_SMILE_CLIENT, TXT_IDS_NUMBER, IND_PREV_ADOPTED, IND_PRIVATE, IND_PUBLIC, IND_INTRNTL, CD_ADOPT_STATE, CD_ADOPT_COUNTY, CD_ADOPT_CNTRY, IND_ADOPT_DISLUTON, TXT_PERSON_ADDL_CMNTS, DT_DISSOLUTION, DT_PREV_ADOPTION, TXT_NAME_OF_ADO_AGENCY, IND_ADOPT_FINALIZED, IND_ADOPT_AFCARS_SENT, IND_ADOPTED, IND_SINGLE_PAR_ADOPT, CD_SINGLE_MOTHER_FATHER) AS 
  select ID_PERSON,DT_LAST_UPDATE,CD_PERSON_SEX,ADDR_PERSON_ST_LN_1,ADDR_PERSON_CITY,ADDR_PERSON_ZIP,DT_PERSON_DEATH,DT_PERSON_BIRTH,CD_PERSON_RELIGION,CD_PERSON_CHAR,CD_PERSON_LIV_ARR,CD_PERS_GUARD_CNSRV,CD_PERSON_STATUS,CD_PERSON_DEATH,CD_PERSON_MARITAL_STATUS,CD_PERSON_LANGUAGE,CD_PERSON_ETHNIC_GROUP,CD_PERSON_STATE,CD_PERSON_COUNTY,IND_PERSON_DOB_APPROX,IND_PERS_CANCEL_HIST,NBR_PERSON_AGE,NBR_PERSON_PHONE,NBR_PERSON_ID_NUMBER,NM_PERSON_FIRST,NM_PERSON_MIDDLE,NM_PERSON_LAST,NM_PERSON_FULL,TXT_PERSON_OCCUPATION,CD_PERSON_SUFFIX,IND_AUTO_PERS_MERGE,CD_DISASTER_RLF,CD_PERSON_TITLE,IND_PERSON_US_CITIZEN,CD_PERSON_IMMIGRATION_STATUS,CD_PERSON_COUNTRY_ORIGIN,TXT_CHAR_CMNTS,CD_PERS_NOT_YET_DIAG,CD_PERSON_PROOF_CITIZENSHIP,TXT_PERSON_OTHER_RELATIONSHIPS,CD_MATCH_TYPE,CD_SMILE_CLIENT,TXT_IDS_NUMBER,IND_PREV_ADOPTED,IND_PRIVATE,IND_PUBLIC,IND_INTRNTL,CD_ADOPT_STATE,CD_ADOPT_COUNTY,CD_ADOPT_CNTRY,IND_ADOPT_DISLUTON,TXT_PERSON_ADDL_CMNTS,DT_DISSOLUTION,DT_PREV_ADOPTION,TXT_NAME_OF_ADO_AGENCY,IND_ADOPT_FINALIZED,IND_ADOPT_AFCARS_SENT,IND_ADOPTED, IND_SINGLE_PAR_ADOPT, CD_SINGLE_MOTHER_FATHER from PERSON;
 


-- MR-074 AFCARS Phase 1 Add New CODES_TABLES

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES
('CSPATYPE', 'SM', 'Single Mother');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES
('CSPATYPE', 'SF', 'Single Father');

-- MR-074 AFCARS Phase 1 Add New MESSAGE

INSERT INTO CAPS.MESSAGE
(ID_MESSAGE,DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES
(0,SYSDATE,60779,'MSG_ADO_SINGLE_PARENT_REQ',
'If Previously Adopted, ''Was this a single parent adoption?'' is required.',
700,500,'N');

INSERT INTO CAPS.MESSAGE
(ID_MESSAGE,DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES
(0,SYSDATE,60780,'MSG_ADO_SINGLE_PARENT_ERR',
'If the previous adoption is a single parent adoption, please select Single Mother or Single Father.',
700,500,'N');



insert into caps.schema_version(id_schema_version,application_version,comments)
            values (910, 'SacwisRev4', 'Release 4.1 - DBCR 16014');

commit;


