--STGAP00017077 - Release(5.0) MR-092 New ADO_SIBLING_EXT_LNK_HISTORY table

CREATE TABLE CAPS.ADO_SIBLING_EXT_LNK_HISTORY
  (
    ID_ADO_SIB_EXT_LNK_HIST NUMBER(16,0) NOT NULL,
    DT_LAST_UPDATE DATE NOT NULL,
    ID_ADO_INFO_EVENT NUMBER(16,0) NOT NULL,
    DT_ADO_INFO_COMPLETE DATE NOT NULL,
    ID_SIBLING_GROUP NUMBER(16,0) NOT NULL,
    ID_PERSON NUMBER(16,0) NOT NULL,
    ID_SIBLING_EXTERNAL_STAGE NUMBER(16,0) NOT NULL,
    CONSTRAINT PK_ADO_SIB_EXT_LNK_HST PRIMARY KEY (ID_ADO_SIB_EXT_LNK_HIST),
    CONSTRAINT FK_ADO_SIB_EXT_LNK_HST_ADO_INF FOREIGN KEY (ID_ADO_INFO_EVENT) REFERENCES CAPS.ADO_INFO (ID_EVENT),
    CONSTRAINT FK_ADO_SIB_EXT_LNK_HST_PERSON FOREIGN KEY (ID_PERSON) REFERENCES CAPS.PERSON (ID_PERSON),
    CONSTRAINT FK_ADO_SIB_EXT_LNK_HST_STAGE FOREIGN KEY (ID_SIBLING_EXTERNAL_STAGE) REFERENCES CAPS.STAGE (ID_STAGE)
  );

COMMENT ON COLUMN CAPS.ADO_SIBLING_EXT_LNK_HISTORY.ID_ADO_SIB_EXT_LNK_HIST IS 'Primary Key';
COMMENT ON COLUMN CAPS.ADO_SIBLING_EXT_LNK_HISTORY.DT_LAST_UPDATE IS 'Date record last updated';
COMMENT ON COLUMN CAPS.ADO_SIBLING_EXT_LNK_HISTORY.ID_ADO_INFO_EVENT IS 'Adoption Information event id';
COMMENT ON COLUMN CAPS.ADO_SIBLING_EXT_LNK_HISTORY.DT_ADO_INFO_COMPLETE IS 'Date Adoption Information event was completed';
COMMENT ON COLUMN CAPS.ADO_SIBLING_EXT_LNK_HISTORY.ID_SIBLING_GROUP IS 'Primary child''s sibling group id';
COMMENT ON COLUMN CAPS.ADO_SIBLING_EXT_LNK_HISTORY.ID_PERSON IS 'Sibling id who has an ADO stage in a different case';
COMMENT ON COLUMN CAPS.ADO_SIBLING_EXT_LNK_HISTORY.ID_SIBLING_EXTERNAL_STAGE IS 'Sibling''s ADO stage id in a different case';

grant select,update,insert,delete on CAPS.ADO_SIBLING_EXT_LNK_HISTORY to capson,capsbat,ops$datafix;
grant select on caps.ADO_SIBLING_EXT_LNK_HISTORY to operator,shinesdm;

CREATE SEQUENCE CAPS.SEQ_ADO_SIB_EXT_LNK_HIST INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;
grant select on caps.SEQ_ADO_SIB_EXT_LNK_HIST to capson,capsbat,ops$datafix;

/
CREATE OR REPLACE TRIGGER CAPS.TIBR_ADO_SIB_EXT_LNK_HIST
 BEFORE INSERT
  ON CAPS.ADO_SIBLING_EXT_LNK_HISTORY
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
  declare
     dummy number(16);
  BEGIN
    :new.DT_LAST_UPDATE := SYSDATE;
    IF :new.ID_ADO_SIB_EXT_LNK_HIST = 0 THEN
      SELECT  CAPS.SEQ_ADO_SIB_EXT_LNK_HIST.NEXTVAL
      INTO  dummy
      FROM dual;
      :new.ID_ADO_SIB_EXT_LNK_HIST := dummy;
    END IF;
  END;
/

/
CREATE OR REPLACE TRIGGER CAPS.TUBR_ADO_SIB_EXT_LNK_HIST
BEFORE UPDATE
ON CAPS.ADO_SIBLING_EXT_LNK_HISTORY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (1094, 'SacwisRev5', 'Release 5.0 - DBCR 17077');

commit;
