-- change STGAP00005430
INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV,CD_EQUIV_FUNDING_STREAM,CD_EQUIV_OBJ_ALW,
CD_EQUIV_PAC,CD_EQUIV_STAGE,CD_EQUIV_STAGE_TYPE,
CD_EQUIV_SVC_DTL_SERVICE,DT_EQUIV_START_DATE,DT_EQUIV_END_DATE,NBR_EQUIV_OBJ_ALW,
NBR_EQUIV_OBJ_CERT,NBR_EQUIV_OBJ_PURE) VALUES
(0,'SB','574SB',574,'ALL','ALL','574SB',TO_DATE('01/01/2007','MM/DD/YYYY'),
TO_DATE('12/31/4712','MM/DD/YYYY'),1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV,CD_EQUIV_FUNDING_STREAM,CD_EQUIV_OBJ_ALW,
CD_EQUIV_PAC,CD_EQUIV_STAGE,CD_EQUIV_STAGE_TYPE,
CD_EQUIV_SVC_DTL_SERVICE,DT_EQUIV_START_DATE,DT_EQUIV_END_DATE,NBR_EQUIV_OBJ_ALW,
NBR_EQUIV_OBJ_CERT,NBR_EQUIV_OBJ_PURE) VALUES
(0,'SB','575SB',575,'ALL','ALL','575SB',TO_DATE('01/01/2007','MM/DD/YYYY'),
TO_DATE('12/31/4712','MM/DD/YYYY'),1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV,CD_EQUIV_FUNDING_STREAM,CD_EQUIV_OBJ_ALW,
CD_EQUIV_PAC,CD_EQUIV_STAGE,CD_EQUIV_STAGE_TYPE,
CD_EQUIV_SVC_DTL_SERVICE,DT_EQUIV_START_DATE,DT_EQUIV_END_DATE,NBR_EQUIV_OBJ_ALW,
NBR_EQUIV_OBJ_CERT,NBR_EQUIV_OBJ_PURE) VALUES
(0,'SB','577SB',577,'ALL','ALL','577SB',TO_DATE('01/01/2007','MM/DD/YYYY'),
TO_DATE('12/31/4712','MM/DD/YYYY'),1,0,0);

INSERT INTO CAPS.EQUIVALENCY (ID_EQUIV,CD_EQUIV_FUNDING_STREAM,CD_EQUIV_OBJ_ALW,
CD_EQUIV_PAC,CD_EQUIV_STAGE,CD_EQUIV_STAGE_TYPE,
CD_EQUIV_SVC_DTL_SERVICE,DT_EQUIV_START_DATE,DT_EQUIV_END_DATE,NBR_EQUIV_OBJ_ALW,
NBR_EQUIV_OBJ_CERT,NBR_EQUIV_OBJ_PURE) VALUES
(0,'SB','579SB',579,'ALL','ALL','579SB',TO_DATE('01/01/2007','MM/DD/YYYY'),
TO_DATE('12/31/4712','MM/DD/YYYY'),1,0,0);

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (241, 'SacwisRev2', 'insert 4 equivalency rows');  
commit;
