-- Standard Alter Table SQL

ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND MODIFY(NBR_PER_DIEM  NUMBER(10,2))
;
ALTER TABLE SACWISIFC.CHILDSUP_REF_OUTBOUND MODIFY(NBR_PER_MONTH  NUMBER(10,2))
;
ALTER TABLE SACWISIFC.CSUP_PARENT_OUTBOUND MODIFY(NBR_PER_DIEM  NUMBER(10,2))
;
ALTER TABLE SACWISIFC.CSUP_PARENT_OUTBOUND MODIFY(NBR_PER_MONTH  NUMBER(10,2))
;
ALTER TABLE SACWISIFC.INVOICE_OUTBOUND MODIFY(NM_RESOURCE  VARCHAR2(45))
;
ALTER TABLE SACWISIFC.VENDOR_INBOUND MODIFY(NM_RESOURCE  VARCHAR2(45))
;
ALTER TABLE SACWISIFC.VENDOR_OUTBOUND MODIFY(NM_RESOURCE  VARCHAR2(45))
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- STGAP00004404
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE,CODE,DECODE,DT_LAST_UPDATE) VALUES ('CRBPROGI','a','Base',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','b','AWO',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','c','MWO',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','d','Emergency Shelter',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','e','Camp',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','f','2nd Chance',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','g','Teen Development',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','h','Maternity Home',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','i','MAAC',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','j','SR1',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','k','SR2',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','l','SR3',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','m','SR4',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGI','n','MWO Emergency Shelter',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','o','CCI TBD 1',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','p','CCI TBD 2',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','q','CCI TBD 3',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','r','CCI TBD 4',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','s','CCI TBD 5',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','t','CCI TBD 6',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','u','CCI TBD 7',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','v','CCI TBD 8',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','w','CCI TBD 9',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','x','CCI TBD 10',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','y','CCI TBD 11',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGI','z','CCI TBD 12',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','a','Traditional',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','b','Base',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','c','MWO',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','d','SSMD',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','e','MSSMD',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','f','HMF',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','g','SPRTF1',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','h','SPRTF2',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','i','SPRTF3',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CRBPROGA','j','SPRTF4',SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','k','CPA TBD 1',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','l','CPA TBD 2',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','m','CPA TBD 3',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','n','CPA TBD 4',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','o','CPA TBD 5',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','p','CPA TBD 6',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','q','CPA TBD 7',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','r','CPA TBD 8',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','s','CPA TBD 9',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','t','CPA TBD 10',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','u','CPA TBD 11',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','v','CPA TBD 12',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','w','CPA TBD 13',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','x','CPA TBD 14',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','y','CPA TBD 15',SYSDATE,SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_END, DT_LAST_UPDATE) VALUES ('CRBPROGA','z','CPA TBD 16',SYSDATE,SYSDATE);

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (221, 'SacwisRev2', 'static updates, column expansion in sacwisifc');                        
commit;
