
-- Standard Alter Table SQL

ALTER TABLE CAPS.CASE_FILE_MANAGEMENT ADD TXT_PRIOR_CMNTS VARCHAR2(300)     NULL
;

-- Standard Alter Table SQL

DROP INDEX CAPS.IND_CASE_LINK_1
;

-- Drop Referencing Constraint SQL


-- Drop Constraint, Rename and Create Table SQL

ALTER TABLE CAPS.TRIBAL DROP CONSTRAINT FK_TRIBAL_PERSON
;
ALTER TABLE CAPS.TRIBAL DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE CAPS.TRIBAL RENAME TO TRIBAL_11192006010349000
;
CREATE TABLE CAPS.TRIBAL
(
    ID_TRIBAL                 NUMBER(16)   NOT NULL,
    ID_PERSON                 NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE            DATE         NOT NULL,
    NBR_TRBL_PERCENT_HERITAGE NUMBER(3)        NULL,
    TXT_TRIBAL_NAME           VARCHAR2(75)     NULL,
    NBR_TRIBAL_REGISTRY       VARCHAR2(15)     NULL,
    IND_TRBL_MEMBER           VARCHAR2(1)      NULL,
    IND_TRBL_REGISTERED       VARCHAR2(1)      NULL
)
TABLESPACE DATA01
NOLOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 1M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON COLUMN CAPS.TRIBAL.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON CAPS.TRIBAL TO CAPSBAT
;
GRANT INSERT ON CAPS.TRIBAL TO CAPSBAT
;
GRANT SELECT ON CAPS.TRIBAL TO CAPSBAT
;
GRANT UPDATE ON CAPS.TRIBAL TO CAPSBAT
;
GRANT DELETE ON CAPS.TRIBAL TO CAPSON
;
GRANT INSERT ON CAPS.TRIBAL TO CAPSON
;
GRANT SELECT ON CAPS.TRIBAL TO CAPSON
;
GRANT UPDATE ON CAPS.TRIBAL TO CAPSON
;
GRANT SELECT ON CAPS.TRIBAL TO OPERATOR
;

-- Insert Data SQL

ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO CAPS.TRIBAL(
                        ID_TRIBAL,
                        ID_PERSON,
                        DT_LAST_UPDATE,
                        NBR_TRBL_PERCENT_HERITAGE,
                        TXT_TRIBAL_NAME,
                        NBR_TRIBAL_REGISTRY,
                        IND_TRBL_MEMBER,
                        IND_TRBL_REGISTERED
                       )
                 SELECT 
                        ID_TRIBAL,
                        ID_PERSON,
                        DT_LAST_UPDATE,
                        NBR_TRBL_PERCENT_HERITAGE,
                        TXT_TRIBAL_NAME,
                        TO_CHAR(NBR_TRIBAL_REGISTRY),
                        IND_TRBL_MEMBER,
                        IND_TRBL_REGISTERED
                   FROM CAPS.TRIBAL_11192006010349000 
;
COMMIT
;
ALTER TABLE CAPS.TRIBAL LOGGING
;

-- Add Constraint SQL

ALTER TABLE CAPS.TRIBAL ADD CONSTRAINT PK_TRIBAL
PRIMARY KEY (ID_TRIBAL)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 1M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;

-- Add Indexes SQL


-- Add Dependencies SQL
/
DROP TRIGGER CAPS.TIBR_TRIBAL
/
/
CREATE OR REPLACE TRIGGER CAPS.TIBR_TRIBAL
BEFORE INSERT
ON CAPS.TRIBAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	IF (:new.ID_TRIBAL = 0) THEN
		SELECT	SEQ_TRIBAL.NEXTVAL
		INTO	dummy
		FROM	DUAL;
		:new.ID_TRIBAL := dummy;
	END IF;
END;
/
/
DROP TRIGGER CAPS.TUBR_TRIBAL
/
/
CREATE OR REPLACE TRIGGER CAPS.TUBR_TRIBAL
BEFORE UPDATE
ON CAPS.TRIBAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/

-- Update Views SQL


-- Add Privileges SQL


-- Alter Index SQL

CREATE INDEX CAPS.IND_CASE_LINK_1
    ON CAPS.CASE_LINK(ID_CASE)
TABLESPACE INDEX01
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 2M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE CAPS.TRIBAL ADD CONSTRAINT FK_TRIBAL_PERSON
FOREIGN KEY (ID_PERSON)
REFERENCES CAPS.PERSON (ID_PERSON)
ENABLE
;

DROP TABLE CAPS.TRIBAL_11192006010349000;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };


-- change 201 R2/R1
update caps.message set txt_message = 'Your approval has been recorded. Do you wish to add another approver?' where txt_message_name = 'MSG_CMN_ADD_APRVR';

-- change 200 R2 ONLY

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','00','00 - Other Costs',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','04','04 - Initial Clothing',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','05','05 - Annual Clothing',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','06','06 - Support Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','08','08 - In-Hospital Care',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','10','10 - Unusual Medical/Burial',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','11','11 - Child Restraint Device',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','12','12 - Other Reimbursable Costs',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','17','17 - Supplemental Supervision',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','19','19 - Medical Exams (CCFA/Child)',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','20','20 - Medical Exams - Adult',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','24','24 - Crisis Intervention Prevent Disruption',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','29','29 - Assessments',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','47','47 - Crisis Intervention Behavior Management',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','48','48 - Emergency Housing',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','49','49 - Day Care Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','50','50 - Counseling',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','51','51 - Drug Screens',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','52','52 - Substance Abuse',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','53','53 - Medical/Dental Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','54','54 - Psychological Evaluation',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','56','56 - Transportation',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','61','61 - Homestead Services',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','62','62 - Crisis Intervention Payment',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','67','67 - IMPACT',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','68','68 - Continued Parent Development',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','71','71 - In Home Case Management',SYSDATE); 

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE,CODE,DECODE, DT_LAST_UPDATE) 
VALUES('CENTCODE','72','72 - Parent Aide Services',SYSDATE); 

-- change 203 R2/R1
UPDATE CAPS.CODES_TABLES 
SET code='SFA' 
WHERE code_type='CSFFAC' 
AND code='SF1'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFB' 
WHERE code_type='CSFFAC' 
AND code='SF2'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFC' 
WHERE code_type='CSFFAC' 
AND code='SF3'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFD' 
WHERE code_type='CSFFAC' 
AND code='SF4'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFE' 
WHERE code_type='CSFFAC' 
AND code='SF5'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFF' 
WHERE code_type='CSFFAC' 
AND code='SF6'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFG' 
WHERE code_type='CSFFAC' 
AND code='SF7'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFH' 
WHERE code_type='CSFFAC' 
AND code='SF8'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFI' 
WHERE code_type='CSFFAC' 
AND code='SF9'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFJ' 
WHERE code_type='CSFFAC' 
AND code='SF10'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFK' 
WHERE code_type='CSFFAC' 
AND code='SF11'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFL' 
WHERE code_type='CSFFAC' 
AND code='SF12'; 

UPDATE CAPS.CODES_TABLES 
SET code='SFM' 
WHERE code_type='CSFFAC' 
AND code='SF13';

-- change 206 R2 ONLY
INSERT INTO CAPS.METAPHOR 
(ID_TAB,TXT_TAB_URL,TXT_TAB_CONSTANT,TXT_TAB,TXT_L1_IMG_INACTIVE, 
TXT_L1_IMG_ACTIVE,TXT_FILTER_PATH,DT_LAST_UPDATE) 
VALUES ('1460', '/admin/StaffCorrAcnPlan/displayStaffCorrAcnPlan', 
'STAFF_CORRECTIVE_ACTION_PLAN_LIST_STAFFCORRACNPLANLIST', 
'Staff Corrective<br> Action Plan ',' ',' ', 
'gov.georgia.dhr.dfcs.sacwis.web.metaphor.StaffCorrAcnPlanShowTab',SYSDATE);


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (112, 'SacwisRev2', 'static updates, add column to CASE_FILE_MANAGEMENT, change CASE_LINK index, change datatype in TRIBAL');

commit;                         

