-- change STGAP00001981
INSERT INTO CAPS.MESSAGE (id_message, nbr_message, txt_message_name, txt_message)
VALUES (0, 60300, 'MSG_FCE_COMMENT_CHILD_SUP_REF', 'Please provide Comments as to why this child is not being referred to child support.');

-- change STGAP00001982
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) 
  VALUES (60301, 'MSG_RSRC_DT_END_NO_FUTURE','End Date cannot be a future date.',760,500, 'N');

-- change STGAP00001983
UPDATE CAPS.MESSAGE m
SET m.TXT_MESSAGE = 'No more than two active caretakers can be added to a Placement Provider.'
WHERE m.NBR_MESSAGE=25204;

-- change STGAP00001979
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','252','252 - Children Restricted Funds',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','253','253 - Donated Restricted Funds',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','450','450 - County Funds - Foster Care Children Under 14',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','460','460 - County Funds - Foster Care Children 14 and Over',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','508','508 - State Adoption Assistance',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','509','509 - IV-E Adoption Assistance',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','510','510 - Non-Recurring Adoption Assistance',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','512','512 - Special Services Adoption Assistance',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','547','547 - Emergency Foster Care Beds',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','78','550 - Non-Relative Subidized Guardianship and Enhanced Subsidized Guardianship',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','575','575 - IV-E Voluntary Specialized Foster Care - State Approved Per Diem Waivers',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','577','577 IV-B Child Welfare Specialized Foster Care - State Approved Per Diem Waivers',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','579','579 - Initial Child Welfare Specialized Foster Care - State Approved Per Diem Waivers',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','595','595 - CCI Parental Custody/Purchased Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','596','596 - CPA Parental Custody/Purchased Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','604','604 - State Related Foster Care Expenses',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','605','605 - IV-E Institutional Foster Care (CCI)',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','606','606 - State CW - Institutional Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','607','607 - Initial Institutional Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','608','608 - IV-E Voluntary Instititional Foster Care (CCI)',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','609','609 - IV-E Privately Supervised FFC (CPA)',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','610','610 - State Privately Supervised FFC (CPA)',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','611','611 - Initial TANF Privately Supervised FFC (CPA)',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCODE','698','698 - Emergency/Disasters',SYSDATE);

Update caps.Codes_Tables 
Set decode = '529 - Undocumented Immigrant Children in Family Foster Home'
Where code_type = 'CPRGCODE'
And code = '529';

Update caps.Codes_Tables 
Set decode = '530 - State Undocumented Immigrant Children in IFC'
Where code_type = 'CPRGCODE'
And code = '530';

Update caps.Codes_Tables 
Set decode = '563 - IV-E Privately Supervised Family Foster Care (CPA)'
Where code_type = 'CPRGCODE'
And code = '563';

Update caps.Codes_Tables 
Set decode = '564 - IV-B Privately Supervised Family Foster Care (CPA)'
Where code_type = 'CPRGCODE'
And code = '564';

Update caps.Codes_Tables 
Set decode = '565 - Initial Privately Supervised Family Foster Care (CPA)'
Where code_type = 'CPRGCODE'
And code = '565';

INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','504','504 - State Related Family Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','510','510 - Non-Recurring Adoption Assistance',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','511','511 - Comprehensive Child and Family Assessment',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','512','512 - Special Services Adoption Assistance',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','513','513 - Return of Runaways',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','518','518 - CCFA Wrap Around Services',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','521','521 - PUP',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','522','522 - State CW Family Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','525','525 - Medical Exams and Records',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','531','531 - Foster/Adoptive Parent Support Services',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','547','547 - Emergency Foster Care Beds',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','571','571 - Homestead Services',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','573','573 - Parent Aide Services',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','576','576 - State Related Specialized Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','578','578 - State Child Welfare Related Specialized Foster Care',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','583','583 - Educational Related Expenses for Youth 21-25',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','584','584 - College/Vocational Related Expenses',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','585','585 - Educational and Enrichment Expenses',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','586','586 - Transitional Living Program',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','588','588 - Family Services (CPPC)',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','591','591 - Education and Training Voucher',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','597','597 - Wraparound Parental Custody',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','598','598 - Wraparound DFCS Custody',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','604','604 - State Related Foster Care Expenses',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','698','698 - Emergency/Disasters',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','773','773 - PSSF - Crisis Intervention',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','774','774 - PSSF - Family Support Services',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','783','783 - PSSF - Time Limited Reunification',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','784','784 - PSSF - Adoption Promotion',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','873','873 - PSSF C/M Crisis Intervention',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','874','874 - PSSF - C/M Family Support',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','883','883 - PSSF - C/M Time Limited Reunification',SYSDATE);
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CPRGCOD1','884','884 - PSSF - C/M Adoption Promotion',SYSDATE);

-- change STGAP00001985
insert into CAPS.MESSAGE(NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) values (60302, 'MSG_SVC_SEL_APRV', 'Only Approved Plans can be selected.', 700, 500, 'N');
insert into CAPS.MESSAGE(NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) values (60303, 'MSG_SVC_WVR_VALID', 'The policy Waiver is not valid for the services requested in the current Service Authorization.', 700, 500, 'N');

-- change STGAP00001986
-- These are updates to the CREGOFF and CSVCRGNS codes tables to include the new regions is Georgia

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CREGOFF', '12','Region 12', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CREGOFF', '13','Region 13', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CREGOFF', '14','Region 14', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CREGOFF', '15','Region 15', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CREGOFF', '16','Region 16', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CREGOFF', '17','Region 17', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CREGOFF', '98','Statewide', SYSDATE);

update CAPS.codes_tables set dt_end =to_date('01/01/2006','MM/DD/YYYY')
where code = '00'
and code_type = 'CREGOFF';

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CSVCRGNS', '12','Region 12', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CSVCRGNS', '13','Region 13', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CSVCRGNS', '14','Region 14', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CSVCRGNS', '15','Region 15', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CSVCRGNS', '16','Region 16', SYSDATE);

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) 
VALUES('CSVCRGNS', '17','Region 17', SYSDATE);

update CAPS.codes_tables set dt_end = to_date('01/01/2006','MM/DD/YYYY')
where code = '00'
and code_type = 'CSVCRGNS';

-- change STGAP00001987
Insert into caps.message
   (ID_MESSAGE, DT_LAST_UPDATE, NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH)
 Values
   (0, SYSDATE, 60304, 'MSG_RSRC_PROX_ADDR_INVALID', 
   'The address provided cannot be validated. Please enter a valid address to perform proximity search', 740, 500, 'N');

-- change STGAP00001990
Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER)
 Values
   ('9870',SYSDATE, 'WVR', 'ADO', 'CPS', '1', '1', '1', '0', '0', '0', '1', 'Policy Waiver', 'CASE_CASESEARCH', 'CASE_MANAGEMENT_CASEMNT', 'POLICY_WAIVER_EVENTLIST', '/investigation/PolicyWaiver/displayPolicyWaiver', 3);

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER)
 Values
   ('3235', SYSDATE, 'WVR', 'SUB', 'CPS', '1', '1', '1', '0', '0', '0', '1', 'Policy Waiver', 'CASE_CASESEARCH', 'CASE_MANAGEMENT_CASEMNT', 'POLICY_WAIVER_EVENTLIST', '/investigation/PolicyWaiver/displayPolicyWaiver', 3);

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER)
 Values
   ('8265', SYSDATE, 'WVR', 'FAD', 'CPS', '1', '1', '1', '0', '0', '0', '1', 'Policy Waiver', 'CASE_CASESEARCH', 'CASE_MANAGEMENT_CASEMNT', 'POLICY_WAIVER_EVENTLIST', '/investigation/PolicyWaiver/displayPolicyWaiver', 3);

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER)
 Values
   ('2235', SYSDATE, 'WVR', 'DIV', 'CPS', '1', '1', '1', '0', '0', '0', '1', 'Policy Waiver', 'CASE_CASESEARCH', 'CASE_MANAGEMENT_CASEMNT', 'POLICY_WAIVER_EVENTLIST', '/investigation/PolicyWaiver/displayPolicyWaiver', 3);

-- change STGAP00001992
INSERT INTO caps.codes_tables (code_type, code, DECODE,dt_last_update) VALUES('CSECATTR','PA','MES Program Assistant',SYSDATE); 

-- change STGAP00001999
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES('CFACTYP4', 'RN','Relative (No Payment)', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES('CFACTYP4', 'RC','Relative Care Subsidy', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES('CFACTYP4', 'RE','Relative Enhanced Relative Rate', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES('CFACTYP4', 'RT','Relative TANF', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES('CFACTYP4', 'SG','Subsidized Guardianship', SYSDATE);

-- change STGAP00002007
-- BEGIN CFOSSVCD
-- This represents the Foster Care Services Code values used in the approval process for a Home
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '25200', '25200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '25201', '25201', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '25204', '25204', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '25210', '25210', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '25217', '25217', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '25300', '25300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45000', '45000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45001', '45001', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45004', '45004', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45010', '45010', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45017', '45017', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45091', '45091', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45092', '45092', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45093', '45093', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45094', '45094', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45095', '45095', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45096', '45096', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45097', '45097', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '45098', '45098', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46000', '46000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46001', '46001', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46004', '46004', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46010', '46010', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46017', '46017', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46091', '46091', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46092', '46092', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46093', '46093', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46094', '46094', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46095', '46095', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46096', '46096', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46097', '46097', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '46098', '46098', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50101', '50101', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50102', '50102', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50104', '50104', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50105', '50105', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50117', '50117', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '501SB', '501SB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50201', '50201', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50202', '50202', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50204', '50204', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50205', '50205', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50208', '50208', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50217', '50217', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '502SB', '502SB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50301', '50301', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50302', '50302', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50304', '50304', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50305', '50305', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50308', '50308', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50311', '50311', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50317', '50317', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50399', '50399', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50300a', '50300a', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50300b', '50300b', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50300c', '50300c', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50310a', '50310a', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50310b', '50310b', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50310c', '50310c', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '50310d', '50310d', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '503SB', '503SB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52060', '52060', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52094', '52094', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52901', '52901', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52902', '52902', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52904', '52904', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52905', '52905', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52908', '52908', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52911', '52911', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52917', '52917', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52999', '52999', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52910a', '52910a', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52910b', '52910b', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52910c', '52910c', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '52910d', '52910d', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '529SB', '529SB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '56001', '56001', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '56002', '56002', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '56004', '56004', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '56005', '56005', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '56017', '56017', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '560SB', '560SB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57401', '57401', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57402', '57402', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57404', '57404', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57405', '57405', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57417', '57417', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57499', '57499', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57501', '57501', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57502', '57502', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57504', '57504', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57505', '57505', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57517', '57517', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57599', '57599', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57701', '57701', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57702', '57702', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57704', '57704', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57705', '57705', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57708', '57708', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57717', '57717', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57799', '57799', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57901', '57901', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57902', '57902', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57904', '57904', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57905', '57905', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57908', '57908', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57911', '57911', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57917', '57917', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSSVCD', '57999', '57999', SYSDATE);
-- END CFOSSVCD

-- BEGIN CFOSUTYP
-- This represents the Foster Care Services Unit Type Code values used in the approval process for a Home.  They map to the Foster Care Services Code one-to-one.
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '25200', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '25201', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '25204', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '25210', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '25217', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '25300', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45000', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45001', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45004', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45010', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45017', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45091', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45092', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45093', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45094', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45095', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45096', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45097', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '45098', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46000', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46001', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46004', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46010', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46017', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46091', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46092', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46093', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46094', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46095', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46096', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46097', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '46098', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50101', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50102', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50104', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50105', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50117', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '501SB', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50201', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50202', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50204', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50205', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50208', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50217', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '502SB', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50301', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50302', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50304', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50305', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50308', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50311', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50317', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50399', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50300a', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50300b', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50300c', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50310a', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50310b', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50310c', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '50310d', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '503SB', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52060', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52094', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52901', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52902', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52904', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52905', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52908', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52911', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52917', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52999', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52910a', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52910b', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52910c', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '52910d', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '529SB', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '56001', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '56002', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '56004', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '56005', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '56017', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '560SB', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57401', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57402', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57404', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57405', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57417', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57499', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57501', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57502', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57504', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57505', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57517', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57599', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57701', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57702', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57704', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57705', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57708', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57717', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57799', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57901', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57902', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57904', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57905', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57908', 'DA2', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57911', 'XXX', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57917', 'DAY', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTYP', '57999', 'DA2', SYSDATE);
-- END CFOSUTYP

-- BEGIN CFOSPTYP
-- This represents the Foster Care Services Payment Type Code values used in the approval process for a Home. They map to the Foster Care Services Code one-to-one.
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '25200', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '25201', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '25204', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '25210', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '25217', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '25300', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45000', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45001', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45004', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45010', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45017', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45091', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45092', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45093', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45094', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45095', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45096', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45097', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '45098', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46000', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46001', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46004', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46010', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46017', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46091', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46092', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46093', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46094', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46095', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46096', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46097', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '46098', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50101', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50102', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50104', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50105', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50117', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '501SB', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50201', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50202', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50204', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50205', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50208', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50217', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '502SB', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50301', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50302', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50304', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50305', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50308', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50311', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50317', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50399', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50300a', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50300b', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50300c', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50310a', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50310b', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50310c', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '50310d', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '503SB', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52060', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52094', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52901', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52902', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52904', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52905', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52908', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52911', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52917', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52999', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52910a', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52910b', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52910c', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '52910d', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '529SB', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '56001', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '56002', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '56004', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '56005', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '56017', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '560SB', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57401', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57402', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57404', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57405', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57417', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57499', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57501', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57502', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57504', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57505', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57517', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57599', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57701', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57702', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57704', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57705', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57708', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57717', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57799', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57901', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57902', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57904', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57905', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57908', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57911', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57917', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSPTYP', '57999', 'VUR', SYSDATE);
-- END CFOSPTYP

-- BEGIN CFOSUTRT
-- This represents the Foster Care Services Unit Rate values used in the approval process for a Home. They map to the Foster Care Services Code one-to-one.
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '25200', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '25201', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '25204', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '25210', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '25217', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '25300', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45000', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45001', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45004', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45010', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45017', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45091', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45092', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45093', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45094', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45095', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45096', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45097', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '45098', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46000', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46001', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46004', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46010', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46017', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46091', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46092', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46093', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46094', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46095', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46096', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46097', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '46098', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50101', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50102', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50104', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50105', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50117', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '501SB', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50201', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50202', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50204', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50205', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50208', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50217', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '502SB', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50301', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50302', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50304', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50305', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50308', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50311', '500', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50317', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50399', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50300a', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50300b', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50300c', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50310a', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50310b', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50310c', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '50310d', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '503SB', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52060', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52094', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52901', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52902', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52904', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52905', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52908', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52911', '500', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52917', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52999', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52910a', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52910b', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52910c', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '52910d', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '529SB', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '56001', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '56002', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '56004', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '56005', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '56017', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '560SB', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57401', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57402', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57404', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57405', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57417', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57499', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57501', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57502', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57504', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57505', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57517', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57599', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57701', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57702', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57704', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57705', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57708', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57717', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57799', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57901', '18.25', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57902', '1.75', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57904', '300', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57905', '200', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57908', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57911', '500', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57917', '100', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CFOSUTRT', '57999', '1000', SYSDATE);
-- END CFOSUTRT

-- BEGIN CADOSVCD
-- This represents the Adoption Services Code values used in the approval process for a Home
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '50807', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '50813', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '50913', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51033a', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51033b', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51033c', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51033d', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51033e', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51033f', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51217', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51257', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51260', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51277', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51258a', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51258b', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51258c', '', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOSVCD', '51258d', '', SYSDATE);
-- END CADOSVCD

-- BEGIN CADOUTYP
-- This represents the Adoption Services Unit Type Code values used in the approval process for a Home.  They map to the Adoption Services Code one-to-one.
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '50807', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '50813', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '50913', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51033a', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51033b', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51033c', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51033d', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51033e', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51033f', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51217', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51257', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51260', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51277', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51258a', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51258b', 'SUB', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTYP', '51258c', 'SUB', SYSDATE);
-- END CADOUTYP

-- BEGIN CADOPTYP
--This represents the Adoption Services Payment Type Code values used in the approval process for a Home. They map to the Adoption Services Code one-to-one.
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '50807', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '50813', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '50913', 'URT', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51033a', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51033b', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51033c', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51033d', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51033e', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51033f', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51217', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51257', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51260', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51277', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51258a', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51258b', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51258c', 'VUR', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOPTYP', '51258d', 'VUR', SYSDATE);
-- END CADOPTYP

--BEGIN CADOUTRT
--This represents the Adoption Services Unit Rate values used in the approval process for a Home. They map to the Adoption Services Code one-to-one.
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '50807', '433.43', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '50813', '433.43', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '50913', '433.43', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51033a', '2000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51033b', '2000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51033c', '2000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51033d', '2000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51033e', '2000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51033f', '2000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51217', '500', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51257', '5000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51260', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51277', '3000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51258a', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51258b', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51258c', '1000', SYSDATE);
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES( 'CADOUTRT', '51258d', '1000', SYSDATE);
-- END CADOUTRT


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (157, 'SacwisRev2', 'static updates');                        
commit;
