-- Standard Alter Table SQL

ALTER TABLE CAPS.CNSRVTRSHP_REMOVAL MODIFY(TXT_DESCRIPTION_OF_INCIDENT  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_EFFRTS_REM  VARCHAR2(1000))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_CHILD_ADJ_COMM  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_AFSA  VARCHAR2(1000))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_TPR  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_STEPS  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_ADDTL_INFO  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_IMM_UTD  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_IMM_ONFILE  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_ONGOING_PROB  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_MEDREC_ONFILE  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_PSYCH_ONFILE  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_EVAL_DATES  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_CHILD MODIFY(TXT_RELEVANT_MED  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_FAMILY MODIFY(TXT_PRIM_COMP_RSNS  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_FAMILY MODIFY(TXT_SECND_COMP_RSNS  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_FAMILY MODIFY(TXT_RSNS_PROT  VARCHAR2(1000))
;
ALTER TABLE CAPS.FCCP_FAMILY MODIFY(TXT_HARM  VARCHAR2(1000))
;
ALTER TABLE CAPS.FCCP_FAMILY MODIFY(TXT_PRNT_PRTCPT  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_FAMILY MODIFY(TXT_CHILD_PRTCPT  VARCHAR2(500))
;
ALTER TABLE CAPS.FCCP_FAMILY MODIFY(TXT_RSN_DSCHRG_AFTERCARE  VARCHAR2(500))
;
ALTER TABLE CAPS.PLAN_GOAL MODIFY(TXT_GOAL  VARCHAR2(1000))
;
ALTER TABLE CAPS.PLAN_SEC_GOAL MODIFY(TXT_DESC  VARCHAR2(1000))
;
ALTER TABLE CAPS.PLAN_STEP MODIFY(TXT_STEP  VARCHAR2(1000))
;
ALTER TABLE CAPS.PLAN_STEP MODIFY(TXT_STEP_COMM  VARCHAR2(1000))
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (249, 'SacwisRev2', 'extend column width to match CPRS');                                    
commit;
