--STGAP00016005 - Release(4.01) Record Check R4 conversion

--This is to supplement STGAP00016000: to add 3 new record check types: IM, IC, PS for every PH. A PH is considered equivalent to these 3. PH is endated in R4 so convert all existing PH record checks by adding these new types to each PH. This DBCR is complement of STGAP00016000 so there will not be overlapping between the 2 populations.

-- Adding IM record check for stages that do not id_case populated for but the stage belongs to a case
insert into caps.records_check 
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,IND_RECCHK_RECMNDATN) 
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'IM',r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.stage s, caps.caps_case c 
where r.id_case is null and r.cd_rec_check_check_type = 'PH'
and r.id_stage = s.id_stage and s.id_case = c.id_case
and (c.dt_case_closed is null or c.dt_case_closed=to_date('12/31/4712', 'MM/DD/YYYY'));
-- Adding IM record check for stages that has yet assigned a case like open intake
insert into caps.records_check 
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,IND_RECCHK_RECMNDATN) 
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'IM',r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.stage s 
where r.id_case is null and r.cd_rec_check_check_type = 'PH'
and r.id_stage = s.id_stage and s.dt_stage_close is null
and s.id_case is null;                
-- Adding IC record check for stages that do not id_case populated for but the stage belongs to a case
insert into caps.records_check 
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,IND_RECCHK_RECMNDATN) 
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'IC',r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.stage s, caps.caps_case c 
where r.id_case is null and r.cd_rec_check_check_type = 'PH'
and r.id_stage = s.id_stage and s.id_case = c.id_case
and (c.dt_case_closed is null or c.dt_case_closed=to_date('12/31/4712', 'MM/DD/YYYY'));
-- Adding IC record check for stages that has yet assigned a case like open intake
insert into caps.records_check 
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,IND_RECCHK_RECMNDATN) 
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'IC',r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.stage s 
where r.id_case is null and r.cd_rec_check_check_type = 'PH'
and r.id_stage = s.id_stage and s.dt_stage_close is null
and s.id_case is null;                
-- Adding PS record check for stages that do not id_case populated for but the stage belongs to a case
insert into caps.records_check 
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,IND_RECCHK_RECMNDATN) 
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'PS',r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.stage s, caps.caps_case c 
where r.id_case is null and r.cd_rec_check_check_type = 'PH'
and r.id_stage = s.id_stage and s.id_case = c.id_case
and (c.dt_case_closed is null or c.dt_case_closed=to_date('12/31/4712', 'MM/DD/YYYY'));
-- Adding PS record check for stages that has yet assigned a case like open intake
insert into caps.records_check 
(ID_REC_CHECK,DT_LAST_UPDATE,ID_REC_CHECK_PERSON,ID_REC_CHECK_REQUESTOR,ID_STAGE,ID_CASE,CD_REC_CHECK_CHECK_TYPE,CD_REC_CHECK_EMP_TYPE,CD_REC_CHECK_STATUS,DT_REC_CHECK_COMPLETED,DT_REC_CHECK_REQUEST,TXT_REC_CHECK_COMMENTS,IND_RECCHECK_HISTORY,DT_REC_CHECK_CRIM_REL_REC,IND_RECCHK_FPCARD,IND_RECCHK_LIVE_SCAN,DT_RECCHK_FP_CARD_GIVEN,DT_RECCHK_FP_CARD_RETURN,DT_RECCHK_LS_PERFORMED,DT_RECCHK_LSRESULT_REC,IND_RECCHK_REFUSE_INV_CLRNCE,IND_RECCHK_FPCHK_RESULT,IND_RECCHK_RECMNDATN) 
select 0,sysdate,r.ID_REC_CHECK_PERSON,r.ID_REC_CHECK_REQUESTOR,r.ID_STAGE,r.ID_CASE,'PS',r.CD_REC_CHECK_EMP_TYPE,r.CD_REC_CHECK_STATUS,r.DT_REC_CHECK_COMPLETED,r.DT_REC_CHECK_REQUEST,r.TXT_REC_CHECK_COMMENTS,r.IND_RECCHECK_HISTORY,r.DT_REC_CHECK_CRIM_REL_REC,r.IND_RECCHK_FPCARD,r.IND_RECCHK_LIVE_SCAN,r.DT_RECCHK_FP_CARD_GIVEN,r.DT_RECCHK_FP_CARD_RETURN,r.DT_RECCHK_LS_PERFORMED,r.DT_RECCHK_LSRESULT_REC,r.IND_RECCHK_REFUSE_INV_CLRNCE,r.IND_RECCHK_FPCHK_RESULT,r.IND_RECCHK_RECMNDATN
from caps.records_check r, caps.stage s 
where r.id_case is null and r.cd_rec_check_check_type = 'PH'
and r.id_stage = s.id_stage and s.dt_stage_close is null
and s.id_case is null;    


insert into caps.schema_version(id_schema_version,application_version,comments)
            values (908, 'SacwisRev4', 'Release 4.01 - DBCR 16005');

commit;






