
--STGAP00014574 - Show UDR Resource Dev Rept Link and Update Params

UPDATE "CAPS"."REPORTS" SET IND_RPT_PAGE = 'Y' WHERE NM_RPT_SQR_NAME = 'UDRResourceDevRept' AND NM_RPT_SQR_VER = '00';


delete from caps.REPORT_PARAMETER
where NM_RPT_SQR_NAME = 'UDRResourceDevRept'
and NM_RPT_SQR_VER = '00'
and NBR_RPT_PARM_SEQ =	'1'
and NBR_RPT_PARM_LENGTH = '10'
and NM_RPT_PARM_NAME = 	'BEGINDATE'
and TXT_RPT_PARM_TYPE =	'DATE'
and IND_REQUIRED = 	'Y';

UPDATE caps.REPORT_PARAMETER
SET NBR_RPT_PARM_SEQ =	'1'
WHERE NM_RPT_SQR_NAME = 'UDRResourceDevRept'
AND NM_RPT_SQR_VER = '00'
AND NM_RPT_PARM_NAME = 'ENDDATE';

UPDATE caps.REPORT_PARAMETER
SET NM_RPT_PARM_LABEL =	'As of (MM/DD/YYYY)'
WHERE NM_RPT_SQR_NAME = 'UDRResourceDevRept'
AND NM_RPT_SQR_VER = '00'
AND NM_RPT_PARM_NAME = 'ENDDATE';

UPDATE caps.REPORT_PARAMETER
SET NBR_RPT_PARM_SEQ =	'2'
WHERE NM_RPT_SQR_NAME = 'UDRResourceDevRept'
AND NM_RPT_SQR_VER = '00'
AND NM_RPT_PARM_NAME = 'REGIONCD';

UPDATE caps.REPORT_PARAMETER
SET NBR_RPT_PARM_SEQ =	'3'
WHERE NM_RPT_SQR_NAME = 'UDRResourceDevRept'
AND NM_RPT_SQR_VER = '00'
AND NM_RPT_PARM_NAME = 'COUNTYCD';


--STGAP00014583 - MR-034 New Codes Table values for Rerate batch

UPDATE CAPS.CODES_TABLES 
SET DECODE = 'Not Adjustment'
WHERE CODE_TYPE = 'CINVADJT'
AND CODE = 'N';

UPDATE CAPS.CODES_TABLES 
SET DECODE = 'Non IV-E Adjustment'
WHERE CODE_TYPE = 'CINVADJT'
AND CODE = 'Y';

UPDATE CAPS.CODES_TABLES 
SET DECODE = 'IV-E Adjustment'
WHERE CODE_TYPE = 'CINVADJT'
AND CODE = 'C';

INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE,DT_LAST_UPDATE) VALUES
('CINVADJT','R','Recoupment',SYSDATE);


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (492, 'SacwisRev3', 'Release 3.2 - DBCRs 14574,14583,14583');

commit;


