--STGAP00015823 - Release(3.5) DBCR Admin Review Decision Letter Form Narrative

--Add table and triggers for Administrative Review Decision Letter Form

CREATE TABLE CAPS.ADMN_RVW_DECISION_NARR ( 
	ID_EVENT NUMBER(16,0) NOT NULL ENABLE, 
	DT_LAST_UPDATE DATE NOT NULL ENABLE, 
	ID_CASE NUMBER(16,0), 
	CD_TYPE VARCHAR2(1) NOT NULL ENABLE, 
  NARRATIVE LONG RAW,
  ID_DOCUMENT_TEMPLATE NUMBER(16,0),
    CONSTRAINT PK_ADMN_RVW_DECISION_NARR PRIMARY KEY (ID_EVENT, CD_TYPE) using index tablespace index01,
    CONSTRAINT FK_ADMN_RVW_DECISION_REF_EVENT FOREIGN KEY (ID_EVENT) REFERENCES CAPS.EVENT(ID_EVENT),
    CONSTRAINT FK_ADMN_RVW_DECISION_REF_CASE FOREIGN KEY (ID_CASE) REFERENCES CAPS.CAPS_CASE(ID_CASE)
) tablespace data01;


grant select,update,insert,delete on caps.ADMN_RVW_DECISION_NARR to capson,capsbat,ops$datafix;

grant select  on caps.ADMN_RVW_DECISION_NARR to operator,shinesdm;


/
CREATE OR REPLACE TRIGGER CAPS.TIBR_ADMN_RVW_DECISION_NARR 
BEFORE INSERT ON CAPS.ADMN_RVW_DECISION_NARR
FOR EACH ROW

BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
	SELECT	ID_CASE
	INTO		:new.ID_CASE
	FROM		EVENT
	WHERE 	ID_EVENT = :new.ID_EVENT;
EXCEPTION
	WHEN OTHERS THEN
		IF SQL%NOTFOUND THEN
			:new.ID_CASE := NULL;
		END IF;
END;
/

/
CREATE OR REPLACE TRIGGER CAPS.TUBR_ADMN_RVW_DECISION_NARR 
BEFORE UPDATE ON CAPS.ADMN_RVW_DECISION_NARR
FOR EACH ROW

BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (770, 'SacwisRev3', 'Release 3.5 - DBCR 15823');

commit;

