-- change STGAP00006992
update CAPS.REPORTS set NM_RPT_DESC='Multiple statistics reported for foster care cases in the county within the month. Generated for a specific case manager and service month.' where NM_RPT_SQR_NAME='FosterCareMonthlyStatus';
update CAPS.REPORTS set NM_RPT_DESC='Multiple statistics reported for ongoing cases in the county within the month. Generated for a specific case manager and service month.',NM_RPT_AREA_TYPE='Ongoing',IND_RPT_PAGE='Y' where NM_RPT_SQR_NAME='FamilyPreservationMonthlyStatus';
update CAPS.REPORTS set NM_RPT_DESC='A list of foster care cases that have been opened for more than 45 days without an approved eligibility determination.  Generated for a specific county.',NM_RPT_ORIENTATION='P',IND_RPT_PAGE='Y' where NM_RPT_SQR_NAME='OverStandardOfPromptness';
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'StaffToDoList', '00', 7, 'A', 'Staff To-Do List', 'ondport', 'L', 'W', 'A list of outstanding alerts and tasks generated for a specific case manager.', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'CaseHistoryOfInvestigations', '00', 7, 'A', 'Case History of Investigations', 'ondport', 'P', 'W', 'Investigation details generated for a specific case.', 'Investigation', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'pendingincidents', '00', 7, 'A', 'Pending Incidents', 'ondport', 'P', 'W', 'A list of pending investigations and the days outstanding from the intake date.  Generated for a specific county.', 'Investigation', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'fprmonthlystatistics', '00', 7, 'A', 'Family Preservation Monthly Statistics ', 'ondport', 'P', 'W', 'Multiple statistics reported for ongoing cases in the county within the month. Generated for a specific county and service month with an optional unit parameter.', 'Ongoing', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'FosterCareDischargeReport', '00', 7, 'A', 'Foster Care Discharge Report ', 'ondport', 'P', 'W', 'A list of children who exited foster care during the reporting month.  Generated for a specific county and service month.', 'Foster Care', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'caseloadlisting', '00', 7, 'A', 'Caseload Listing (Worker)', 'ondport', 'L', 'W', 'A list of active cases currently assigned to the case manager. ', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'caseloadlistingcounty', '00', 7, 'A', 'Caseload Listing (County)', 'ondport', 'L', 'W', 'A comprehensive view of all caseloads in a county grouped by unit then by case manager.  Generated for a specific county with an optional unit parameter.', 'Administration', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'afcarsdischarge', '00', 7, 'A', 'Foster Care Discharge', 'ondport', 'P', 'W', 'A list of children who exited foster care during the reporting month.  Generated for a specific county and service month.', 'Foster Care', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'fosterhomeinquiry', '00', 7, 'A', 'Foster Home Inquiry', 'ondport', 'P', 'W', 'Outstanding inquiries of people interested in becoming foster parents.  ', 'Resource Development', 'Y');
insert into CAPS.REPORTS (DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_RETAINAGE, NM_RPT_TYPE, TXT_RPT_FULL_NAME, NM_RPT_TEMPLATE_NAME, NM_RPT_ORIENTATION, TXT_RPT_EMAIL_OPTIONS, NM_RPT_DESC, NM_RPT_AREA_TYPE, IND_RPT_PAGE) values (sysdate, 'TCMMonthlyBillingStatistics', '00', 7, 'A', 'TCM Monthly Billing Statistics', 'ondport', 'P', 'W', 'Counts and percentages of TCM claims during the month.  Generated for a specific region and service month with an optional county parameter.', 'Administration', 'N');

delete from CAPS.REPORT_PARAMETER where NM_RPT_SQR_NAME='FamilyPreservationMonthlyStatus';
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FosterCareMonthlyStatus', '00', 2, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'StaffToDoList', '00', 1, 16, 'WORKERID', 'CHAR', 'Y', 'Staff ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'CaseHistoryOfInvestigations', '00', 1, 16, 'CASEID', 'CHAR', 'Y', 'Case ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'pendingincidents', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'pendingincidents', '00', 2, 3, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'fprmonthlystatistics', '00', 1, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'fprmonthlystatistics', '00', 2, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'fprmonthlystatistics', '00', 3, 3, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FosterCareDischargeReport', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FosterCareDischargeReport', '00', 2, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FamilyPreservationMonthlyStatus', '00', 1, 16, 'WORKERID', 'CHAR', 'Y', 'Staff ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'FamilyPreservationMonthlyStatus', '00', 2, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'caseloadlisting', '00', 1, 16, 'WORKERID', 'CHAR', 'Y', 'Staff ID');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'caseloadlistingcounty', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'caseloadlistingcounty', '00', 2, 3, 'UNIT', 'CHAR', 'N', 'Unit');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'afcarsdischarge', '00', 1, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'afcarsdischarge', '00', 2, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'fosterhomeinquiry', '00', 1, 3, 'COUNTYCD', 'CHAR', 'Y', 'County');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'TCMMonthlyBillingStatistics', '00', 1, 7, 'MONTHYEAR', 'CHAR', 'Y', 'Month/Year');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'TCMMonthlyBillingStatistics', '00', 2, 3, 'REGIONCD', 'CHAR', 'Y', 'Region');
insert into CAPS.REPORT_PARAMETER (ID_RPT_PARAMETER, DT_LAST_UPDATE, NM_RPT_SQR_NAME, NM_RPT_SQR_VER, NBR_RPT_PARM_SEQ, NBR_RPT_PARM_LENGTH, NM_RPT_PARM_NAME, TXT_RPT_PARM_TYPE, IND_REQUIRED, NM_RPT_PARM_LABEL) values (0, sysdate, 'TCMMonthlyBillingStatistics', '00', 3, 3, 'COUNTYCD', 'CHAR', 'N', 'County');

insert into caps.schema_version (id_schema_version, application_version, comments)
                       values (272, 'SacwisRev2', 'static table updates - Report tables');
commit;