--STGAP00011071 -Correct the message nbr dbcr 10310

update caps.message set nbr_message=60492 where TXT_MESSAGE_NAME  = 'MSG_ASGN_LSTED_TWICE';


-- STGAP00011002

insert all
   when not exists(select 'x' from caps.security_class where CD_SECURITY_CLASS_NAME = 'IT HELP DESK') then
into caps.security_class
   select 'IT HELP DESK',to_date('10/05/2008','MM/DD/YYYY'),'01010000000001001111100000000000000000000000000000000000000000000000000000000000000000000000','N',(Select min(id_person) from caps.emp_sec_class_link
where CD_SECURITY_CLASS_NAME = 'SYS_ADMIN')
     from dual;

insert all
   when not exists(select 'x' from caps.security_class where CD_SECURITY_CLASS_NAME = 'MED_BILL_MGMT') then
into caps.security_class
   select 'MED_BILL_MGMT',to_date('10/05/2008','MM/DD/YYYY'),'10000001100100000000000000000000000000000000000001001001000001100000000000010000000001000000','N',(Select min(id_person) from caps.emp_sec_class_link 
where CD_SECURITY_CLASS_NAME = 'SYS_ADMIN')
     from dual;

insert all
   when not exists(select 'x' from caps.security_class where CD_SECURITY_CLASS_NAME = 'MED_BILL_STAFF') then
into caps.security_class
   select 'MED_BILL_STAFF',to_date('10/05/2008','MM/DD/YYYY'),'10000000100100000000000000000000000000000000000001001001000001100000000000010000000000000000','N',(Select min(id_person) from caps.emp_sec_class_link 
where CD_SECURITY_CLASS_NAME = 'SYS_ADMIN')
     from dual;

insert all
   when not exists(select 'x' from caps.security_class where CD_SECURITY_CLASS_NAME = 'ORS_PRU MAINT') then
into caps.security_class
   select 'ORS_PRU MAINT',to_date('11/05/2008','MM/DD/YYYY'),'00000000000000000001000000000000000000000000000000000000000000000000000000000000000000001000','N',(Select min(id_person) from caps.emp_sec_class_link 
where CD_SECURITY_CLASS_NAME = 'SYS_ADMIN')
     from dual;

insert all
   when not exists(select 'x' from caps.security_class where CD_SECURITY_CLASS_NAME = 'SAU_SEALED') then
into caps.security_class
   select 'SAU_SEALED',to_date('10/16/2008','MM/DD/YYYY'),'00000010001000000000000000000000000000000000000000000101000000000000010001000000000001000011','N',(Select min(id_person) from caps.emp_sec_class_link 
where CD_SECURITY_CLASS_NAME = 'SYS_ADMIN')
     from dual;

insert all
   when not exists(select 'x' from caps.security_class where CD_SECURITY_CLASS_NAME = 'SAU_STAFF') then
into caps.security_class
   select 'SAU_STAFF',to_date('10/21/2008','MM/DD/YYYY'),'00000010001000000000000000000000000000000000000000000101000000010000010001000000000001000001','N',(Select min(id_person) from caps.emp_sec_class_link 
where CD_SECURITY_CLASS_NAME = 'SYS_ADMIN')
     from dual;

insert all
   when not exists(select 'x' from caps.security_class where CD_SECURITY_CLASS_NAME = 'SENSITIVE_CASE') then
into caps.security_class
   select 'SENSITIVE_CASE',to_date('11/05/2008','MM/DD/YYYY'),'00000010000000000001000000000000000000000000000000000000000000000000000000000000000000000000','N',(Select min(id_person) from caps.emp_sec_class_link 
where CD_SECURITY_CLASS_NAME = 'SYS_ADMIN')
     from dual;



-----------------Adding missing bytes for SENSITIVE_CASE----------------
UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '00'
WHERE CD_SECURITY_CLASS_NAME = 'SENSITIVE_CASE'
and length(TXT_SECURITY_CLASS_PROFIL) = 88;

----------------SECURITY PROFILE for Regional Adoption Coordinator ----------------------------
INSERT INTO CAPS.CODES_TABLES (code_type, code, DECODE, dt_last_update) VALUES ('CSECATTR', 'PJ', 'Regional Adoption Coordinator', SYSDATE);

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'CASE_MANAGER'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'CONTRACT_LEAD'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'CONTRACTED_CBO'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'COUNTY_MGMNT'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'DJJ_AFCARS'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'DPTY_CNTY_DRCTR'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'FSCL_SVC_ST_STF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'IT HELP DESK'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_01'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_02'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_03'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_04'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_05'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_06'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_07'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_08'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_09'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_10'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_11'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_12'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_13'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_14'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_15'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_16'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_17'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_99'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MED_BILL_MGMT'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MED_BILL_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MES_PROG_ASST'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'OFI SCREENER'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REGNL_ACCT_MGMT'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REGNL_ACCT_STF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REGNL_SS_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REG_FAM_IND_MGT'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REG_FAM_IND_STF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'RSRC_DVLPR'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SHINES_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SS_ADMIN_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'STATE_OFC_CONS'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'STATE_OFC_MGMT'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SUPERVISOR'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SYS_ADMIN'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'UNIT_TEAM_LEAD'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MED_BILL_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MED_BILL_MGMT'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SENSITIVE_CASE'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'IT HELP DESK'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'ORS_PRU MAINT'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SAU_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SAU_SEALED'
and length(TXT_SECURITY_CLASS_PROFIL) = 92;


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (401, 'SacwisRev3', 'Release 3.0 - DBCRs 11002,11071');

commit;


