
-- Alter Index SQL for CAPS SCHEMA

CREATE INDEX CAPS.IND_INCOME_AND_RESOURCES_3
    ON CAPS.INCOME_AND_RESOURCES(CD_INC_RSRC_TYPE,CD_INC_RSRC_INCOME,DT_INC_RSRC_FROM,SDS_INC_RSRC_SOURCE,DT_INC_RSRC_TO,TXT_INC_RSRC_SRC_ADDR_ZIP)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

DROP TABLE CAPS.INCOME_RESOURCE_INBOUND;
DROP SEQUENCE CAPS.SEQ_INCOME_RESOURCE_INBOUND;

-- SACWISIFC STUFF
-- Sequence Alter SQL

CREATE SEQUENCE SACWISIFC.SEQ_MEDICAID_COA_INBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_MEDICAID_COA_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_MEDICAID_COA_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_MEDICAID_COA_INBOUND TO CAPSBAT
;
CREATE SEQUENCE SACWISIFC.SEQ_INVOICE_INBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_INVOICE_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_INVOICE_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_INVOICE_INBOUND TO CAPSBAT
;
CREATE SEQUENCE SACWISIFC.SEQ_TCM_CLAIM_INBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_TCM_CLAIM_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_TCM_CLAIM_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_TCM_CLAIM_INBOUND TO CAPSBAT
;
CREATE SEQUENCE SACWISIFC.SEQ_CHILD_SUPPORT_INBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_CHILD_SUPPORT_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_CHILD_SUPPORT_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_CHILD_SUPPORT_INBOUND TO CAPSBAT
;
CREATE SEQUENCE SACWISIFC.SEQ_INCOME_RESOURCE_INBOUND
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
GRANT SELECT ON SACWISIFC.SEQ_INCOME_RESOURCE_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.SEQ_INCOME_RESOURCE_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.SEQ_INCOME_RESOURCE_INBOUND TO CAPSBAT
;

-- Dictionary Object Alter SQL


-- Standard Alter Table SQL

ALTER TABLE SACWISIFC.MEDICAID_COAREQ_OUTBOUND ADD ID_EVENT NUMBER(16) DEFAULT 0 NOT NULL
;

-- Drop Referencing Constraint SQL


-- Drop Constraint, Rename and Create Table SQL

CREATE TABLE SACWISIFC.CHILD_SUPPORT_INBOUND
(
    ID_CHLD_SPPRT_INBOUND NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE        DATE         NOT NULL,
    DT_CHLD_SPPRT_RCVD    DATE         NOT NULL,
    AMT_CHLD_SPPRT_AMNT   NUMBER(10,2) NOT NULL,
    NBR_COUNTY_CRS_ID     NUMBER(9)        NULL,
    NBR_NCP_CRS_ID        NUMBER(9)        NULL,
    NBR_CHECK             NUMBER(10)       NULL,
    NBR_CNTY_OFFICE       NUMBER(16)       NULL,
    CONSTRAINT PK_CHILD_SUPPORT_INBOUND
    PRIMARY KEY (ID_CHLD_SPPRT_INBOUND)
    USING INDEX TABLESPACE INDEX01
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(INITIAL 2M
                        NEXT 1M
                        MINEXTENTS 1
                        MAXEXTENTS UNLIMITED
                        PCTINCREASE 0
                        BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE(INITIAL 2M
        NEXT 1M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE SACWISIFC.CHILD_SUPPORT_INBOUND IS
'Contains child support receipt data (related to DFCS clients) from the Office of the Attorney General''s (OAG) child support enforcement system.'
;
COMMENT ON COLUMN SACWISIFC.CHILD_SUPPORT_INBOUND.NBR_COUNTY_CRS_ID IS
'This is the Client Identifier obtained from CRS (Client Repository System) which is used in state of Georgia applications.'
;
COMMENT ON COLUMN SACWISIFC.CHILD_SUPPORT_INBOUND.NBR_NCP_CRS_ID IS
'This is the Client Identifier obtained from CRS (Client Repository System) which is used in state of Georgia applications.'
;
COMMENT ON COLUMN SACWISIFC.CHILD_SUPPORT_INBOUND.NBR_CHECK IS
'The number of the check associated with a payment'
;
GRANT DELETE ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.CHILD_SUPPORT_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO OPERATOR
;
GRANT SELECT ON SACWISIFC.CHILD_SUPPORT_INBOUND TO SACWISIFC
;
CREATE TABLE SACWISIFC.INCOME_RESOURCE_INBOUND
(
    ID_INCOME_RESOURCE_INBOUND   NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE               DATE         NOT NULL,
    ID_CLIENT                    NUMBER(16)       NULL,
    CLIENT_STATUS                VARCHAR2(1)      NULL,
    AU_NUMBER                    NUMBER(9)        NULL,
    CD_PROGRAM_TYPE              VARCHAR2(2)      NULL,
    BNFT_MONTH                   NUMBER(6)        NULL,
    CD_INC_RSRC_IND              VARCHAR2(3)      NULL,
    CD_INC_RSRC_TYPE             VARCHAR2(3)      NULL,
    IND_EARNED                   VARCHAR2(1)      NULL,
    SDS_INC_RSRC_SOURCE          VARCHAR2(33)     NULL,
    TXT_INC_RSRC_SRC_ADDR_ST_LN1 VARCHAR2(25)     NULL,
    TXT_INC_RSRC_SRC_ADDR_ST_LN2 VARCHAR2(25)     NULL,
    TXT_INC_RSRC_SRC_ADDR_CITY   VARCHAR2(22)     NULL,
    TXT_INC_RSRC_SRC_ADDR_STATE  VARCHAR2(2)      NULL,
    TXT_INC_RSRC_SRC_ADDR_ZIP    VARCHAR2(10)     NULL,
    INC_RSRC_AMT                 NUMBER(10,2)     NULL,
    CD_INC_RSRC_FREQ_TYPE        VARCHAR2(2)      NULL,
    CD_INC_RSRC_VRF              VARCHAR2(2)      NULL,
    DT_INC_RSRC_FROM             DATE             NULL,
    DT_INC_RSRC_TO               DATE             NULL,
    UN_ERND_INC_AMT              NUMBER(10,2)     NULL,
    CD_UN_ERND_INC_FREQ_TYPE     VARCHAR2(2)      NULL,
    CD_UN_ERND_INC_VRF           VARCHAR2(2)      NULL,
    RSRC_AMT                     NUMBER(10,2)     NULL,
    CD_RSRC_VRF                  VARCHAR2(2)      NULL,
    AU_STATUS                    VARCHAR2(1)      NULL,
    TANFRFOOD_BNFT_AMT           NUMBER(7,2)      NULL,
    CASE_LOAD_NUMBER             VARCHAR2(4)      NULL,
    RETURN_CODE                  VARCHAR2(10)     NULL,
    CONSTRAINT PK_INCOME_RESOURCE_INBOUND
    PRIMARY KEY (ID_INCOME_RESOURCE_INBOUND)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE SACWISIFC.INCOME_RESOURCE_INBOUND IS
'This table contains all income and resource data that has been sent by an external system such as SUCCESS. This information will typically go into the official INCOME_AND_RESOURCES table. However, application logic will attempt to prevent inserting duplicate or irrelevant data in the official table. This table will contain ALL data sent in a transaction, regardless of whether it is viewed as a duplicate or not.'
;
COMMENT ON COLUMN SACWISIFC.INCOME_RESOURCE_INBOUND.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.INCOME_RESOURCE_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO OPERATOR
;
GRANT SELECT ON SACWISIFC.INCOME_RESOURCE_INBOUND TO SACWISIFC
;
CREATE TABLE SACWISIFC.INVOICE_INBOUND
(
    ID_INVOICE_INBOUND   NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE       DATE         NOT NULL,
    ID_INVOICE_OUTBOUND  NUMBER(16)       NULL,
    NBR_CHECK_NUM        NUMBER(10)       NULL,
    DT_PAYMENT           DATE             NULL,
    AMT_REST_FUNDS_CHECK NUMBER(13,2)     NULL,
    AMT_REST_FUNDS_SAVE  NUMBER(13,2)     NULL,
    AMT_PAYMENT          NUMBER(13,2)     NULL,
    ID_INVOICE           NUMBER(16)       NULL,
    ERROR_STATUS         VARCHAR2(10)     NULL,
    CONSTRAINT PK_INVOICE_INBOUND
    PRIMARY KEY (ID_INVOICE_INBOUND)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE SACWISIFC.INVOICE_INBOUND IS
'AUDIT table for inbound invoice transactions
'
;
COMMENT ON COLUMN SACWISIFC.INVOICE_INBOUND.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON SACWISIFC.INVOICE_INBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.INVOICE_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.INVOICE_INBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.INVOICE_INBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.INVOICE_INBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.INVOICE_INBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.INVOICE_INBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.INVOICE_INBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.INVOICE_INBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.INVOICE_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.INVOICE_INBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.INVOICE_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.INVOICE_INBOUND TO OPERATOR
;
GRANT SELECT ON SACWISIFC.INVOICE_INBOUND TO SACWISIFC
;
CREATE TABLE SACWISIFC.MEDICAID_COA_INBOUND
(
    ID_MEDICAID_COA_INBOUND NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE          DATE         NOT NULL,
    MED_COA                 VARCHAR2(3)      NULL,
    DT_FIRST_DAY_LIABILITY  DATE             NULL,
    AMT_FIRST_DAY_LIABILITY NUMBER(7,2)      NULL,
    BNFT_MONTH              NUMBER(6)        NULL,
    CD_CLIENT_STATUS        VARCHAR2(1)      NULL,
    DT_CLIENT_STATUS        DATE             NULL,
    RETURN_CODE             VARCHAR2(10)     NULL,
    CONSTRAINT PK_MEDICAID_COA_INBOUND
    PRIMARY KEY (ID_MEDICAID_COA_INBOUND)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE SACWISIFC.MEDICAID_COA_INBOUND IS
'Table used for AUDIT purposes to record all Medicaid Class Of Assistance Web Service calls.'
;
COMMENT ON COLUMN SACWISIFC.MEDICAID_COA_INBOUND.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.MEDICAID_COA_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.MEDICAID_COA_INBOUND TO OPERATOR
;
GRANT SELECT ON SACWISIFC.MEDICAID_COA_INBOUND TO SACWISIFC
;
CREATE TABLE SACWISIFC.TCM_CLAIM_INBOUND
(
    ID_TCM_CLAIM_INBOUND  NUMBER(16)   NOT NULL,
    DT_LAST_UPDATE        DATE         NOT NULL,
    ID_TCM_CLAIM_OUTBOUND NUMBER(16)       NULL,
    TCM_CLAIM_STATUS      VARCHAR2(2)      NULL,
    EOB_CODES             VARCHAR2(30)     NULL,
    DT_PAYMENT            DATE             NULL,
    NBR_TCN               VARCHAR2(17)     NULL,
    NBR_RA                VARCHAR2(8)      NULL,
    CONSTRAINT PK_TCM_CLAIM_INBOUND
    PRIMARY KEY (ID_TCM_CLAIM_INBOUND)
    USING INDEX TABLESPACE INDEX01
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
TABLESPACE DATA01
LOGGING
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
;
COMMENT ON TABLE SACWISIFC.TCM_CLAIM_INBOUND IS
'Inbound responses to TCM Claims from SMI'
;
COMMENT ON COLUMN SACWISIFC.TCM_CLAIM_INBOUND.DT_LAST_UPDATE IS
'Date of insert or last update'
;
GRANT DELETE ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPS
;
GRANT INSERT ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPS
;
GRANT SELECT ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPS
;
GRANT UPDATE ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPS
;
GRANT DELETE ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSBAT
;
GRANT INSERT ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSBAT
;
GRANT SELECT ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSBAT
;
GRANT UPDATE ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSBAT
;
GRANT DELETE ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSON
;
GRANT INSERT ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSON
;
GRANT UPDATE ON SACWISIFC.TCM_CLAIM_INBOUND TO CAPSON
;
GRANT SELECT ON SACWISIFC.TCM_CLAIM_INBOUND TO OPERATOR
;
GRANT SELECT ON SACWISIFC.TCM_CLAIM_INBOUND TO SACWISIFC
;

-- Alter Index SQL

CREATE INDEX SACWISIFC.IND_INVOICE_INBOUND_1
    ON SACWISIFC.INVOICE_INBOUND(ID_INVOICE_OUTBOUND)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX SACWISIFC.IND_TCM_CLAIM_INBOUND_1
    ON SACWISIFC.TCM_CLAIM_INBOUND(ID_TCM_CLAIM_OUTBOUND)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE SACWISIFC.INVOICE_INBOUND 
    ADD CONSTRAINT FK_INV_INB_INV_OUTB
FOREIGN KEY (ID_INVOICE_OUTBOUND)
REFERENCES SACWISIFC.INVOICE_OUTBOUND (ID_INVOICE_OUTBOUND)
ENABLE
;
ALTER TABLE SACWISIFC.TCM_CLAIM_INBOUND 
    ADD CONSTRAINT FK_TCM_CLAIM_IN_TCM_OUT
FOREIGN KEY (ID_TCM_CLAIM_OUTBOUND)
REFERENCES SACWISIFC.TCM_CLAIM_OUTBOUND (ID_TCM_CLAIM_OUTBOUND)
ENABLE
;

-- Alter Trigger SQL
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_CHILD_SUPPORT_INBOUND
BEFORE UPDATE
ON SACWISIFC.CHILD_SUPPORT_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_CHILD_SUPPORT_INBOUND
BEFORE INSERT
ON SACWISIFC.CHILD_SUPPORT_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
	dummy		NUMBER;
BEGIN
	:new.DT_LAST_UPDATE := SYSDATE;
     IF (:new.ID_CHLD_SPPRT_INBOUND=0) THEN
	SELECT	SEQ_CHILD_SUPPORT_INBOUND.NEXTVAL
	INTO	dummy
	FROM	DUAL;
	:new.ID_CHLD_SPPRT_INBOUND := dummy;
     END IF;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_INCOME_RESOURCE_INBOUND
BEFORE UPDATE
ON SACWISIFC.INCOME_RESOURCE_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_INCOME_RESOURCE_INBOUND
BEFORE INSERT
ON SACWISIFC.INCOME_RESOURCE_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:NEW.ID_INCOME_RESOURCE_INBOUND IS NULL OR :new.ID_INCOME_RESOURCE_INBOUND = 0) THEN
    SELECT  SEQ_INCOME_RESOURCE_INBOUND.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_INCOME_RESOURCE_INBOUND := dummy;
  END IF;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_INVOICE_INBOUND
BEFORE UPDATE
ON SACWISIFC.INVOICE_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_INVOICE_INBOUND
BEFORE INSERT
ON SACWISIFC.INVOICE_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:NEW.ID_INVOICE_INBOUND IS NULL OR :new.ID_INVOICE_INBOUND = 0) THEN
    SELECT  SEQ_INVOICE_INBOUND.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_INVOICE_INBOUND := dummy;
  END IF;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_MEDICAID_COA_INBOUND
BEFORE UPDATE
ON SACWISIFC.MEDICAID_COA_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_MEDICAID_COA_INBOUND
BEFORE INSERT
ON SACWISIFC.MEDICAID_COA_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:NEW.ID_MEDICAID_COA_INBOUND IS NULL OR :new.ID_MEDICAID_COA_INBOUND = 0) THEN
    SELECT  SEQ_MEDICAID_COA_INBOUND.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_MEDICAID_COA_INBOUND := dummy;
  END IF;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TUBR_TCM_CLAIM_INBOUND
BEFORE UPDATE
ON SACWISIFC.TCM_CLAIM_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
END;
/
/
CREATE OR REPLACE TRIGGER SACWISIFC.TIBR_TCM_CLAIM_INBOUND
BEFORE INSERT
ON SACWISIFC.TCM_CLAIM_INBOUND
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  dummy    NUMBER;
BEGIN
  :new.DT_LAST_UPDATE := SYSDATE;
  IF (:NEW.ID_TCM_CLAIM_INBOUND IS NULL OR :new.ID_TCM_CLAIM_INBOUND = 0) THEN
    SELECT  SEQ_TCM_CLAIM_INBOUND.NEXTVAL
    INTO  dummy
    FROM  DUAL;
    :new.ID_TCM_CLAIM_INBOUND := dummy;
  END IF;
END;
/

-- Create Synonyms for CAPS, CAPSON, and CAPSBAT. CHARLES, watch out for this code.
create synonym CAPS.CHILD_SUPPORT_INBOUND for SACWISIFC.CHILD_SUPPORT_INBOUND;
create synonym CAPS.INCOME_RESOURCE_INBOUND for SACWISIFC.INCOME_RESOURCE_INBOUND;
create synonym CAPS.INVOICE_INBOUND for SACWISIFC.INVOICE_INBOUND;
create synonym CAPS.MEDICAID_COA_INBOUND for SACWISIFC.MEDICAID_COA_INBOUND;
create synonym CAPS.TCM_CLAIM_INBOUND for SACWISIFC.TCM_CLAIM_INBOUND;
create synonym CAPS.SEQ_MEDICAID_COA_INBOUND for SACWISIFC.SEQ_MEDICAID_COA_INBOUND;
create synonym CAPS.SEQ_INCOME_RESOURCE_INBOUND for SACWISIFC.SEQ_INCOME_RESOURCE_INBOUND;
create synonym CAPS.SEQ_INVOICE_INBOUND for SACWISIFC.SEQ_INVOICE_INBOUND;
create synonym CAPS.SEQ_TCM_CLAIM_INBOUND for SACWISIFC.SEQ_TCM_CLAIM_INBOUND;
create synonym CAPS.SEQ_CHILD_SUPPORT_INBOUND for SACWISIFC.SEQ_CHILD_SUPPORT_INBOUND;

create synonym CAPSON.CHILD_SUPPORT_INBOUND for SACWISIFC.CHILD_SUPPORT_INBOUND;
create synonym CAPSON.INCOME_RESOURCE_INBOUND for SACWISIFC.INCOME_RESOURCE_INBOUND;
create synonym CAPSON.INVOICE_INBOUND for SACWISIFC.INVOICE_INBOUND;
create synonym CAPSON.MEDICAID_COA_INBOUND for SACWISIFC.MEDICAID_COA_INBOUND;
create synonym CAPSON.TCM_CLAIM_INBOUND for SACWISIFC.TCM_CLAIM_INBOUND;
create synonym CAPSON.SEQ_MEDICAID_COA_INBOUND for SACWISIFC.SEQ_MEDICAID_COA_INBOUND;
create synonym CAPSON.SEQ_INCOME_RESOURCE_INBOUND for SACWISIFC.SEQ_INCOME_RESOURCE_INBOUND;
create synonym CAPSON.SEQ_INVOICE_INBOUND for SACWISIFC.SEQ_INVOICE_INBOUND;
create synonym CAPSON.SEQ_TCM_CLAIM_INBOUND for SACWISIFC.SEQ_TCM_CLAIM_INBOUND;
create synonym CAPSON.SEQ_CHILD_SUPPORT_INBOUND for SACWISIFC.SEQ_CHILD_SUPPORT_INBOUND;

create synonym CAPSBAT.CHILD_SUPPORT_INBOUND for SACWISIFC.CHILD_SUPPORT_INBOUND;
create synonym CAPSBAT.INCOME_RESOURCE_INBOUND for SACWISIFC.INCOME_RESOURCE_INBOUND;
create synonym CAPSBAT.INVOICE_INBOUND for SACWISIFC.INVOICE_INBOUND;
create synonym CAPSBAT.MEDICAID_COA_INBOUND for SACWISIFC.MEDICAID_COA_INBOUND;
create synonym CAPSBAT.TCM_CLAIM_INBOUND for SACWISIFC.TCM_CLAIM_INBOUND;
create synonym CAPSBAT.SEQ_MEDICAID_COA_INBOUND for SACWISIFC.SEQ_MEDICAID_COA_INBOUND;
create synonym CAPSBAT.SEQ_INCOME_RESOURCE_INBOUND for SACWISIFC.SEQ_INCOME_RESOURCE_INBOUND;
create synonym CAPSBAT.SEQ_INVOICE_INBOUND for SACWISIFC.SEQ_INVOICE_INBOUND;
create synonym CAPSBAT.SEQ_TCM_CLAIM_INBOUND for SACWISIFC.SEQ_TCM_CLAIM_INBOUND;
create synonym CAPSBAT.SEQ_CHILD_SUPPORT_INBOUND for SACWISIFC.SEQ_CHILD_SUPPORT_INBOUND;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00002425
UPDATE CAPS.MESSAGE SET TXT_MESSAGE='You must have an approved RBWO Payment of Care to place a child in a contracted facility'
WHERE TXT_MESSAGE_NAME='MSG_NO_LOC_RECORDED';

-- change STGAP00002426
UPDATE CAPS.CODES_TABLES SET DECODE='Parent/Child Visitation' WHERE code_type='CCNTCTYP' AND DECODE='Parent/Child Visit';

-- change STGAP00002451
INSERT INTO CAPS.METAPHOR
(ID_TAB,TXT_TAB_URL,TXT_TAB_CONSTANT,TXT_TAB)
VALUES(1585,'/workload/EventSearch/displayEventList','ADOPTION_INFORMATION_FOR_CASE_EVENTLIST',
'Adoption Information for Case');

INSERT INTO CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, CD_TASK_PRIOR, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_ENABLE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, IND_TASK_TODO_ENABLE, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
 VALUES
   ('9995', SYSDATE, 'COMP', 
'ADO', 'CCMN51W', '9520', 'ADO', 'CPS', 'CSUB01W', '0', '0', '0', '1', '1', '0', '1',
 '1', '0', '1', '0', 'Adoption Information for Case', 'CASE_CASESEARCH', 
'CHILD_PLANS_EVENTLIST', 'ADOPTION_INFORMATION_FOR_CASE_EVENTLIST', 
'/subcare/AdoptionInformation/displayAdoption', 3, '0', '0', '0');

-- change STGAP00002452
UPDATE CAPS.CODES_TABLES SET DECODE='Administrative Review'  WHERE code_type='CEVNTTYP' AND code='ARI'; 
UPDATE CAPS.CODES_TABLES SET DECODE='Administrative Review'  WHERE code_type='CSTAGES' AND code='ARI'; 

-- change STGAP00002466
insert into CAPS.TASK (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL)
Values ('9410', sysdate, 'APP', 'SUB', 'CPS', '0', '1', '1', '0', '0', '0', '0', 'Approve Team Meetings/Reviews', 'CASE_CASESEARCH', 'CHILD_PLANS_EVENTLIST', 'PERMANENCY_PLANNING_REVIEW_PPT_EVENTLIST', '/subcare/PPT/displayPPT');
update CAPS.CODES_TABLES set DECODE = 'Team Meetings/Reviews' where CODE = 'PPT' and CODE_TYPE = 'CEVNTTYP' AND DECODE = 'Permanency Plan Rev.';

-- change STGAP00002478
UPDATE CAPS.TASK  SET IND_TASK_CODE_PREFER = '2' WHERE CD_TASK = '8090';

-- change STGAP00002495
UPDATE CAPS.TASK SET TXT_TASK_DECODE = 'Approve Foster Care Case Plan Child'  WHERE CD_TASK = '3370';
UPDATE CAPS.TASK SET TXT_TASK_DECODE = 'Foster Care Case Plan Child'  WHERE CD_TASK = '3160' ;
UPDATE CAPS.TASK SET TXT_TASK_DECODE = 'Foster Care Case Plan Child for Case'  WHERE CD_TASK = '3170';

-- change STGAP00002496
update caps.task t set t.ind_task_code_prefer = 2 where t.cd_task = '9500';

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (171, 'SacwisRev2', 'static updates, sacwisifc additions');

commit;
