
--STGAP00002550
update caps.CODES_TABLES set DT_END = SYSDATE where CODE = 'AP' and CODE_TYPE = 'CRPTRINT';


--STGAP00002613
Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, 
CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_EVENT_CREATE, 
IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, 
IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, 
TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, 
IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
 Values
   ('3195', SYSDATE, 'COMP', 'VIS', 'CCMN51W', 'SUB', 'CPS', 'CSUB09C', '1', '1', '1', '1', 
'0', '0', '1', 'Visitation Plan', 'CASE_CASESEARCH', 'CHILD_PLANS_EVENTLIST', 
'VISITATION_PLAN_FOR_CASE_EVENTLIST', '/admin/OutputLaunch/displayInitOutputLaunch', 3, '1', 
'0', '0');


Insert into CAPS.METAPHOR
   (ID_TAB, TXT_TAB_URL, TXT_TAB_CONSTANT, TXT_TAB, DT_LAST_UPDATE)
 Values
   (1395, '/workload/EventSearch/displayEventList', 'VISITATION_PLAN_FOR_CASE_EVENTLIST', 
'Visitation Plan for Case List',SYSDATE);

--STGAP00002654 
Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'ADO', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'ARR', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'BOT', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'CAA', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'CPS', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'CTH', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'CNP', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'CPC', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'ERP', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'DNW', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'FCS', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'MTR', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'MRC', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'FRC', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'FHP', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'NPR', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'HDD', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');

Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'ICC', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'NRY', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'OTR', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'OFC', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'PFP', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'PFA', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'PRF', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'PFO', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'RTT', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


Insert into caps.STAGE_PROG
   (ID_STAGE_PROG, DT_LAST_UPDATE, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_RSN_CLOSE, CD_STAGE_PROG_PROGRAM, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC)
 Values
   (0, SYSDATE, 'FAD', 'FNA', 'CPS', '0', 'STG', 'COMP', 'F/A Home Stage Closed');


--STGAP00002664 
UPDATE caps.CODES_TABLES SET DECODE='Adjudicated Delinquent' WHERE CODE='ADJ' AND CODE_TYPE='CLEGLOUT';

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (174, 'SacwisRev2', 'static updates to tasks, stage_prog, metaphor, and codes_tables');   
commit;
