
-- Standard Alter Table SQL

ALTER TABLE CAPS.STAGE MODIFY(TXT_STAGE_PRIORITY_CMNTS  VARCHAR2(300))
;

-- SACWISIFC Interface Stuff

-- Alter Index SQL

CREATE INDEX SACWISIFC.IND_CPRS_OUTBOUND_2
    ON SACWISIFC.CPRS_OUTBOUND(ID_CASE,INTERFACE_STATUS)
TABLESPACE INDEX01
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

-- Alter Procedure SQL
/
CREATE OR REPLACE PROCEDURE SACWISIFC.UPDATE_CASEPLAN (xCD_COUNTY IN SACWISIFC.CPRS_OUTBOUND.CD_COUNTY%TYPE, 
xID_CASE IN SACWISIFC.CPRS_OUTBOUND.ID_CASE%TYPE)
AS
v_cntr_case	NUMBER := 0;

BEGIN

SELECT COUNT(*)
	  INTO v_cntr_case
	  FROM CPRS_OUTBOUND
	  WHERE id_case = xID_CASE AND INTERFACE_STATUS='NEW';
	  
IF v_cntr_case = 0
THEN
  INSERT INTO CPRS_OUTBOUND (INTERFACE_STATUS, DT_CREATED, CD_COUNTY, ID_CASE)
     VALUES ('NEW', SYSDATE, xCD_COUNTY, xID_CASE);
END IF;

EXCEPTION
   WHEN OTHERS THEN RAISE;
      
END UPDATE_CASEPLAN;
/

GRANT EXECUTE ON SACWISIFC.UPDATE_CASEPLAN TO CAPS;
GRANT EXECUTE ON SACWISIFC.UPDATE_CASEPLAN TO CAPSBAT;
GRANT EXECUTE ON SACWISIFC.UPDATE_CASEPLAN TO CAPSON;

create synonym CAPS.UPDATE_CASEPLAN for SACWISIFC.UPDATE_CASEPLAN;
create synonym CAPSBAT.UPDATE_CASEPLAN for SACWISIFC.UPDATE_CASEPLAN;
create synonym CAPSON.UPDATE_CASEPLAN for SACWISIFC.UPDATE_CASEPLAN;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00002781
UPDATE CAPS.MESSAGE SET TXT_MESSAGE = 'Warning- No allegations have been recorded' 
WHERE NBR_MESSAGE = '3050';

-- change STGAP00002801
INSERT INTO CAPS.MESSAGE (ID_MESSAGE, NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) VALUES (0, 60333, 'MSG_CMN_ADD_TO_UNIT', 'This unit already has a Unit Approver. Add the employee as a Member first.', '560', '740', 'N');
INSERT INTO CAPS.MESSAGE (ID_MESSAGE, NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) VALUES (0, 60334, 'MSG_CMN_FIRST_UNIT_MBR', 'The first employee assigned to a unit must be the Unit Approver.', '560', '740', 'N');
INSERT INTO CAPS.MESSAGE (ID_MESSAGE, NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) VALUES (0, 60335, 'MSG_CMN_NO_UNIT_APPRV', 'This unit has no designated Unit Approver. Please add one from the Staff Detail page.', '560', '740', 'N');
INSERT INTO CAPS.MESSAGE (ID_MESSAGE, NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE, CD_PRESENTATION, IND_BATCH) VALUES (0, 60336, 'MSG_CMN_UNIT_NO_MOD', 'This unit cannot be modified until a Unit Approver is assigned from the Staff Detail page.', '550', '700', 'N');

-- change STGAP00002803
INSERT INTO CAPS.CODES_TABLES VALUES('CRSRC', 'IDI', 'Interest/Dividend', NULL, SYSDATE);

-- change STGAP00002804
-- The following CINCRSRC decodes should be modified for consistency with the CINC and CRSRC decodes, as follows:
UPDATE CAPS.CODES_TABLES SET DECODE='Retirement Income' WHERE CODE_TYPE='CINCRSRC' AND CODE='RET';
UPDATE CAPS.CODES_TABLES SET DECODE='Gross Earned Income' WHERE CODE_TYPE='CINCRSRC' AND CODE='GRS';
UPDATE CAPS.CODES_TABLES SET DECODE='Self-Employed Income' WHERE CODE_TYPE='CINCRSRC' AND CODE='SLF';
UPDATE CAPS.CODES_TABLES SET DECODE='Workers Compensation' WHERE CODE_TYPE='CINCRSRC' AND CODE='CMP';
UPDATE CAPS.CODES_TABLES SET DECODE='Primary Residence' WHERE CODE_TYPE='CINCRSRC' AND CODE='HOM';

-- change STGAP00002806
INSERT INTO CAPS.CODES_TABLES VALUES('CINCRSRC', 'ALI', 'Alimony', NULL, SYSDATE);
INSERT INTO CAPS.CODES_TABLES VALUES('CINCRSRC', 'VEH', 'Vehicle', NULL, SYSDATE);
INSERT INTO CAPS.CODES_TABLES VALUES('CINCRSRC', 'UNE', 'Unemployment', NULL, SYSDATE);
INSERT INTO CAPS.CODES_TABLES VALUES('CINCRSRC', 'CNT', 'Contributions', NULL, SYSDATE);

-- change STGAP00002807
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CINCRSRC' AND CODE IN ('RES', 'RIN');

-- change STGAP00002808
UPDATE CAPS.CODES_TABLES SET DECODE='Adoption Disruption' WHERE CODE_TYPE='CSUBCLOS' AND CODE='AD';

-- change STGAP00002809
INSERT INTO CAPS.CODES_TABLES VALUES ('CSUBCLOS', 'AS', 'Adoption Dissolution', NULL, SYSDATE);

-- change STGAP00002814
UPDATE CAPS.CODES_TABLES
SET DECODE = 'CCI'
WHERE CODE IN ('IFH','EMS','GRH','CCL','SFH','ICF')
AND CODE_TYPE = 'CPLCMTRU';

-- change STGAP00002818
-- STGAP00002766
update CAPS.METAPHOR set TXT_TAB = 'Foster Care Case Plan Family' where ID_TAB = 525;
UPDATE CAPS.TASK SET TXT_TASK_DECODE = 'Foster Care Case Plan Family' WHERE CD_TASK = '7065';
-- STGAP00002776
update CAPS.MESSAGE set TXT_MESSAGE = 'Permanency plan type must be Concurrent to save a Concurrent Permanency Plan.' where NBR_MESSAGE = 60115;

-- change STGAP00002820
Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
 Values
   ('8695', SYSDATE, 'COMP', 'VIS', 'CCMN51W', 'ADO', 'CPS', 'CSUB09C', '1', '1', '1', '1', '0', '0', '1', 'Visitation Plan - English', 'CASE_CASESEARCH', 'CHILD_PLANS_EVENTLIST', 'VISITATION_PLAN_FOR_CASE_EVENTLIST', '/admin/OutputLaunch/displayInitOutputLaunch', 3, '1', '0', '0');
   
-- change STGAP00002821
insert into caps.codes_tables
(code_type, code, decode, dt_last_update)
values
('CREGDIV', 'DJJ','DJJ Eligibility Staff',sysdate);

-- change STGAP00002838
-- CINQRCBY
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CINQRCBY' AND CODE='EM';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CINQRCBY' AND CODE='BE';
INSERT INTO CAPS.CODES_TABLES VALUES('CINQRCBY', 'CL', 'Contract Lead Agency Provider', NULL, SYSDATE);
INSERT INTO CAPS.CODES_TABLES VALUES('CINQRCBY', 'CC', 'Contracted Community Based Organization', NULL, SYSDATE);
-- CFASRCIN 
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CFASRCIN' AND CODE='AUS';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CFASRCIN' AND CODE='CAP';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CFASRCIN' AND CODE='FOH';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CFASRCIN' AND CODE='GFC';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CFASRCIN' AND CODE='MTN';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CFASRCIN' AND CODE='WED';
INSERT INTO CAPS.CODES_TABLES VALUES('CFASRCIN', 'CLP', 'Contract Lead Agency Provider', NULL, SYSDATE);
INSERT INTO CAPS.CODES_TABLES VALUES('CFASRCIN', 'CCO', 'Contracted Community Based Organization', NULL, SYSDATE);
-- CPRGMINT 
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CPRGMINT' AND CODE='EMB';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CPRGMINT' AND CODE='AUS';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CPRGMINT' AND CODE='FOH';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CPRGMINT' AND CODE='GFC';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CPRGMINT' AND CODE='MTN';
UPDATE CAPS.CODES_TABLES SET DT_END=SYSDATE WHERE CODE_TYPE='CPRGMINT' AND CODE='WED';
INSERT INTO CAPS.CODES_TABLES VALUES('CPRGMINT', 'CLP', 'Contract Lead Agency Provider', NULL, SYSDATE);
INSERT INTO CAPS.CODES_TABLES VALUES('CPRGMINT', 'CCO', 'Contracted Community Based Organization', NULL, SYSDATE);

-- change STGAP00002845
update caps.message
set txt_message = 'Non-incident Requests cannot be merged.'
where txt_message_name = 'MSG_CFC_CMS_NO_MRG';

-- change STGAP00002846
update caps.codes_tables
set dt_end = sysdate
where code in ('FPL','FFP')
and code_type = 'CEVNTTYP';

-- change STGAP00002857
INSERT INTO CAPS.STAGE_PROG (ID_STAGE_PROG, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_PROGRAM, CD_STAGE_PROG_RSN_CLOSE, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC) VALUES (0, 'DIV', 'CPS', 'NFI', '0', 'STG', 'COMP', 'Diversion Stage Closed');
INSERT INTO CAPS.STAGE_PROG (ID_STAGE_PROG, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_PROGRAM, CD_STAGE_PROG_RSN_CLOSE, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC) VALUES (0, 'DIV', 'CPS', 'RFS', '0', 'STG', 'COMP', 'Diversion Stage Closed');
INSERT INTO CAPS.STAGE_PROG (ID_STAGE_PROG, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_PROGRAM, CD_STAGE_PROG_RSN_CLOSE, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC) VALUES (0, 'DIV', 'CPS', 'RFI', '0', 'STG', 'COMP', 'Diversion Stage Closed');
INSERT INTO CAPS.STAGE_PROG (ID_STAGE_PROG, CD_STAGE_PROG_STAGE, CD_STAGE_PROG_PROGRAM, CD_STAGE_PROG_RSN_CLOSE, IND_STAGE_PROG_CLOSE, CD_STAGE_PROG_EVENT_TYPE, CD_STAGE_PROG_STATUS, TXT_STAGE_PROG_EVNT_DESC) VALUES (0, 'DIV', 'CPS', 'TRS', '0', 'STG', 'COMP', 'Diversion Stage Closed');

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (178, 'SacwisRev2', 'static updates, STAGE column expansion, CPRS stuff in SACWISIFC');  

commit;
