--STGAP00016094 - Release(4.2) Update TCM Denial Codes to have all capital letter

-- Some TCM Denial Codes had all capital decodes while others had just the first letter of the
-- first word capitalized. This DBCR will make all of the active decodes have all capital letters.


UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '1156 - REPLACEMENT OR CREDIT OF A DENIED CLAIM'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '1156';

UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '2064 - CLAIM DOS/MEMBER DATE OF DEATH CONFLICT'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '2064';

UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '2521 - MEMBER HAS COB RESOURCE AND THE SERVICE OR COB RESOURCE INDICATES PAY AND CHASE'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '2521';

UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '3699 - PROVIDER ENROLLED FOR ELECTRONIC BILLING'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '3699';

UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '6288 - ONLY ONE VISIT ALLOWED PER MONTH OF SERVICE'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '6288';

UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '6380 - TWO CASE MANAGEMENT CLAIMS CAN NOT PAID IN THE SAME CALENDAR MONTH'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '6380';

UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '9918 - PRICING ADJUSTMENT - MAX FEE PRICING APPLIED'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '9918';

UPDATE  CAPS.CODES_TABLES CT
SET     CT.DECODE = '9955 - PRICING ADJUSTMENT CALCULATED ALLOWED AMOUNT GREATER THAN BILLED AMOUNT - CUTBACK TO BILLED'
WHERE CT.CODE_TYPE = 'CTCMDEN' AND CODE = '9955';

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (978, 'SacwisRev4', 'Release 4.2 - DBCR 16094');

commit;


