-- Release 2.5 
--change STGAP00009264 

INSERT INTO CAPS.CODES_TABLES (code_type, code, DECODE, dt_last_update) VALUES ('CSECATTR', 'PG', 'Modify State/CPA Concurrence', SYSDATE);

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'CASE_MANAGER'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'CONTRACT_LEAD'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'CONTRACTED_CBO'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'COUNTY_MGMNT'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'DJJ_AFCARS'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'DPTY_CNTY_DRCTR'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'FSCL_SVC_ST_STF'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'IT HELP DESK'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_01'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_02'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_03'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_04'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_05'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_06'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_07'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_08'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_09'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_10'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_11'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_12'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_13'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_14'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_15'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_16'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_17'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MAINTAIN_REG_99'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MED_BILL_MGMT'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MED_BILL_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'MES_PROG_ASST'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'OFI SCREENER'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REGNL_ACCT_MGMT'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REGNL_ACCT_STF'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REGNL_SS_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REG_FAM_IND_MGT'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'REG_FAM_IND_STF'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'RSRC_DVLPR'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SHINES_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SS_ADMIN_STAFF'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'STATE_OFC_CONS'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'STATE_OFC_MGMT'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SUPERVISOR'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'SYS_ADMIN'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

UPDATE CAPS.SECURITY_CLASS 
SET TXT_SECURITY_CLASS_PROFIL = TXT_SECURITY_CLASS_PROFIL || '0'
WHERE CD_SECURITY_CLASS_NAME = 'UNIT_TEAM_LEAD'
and length(TXT_SECURITY_CLASS_PROFIL) = 89;

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (342, 'SacwisRev2', 'new security attribute for CPA concurrence');                        
commit;
