--STGAP00017863 - Release(5.1) DB Change Request for CQ# STGAP00017827

-- PER CLEARQUEST STGAP00017827
--        i) ADD A COLUMN IND_ICPC_DOC IN EXT_DOCUMENTATION TO INDICATE IF THE UPLOADED DOCUMENT IS ICPC
--       ii) UPDATE THE DECODE VALUE FOR THE CODE IC FOR THE TYPE CEXDOTYP IN CODES_TABLES
--      iii) ADD NEW RECORD IN CODES_TABLES FOR CODE IB AND TYPES CEXDOTTC AND CEXDOTYP IN CODES_TABLES


ALTER TABLE CAPS.EXT_DOCUMENTATION
ADD (
   IND_ICPC_DOC VARCHAR2(1) DEFAULT 'N'
);

comment on column CAPS.EXT_DOCUMENTATION.IND_ICPC_DOC is 'Indicates whether file is an ICPC Document';

UPDATE CAPS.CODES_TABLES
SET DECODE ='ICPC Document (Custody With Georgia)'
WHERE CODE_TYPE = 'CEXDOTYP' AND CODE='IC';

UPDATE CAPS.CODES_TABLES
SET DECODE ='ICPC Document (Custody With Georgia)'
WHERE CODE_TYPE = 'CEXDOCCD' AND CODE='IC';

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE, CODE,DECODE)
VALUES ('CEXDOTTC', 'IB', 'CD');

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE, CODE,DECODE)
VALUES ('CEXDOTYP', 'IB', 'ICPC Document (Custody With Other State)');

INSERT INTO CAPS.CODES_TABLES(CODE_TYPE, CODE,DECODE)
VALUES ('CEXDOCCD', 'IB', 'ICPC Document (Custody With Other State)');

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (1196, 'SacwisRev5', 'Release 5.1 - DBCR 17863');

commit;
