-- change STGAP00003755
-- Because of the inconsistency in the 'CSRCRPTR' code type the reporter type dropdown is not being put in alpha order Some letters need to be capitalized and hyphens removed to get correct order also one of the paramour entries needs to be end dated 
UPDATE caps.Codes_tables SET DECODE = 'Non-Parent Spouse' WHERE code_type = 'CSRCRPTR' AND code = 'NS';
UPDATE caps.Codes_tables SET DECODE = 'Non-Custodial Parent' WHERE code_type = 'CSRCRPTR' AND code = 'NC';
UPDATE caps.Codes_tables SET DECODE = 'Step-Grandparent' WHERE code_type = 'CSRCRPTR' AND code = 'GS';
UPDATE caps.CODES_TABLES SET DT_END = SYSDATE WHERE code_type = 'CSRCRPTR' AND CODE = 'PP';

-- change STGAP00003836
Update caps.codes_tables
set dt_end  =sysdate
where code_type = 'CREGDIV'
and code in ('CO', 'CS','DJJ','DO','DTS','ER','ETU','FFS','ICP','LS','MBU','OA','OCA','OIT','PPD','RC','SAU','SDL','SP','TSU');

-- change STGAP00003847
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE, DT_LAST_UPDATE) VALUES ('CREGDIV', '099', 'State Office', SYSDATE);

-- change STGAP00003855
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (90036, 'MSG_CRS_UNA_NBR','User is not authorized to execute program', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (90793, 'MSG_CRS_DNF_NBR','Duplicate name found', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91002, 'MSG_CRS_ORS_NBR','At least one race must be selected', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91003, 'MSG_CRS_RCI_NBR','Race Code Invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91004, 'MSG_CRS_SCM_NBR','Sex Code Missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91005, 'MSG_CRS_SCI_NBR','Sex Code Invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91006, 'MSG_CRS_CNM_NBR','County Number Missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91007, 'MSG_CRS_CNI_NBR','County Number Invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91008, 'MSG_CRS_DOBM_NBR','Date of Birth Missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91009, 'MSG_CRS_DOBI_NBR','Date of Birth Invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91011, 'MSG_CRS_CNICRS_NBR','CLIENT IS NOT ON CRS', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91045, 'MSG_CRS_DOBVM_NBR','Date of Birth Verification Code is missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91046, 'MSG_CRS_DOBVI_NBR','Date of Birth Verification Code is invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91047, 'MSG_CRS_DOB120_NBR','Date of Birth indicates the client is older than 120 years old', 700,500,'N');

INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91048, 'MSG_CRS_SSNVI_NBR','Social Security Number Verification Code is invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91049, 'MSG_CRS_SSNVM_NBR','Social Security Number Verification Code is missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91050, 'MSG_CRS_FCLNB_NBR','First character of Last Name cannot be blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91051, 'MSG_CRS_FCSNB_NBR','First character of Suffix Name cannot be blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91052, 'MSG_CRS_FCMNB_NBR','First character of Middle Name cannot be blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91053, 'MSG_CRS_FCFNB_NBR','First character of First Name cannot be blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91054, 'MSG_CRS_NM_NBR','Name Missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91055, 'MSG_CRS_FNME_NBR','First Name Must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91056, 'MSG_CRS_LNME_NBR','Last Name Must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91057, 'MSG_CRS_SSNM_NBR','Social Security Number Missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91058, 'MSG_CRS_SSNME_NBR','Social Security Number Must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91059, 'MSG_CRS_AFNME_NBR','Alias First Name Must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91060, 'MSG_CRS_ALNME_NBR','Alias Last Name Must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91177, 'MSG_CRS_CSSNME_NBR','Client SSN must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91178, 'MSG_CRS_SSNI_NBR','Social Security Number Invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91179, 'MSG_CRS_DSSN_NBR','Duplicate Social Security Numbers exsist', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91184, 'MSG_CRS_NMF_NBR','No matches found', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91186, 'MSG_CRS_NEBS_NBR','Embedded spaces are not allowed', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91187, 'MSG_CRS_CMTI_NBR','Invalid custodian member type', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (91188, 'MSG_CRS_CODR_NBR','Court order data is required if a child is marked as on the crt order', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92056, 'MSG_CRS_IVS_NBR','Invalid Selection - Indicator must be "Y" or blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92072, 'MSG_CRS_INCI_NBR','Inches must be from 1 to 11', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92169, 'MSG_CRS_NMF69_NBR','No matches found', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92172, 'MSG_CRS_EOM_NBR','End of Matches', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92179, 'MSG_CRS_SNNN_NBR','Social Security Number must be numeric', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92214, 'MSG_CRS_INE_NBR','Invalid entry. Must be "Y" or blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92301, 'MSG_CRS_DMCI_NBR','There must be a direct match on client identifier', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92302, 'MSG_CRS_CNASSN_NBR','Cannot assign new Id on a primary Social Security Number match', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92303, 'MSG_CRS_CIAS_NBR','This client identifier has alreadh been selected for a match', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92357, 'MSG_CRS_CME_NBR','Client is marked as erroneous: Match is not allowed', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92392, 'MSG_CRS_SSNAEAC_NBR','SSN entered exists as a primary SSN for another client', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92404, 'MSG_CRS_CIACE_NBR','Error Client Id and Active Client Id Must be Entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (92405, 'MSG_CRS_CIACNS_NBR','Error ClientID and Active Client ID Can not be the same', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99006, 'MSG_CRS_ICI_NBR','Invalid client identifier', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99007, 'MSG_CRS_IVMO_NBR','The month is invalid should be greater than 0 and less than 13', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99008, 'MSG_CRS_IVDAY_NBR','The day is invalid should be greater than 0 and less than 32', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99009, 'MSG_CRS_INYR_NBR','The year is invalid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99010, 'MSG_CRS_RFME_NBR','Required fields must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99011, 'MSG_CRS_UNAF_NBR','User not authorized to select this function', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99012, 'MSG_CRS_UNKE_NBR','Error number not found in error table', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99022, 'MSG_CRS_DMBE_NBR','Date must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99040, 'MSG_CRS_NCNAZ_NBR','Numeric field cannot be all zeroes', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99041, 'MSG_CRS_CPNME_NBR','Complete phone number must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99052, 'MSG_CRS_SYB_NBR','Selection field must be "Y" or blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99053, 'MSG_CRS_MINORA_NBR','Minimum of ONE race must be selected', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99054, 'MSG_CRS_IEC_NBR','Invalid ethnicity code entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99055, 'MSG_CRS_ECM_NBR','Ethnicity code missing', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99071, 'MSG_CRS_FMN_NBR','Field must be numeric', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99072, 'MSG_CRS_DB2E_NBR','Unexpected DB2 error occurred', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99073, 'MSG_CRS_CICSE_NBR','Unexpected CICS error occurred', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99092, 'MSG_CRS_SNVBL_NBR','Selection is not valid on a blank line', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99095, 'MSG_CRS_IRMYB_NBR','Invalid request.  Must be Y or blank', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99113, 'MSG_CRS_CIME_NBR','Client Identifier must be entered', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99123, 'MSG_CRS_NCICS_NBR','No CICS communications area passed', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99124, 'MSG_CRS_UECCA_NBR',' Unexpected entry code in communciations area', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99125, 'MSG_CRS_UVPES_NBR','Unexpected value in program exit switch', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99127, 'MSG_CRS_TPNFT_NBR','Transfer program was not found in table', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99128, 'MSG_CRS_IQCS_NBR','Inquiry completed successfully', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99131, 'MSG_CRS_FTCSSNZ_NBR','First three digits of social security number cannot be zeroes', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99132, 'MSG_CRS_STSSNZ_NBR','Second two digits of social security number cannot be zeroes', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99133, 'MSG_CRS_LFSSNCZ_NBR','Last four digits of social security number cannot be zeroes', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99135, 'MSG_CRS_FNAT_NBR','Function not available at this time', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99205, 'MSG_CRS_SNAME_NBR','The selected Id is Erroneously marked as an Alias', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99206, 'MSG_CRS_CINSX_NBR','The Client Identifier is not on SOUNDEX', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99300, 'MSG_CRS_NFLLB_NBR','is not found it the load library', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99304, 'MSG_CRS_IDCCS_NBR','Id correction completed successfully', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99305, 'MSG_CRS_TMSC_NBR','TOO MANY SPECIAL CHARACTERS (-,".* #) IN THE NAME', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99306, 'MSG_CRS_REFSC_NBR','Unable to display information. Refine search criteria with DOB or SSN', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99307, 'MSG_CRS_SCNV_NBR','State code is not valid', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99308, 'MSG_CRS_SCCS_NBR','Screening completed successfully', 700,500,'N');
INSERT INTO CAPS.MESSAGE (NBR_MESSAGE, TXT_MESSAGE_NAME, TXT_MESSAGE, CD_SOURCE,  CD_PRESENTATION, IND_BATCH) VALUES (99309, 'MSG_CRS_CNCSSN_NBR','Can not change SSN,Federally Verified', 700,500,'N');


insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (206, 'SacwisRev2', 'static updates');                        
commit;
