-- Standard Alter Table SQL - STGAP00003201

ALTER TABLE CAPS.BATCH_SERVICE_LOCKS MODIFY(NM_SERVICE_NAME  VARCHAR2(85))
;

-- Alter Trigger SQL - STGAP00003225
/
CREATE OR REPLACE TRIGGER CAPS.TIAR_CPRS_FCCP_CHILD
AFTER INSERT OR UPDATE
ON CAPS.FCCP_CHILD
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
  DATA_PRESENT VARCHAR2(1);
  DATA_MODIFIED VARCHAR2(1);
  UPD_FLAG VARCHAR2(1);
  xCD_EVENT_STATUS EVENT.CD_EVENT_STATUS%TYPE;
  xCD_COUNTY VARCHAR2(3);
  xID_CASE CAPS_CASE.ID_CASE%TYPE;
BEGIN
    -- DBMS_OUTPUT.put_line('IN TIAR_CPRS_FCCP_CHILD');
    UPD_FLAG := 'N';
    DATA_PRESENT := 'N';
    DATA_MODIFIED := 'N';
    IF (:NEW.TXT_EFFRTS_REM IS NOT NULL)
    THEN
       DATA_PRESENT := 'Y';
	   -- DBMS_OUTPUT.put_line('IN TIAR_CPRS_FCCP_CHILD - DATA PRESENT');
    END IF;
    IF (INSERTING AND DATA_PRESENT='Y') 
	THEN
      UPD_FLAG := 'Y';
	  -- DBMS_OUTPUT.put_line('IN TIAR_CPRS_FCCP_CHILD - INSERT HAS DATA PRESENT');
	  SELECT CD_EVENT_STATUS, ID_CASE
	  INTO xCD_EVENT_STATUS, xID_CASE
      FROM EVENT
      WHERE ID_EVENT = :NEW.ID_EVENT;
    ELSIF (UPDATING AND DATA_PRESENT='Y') 
	THEN
      IF (:NEW.TXT_EFFRTS_REM IS NOT NULL AND (:OLD.TXT_EFFRTS_REM IS NULL OR
            :NEW.TXT_EFFRTS_REM <> :OLD.TXT_EFFRTS_REM))
      THEN
             DATA_MODIFIED := 'Y';
             SELECT CD_EVENT_STATUS, ID_CASE
			 INTO xCD_EVENT_STATUS, xID_CASE
             FROM EVENT
             WHERE ID_EVENT = :NEW.ID_EVENT;
             -- If Plan has not been completed yet, it may not have been sent down to CPRS.
             -- So we will update CPRS with data we have so far on these fields.
             IF (xCD_EVENT_STATUS <> 'COMP')
             THEN
                UPD_FLAG := 'Y';
             END IF;
      END IF;
    END IF;
    IF (UPD_FLAG = 'Y')
    THEN
	       -- DBMS_OUTPUT.put_line('IN TIAR_CPRS_FCCP_CHILD - Update CPRS is a go. Case is ' || xID_CASE);
    	   SELECT CD_CASE_COUNTY
           INTO   xCD_COUNTY
           FROM   CAPS_CASE C
           WHERE  C.ID_CASE = xID_CASE;
           IF (xCD_COUNTY IS NOT NULL)
           THEN
              UPDATE_CASEPLAN (xCD_COUNTY, xID_CASE);  
           END IF;     
    END IF;
    
    EXCEPTION
    	WHEN OTHERS THEN
		DBMS_OUTPUT.put_line('IN TIAR_CPRS_FCCP_CHILD, SQLCODE: '||SQLCODE);
    	IF SQL%NOTFOUND THEN
    			xCD_COUNTY := NULL;
		END IF;
END;
/

-- SACWISIFC - Hey Charles, the below schema changes is all SACWISIFC
-- Standard Alter Table SQL - STGAP00003240

ALTER TABLE SACWISIFC.CSUP_PARENT_OUTBOUND MODIFY(ID_CASE   NULL)
;
ALTER INDEX SACWISIFC.PK_CSUP_PARENT_OUTBOUND 
REBUILD TABLESPACE INDEX01
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- change STGAP00003197
update CAPS.TASK
SET IND_TASK_NEW_USING = 1
where cd_task_event_type='AUT';

-- change STGAP00003200
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.ContractValidation', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveAddressAndPhone', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CASV01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveAdoptionSubsidy', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveAdoptionSubsidy', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C03B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.RetrieveCaseMergeList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C04B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.RetrieveCaseMergeList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C05B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.RetrieveCaseMergeList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C03B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.RetrieveCaseMergeVerify', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C04B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.RetrieveCaseMergeVerify', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C05B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.RetrieveCaseMergeVerify', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveCloseReopenFAHome', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.RetrieveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.RetrieveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrieveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B ', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrievePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.RetrievePlacementDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.RetrieveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CASV01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveAdoptionSubsidy', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveAdoptionSubsidy', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C03B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.SaveCaseMerge', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C04B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.SaveCaseMerge', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CR2C05B', 'gov.georgia.dhr.dfcs.sacwis.service.admin.SaveCaseMerge', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.fce.SaveEligibility', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveFAHomeCloseReopen', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeDemographics', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SaveHomeLicense', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.courtprocess.SaveLegalService', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.casemgmt.SaveLevelofCare', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SavePaymentApprovalList', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SavePlacementReferralDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CINT01B', 'gov.georgia.dhr.dfcs.sacwis.service.resource.SavePlacementReferralDetail', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CCON01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN02B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN03B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN04B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN10B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN11B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CFIN22B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveServiceAuthorization', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CTCM01B', 'gov.georgia.dhr.dfcs.sacwis.service.financials.SaveTCMClaim', SYSDATE, 'N');
INSERT INTO CAPS.BATCH_SERVICE_LOCKS (NM_BATCH_SCRIPT, NM_SERVICE_NAME, DT_LAST_UPDATE, IND_SERVICE_LOCKED) VALUES ('CTCM01B', 'gov.georgia.dhr.dfcs.sacwis.web.ws.UpdateTcmClaimInfoWS', SYSDATE, 'N');

-- change STGAP00003217
UPDATE CAPS.TODO SET txt_todo_desc = 'Approve Child Life History'
WHERE txt_todo_desc = 'Approve HSEGH';

-- change STGAP00003218
UPDATE CAPS.CODES_TABLES
SET DECODE = 'VID not 1-8 chars', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRJCTRSN'
AND CODE = 'VL';

UPDATE CAPS.CODES_TABLES
SET DECODE = 'VID empty', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRJCTRSN'
AND CODE = 'VN';

UPDATE CAPS.CODES_TABLES
SET DECODE = 'No POC', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRJCTRSN'
AND CODE = 'AL';

UPDATE CAPS.CODES_TABLES
SET DECODE = 'No POC', DT_LAST_UPDATE = SYSDATE
WHERE CODE_TYPE = 'CRJCTRSN'
AND CODE = 'BL';

-- change STGAP00003223
UPDATE caps.message SET txt_message='The Vendor ID must be no more than 8 characters long.'
WHERE txt_message_name='MSG_ARC_CONSTR_VENDORID';

-- change STGAP00003224
UPDATE CAPS.CODES_TABLES
SET DECODE = 'Child 6 or under in congregate care', DT_LAST_UPDATE = SYSDATE
WHERE
CODE_TYPE = 'CWLCRSN'
AND
CODE = 'IC6';

UPDATE CAPS.CODES_TABLES
SET DECODE = 'Child under 12 in congregate care', DT_LAST_UPDATE = SYSDATE
WHERE
CODE_TYPE = 'CWLCRSN'
AND
CODE = 'I12';

UPDATE CAPS.CODES_TABLES
SET DT_END = SYSDATE, DT_LAST_UPDATE = SYSDATE
WHERE
CODE_TYPE = 'CWPWRSN'
AND
CODE IN ('P6H','P12');

insert into caps.schema_version (id_schema_version, application_version, comments)
                         values (187, 'SacwisRev2', 'static updates, CPRS trigger, SACWISIFC minor change');

commit;
