--STGAP00016053 - Release(4.1) MR-074 AFCARS: config stage prog, error msg HL

-- sms#81140
-- Configure ICPC - Adoption closure: no stage open

--REM INSERTING into STAGE_PROG
Insert into caps.STAGE_PROG (ID_STAGE_PROG,DT_LAST_UPDATE,CD_STAGE_PROG_STAGE,CD_STAGE_PROG_RSN_CLOSE,CD_STAGE_PROG_PROGRAM,IND_STAGE_PROG_CLOSE,CD_STAGE_PROG_OPEN,CD_STAGE_PROG_EVENT_TYPE,CD_STAGE_PROG_STAGE_TYPE,CD_STAGE_PROG_STATUS,CD_STAGE_PROG_TASK,CD_STAGE_PROG_TODO_INFO,TXT_STAGE_PROG_EVNT_DESC,TXT_STAGE_PROG_TODO_DESC,NBR_STAGE_PROG_DAYS_DUE)
values (0,SYSDATE,'ADO','ICA','CPS','0','ADO','STG',null,'COMP',null,null,'Adoption Stage Closed',null,null);

-- Made error hyperlinked in the popup error list
Insert into caps.ERROR_LIST (ID_ERROR_LIST,DT_LAST_UPDATE,NBR_MESSAGE,TXT_PRGM_CD,TXT_STAGE_CD,ID_TAB,CD_TASK)
values (0,SYSDATE,8192,'CPS','ADO',1000,'8590');
Insert into caps.ERROR_LIST (ID_ERROR_LIST,DT_LAST_UPDATE,NBR_MESSAGE,TXT_PRGM_CD,TXT_STAGE_CD,ID_TAB,CD_TASK)
values (0,SYSDATE,60805,'CPS','ADO',830,'8560');
Insert into caps.ERROR_LIST (ID_ERROR_LIST,DT_LAST_UPDATE,NBR_MESSAGE,TXT_PRGM_CD,TXT_STAGE_CD,ID_TAB,CD_TASK)
values (0,SYSDATE,60806,'CPS','ADO',1000,'8590');
Insert into caps.ERROR_LIST (ID_ERROR_LIST,DT_LAST_UPDATE,NBR_MESSAGE,TXT_PRGM_CD,TXT_STAGE_CD,ID_TAB,CD_TASK)
values (0,SYSDATE,60807,'CPS','ADO',1000,'8590');

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (945, 'SacwisRev4', 'Release 4.1 - DBCR 16053');

commit;


