--STGAP00014454 - SVC_AUTH_DETAIL - add DT_SA_LAST_PREBILL

--For SVC_AUTH_DETAIL - please add a new DATE field DT_SA_LAST_PREBILL

alter table caps.svc_auth_detail add (DT_SA_LAST_PREBILL date) ;


--STGAP00014467 - Adding new column  to PERSON_DTL as per Mr-20

alter table caps.person_dtl add (IND_PK_HSHD_MEMBER varchar2(1)) ;
comment on column caps.person_dtl.IND_PK_HSHD_MEMBER is 'Primary Caretaker House Hold Member' ;


--STGAP00014475 - Safety resource Adding Approve tasks as per MR-20

insert into caps.task
(CD_TASK, DT_LAST_UPDATE,CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, CD_TASK_PRIOR, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW,
 IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_ENABLE, IND_TASK_NEW_USING,
 IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, IND_TASK_TODO_ENABLE, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, 
TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
values
('7332', sysdate, null, 'APP', null, null, 'INV', 'CPS', null, null, 0, 1,null, 1, null, 0, 0, 0, 0, null, 'Approve Safety Resource', 'CASE_CASESEARCH', 
'RISK_ASSESSMENT_RISKASSMT', 'SAFETY_RESOURCE_EVENTLIST', '/investigation/SafetyResource/displaySafetyResource', 0, 0, 0, 0);

 insert into caps.task
(CD_TASK, DT_LAST_UPDATE,CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, CD_TASK_PRIOR, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW,
 IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_ENABLE, IND_TASK_NEW_USING,
 IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, IND_TASK_TODO_ENABLE, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, 
TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
values
('7333', sysdate, null, 'APP', null, null, 'FPR', 'CPS', null, null, 0, 1,null, 1, null, 0, 0, 0, 0, null, 'Approve Safety Resource', 'CASE_CASESEARCH', 
'RISK_ASSESSMENT_RISKASSMT', 'SAFETY_RESOURCE_EVENTLIST', '/investigation/SafetyResource/displaySafetyResource', 0, 0, 0, 0);


--STGAP00014503 - Remove Other option from Custody for STGAP00014338

UPDATE CAPS.CODES_TABLES SET DT_END = TO_DATE('24-JUN-09', 'DD-MON-RR')
WHERE CODE_TYPE = 'CREMFRHR' AND CODE = 'XXX';


--STGAP00014509 - New Messages for Legal Status MR-051

INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES(SYSDATE,60551,'MSG_OUT_OF_STATE_LEG_CNTY','Out of State may not be selected as the Legal County while the Legal Status indicates in DFCS custody.',
700,500,'N');

INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES(SYSDATE,60552,'MSG_CUSTODY_WITH_OTHER_STATE','The Legal County must be Out of State if the Legal Status is Not In DFCS Custody - Custody With Other State.',
700,500,'N');

INSERT INTO CAPS.MESSAGE(DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,
TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH)
VALUES(SYSDATE,60553,'MSG_MISSING_PARENT_TPR','Selecting the Legal Status of Adoption Finalized requires that a TPR Date, Voluntary Surrender Date, or Date of Death exist for both mother and father on the stage.',
700,500,'N');


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (488, 'SacwisRev3', 'Release 3.2 - DBCRs 14454,14467,14475,14503,14509');

commit;


