--STGAP00010403 - Store Vantive Ticket # in DATAFIX_AUDIT_TABLE

alter table caps.datafix_audit_table add  (vantive_ticket number(16));


--STGAP00010443 - (ADAM Conversion) Increase EXCHANGE_CHILD field sz

ALTER TABLE CAPS.EXCHANGE_CHILD MODIFY (TXT_AVAIL_COMMENTS VARCHAR2(1000));


--STGAP00010444 - Adoption Legal Actions PAD stage task code


Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_LIST_WINDOW, CD_TASK_PRIOR, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE, IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
 Values
   ('9075', TO_DATE('06/08/2007 17:52:00', 'MM/DD/YYYY HH24:MI:SS'), 'LEG', 'CCMN51W', '9070', 'PAD', 'CPS', 'CSUB10C', '1', '1', '1', '1', '1', '0', '1', 'Legal Actions for Case','CASE_CASESEARCH', 'LEGAL_EVENTLIST', 'LEGAL_ACTIONS_FOR_CASE_EVENTLIST', '/subcare/LegalActions/displayLegalActions', 3, '1', '0', '0');

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_TYPE, CD_TASK_STAGE, CD_TASK_STAGE_PROGRAM, IND_TASK_EVENT_CREATE, IND_TASK_EVENT_NAVIG, IND_TASK_MULTIPLE_INSTANCE,IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE, IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB, TXT_EVENT_DETAIL_URL)
 Values
   ('9071', TO_DATE('09/26/2006 21:23:03', 'MM/DD/YYYY HH24:MI:SS'), 'APP', 'PAD', 'CPS', '0', '1', '1', '0', '0', '0', '0', 'Approve Legal Action', 'CASE_CASESEARCH', 'LEGAL_EVENTLIST', 'LEGAL_ACTIONS_EVENTLIST', '/subcare/LegalActions/displayLegalActions');


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (392, 'SacwisRev3', 'Release 3.0 - DBCRs 10403,10443,10444');

commit;


