--STGAP00010043 - Services and Referrals Checklist: Adding stages

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_STAGE,
CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE,
 IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE,
IND_TASK_NEW_ENABLE, IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE,
IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB,
TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE,
IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
 Values
   ('2305', TO_DATE('05/31/2008 12:10:12', 'MM/DD/YYYY HH24:MI:SS'), 'COMP', 'CHK', 'ADO', 'CPS', 'CINV25W',
 '1', '1', '1', '0', '0', '0', '0', '0', '0', '1', 'Services and Referrals Checklist', 'CASE_CASESEARCH', 'CASE_MANAGEMENT_CASEMNT',
 'SERVICES_AND_REFERRALS_CHECKLIST_SRVCSRFRRLSCHECKLIST',
'/investigation/SrvcsRfrrlsChecklist/displaySrvcsRfrrlsChecklist', 3, '1', '0', '0');

Insert into CAPS.TASK
   (CD_TASK, DT_LAST_UPDATE, CD_TASK_EVENT_STATUS, CD_TASK_EVENT_TYPE, CD_TASK_STAGE,
 CD_TASK_STAGE_PROGRAM, CD_TASK_TOP_WINDOW, IND_TASK_DETAIL_ENABLE, IND_TASK_EVENT_CREATE,
 IND_TASK_EVENT_NAVIG, IND_TASK_LIST_ENABLE, IND_TASK_MULTIPLE_INSTANCE, IND_TASK_NEW_ENABLE,
IND_TASK_NEW_USING, IND_TASK_NU_ACROSS_CASE, IND_TASK_RTRV_PRIOR_STAGE,
IND_TASK_SHOW_IN_LIST, TXT_TASK_DECODE, TXT_1ST_TAB, TXT_2ND_TAB, TXT_3RD_TAB,
TXT_EVENT_DETAIL_URL, IND_TASK_CODE_PREFER, IND_TASK_NEW_CASE_TODO_ENABLE,
IND_TASK_FORCE_EVENT_LINK, IND_STAGE_CLOSURE)
 Values
   ('2304', TO_DATE('05/31/2008 12:10:12', 'MM/DD/YYYY HH24:MI:SS'), 'COMP', 'CHK', 'PAD', 'CPS', 'CINV25W',
'1', '1', '1', '0', '0', '0', '0', '0', '0', '1', 'Services and Referrals Checklist', 'CASE_CASESEARCH', 'CASE_MANAGEMENT_CASEMNT',
 'SERVICES_AND_REFERRALS_CHECKLIST_SRVCSRFRRLSCHECKLIST', '/investigation/SrvcsRfrrlsChecklist/displaySrvcsRfrrlsChecklist', 3, '1', '0', '0');



insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (374, 'SacwisRev3', 'Release 3.0 - DBCR 10043');

commit;


