-- Release 2.5 
/
DECLARE 
  
  table_count    NUMBER(5);

BEGIN
  select count(*) into table_count from all_tables where table_name='AFCARS' and owner='CAPS';
  
  IF table_count > 0 THEN
     DBMS_OUTPUT.PUT_LINE(' TABLE COUNT IS  ' || table_count || ' ------');
  ELSE
     DBMS_OUTPUT.PUT_LINE('AFCARS NOT PRESENT - TIME TO CREATE IT');
  
EXECUTE IMMEDIATE 'CREATE TABLE CAPS.AFCARS
(
    STATE                        VARCHAR2(2)      NULL,
    REPORT_DATE                  VARCHAR2(6)      NULL,
    LOCAL_AGENCY_FIPS_CODE       VARCHAR2(5)      NULL,
    RECORD_NUMBER                VARCHAR2(12)     NULL,
    DATE_OF_PERIODIC_REVIEW      VARCHAR2(8)      NULL,
    CHILDS_DATE_OF_BIRTH         VARCHAR2(8)      NULL,
    SEX                          VARCHAR2(1)      NULL,
    RACE_A                       VARCHAR2(1)      NULL,
    RACE_B                       VARCHAR2(1)      NULL,
    RACE_C                       VARCHAR2(1)      NULL,
    RACE_D                       VARCHAR2(1)      NULL,
    RACE_E                       VARCHAR2(1)      NULL,
    RACE_F                       VARCHAR2(1)      NULL,
    HISPANIC_OR_LATINO_ORIGIN    VARCHAR2(1)      NULL,
    CHILD_DISABILITY             VARCHAR2(1)      NULL,
    MENTAL_RETARDATION           VARCHAR2(1)      NULL,
    VISUALLY_OR_HEARING_IMPAIRED VARCHAR2(1)      NULL,
    PHYSICALLY_DISABLED          VARCHAR2(1)      NULL,
    EMOTIONALLY_DISTURBED        VARCHAR2(1)      NULL,
    OTHER_DIAGNOSED_CONDITION    VARCHAR2(1)      NULL,
    EVER_ADOPTED                 VARCHAR2(1)      NULL,
    AGE_ADOPTED                  VARCHAR2(1)      NULL,
    DATE_OF_FIRST_REMOVAL        VARCHAR2(8)      NULL,
    TOTAL_NUMBER_OF_REMOVALS     VARCHAR2(2)      NULL,
    LAST_FOSTER_CARE_DISCHARGE   VARCHAR2(8)      NULL,
    LATEST_REMOVAL_FROM_HOME     VARCHAR2(8)      NULL,
    REMOVAL_TRANSACTION_DATE     VARCHAR2(8)      NULL,
    DATE_OF_CURRENT_PLACEMENT    VARCHAR2(8)      NULL,
    NUMBER_PLACEMENT_SETTINGS    VARCHAR2(2)      NULL,
    MANNER_OF_REMOVAL            VARCHAR2(1)      NULL,
    PHYSICAL_ABUSE               VARCHAR2(1)      NULL,
    SEXUAL_ABUSE                 VARCHAR2(1)      NULL,
    NEGLECT                      VARCHAR2(1)      NULL,
    ALCOHOL_ABUSE_PARENT         VARCHAR2(1)      NULL,
    DRUG_ABUSE_PARENT            VARCHAR2(1)      NULL,
    ALCOHOL_ABUSE_CHILD          VARCHAR2(1)      NULL,
    DRUG_ABUSE_CHILD             VARCHAR2(1)      NULL,
    CHILDS_DISABILITY            VARCHAR2(1)      NULL,
    CHILDS_BEHAVIOR_PROBLEM      VARCHAR2(1)      NULL,
    DEATH_OF_PARENTS             VARCHAR2(1)      NULL,
    INCARCERATION_OF_PARENTS     VARCHAR2(1)      NULL,
    INABILITY_TO_COPE            VARCHAR2(1)      NULL,
    ABANDONMENT                  VARCHAR2(1)      NULL,
    RELINQUISHMENT               VARCHAR2(1)      NULL,
    INADEQUATE_HOUSING           VARCHAR2(1)      NULL,
    CURRENT_PLACEMENT_SETTING    VARCHAR2(1)      NULL,
    OUT_OF_STATE                 VARCHAR2(1)      NULL,
    MOST_RECENT_CASE_PLAN_GOAL   VARCHAR2(1)      NULL,
    CARETAKER_FAMILY_STRUCTURE   VARCHAR2(1)      NULL,
    YOB_1ST_PRIN_CARETAKER       VARCHAR2(4)      NULL,
    YOB_2ND_PRIN_CARETAKER       VARCHAR2(4)      NULL,
    RIGHTS_TERMINATION_MOTHER    VARCHAR2(8)      NULL,
    RIGHTS_TERMINATION_FATHER    VARCHAR2(8)      NULL,
    FOSTER_FAMILY_STRUCTURE      VARCHAR2(1)      NULL,
    YOB_1ST_FOSTER_CARETAKER     VARCHAR2(4)      NULL,
    YOB_2ND_FOSTER_CARETAKER     VARCHAR2(4)      NULL,
    RACE_1ST_FOSTER_CARETAKER_A  VARCHAR2(1)      NULL,
    RACE_1ST_FOSTER_CARETAKER_B  VARCHAR2(1)      NULL,
    RACE_1ST_FOSTER_CARETAKER_C  VARCHAR2(1)      NULL,
    RACE_1ST_FOSTER_CARETAKER_D  VARCHAR2(1)      NULL,
    RACE_1ST_FOSTER_CARETAKER_E  VARCHAR2(1)      NULL,
    RACE_1ST_FOSTER_CARETAKER_F  VARCHAR2(1)      NULL,
    HL_ORIGIN_1ST_FOS_CARETAKER  VARCHAR2(1)      NULL,
    RACE_2ND_FOSTER_CARETAKER_A  VARCHAR2(1)      NULL,
    RACE_2ND_FOSTER_CARETAKER_B  VARCHAR2(1)      NULL,
    RACE_2ND_FOSTER_CARETAKER_C  VARCHAR2(1)      NULL,
    RACE_2ND_FOSTER_CARETAKER_D  VARCHAR2(1)      NULL,
    RACE_2ND_FOSTER_CARETAKER_E  VARCHAR2(1)      NULL,
    RACE_2ND_FOSTER_CARETAKER_F  VARCHAR2(1)      NULL,
    HL_ORIGIN_2ND_FOS_CARETAKER  VARCHAR2(1)      NULL,
    DATE_OF_DISCHARGE            VARCHAR2(8)      NULL,
    DISCHARGE_TRANSACTION_DATE   VARCHAR2(8)      NULL,
    REASON_FOR_DISCHARGE         VARCHAR2(1)      NULL,
    TITLE_IV_E_FOSTER_CARE       VARCHAR2(1)      NULL,
    TITLE_IV_E_ADOPTION          VARCHAR2(1)      NULL,
    TITLE_IV_A                   VARCHAR2(1)      NULL,
    TITLE_IV_D                   VARCHAR2(1)      NULL,
    TITLE_XIX                    VARCHAR2(1)      NULL,
    SSI                          VARCHAR2(1)      NULL,
    NO_FED                       VARCHAR2(1)      NULL,
    AMT_OF_FOSTER_CARE_PAYMENT   VARCHAR2(5)      NULL
)
TABLESPACE DATA01
NOPARALLEL
NOCACHE
'
;
EXECUTE IMMEDIATE 'COMMENT ON TABLE CAPS.AFCARS IS
''To support state reporting, this request creates the AFCARS table.  Each month, data will be reloaded in this table following a new run of the AFCARS Batch Extract to store the information from the flat file produced.  Together with the AFCARS_VIEW, the AFCARS table will satisfy multiple state office reporting requirements'''
;

EXECUTE IMMEDIATE 'GRANT DELETE ON CAPS.AFCARS TO CAPSBAT'
;
EXECUTE IMMEDIATE 'GRANT INSERT ON CAPS.AFCARS TO CAPSBAT'
;
EXECUTE IMMEDIATE 'GRANT SELECT ON CAPS.AFCARS TO CAPSBAT'
;
EXECUTE IMMEDIATE 'GRANT UPDATE ON CAPS.AFCARS TO CAPSBAT'
;
EXECUTE IMMEDIATE 'GRANT DELETE ON CAPS.AFCARS TO CAPSON'
;
EXECUTE IMMEDIATE 'GRANT INSERT ON CAPS.AFCARS TO CAPSON'
;
EXECUTE IMMEDIATE 'GRANT SELECT ON CAPS.AFCARS TO CAPSON'
;
EXECUTE IMMEDIATE 'GRANT UPDATE ON CAPS.AFCARS TO CAPSON'
;
EXECUTE IMMEDIATE 'GRANT SELECT ON CAPS.AFCARS TO OPERATOR'
;


END IF;
END;
/

-- Standard Alter Table SQL

ALTER TABLE CAPS.EDUCATIONAL_HISTORY ADD TXT_SCH_CNG_CMNT VARCHAR2(500)     NULL
;
ALTER TABLE CAPS.NEEDS_OUTCOMES ADD TXT_UNDER4_NO_DEV_SRC_CMNT VARCHAR2(500)     NULL
;
ALTER TABLE CAPS.NEEDS_OUTCOMES ADD TXT_UND_SCHOOLAGE_NO_DEV_ASS VARCHAR2(500)     NULL
;
ALTER TABLE CAPS.STAGE_PERSON_LINK DROP UNIQUE (ID_STAGE, ID_PERSON) DROP INDEX
;
ALTER TABLE CAPS.STAGE_PERSON_LINK ADD CONSTRAINT UK1_STAGE_PERSON
UNIQUE (ID_STAGE,ID_PERSON,CD_STAGE_PERS_TYPE)
USING INDEX TABLESPACE INDEX01
            PCTFREE 10
            INITRANS 2
            MAXTRANS 255
            STORAGE(INITIAL 2M
                    NEXT 1M
                    MINEXTENTS 1
                    MAXEXTENTS UNLIMITED
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
;

-- Update Views SQL

create or replace view CAPS.AFCARS_VIEW
(
STATE,
REPORT_DATE,
LOCAL_AGENCY_FIPS_CODE,
RECORD_NUMBER,
DATE_OF_PERIODIC_REVIEW,
CHILDS_DATE_OF_BIRTH,
SEX,
RACE_A,
RACE_B,
RACE_C,
RACE_D,
RACE_E,
RACE_F,
HISPANIC_OR_LATINO_ORIGIN,
CHILD_DISABILITY,
MENTAL_RETARDATION,
VISUALLY_OR_HEARING_IMPAIRED,
PHYSICALLY_DISABLED,
EMOTIONALLY_DISTURBED,
OTHER_DIAGNOSED_CONDITION,
EVER_ADOPTED,
AGE_ADOPTED,
DATE_OF_FIRST_REMOVAL,
TOTAL_NUMBER_OF_REMOVALS,
LAST_FOSTER_CARE_DISCHARGE,
LATEST_REMOVAL_FROM_HOME,
REMOVAL_TRANSACTION_DATE,
DATE_OF_CURRENT_PLACEMENT,
NUMBER_PLACEMENT_SETTINGS,
MANNER_OF_REMOVAL,
PHYSICAL_ABUSE,
SEXUAL_ABUSE,
NEGLECT,
ALCOHOL_ABUSE_PARENT,
DRUG_ABUSE_PARENT,
ALCOHOL_ABUSE_CHILD,
DRUG_ABUSE_CHILD,
CHILDS_DISABILITY,
CHILDS_BEHAVIOR_PROBLEM,
DEATH_OF_PARENTS,
INCARCERATION_OF_PARENTS,
INABILITY_TO_COPE,
ABANDONMENT,
RELINQUISHMENT,
INADEQUATE_HOUSING,
CURRENT_PLACEMENT_SETTING,
OUT_OF_STATE,
MOST_RECENT_CASE_PLAN_GOAL,
CARETAKER_FAMILY_STRUCTURE,
YOB_1ST_PRIN_CARETAKER,
YOB_2ND_PRIN_CARETAKER,
RIGHTS_TERMINATION_MOTHER,
RIGHTS_TERMINATION_FATHER,
FOSTER_FAMILY_STRUCTURE,
YOB_1ST_FOSTER_CARETAKER,
YOB_2ND_FOSTER_CARETAKER,
RACE_1ST_FOSTER_CARETAKER_A,
RACE_1ST_FOSTER_CARETAKER_B,
RACE_1ST_FOSTER_CARETAKER_C,
RACE_1ST_FOSTER_CARETAKER_D,
RACE_1ST_FOSTER_CARETAKER_E,
RACE_1ST_FOSTER_CARETAKER_F,
HL_ORIGIN_1ST_FOS_CARETAKER,
RACE_2ND_FOSTER_CARETAKER_A,
RACE_2ND_FOSTER_CARETAKER_B,
RACE_2ND_FOSTER_CARETAKER_C,
RACE_2ND_FOSTER_CARETAKER_D,
RACE_2ND_FOSTER_CARETAKER_E,
RACE_2ND_FOSTER_CARETAKER_F,
HL_ORIGIN_2ND_FOS_CARETAKER,
DATE_OF_DISCHARGE,
DISCHARGE_TRANSACTION_DATE,
REASON_FOR_DISCHARGE,
TITLE_IV_E_FOSTER_CARE,
TITLE_IV_E_ADOPTION,
TITLE_IV_A,
TITLE_IV_D,
TITLE_XIX,
SSI,
NO_FED,
AMT_OF_FOSTER_CARE_PAYMENT,
PERSON_ID
) AS
Select
AFCARS.STATE,
AFCARS.REPORT_DATE,
AFCARS.LOCAL_AGENCY_FIPS_CODE,
AFCARS.RECORD_NUMBER,
AFCARS.DATE_OF_PERIODIC_REVIEW,
AFCARS.CHILDS_DATE_OF_BIRTH,
AFCARS.SEX,
AFCARS.RACE_A,
AFCARS.RACE_B,
AFCARS.RACE_C,
AFCARS.RACE_D,
AFCARS.RACE_E,
AFCARS.RACE_F,
AFCARS.HISPANIC_OR_LATINO_ORIGIN,
AFCARS.CHILD_DISABILITY,
AFCARS.MENTAL_RETARDATION,
AFCARS.VISUALLY_OR_HEARING_IMPAIRED,
AFCARS.PHYSICALLY_DISABLED,
AFCARS.EMOTIONALLY_DISTURBED,
AFCARS.OTHER_DIAGNOSED_CONDITION,
AFCARS.EVER_ADOPTED,
AFCARS.AGE_ADOPTED,
AFCARS.DATE_OF_FIRST_REMOVAL,
AFCARS.TOTAL_NUMBER_OF_REMOVALS,
AFCARS.LAST_FOSTER_CARE_DISCHARGE,
AFCARS.LATEST_REMOVAL_FROM_HOME,
AFCARS.REMOVAL_TRANSACTION_DATE,
AFCARS.DATE_OF_CURRENT_PLACEMENT,
AFCARS.NUMBER_PLACEMENT_SETTINGS,
AFCARS.MANNER_OF_REMOVAL,
AFCARS.PHYSICAL_ABUSE,
AFCARS.SEXUAL_ABUSE,
AFCARS.NEGLECT,
AFCARS.ALCOHOL_ABUSE_PARENT,
AFCARS.DRUG_ABUSE_PARENT,
AFCARS.ALCOHOL_ABUSE_CHILD,
AFCARS.DRUG_ABUSE_CHILD,
AFCARS.CHILDS_DISABILITY,
AFCARS.CHILDS_BEHAVIOR_PROBLEM,
AFCARS.DEATH_OF_PARENTS,
AFCARS.INCARCERATION_OF_PARENTS,
AFCARS.INABILITY_TO_COPE,
AFCARS.ABANDONMENT,
AFCARS.RELINQUISHMENT,
AFCARS.INADEQUATE_HOUSING,
AFCARS.CURRENT_PLACEMENT_SETTING,
AFCARS.OUT_OF_STATE,
AFCARS.MOST_RECENT_CASE_PLAN_GOAL,
AFCARS.CARETAKER_FAMILY_STRUCTURE,
AFCARS.YOB_1ST_PRIN_CARETAKER,
AFCARS.YOB_2ND_PRIN_CARETAKER,
AFCARS.RIGHTS_TERMINATION_MOTHER,
AFCARS.RIGHTS_TERMINATION_FATHER,
AFCARS.FOSTER_FAMILY_STRUCTURE,
AFCARS.YOB_1ST_FOSTER_CARETAKER,
AFCARS.YOB_2ND_FOSTER_CARETAKER,
AFCARS.RACE_1ST_FOSTER_CARETAKER_A,
AFCARS.RACE_1ST_FOSTER_CARETAKER_B,
AFCARS.RACE_1ST_FOSTER_CARETAKER_C,
AFCARS.RACE_1ST_FOSTER_CARETAKER_D,
AFCARS.RACE_1ST_FOSTER_CARETAKER_E,
AFCARS.RACE_1ST_FOSTER_CARETAKER_F,
AFCARS.HL_ORIGIN_1ST_FOS_CARETAKER,
AFCARS.RACE_2ND_FOSTER_CARETAKER_A,
AFCARS.RACE_2ND_FOSTER_CARETAKER_B,
AFCARS.RACE_2ND_FOSTER_CARETAKER_C,
AFCARS.RACE_2ND_FOSTER_CARETAKER_D,
AFCARS.RACE_2ND_FOSTER_CARETAKER_E,
AFCARS.RACE_2ND_FOSTER_CARETAKER_F,
AFCARS.HL_ORIGIN_2ND_FOS_CARETAKER,
AFCARS.DATE_OF_DISCHARGE,
AFCARS.DISCHARGE_TRANSACTION_DATE,
AFCARS.REASON_FOR_DISCHARGE,
AFCARS.TITLE_IV_E_FOSTER_CARE,
AFCARS.TITLE_IV_E_ADOPTION,
AFCARS.TITLE_IV_A,
AFCARS.TITLE_IV_D,
AFCARS.TITLE_XIX,
AFCARS.SSI,
AFCARS.NO_FED,
AFCARS.AMT_OF_FOSTER_CARE_PAYMENT, 
(
  NVL((SELECT AH.ID_PERSON FROM AFCARS_HISTORY AH
  WHERE AFCARS.RECORD_NUMBER = AH.ID_AFCARS),(SUBSTR(AFCARS.RECORD_NUMBER,6,1)||SUBSTR(AFCARS.RECORD_NUMBER,2,4)||
  SUBSTR(AFCARS.RECORD_NUMBER,1,1)||SUBSTR(AFCARS.RECORD_NUMBER,10,1)||SUBSTR(AFCARS.RECORD_NUMBER,8,2)||SUBSTR(AFCARS.RECORD_NUMBER,7,1)||
  SUBSTR(AFCARS.RECORD_NUMBER,11,2)))
)as PERSON_ID
FROM AFCARS
;

{ call dbms_utility.compile_schema('CAPS') };
{ call dbms_utility.compile_schema('CAPSBAT') };
{ call dbms_utility.compile_schema('CAPSON') };
{ call dbms_utility.compile_schema('OPERATOR') };
{ call dbms_utility.compile_schema('SACWISIFC') };

-- Release 2.5 

-- change STGAP00009033
UPDATE CAPS.TASK
SET txt_2nd_tab = 'CALL_INFORMATION_CALLINFRMTN'
WHERE cd_task = '1044';

-- change STGAP00009066
Insert into caps.MESSAGE 
(ID_MESSAGE,DT_LAST_UPDATE,NBR_MESSAGE,TXT_MESSAGE_NAME,TXT_MESSAGE,CD_SOURCE,CD_PRESENTATION,IND_BATCH) values 
(0,sysdate,60427,'MSG_LEGAL_STATUS_CHANGE_WARN','Warning: changing the legal status or legal status effective date may affect IV-E eligibility, payments, AFCARS reporting, etc.  Proceed with caution.',750,560,'N'); 

insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (329, 'SacwisRev2', 'static table updates, new AFCARS table'); 
commit;
