--STGAP00015643 - Portal Delete Triggers

grant select on caps.person to capson;
/
CREATE OR REPLACE TRIGGER CAPS.TDBR_PORTAL_USER
BEFORE DELETE
ON CAPS.PORTAL_USER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

BEGIN

  insert into PORTAL_USER_AUDIT(
        ID_USER,
	DT_LAST_UPDATE,
	NM_USER_FIRST,
	NM_USER_MIDDLE,
	NM_USER_LAST,
	NM_USER_FULL,
	TXT_TITLE,
	TXT_USER_EMAIL,
	NBR_USER_PHONE,
	NBR_USER_PHONE_EXTENSION,
        ADDR_USER_ADDR_ZIP,
        CD_USER_ADDR_STATE,
        ADDR_USER_ADDR_CITY,
        ADDR_USER_ADDR_ST_LN_1,
        ADDR_USER_ADDR_ST_LN_2,
        CD_USER_ADDR_COUNTY,
        CD_REQUEST_TYPE,
        TXT_OTHER,
        TXT_PASSWORD,
        IND_USER_AGREEMENT,
        IND_ADMIN_AGREEMENT,
        CD_STATUS,
        CD_QUESTION_1,
        CD_QUESTION_2,
        CD_QUESTION_3,
        TXT_ANSWER_1,
	TXT_ANSWER_2,
        TXT_ANSWER_3,
        DT_LAST_PASSWD_RESET,
        IND_PASSWD_TEMP,
        NBR_FAILED_LOGIN_ATTEMPTS,
        ID_SHINES_PERSON_MODIFIED_BY,
        ID_PORTAL_PERSON_MODIFIED_BY,
	TABLE_ACTION
    ) values (
        :OLD.ID_USER,
	:OLD.DT_LAST_UPDATE,
	:OLD.NM_USER_FIRST,
	:OLD.NM_USER_MIDDLE,
	:OLD.NM_USER_LAST,
	:OLD.NM_USER_FULL,
	:OLD.TXT_TITLE,
	:OLD.TXT_USER_EMAIL,
	:OLD.NBR_USER_PHONE,
	:OLD.NBR_USER_PHONE_EXTENSION,
        :OLD.ADDR_USER_ADDR_ZIP,
        :OLD.CD_USER_ADDR_STATE,
        :OLD.ADDR_USER_ADDR_CITY,
        :OLD.ADDR_USER_ADDR_ST_LN_1,
        :OLD.ADDR_USER_ADDR_ST_LN_2,
        :OLD.CD_USER_ADDR_COUNTY,
        :OLD.CD_REQUEST_TYPE,
        :OLD.TXT_OTHER,
        :OLD.TXT_PASSWORD,
        :OLD.IND_USER_AGREEMENT,
        :OLD.IND_ADMIN_AGREEMENT,
        :OLD.CD_STATUS,
        :OLD.CD_QUESTION_1,
        :OLD.CD_QUESTION_2,
        :OLD.CD_QUESTION_3,
        :OLD.TXT_ANSWER_1,
	:OLD.TXT_ANSWER_2,
        :OLD.TXT_ANSWER_3,
        :OLD.DT_LAST_PASSWD_RESET,
        :OLD.IND_PASSWD_TEMP,
        :OLD.NBR_FAILED_LOGIN_ATTEMPTS,
        :OLD.ID_SHINES_PERSON_MODIFIED_BY,
        :OLD.ID_PORTAL_PERSON_MODIFIED_BY,
        'DELETE'
    );
END;
/

grant select on caps.person to capson;
/
CREATE OR REPLACE TRIGGER CAPS.TDBR_PORTAL_USR_VNDR_LNK
BEFORE DELETE
ON CAPS.PORTAL_USER_VENDOR_LINK
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

BEGIN

  insert into PORTAL_USR_VENDOR_LNK_AUDIT(
        ID_PORTAL_USER_VENDOR_LINK,
  	DT_LAST_UPDATE, 
  	ID_USER, 
  	ID_RESOURCE, 
  	CD_ACCESS_TYPE, 
  	CD_STATUS,
  	ID_SHINES_PERSON_MODIFIED_BY,
        ID_PORTAL_PERSON_MODIFIED_BY,
        DT_START, 
	DT_END,
        TABLE_ACTION)
   VALUES (
        :OLD.ID_PORTAL_USER_VENDOR_LINK,
  	:OLD.DT_LAST_UPDATE, 
  	:OLD.ID_USER, 
  	:OLD.ID_RESOURCE, 
  	:OLD.CD_ACCESS_TYPE, 
  	:OLD.CD_STATUS,
  	:OLD.ID_SHINES_PERSON_MODIFIED_BY,
        :OLD.ID_PORTAL_PERSON_MODIFIED_BY,
        :OLD.DT_START, 
	:OLD.DT_END,
        'DELETE');
END;
/  

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (641, 'SacwisRev3', 'Release Undetermined - DBCR 15643');

commit;


