-- STGAP00009389 - Need to update the decode value to display the apostrophe properly.

UPDATE CAPS.CODES_TABLES
SET DECODE = 'Caretaker not willing to meet child''s basic needs'
WHERE CODE_TYPE = 'CNEGLECT'
AND CODE = 'NCLQ';


-- STGAP00009392 - Need to update the INCMG_DETERM_FACTORS table with the changed codes. 


-- MR-011 Updating Physical Abuse Codes--

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'PCAQ'
WHERE CD_INCMG_DETERM = 'PAMC'
AND CD_INCMG_DETERM_TYPE = 'P';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'PCBD'
WHERE CD_INCMG_DETERM = 'PCNP'
AND CD_INCMG_DETERM_TYPE = 'P';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'PCBP'
WHERE CD_INCMG_DETERM = 'PBCB'
AND CD_INCMG_DETERM_TYPE = 'P';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'PCJA'
WHERE CD_INCMG_DETERM = 'PCPI'
AND CD_INCMG_DETERM_TYPE = 'P';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'PCKA'
WHERE CD_INCMG_DETERM = 'PMTH'
AND CD_INCMG_DETERM_TYPE = 'P';


-- MR-011 Updating Neglect Codes--

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'NC1A'
WHERE CD_INCMG_DETERM = 'NCLA'
AND CD_INCMG_DETERM_TYPE = 'N';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'NCLQ'
WHERE CD_INCMG_DETERM = 'NCBN'
AND CD_INCMG_DETERM_TYPE = 'N';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'NCNA'
WHERE CD_INCMG_DETERM = 'NSMC'
AND CD_INCMG_DETERM_TYPE = 'N';



-- MR-011 Updating Emotional Abuse Codes--

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'ECCK'
WHERE CD_INCMG_DETERM = 'ECPC'
AND CD_INCMG_DETERM_TYPE = 'E';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'ECQD'
WHERE CD_INCMG_DETERM = 'ECII'
AND CD_INCMG_DETERM_TYPE = 'E';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'ECQS'
WHERE CD_INCMG_DETERM = 'ECPI'
AND CD_INCMG_DETERM_TYPE = 'E';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'ECQB'
WHERE CD_INCMG_DETERM = 'ECEI'
AND CD_INCMG_DETERM_TYPE = 'E';

-- MR-011 Updating Sexual Abuse Codes--


UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'SPAD'
WHERE CD_INCMG_DETERM = 'SCAH'
AND CD_INCMG_DETERM_TYPE = 'S';

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'SSND'
WHERE CD_INCMG_DETERM = 'SCNP'
AND CD_INCMG_DETERM_TYPE = 'S';



-- MR-011 Updating Other Codes--

UPDATE CAPS.INCMG_DETERM_FACTORS
SET CD_INCMG_DETERM = 'OCDD'
WHERE CD_INCMG_DETERM = 'OECC'
AND CD_INCMG_DETERM_TYPE = 'O';


insert into caps.schema_version (id_schema_version, application_version, comments)
                        values (351, 'SacwisRev2', 'Release 2.5 - DBCRs 9389,9392');
commit;
