--STGAP00015962 - Release(4.0) MR-70: Batch Alerts add codestable and column

--8/16/2010

alter table CAPS.YRPP_LINK add DT_SURVEY_START Date null;

comment on column CAPS.YRPP_LINK.DT_SURVEY_START is 'Used to record the date that the NYTD Survey was started' ;

alter table CAPS.BATCH_ALERT_PARAMS drop column NYTD_BASELINE_YEAR;


INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES ('CFEDFY', 'AS', '1001');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES ('CFEDFY', 'AE', '0331');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES ('CFEDFY', 'BS', '0401');
INSERT INTO CAPS.CODES_TABLES (CODE_TYPE, CODE, DECODE) VALUES ('CFEDFY', 'BE', '0930');

INSERT INTO CAPS.BATCH_ALERT_PARAMS (ID_BATCH_ALERT_PARAMS, ALERT_EMAIL_STEP_NAME, IND_RUN) VALUES (CAPS.SEQ_BATCH_ALERT_PARAMS.nextVal, 'BGCHECKFHMEMBERTURN18', 'Y');
INSERT INTO CAPS.BATCH_ALERT_PARAMS (ID_BATCH_ALERT_PARAMS, ALERT_EMAIL_STEP_NAME, IND_RUN) VALUES (CAPS.SEQ_BATCH_ALERT_PARAMS.nextVal, 'NYTDGREETANDPASSDIST', 'Y');
INSERT INTO CAPS.BATCH_ALERT_PARAMS (ID_BATCH_ALERT_PARAMS, ALERT_EMAIL_STEP_NAME, IND_RUN) VALUES (CAPS.SEQ_BATCH_ALERT_PARAMS.nextVal, 'NYTDBASESURVEYREMINDER', 'Y');
INSERT INTO CAPS.BATCH_ALERT_PARAMS (ID_BATCH_ALERT_PARAMS, ALERT_EMAIL_STEP_NAME, IND_RUN) VALUES (CAPS.SEQ_BATCH_ALERT_PARAMS.nextVal, 'ADOPTSUBSIDYNOFINALIZATION', 'Y');
INSERT INTO CAPS.BATCH_ALERT_PARAMS (ID_BATCH_ALERT_PARAMS, ALERT_EMAIL_STEP_NAME, IND_RUN) VALUES (CAPS.SEQ_BATCH_ALERT_PARAMS.nextVal, 'CHILDTURNING18', 'Y');

insert into caps.schema_version(id_schema_version,application_version,comments)
            values (868, 'SacwisRev3', 'Release 4.0 - DBCR 15962');

commit;

