package gov.georgia.dhr.dfcs.sacwis.core.lookup.codestables;

public interface Cspecreq {

  public static final String CSPECREQ = "CSPECREQ";
  public static final String CSPECREQ_AH = "AH";
  public static final String CSPECREQ_BD = "BD";
  public static final String CSPECREQ_CAC = "CAC";
  public static final String CSPECREQ_CAD = "CAD";
  public static final String CSPECREQ_CBC = "CBC";
  public static final String CSPECREQ_CCL = "CCL";
  public static final String CSPECREQ_CCO = "CCO";
  public static final String CSPECREQ_CCR = "CCR";
  public static final String CSPECREQ_CD = "CD";
  public static final String CSPECREQ_CDC = "CDC";
  public static final String CSPECREQ_CDD = "CDD";
  public static final String CSPECREQ_CDIC = "CDIC";
  public static final String CSPECREQ_CDNC = "CDNC";
  public static final String CSPECREQ_CFH = "CFH";
  public static final String CSPECREQ_CI = "CI";
  public static final String CSPECREQ_CIC = "CIC";
  public static final String CSPECREQ_CJP = "CJP";
  public static final String CSPECREQ_CLE = "CLE";
  public static final String CSPECREQ_COS = "COS";
  public static final String CSPECREQ_CPB = "CPB";
  public static final String CSPECREQ_CPL = "CPL";
  public static final String CSPECREQ_CST = "CST";
  public static final String CSPECREQ_CTY = "CTY";
  public static final String CSPECREQ_FAH = "FAH";
  public static final String CSPECREQ_FAHP = "FAHP";
  public static final String CSPECREQ_FH = "FH";
  public static final String CSPECREQ_FHP = "FHP";
  public static final String CSPECREQ_GH = "GH";
  public static final String CSPECREQ_ICPC = "ICPC";
  public static final String CSPECREQ_MIC = "MIC";
  public static final String CSPECREQ_MN = "MN";
  public static final String CSPECREQ_MNIC = "MNIC";
  public static final String CSPECREQ_MR = "MR";
  public static final String CSPECREQ_NEX = "NEX";
  public static final String CSPECREQ_NF = "NF";
  public static final String CSPECREQ_NFIC = "NFIC";
  public static final String CSPECREQ_NFNC = "NFNC";
  public static final String CSPECREQ_NIP = "NIP";
  public static final String CSPECREQ_NLA = "NLA";
  public static final String CSPECREQ_NPS = "NPS";
  public static final String CSPECREQ_NRC = "NRC";
  public static final String CSPECREQ_NST = "NST";
  public static final String CSPECREQ_OT = "OT";
  public static final String CSPECREQ_RFAH = "RFAH";
  public static final String CSPECREQ_RH = "RH";
  public static final String CSPECREQ_RHE = "RHE";
  public static final String CSPECREQ_RHP = "RHP";
  public static final String CSPECREQ_RI = "RI";
  public static final String CSPECREQ_RP = "RP";
  public static final String CSPECREQ_RPY = "RPY";
  public static final String CSPECREQ_SI = "SI";
  public static final String CSPECREQ_SIIC = "SIIC";
  public static final String CSPECREQ_SINC = "SINC";
  public static final String CSPECREQ_SP = "SP";
  public static final String CSPECREQ_XXX = "XXX";

}
